### ISSUE TITLE
Increase the time out for provider

### ISSUE THREAD

**Issue by mancuniancol** [scakemyer/plugin.video.quasar#10]
Please, could you change the 4s default for the time out to 30s?  Thank you.

Btw, when it is not links, the master code still says Pulsar :)

**Comment by mancuniancol** [comment]
I've realized that Quasar is calling Pulsar.  I've might downloaded too soon the code :P

**Comment by scakemyer** [comment]
It's not just Windows, there's no plugin.video.quasar release yet ;) It's ready though, I just don't want folks to get stuck with no providers available for those that get automatic upgrades.

Regarding the timeout, 30s sounds like a bit much. How about 10s? It'd make for a nice 10s default, 20s for multicore ARM, and 30s for single cores, while giving some leeway for slower connections.

**Comment by mancuniancol** [comment]
Usually people add all the providers available.  With 30s get the most of them.  Anycase, if the providers give the torrent before it won't delay Quasar job.

However, if you think that with 10s, it won't people having not links error. I don't mind. You know more the code than me.

**Comment by mancuniancol** [comment]
Could you share that code? I really want to test each provider to fix any bug related.  Then, I will be available to submit my providers to repos.

Besides, I need to fix some of them because the site changed and it is easy for me to do it.  I have sandbox machine just with quasar.  I don't want to mix.  Otherwise, I will just release which you tell me what are good. I will wait to have Quasar to do my tests for the rest.

**Comment by scakemyer** [comment]
Of course, I'll just post another pre-release, that's what they're for. And yeah 10s should be plenty, it's all in parallel so there's no reason for providers to take much longer on decent CPUs.

**Comment by mancuniancol** [comment]
Good.

But, it is not parallel, that discussion I had before with Steeve.  More providers you add, more time it takes. Besides, people use Pulsar or will use Quasar en fire stick or android devices or less powerful machines.  But again, you can use 10s, if it doesn't work, you can change in the next release.  

I will close this issue.

**Comment by scakemyer** [comment]
I know it does take more time as they're all making connections and competing for CPU time, but keep in mind that 10s is for non-android devices, those default to 20s and already 30s for single-core devices. I think those are good defaults.
