### ISSUE TITLE
Fast resume on startup does not use Background handling of torrents setting

### ISSUE THREAD

**Issue by Greenbaburu** [scakemyer/plugin.video.quasar#101]
(Nexus 4 - Android M)
with this (awesome!) option turned off, if I close Kodi (currently, torrents folder is empty) and restart, the download of the previous torrents automatically resume in background and i must delete torrents from specific folder where them are reappeared. Now, If i restart Kodi again the torrent is actually erased.
Hoping I was clear :)

**Comment by ShlomiD83** [comment]
Same Problem Here. Torrents keeps downloading on it's own. i disabled background handling of torrents.

**Comment by ShlomiD83** [comment]
maybe you should add a setting to turn off fast resume, think about it.

**Comment by scakemyer** [comment]
Already thought about it yes, but the auto-resuming even with background handling turned off is a bug / something I forgot to enable conditionally of that setting.

**Comment by ShlomiD83** [comment]
the fastresume file isnt deleting itself even if i choose not to keep files after playback stop, that's why it resumes download by itself..

**Comment by scakemyer** [comment]
Yes, fix is on the way

**Comment by Greenbaburu** [comment]
GREAT! :)
