### ISSUE TITLE
stream selection window not apearing when language is hebrew

### ISSUE THREAD

**Issue by ShlomiD83** [scakemyer/plugin.video.quasar#106]
ever since 0.9.6 with the new stream selection screen, when i'm using the hebrew translation string i get no notifications such as "quasar daemon has started" "no links found", and when i click choose stream nothing happens, no error and no notification, just returns to the episode/movie list.
but when i delete all languages beside english everything works like a charm.
i added my log, hope you can fix it soon.

[kodi.txt](https://github.com/scakemyer/plugin.video.quasar/files/120785/kodi.txt)

**Comment by meijin007** [comment]
:+1: for this issue. My system: ArchLinux on Rpi2. This issue actually preventing as from using the add on.

**Comment by scakemyer** [comment]
We'll be fixing the dialogs today, hang in there.

**Comment by meijin007** [comment]
Can you please explain a bit what was the problem?

**Comment by ShlomiD83** [comment]
thnx for the quick reply scakemyer, you're doing awsome work.

**Comment by meijin007** [comment]
maybe there is more info in those logs? 
[kodi.old.txt](https://github.com/scakemyer/plugin.video.quasar/files/121635/kodi.old.txt)
[kodi.txt](https://github.com/scakemyer/plugin.video.quasar/files/121636/kodi.txt)

**Comment by scakemyer** [comment]
Closing in favour of #105, thanks for the logs @meijin007!
