### ISSUE TITLE
HTTP Error 500: internal server error

### ISSUE THREAD

**Issue by MrLegendary** [scakemyer/plugin.video.quasar#110]
Hi,

First of all, great work! Really appreciate the work everyone is doing. One small thing: I keep getting an internal server error when trying to download subtitles. (Running on rooted nvidia shield tv) [Here](http://pastebin.com/AN6AuT6b) is my log.

**Comment by scakemyer** [comment]
```
Error #01: open /data/local/tmp/403701838: permission denied
```
You've got a permissions problem on that rooted shield

**Comment by tobiasvandriessel** [comment]
How can this be resolved? I'm having the same problem on a rooted Android phone.

**Comment by scakemyer** [comment]
Sorry you'll have to look around the interwebs about write issues on those.
