### ISSUE TITLE
Add Tribler support

### ISSUE THREAD

**Issue by iCanuck** [scakemyer/plugin.video.quasar#113]
It would be nice to have Quasar use Tribler for anonymity, it was discussed by steeve & tribler in the past.

http://forum.kodi.tv/showthread.php?tid=200957&pid=1965875#pid1965875

**Comment by scakemyer** [comment]
Sorry but it won't happen, I won't have time to dig through their specs and implement that sort of thing. Feel free to take a stab at it, we'll see if it can be included after without bloating the daemon. If anything that networking layer should be completely separate from Quasar and Kodi itself. It's fine to have the proxy option that's built into libtorrent, but even that isn't something that should be relied upon for anonymity.
