### ISSUE TITLE
odd problem with multi-file torrents opening/playing

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#116]
I just done some easy testing. I copied url for some torrent (whole season) of one tv show and paste it to (paste URL) Quasar to see if he can open the url and folder with that season and he failed it.

Maybe that is the problem why Quasar can't show whole season packs when providers search tv show?

**Comment by ShlomiD83** [comment]
what torrent is that? i wanna try..

**Comment by ShlomiD83** [comment]
did you paste the magnet link or the url address of the torrent? u need to paste the magnet link..

**Comment by nix87** [comment]
damn it I saw paste url and I did that, not magnet link

sorry.. everything is ok

Quasar opens that file without problem

**Comment by nix87** [comment]
Intersting thing is that multi file torrent works with movies. When you search for movie like Back to the Future, Leathel Weapon, Mission Impossible... providers find and show results for movie packs in trilogies, quadrilogies and such but when they should show season packs they failed.

Did someone know maybe where is the problem with tv shows?

**Comment by scakemyer** [comment]
This is working as intended, it's now up to providers to return results with season packs or give different options for those. Enjoy :)

**Comment by mancuniancol** [comment]
Version 1.1.0 providers are capable to show pack season search.
