### ISSUE TITLE
Add season packs in search results

### ISSUE THREAD

**Issue by tstrul1** [scakemyer/plugin.video.quasar#117]
It would be great if you could add another section or tab to search results window (Choose streams) with the episodes season pack.  Old episodes doesn't usually have a lot of seeders and download speed is slow.

If you could search inside season packs during episode search it would be even better but I think its harder to implement.

**Comment by nix87** [comment]
bro I just oppened thread about that problem under your thread :)

**Comment by scakemyer** [comment]
That's up to the providers :)
