### ISSUE TITLE
"Next page" item can be ordered by name in TV Shows

### ISSUE THREAD

**Issue by lrrosa** [scakemyer/plugin.video.quasar#120]
When I order TV Shows by name, the "Next page" item is ordered too.
This problem doesn't happen with movies.

I'm using Quasar 0.9.9 and OpenElec x64 6.0.1 (Kodi 15.2)

**Comment by KillerJoeBR** [comment]
Irrosa, are you having issues lately? In the latest version (0.9.11) i don't get the daemon started message. And the stream selection window doesn't work either. This started after your translation in 0.9.10 and mine 0.9.11 same thing happens. If i manually change the strings.po from version 0.9.9 everything works fine again.

Can you look if you have the same problems? 

ps: caso voce nao veja a mesagem no pull request
