### ISSUE TITLE
Available streams window (ContentPanel.png) too transparent

### ISSUE THREAD

**Issue by iCanuck** [scakemyer/plugin.video.quasar#121]
I find the Available streams window is too transparent, I have tested with several skins.
(plugin.video.quasar\resources\skins\Default\media\AddonWindow\Contentpanel.png)

**Comment by tomer953** [comment]
I Agree. it's look very transparent in my skin too.

**Comment by nix87** [comment]
I use Titan and it looks good on that skin. But I think it wouldn't harm to be less transparent if on other skins available streams window doens't look clear and sharp.

**Comment by scakemyer** [comment]
It's the exact same background as the Confluence skin guys. I checked and they don't darken it either... I'll keep it mind when we change it, or make it darker and send a pull request.

**Comment by scakemyer** [comment]
Turns out we were using ContentPanel (for you know, content) instead of the background for dialogs. Apologies gentlemen, fix will be in the next version.
