### ISSUE TITLE
Quasar isnt showing all search results 

### ISSUE THREAD

**Issue by ShlomiD83** [scakemyer/plugin.video.quasar#122]
When using more than one provider quasar is showing limited results, if i search rarbg alone i get 4-5 results, or with torlock im getting 5-6 results back.  but when i search with both of them, i get a few from torlock and none or 1-2 from rarbg. I think its an issue with the new results dialog..

**Comment by meijin007** [comment]
As far as I know, Quasar is looking for duplicate links, and merge them to show as one. Maybe this is it?

**Comment by ShlomiD83** [comment]
With rarbg ver 1.1.0 it showed me no results when i searched along side another provider, i dont think it deletes duplicates because rarbg had other files in the results.

**Comment by ShlomiD83** [comment]
my bad :) it does remove duplicates. sorry.

**Comment by nix87** [comment]
Yes he removes duplicates, sometimes don't and you get same two torrents from two different providers, but that is rarely.
