### ISSUE TITLE
Leaving settings dialog always clears cache

### ISSUE THREAD

**Issue by epilsits** [scakemyer/plugin.video.quasar#123]
v0.9.9, OSMC on a RPi 2. Whenever I leave the settings dialog via OK, Quasar shows the 'Cache Cleared' message as if I had cleared cache from the maintenance command.

**Comment by dlucic** [comment]
Yeah, because it clears the cache. :D

**Comment by epilsits** [comment]
I think you misunderstand. It clears the cache _every_ time I exit the settings dialog after pressing OK. I'm sure that is not the intended behavior.

**Comment by scakemyer** [comment]
No it's the intended behaviour when you press OK, because you changed the settings and caches need to be cleared for some changes to be applied. They are not if you just exit / press Cancel.
