### ISSUE TITLE
'Not enough space available on the download path' error

### ISSUE THREAD

**Issue by ScottishLad** [scakemyer/plugin.video.quasar#125]
Wondering if anyone can help. I have a 1TB USB HDD formated in NTFS format hooked up to my android box. With Quasar I keep getting the 

'Not enough space available on the download path' error

I only get it after I've tried few movies, generally larger file size movies. If I restart Kodi, works again for few then error comes back. Any ideas?

**Comment by a1danslat3** [comment]
Will not work with external HDD. This is a limitation in libtorrent and will not be available by the looks of it. I have encountered something similar and it seems very strange. 

Maybe it has something to do with sequential downloading. I can see this being a big issue in the future when casual torrent users start using much higher bitrate content.

**Comment by Kiralina** [comment]
I have a external HDD formatted HFS+ attached to an Airport Extreme and smb protocol in OE on RP2 and I have no low space problems.

**Comment by scakemyer** [comment]
As mentioned by @a1danslat3, external storage isn't and most probably won't be supported. This is all handled by libtorrent and I don't intend to start hacking away at libtorrent itself on top of this project. If support for external storage is added to it we'll get it also. Until then, it will probably work with eSATA or USB 3.0 drives mounted at the OS level.

**Comment by ScottishLad** [comment]
Scakemyer, thanks for taking time to reply to me. So if purchased a USB 3.0 dongle, and plug into box it should work ok without any download path errors?

**Comment by scakemyer** [comment]
I can't confirm it will, you'll have to try it. At worst you'll have a shiny new USB 3.0 dongle to use for other things.

**Comment by mhsan** [comment]
I have the same error with android box with 32GB tf card, atlist now I know why it's not working , thanks.

**Comment by ScottishLad** [comment]
scakemyer thanks for reply, checked last night my android box only has USB 2.0? see spec below
USB host
2High speed USB 2.0,support USB DISK and USB HDD

**Comment by trabsou** [comment]
did anyone find a solution for this? all android tv boxes only have 2-4 gb available internal space which is no enough.

**Comment by nmvega** [comment]
Just FYI ... I ran into this issue on a Android media box, where I have a **NTFS** formatted **USB** drive connected to it. The Quasar video plugin (the configuration section of it) allows you to browse to a directory on that drive, but does not allow you to select it as a target. The message you get basically says: "make sure the folder exists and has write permissions". Both of which are true in my case. 

Interestingly, though, I have the **tTorrent** Android program installed and pointing to that same directory, and it has no issues writing to it. Maybe it doesn't use libtorrent.
