### ISSUE TITLE
quasar loading bar stays opened

### ISSUE THREAD

**Issue by nickolayrusev** [scakemyer/plugin.video.quasar#129]
I'm a little bit curious why this loading bar stays opened in kodi main screen? You can label this thread as "question" because everything else works fine...

I'm attaching an image. I'm using Kodi Helix v14.2 on Raspberry Pi 2. 

ps: Great addon and great maintanence !

![img_20160209_235734](https://cloud.githubusercontent.com/assets/2699024/12943688/96899dc2-cfeb-11e5-9490-dc292ee8dea5.jpg)

**Comment by ShlomiD83** [comment]
do you have background handling enabled ?

**Comment by scakemyer** [comment]
This is just the background handling of streams informing you that it's currently active, it's intended behaviour.
