### ISSUE TITLE
Enhancement (Add Year of each show/movie after name)

### ISSUE THREAD

**Issue by compyy** [scakemyer/plugin.video.quasar#133]
Hi,

Can you also add Year of the movie/show after the names ?

**Comment by scakemyer** [comment]
Sorry but that has nothing to do with Quasar but the way your skin displays the information. The year is already there for every movie and show.

**Comment by compyy** [comment]
this is strange for me genesis shows correct year of the movie just with title but quasar doesnt, is there any way to enable it via skin ? when you click on most popular section, do you see the Year in (2010) after movie title ? i only see movie title and and duration.

**Comment by scakemyer** [comment]
If Genesis is adding the year next to movies in listing, it's doing it wrong. This is up to skins and the view modes and that's how it should be. Try changing from "List" to something else, no idea what your skin provides.
