### ISSUE TITLE
Health checks for providers

### ISSUE THREAD

**Issue by scakemyer** [scakemyer/plugin.video.quasar#141]
From @Magic815's great suggestions over [here](http://forum.kodi.tv/showthread.php?tid=200957&pid=2225000#pid2225000)
> The number of providers has ballooned to an enormous amount -- which is awesome! However, I've found that certain providers can often break (and then may or may not get eventually fixed), and it's hard to keep track of broken providers when searching for streams (I'll often just see a quick slew of error messages as Pulsar powers through). For users who often have a large rotating array of providers, it'd be nice to have a user friendly way to evaluate all of the currently enabled providers within Pulsar (either it's GUI or in it's settings) to verify their functionality. Is it possible to put enable/disable control over all providers inside Pulsar? That, plus some nice color coding to show the "health" of each provider would be great.

**Comment by Magic815** [comment]
Ha, very proactive! I was giving you guys a breather after my initial dump of requests on git, but this sounds good to me. :)

**Comment by mancuniancol** [comment]
It is more than I was asking, But, I will be great to get that level.

**Comment by scakemyer** [comment]
There are already too many notifications from providers in the current state of things, so a separate section for health checks and a single notification that something went wrong/changed will be a lot better

**Comment by mancuniancol** [comment]
It is great, again, it is more than I thought :)

**Comment by scakemyer** [comment]
Tada! It'll be in v0.9.13 :)

**Comment by nix87** [comment]
Nice useful feature, indeed.. thanks :)

**Comment by mancuniancol** [comment]
Great

**Comment by scakemyer** [comment]
@mancuniancol You might want to catch less errors in the providers themselves, or (re)throw exceptions when something is obviously failing. Otherwise the provider calls don't see any errors, just get 0 links and no failures are detected.

**Comment by mancuniancol** [comment]
Yes, I will do.
