### ISSUE TITLE
HTTP Error 500: Internal Server Error 

### ISSUE THREAD

**Issue by MrTal** [scakemyer/plugin.video.quasar#146]
HTTP Error 500: Internal Server Error  in version 0.9.11 but tvshows is working fine, it's just in the movies categories. The problem start in verison 0.9.11
windows 7 64 bit  language Hebrew

**Comment by ShlomiD83** [comment]
https://github.com/scakemyer/plugin.video.quasar/issues/142

**Comment by MrTal** [comment]
> 
but this not connected  The Hebrew language im try change the language to english and this not help but category "top rated" yes work

**Comment by ShlomiD83** [comment]
it's the same problem..
