### ISSUE TITLE
Background file auto delete after ratio / quota reached

### ISSUE THREAD

**Issue by corrpel** [scakemyer/plugin.video.quasar#147]
Hi,
Nice job on this one background handling the torrent.
It will be even awesomer if we would have an option to delete the torrent and data after x ratio / y hours automatically.
1. For space reason
2. For private torrents requests

**Comment by Magic815** [comment]
Not a bad idea, but keep in mind that Quasar is not on the approved client list for a lot of private trackers, so you would be risking a ban by using it for those.

Question to the devs - does Quasar have the ability to keep seeding a file after Kodi is exited? Does it continue running as it's own process? Or would the above feature just get force quit if the user exited Kodi? I guess I'm having a hard time understanding how Quasar works as a torrent client when Kodi is not running.

**Comment by nix87** [comment]
Actually Quasar uses libtorrent and I checked, libtorrent is allowed on every private tracker :)

About keep seeding part it was said it will be implemented in future.

**Comment by Falcon-1** [comment]
Hi, Thanks for forking and enhancing and supporting

I'd like to see a seed stop after ratio is reached. 

Setting for "max time"  and "max ratio"  and what to do when that has been reached; "stop seeding"/"delete torrent"/"delete torrent and file".

**Comment by scakemyer** [comment]
The options have been implemented, and torrents will only be paused when a limit is reached, since we don't want to risk deleting a torrent while it's being watched, and deleting is better left to the "Keep files after playback" setting.
