### ISSUE TITLE
Background download freezes KODI when it doesn't have enough speed/MB to buffer minimum size

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#149]
Hi, quasar background queue to start file freezes kodi (i can't click anything) if it doesn't have speed enough to queue first MB. I guess it's waiting till it gets enough MB buffered?

So, please provide a way to not freeze when that happens so we can go to TORRENT window and cancel stream, since it will take forever to start.

**Comment by scakemyer** [comment]
It's not waiting for anything, you can go back at any time even during the Finding part and the background handling keeps going, this sounds a lot more like a skin issue.
