### ISSUE TITLE
Feature request: Add Torrent download to QUEUE

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#150]
Is this possible? Click some show or movie and select "add to queue" it will download torrents in background. 

Sometimes i want to download some files while i am watching others.
We could have an option to use quasar to both watch movie/show and also download in background.
Maybe something for the future.

**Comment by scakemyer** [comment]
That's already how background handling works, and we can't add a context menu to the stream selection dialog, so you just select the stream you want and go back and it downloads in the background / gets queued by libtorrent.
