### ISSUE TITLE
Overlay status gets covered by skin's infobar on pause

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#151]
Hi there, is not possible anymore to see how many seeds/peers/MB is in current download anymore?
Download Infobar.

EDIT: i see if we press pause it shows up. Is it possible to relocate? Infobar covers most of the info.

**Comment by nix87** [comment]
probably depends which skin you use, on Titan everything is superb

**Comment by scakemyer** [comment]
It exactly depends on the skin, if we move it others will complain about the overlay status getting covered by something. The vertical offset could be made configurable though.

**Comment by hfmls** [comment]
OK,  I use default

**Comment by ShlomiD83** [comment]
Can you make it appear/disappear faster?

**Comment by scakemyer** [comment]
No, and that has nothing to do with its position anyway.
