### ISSUE TITLE
Error after Greek translation commit

### ISSUE THREAD

**Issue by Filosofos** [scakemyer/plugin.video.quasar#153]
After Greek translation commit, there is an error on the log which breaks Quasar and no returns are coming back from the providers (ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.quasar/movie/xxxxx/links])

The error is the following:  "No handlers could be found for logger "bjsonrpc.connection"
If i delete Greek folder in languages then everything is back to normal.

I don't know if i broke something in the translation or if it has something to do with the Greek language, but i think that it has been mentioned [here](http://forum.kodi.tv/showthread.php?tid=257967&pid=2240289#pid2240289) before my commit.

**Comment by scakemyer** [comment]
#142
