### ISSUE TITLE
Neither stream windows nor video playback

### ISSUE THREAD

**Issue by zorg1977** [scakemyer/plugin.video.quasar#154]
When search for a content, nothing happens: Quasar doesn't play anything and, if I've previsously selected in the context menu to display the streams, the Streams window never shows up.

In the logs, I can see the providers looking forthe content, and I see /callback/something

Configuration :
Raspberry pi 2 with OSMC (up to date)
Quasar 0.9.11 with a set of providers

**Comment by KillerJoeBR** [comment]
are you using another language instead of english? Seems like the translation stings causes issues when there is (at least in the portuguese translation) special letters (ç, ì, À, etc...) in window dialogs.

Cause special letters inside the settings doesn't seem to cause any problem. Anyway it's better not to use special letters anywhere.

**Comment by zorg1977** [comment]
I'm using a language that is not english but even if I switch back to English (US) for instance, the issue is still there. Sometimes a popup saying playback is impossible shows up.
Here is an error in the log at the time the error message appeared:
10:14:30 38366.304688 T:1571812384  NOTICE: [plugin.video.quasar] [GIN] 2016/02/11 - 09:14:29 |[97;42m 200 [0m 20.254625361s ::1 [97;44m [0m GET     /show/[something]/season/5/episode/1/links
10:14:30 38366.308594 T:1958203952   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.quasar/show/[something]/season/5/episode/1/links]

**Comment by zorg1977** [comment]
And for each provider, I can see this kind of lines:
10:23:43 38919.710938 T:1465906208  NOTICE: [script.quasar.something] >>>>>>10 torrents sent to Quasar<<<<<<<
10:23:43 38919.722656 T:1465906208  NOTICE: [script.quasar.something] <addinfourl at 1590606944 whose fp = <socket._fileobject object at 0x61c45630>>
10:23:43 38919.910156 T:1571812384  NOTICE: [plugin.video.quasar] [GIN] 2016/02/11 - 09:23:43 |[97;42m 200 [0m|        12.5µs | ::1 |[97;46m  [0m POST    /callbacks/726761259

but nothing happens (in this case, I chose "Choose Stream..." to see all the sources available)

**Comment by zorg1977** [comment]
Ok, seems to be related to a too small default provider timeout value (4 seconds, right?), which is not suitable for a Raspberry Pi 2 (around 30 seconds seems pretty good, less may be possible, didn't try)

**Comment by jeanpralo** [comment]
@zorg1977  I have tried to increase that provider timeout but I still get that error:

18:46:58 273.045105 T:1957823024   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.quasar/show/[something]/season/2/episode/1/links]

Did you manage to find a workaround ?

**Comment by zorg1977** [comment]
Actually, I've set the value to 45 seconds and everything runs as expected. No more error like the one described.
