### ISSUE TITLE
Library integration not working

### ISSUE THREAD

**Issue by xlachtan** [scakemyer/plugin.video.quasar#155]
Quasar 0.9.11
Kodi 15.2 Isengard on Windows 8.1

Hi, I have set library path in Quasar settings (let´s say D:\Quasar) but when I try to add anything to library via Quasar context menu "Add / Remove from library" I get error "Quasar - library path not set" followed by another one "Quasar - Navigation error: HTTP error: 404 not found"

This behavior is same for TV shows and movies and I tried few different TV shows. I also tried to set different folders as library in addon setting.

Thank you

**Comment by i96751414** [comment]
There's no way to help you if you do not provide a log

**Comment by xlachtan** [comment]
Nevermind, did clean install and now it´s working ok. Don´t have a clue what was different this time :)
