### ISSUE TITLE
Quasar not open

### ISSUE THREAD

**Issue by abeksis** [scakemyer/plugin.video.quasar#160]
System: Mac

1. On startup a message saying "unable to find Quasar binary" shows up.
2. Restarting Kodi does not solve the problem.
3. Binary is present in Kodi\userdata\addon_data\plugin.video.quasar\bin\.
4. An empty folder was created in Kodi\addons\plugin.video.quasar\resources\bin
5. Manual copying of the binary from addon_data to add ons dot solves the problem. 

`13:27:32 T:140735254601728   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/
13:27:32 T:140735254601728   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/) failed`

**Comment by roee88** [comment]
Same here after latest update. 

System: Windows x64
Language: English
On startup a message saying "unable to find Quasar binary" shows up.
Binary *is* present in Kodi\userdata\addon_data\plugin.video.quasar\bin\windows_x64.
Restarting Kodi does not solve the problem.

**Comment by vgpalmieri** [comment]
Same here after latest update.

System: Android 4.4.2 (Samsung Note 10.1" N8010)
Kodi: 15.2
Language: English

On startup a message saying "unable to find Quasar binary" shows up.
Restarting Kodi does not solve the problem.

**Comment by scakemyer** [comment]
Sorry gents but the official zip packages are fine, and that notification was specifically added to check for that, so you're obviously getting a bad update from somewhere. Logs or it didn't happen.

**Comment by abeksis** [comment]
Can you send another update? To your addons will fall back to your original.

**Comment by scakemyer** [comment]
Just, no. I'm not pushing a release that's the same as the previous one because some third-party repository sent you a bad update. Install the new version manually.

**Comment by deusbraga** [comment]
all due respect to the coder, I've downloaded multiple times the file from your page on github and I still have the same error everytime I try to install it on a brand new install on a RPi3. I surely didn't get it from a third party. Apart from it I also get a error everytime I try to install the general file(the one that covers all different setups) forcing me to install a specific version.

**Comment by scakemyer** [comment]
That is unrelated to this long-closed issue.
