### ISSUE TITLE
Default provider timeout

### ISSUE THREAD

**Issue by zorg1977** [scakemyer/plugin.video.quasar#162]
It seems the default timeout is not set to the correct value for the Raspberry Pi 2. When trying to modify it for the first time in Quasar configuration UI, the value "4" was returned (instead of a greater value like 30 seconds).

**Comment by i96751414** [comment]
That "4" value is normal... Anyway, Raspberry Pi 2 has a default timeout of 30 seconds, I think. It will only be possible to change that value to 4 (or other value) seconds if you enable the checkbox "Provider timeout". So, if you disable it, you should have a timeout of 30 seconds, no?

**Comment by scakemyer** [comment]
The default when overriding the timeout is still set to 4, yes, but check the readme for default timeouts. That default won't change depending on your current calculated default, even if we increase it. So leaving it at 4 actually kind of makes sense for an advanced setting.
