### ISSUE TITLE
themoviedb for tv shows

### ISSUE THREAD

**Issue by razer1s** [scakemyer/plugin.video.quasar#164]
add option that will allow to seach info for tv shows by themoviedb scraper

**Comment by i96751414** [comment]
Quasar already uses tmdb... I'm not sure about what you want

**Comment by scakemyer** [comment]
If you're saying themoviedb should be used for seasons/episodes/fanart data then yes, I've already started to look into that, since tvdb is CloudFlared which makes it impossible to reach in many cases.

**Comment by razer1s** [comment]
great news, thanks. and one more question- why Quasar shows title only in English?

**Comment by scakemyer** [comment]
Fixed in scakemyer/quasar@2ac4c2e, TheMovieDB is now used for seasons and episodes.

Translated titles fixed in scakemyer/quasar@d65a12b with option added in #200
