### ISSUE TITLE
Change color of resolution in "Choose stream dialog"

### ISSUE THREAD

**Issue by exzilexv** [scakemyer/plugin.video.quasar#171]
This would make it easier to spot resolution differences and help easily identify which file you should go with depending on your internet speeds . I would go with traffic signal colors.
1080p = Green (for fast reliable connections)
720p = Yellow (basic connections)
480p/Hdtv = Red (slow connections)

Just had time on my hands, thought Id give some input.

**Comment by dtsexpert** [comment]
Good idea. If possible, please also bolt or color highlighted the stream size.

**Comment by corrpel** [comment]
The stream size is more important :) bigger stream size means better
quality. I usually play 10gb+, ~5gb, and as a last resort ~1gb

**Comment by nix87** [comment]
You mean 1080p = Green (for better quallity)? Reliability doesn't have to much with resolution xD

**Comment by exzilexv** [comment]
You know what I meant Mr. technical! :P Maybe we can get a couple mock ups of how the info in the dialog box should look. Right now its a little to hectic.

**Comment by nix87** [comment]
That is cause priorities have number of seeders and not resolution. If we got first 1080p then 720p then 480p, in that order, things would look less chaotically.

If we resulution get just colors and then with colored providers choose stream box will look like Easter egg :D

**Comment by dimitriss** [comment]
You should add a "seeding ratio" with a minimum seeds threshold and a "quality" property, quality should be a derived by resolution and by release tags. Results should be sorted by seeding_ratio/quality/seeds. Something like that, you get the idea.

**Comment by nix87** [comment]
But sometimes you can get amazing speed with only 2 or 3 seeders, depends. E.g. yesterday I have watched movie who is 7 GB's with only 2 seeders and I got down. speed around 1,6 Mb/s from start to the end of download.

I wouldn't exclude results with less seeders.

**Comment by scakemyer** [comment]
Mock-ups would be great, paging @Magic815 and @Greenbaburu

**Comment by exzilexv** [comment]
Couple mock ups using some of the input I saw yesterday. I feel like a Sort by feature would be the way to go. As for the mock ups I feel like simple is better and the mini version suits my tastes because I like having the fanart visible at all times. @scakemyer 

**Mini**
![mini](https://cloud.githubusercontent.com/assets/11835441/13032251/253d3978-d2a0-11e5-87bc-a295ca54dae6.png)
**Bold**
![full](https://cloud.githubusercontent.com/assets/11835441/13032253/2d37f5b4-d2a0-11e5-8f8b-6469963442c9.png)

**Comment by Greenbaburu** [comment]
With extreme pleasure, just had time. Personally I prefer the full version of exzilexv mock-ups, more usefull when you search torrents specifics and I suggest a small icon for the providers somewhere; at the start of the line for example

**Comment by exzilexv** [comment]
Awesome! Id like to see what you come up with.

**Comment by scakemyer** [comment]
I like the idea of the icon vs. full provider name. The mini version might not really be possible since we have to actively call providers to get that information in the first place, so the big dialog is kind of necessary. We also can't really sort in those, as we'd have to redraw a new dialog with the same items but re-ordered. There's also the other tags like the video codec, audio codec, type and rating that should probably still be there, so the table layout might be a little problematic for all of those.

**Comment by exzilexv** [comment]
Gotcha! Its my first time contributing to an addon I enjoy, so i'm picking things up as I go. Glad to have someone knowledgeable like you as I go along. Might have a couple questions here and there. I do have some experience in graphic design, so if you guys need something done don't hesitate to ask.

**Comment by Greenbaburu** [comment]
It's pretty basic, actually. I'm definitely not a UI/UX Designer! :) 

![choose](https://cloud.githubusercontent.com/assets/8045152/13036175/90182260-d360-11e5-96a9-12d90ba7698e.jpg)

**Comment by dimitriss** [comment]
There is no point in showing the provider name and/or icon, streams with equal hash are merged.

**Comment by yakirp88** [comment]
That looks great just need different color for each provider

**Comment by Greenbaburu** [comment]
I had missed this point
@dimitriss

**Comment by scakemyer** [comment]
That looks awesome :)

What about streams with no equal hash that wasn't merged and came from just one provider? Wouldn't you like to know which one it was? I think it's better to keep both names and icons. You might have two providers for the same site with the same icon, with one failing and the other still returning results, and be glad to see which one it was. I admit it's a bit of a stretch, but still ;)

**Comment by scakemyer** [comment]
@mancuniancol will have to improve the icons if we want this to look as good as your mock-up ;)

**Comment by mancuniancol** [comment]
Well, I think we have real graphics designers here. I just use the same logo file from the website. But, I don't mind to use any artwork who want to share.

**Comment by scakemyer** [comment]
Looking at this, seems you'd also have to return the path to icon, just like the `provider` field that now returns the name. But I still haven't dissected how the callbacks actually work, so maybe none of that is necessary and even the `provider` field for the name could have been avoided in the first place...

**Comment by Greenbaburu** [comment]
If appreciated it I can redraw the providers icons following the previous mock-ups logic. but a little bit nicer. @mancuniancol @scakemyer

**Comment by mancuniancol** [comment]
@Greenbaburu, that it would be great if you can do that.  I am planning to modify them to the new configuration. Then, it will be perfect to add the icons too.  Of course, it will take some time to finish all.  I don't have too much time lately.  But, I will do my best :)

**Comment by nix87** [comment]
You guys are amazing!!

I thought it can be better with last dialog but I was sooo wrong. This (like in Greenbaburu picture) looks stunning!

Is it possible that resulution got advantage over seeders like in those pictures? First 1080p, then 720p, then 480 in that order. I think it would be much more nicer to have all sorted nicely like that. O.M.G. That picture kicksass xDD

**Comment by scakemyer** [comment]
The sorting / resolution preference is a different issue, see #191. Leaving this one here open since we'll probably be doing more improvements after I release those new changes :)

**Comment by mancuniancol** [comment]
Just to be clear @scakemyer, the logo from the provider, you will get it from the icon property from the provider itself?  Or I need to add another key to the return payload?

**Comment by scakemyer** [comment]
It needs another key in the return payload, `"icon": settings.icon` does the trick

**Comment by mancuniancol** [comment]
OK great

**Comment by mancuniancol** [comment]
I will start tomorrow to implement that

**Comment by nix87** [comment]
@scakemyer 
Wow that thing on issue #191 is a lot more complex then what I ask? xD If you can do that then really sky is the limit for Quasar. :D 

I only meant for resolution preference but in stream list dialog. So far streams are sorted by seeders number and I was meant is it possible to have same dialog as on that picture from Greenbaburu? Stream to be sorted by resolution and not seeders. On that picture we have resolution as priority, then seeders number. Just that? :)

**Comment by Magic815** [comment]
@Greenbaburu's picture shows effectively what I would've suggested. As for displaying the provider, what if we had a user setting "Show Provider Info". If Off, then it would not show the icon or the name like @dimitriss is suggesting. But if it's on, then it would show by the provider name and icon. And in the case of merged stream hashes, it would simply say "multiple providers" and have a 'multiple' icon associated with it.

**Comment by scakemyer** [comment]
Well that new layout with icons and color-coded resolutions is already implemented, releasing it in v0.9.18 shortly, they're just still sorted by seeders until #191. I'm not going to be adding an option to display the providers or not, with or without icon and whatnot. Way too much trouble for no actual benefit. Showing it came from multiple providers sounds reasonable.

**Comment by Magic815** [comment]
That sounds fine to me. For my use, I would have kept the provider name/icon on (even if there was a setting to turn it off) just because I'd like to be able to take mental notes of where most top streams are coming from. But I agree, a name and icon for merged (multi) streams would be a nice touch.

**Comment by nix87** [comment]
Honestly I would also love to keep names and (new great thing) icons to show from which provider I streaming torrent. It's just nice to see that in dialog list, second it's fair to mancuniancol and third if we get providers for private trackers in future we must know from which tracker we took torrent it will be easier to follow.

**Comment by scakemyer** [comment]
Names are staying, icons will be here to stay also. Only thing that might change regarding those is a little something else that would say if results were merged. Blended icons? ;)

**Comment by nix87** [comment]
You mean if e.g. rarbg, kickass and magnetdl have all same The Martian 1080p BluRay SPARKS that will be merged in one multi something and will have different marking?

Yeah, I like that idea.

**Comment by scakemyer** [comment]
Exactly, right now the first one gets the provider name (and icon), but there's no indication that other providers returned the same infohash also. The different fields get merged (overridden if not empty really, not ideal either) by subsequent results, but that's it. It's an easy fix, I'm just not sure how to display it so it both makes sense and doesn't bloat the listing.

**Comment by mancuniancol** [comment]
It is really nice the extra information. But, I think that the first which gets the info is enough. Otherwise, it will be too much information at the nobody will check.  I think with the addition of the logos is enough.

**Comment by mancuniancol** [comment]
Btw, I think that @Greenbaburu will need sometime to finish the artwork from all torrent websites. I won't wait for him, I will update the providers, I can one work half an hour every day to that :( but I think that it will be enough

**Comment by nix87** [comment]
Do you think it's necessery that now when resolution get colors to have colored names of the providers too? 
All in all I'm fine with how dialog is looking now, I like ti, just my humble opionion is it's too much colors right now  :) 

But at the end if you decide to stay like this it's not big problem at all. +1

**Comment by mancuniancol** [comment]
The color system is for me. It makes easier to identify the names. But, I could send clear name to Quasar

**Comment by lcaleixo** [comment]
@exzilexv What is the skin that you are using with kodi? :)

**Comment by nix87** [comment]
@mancuniancol 
Ok, I understaind +1

Can't wait to see how it will looks with torrents ordered by resolution preference btw. :)

**Comment by mancuniancol** [comment]
Ok. I've released 2 providers with the new structure.  I will try to release at least one per day :palm_tree:

**Comment by nix87** [comment]
Great job Mancu +1

**Comment by Greenbaburu** [comment]
If you agree I can merge with pull requests the icons ("notmuchcolored" version) on @mancuniancol  's providers when he released them. Eventually i will change these later with a monocrome version; If you don't like the result. @scakemyer

**Comment by mancuniancol** [comment]
Yes, please.

**Comment by scakemyer** [comment]
I like the colors in the provider names also, it's not too much color. Eat the rainbow.

**Comment by Greenbaburu** [comment]
An idea for multi torrent icon

**preview**
![mt](https://cloud.githubusercontent.com/assets/8045152/13093836/a0da7708-d507-11e5-9993-f3b0b0abe4c3.jpg)
**.PNG**
![mt](https://cloud.githubusercontent.com/assets/8045152/13093838/a2a75c04-d507-11e5-9e3d-cff2df229396.png)

**Comment by exzilexv** [comment]
@lcaleixo Its Freds "Modded Bello" skin, here the link to his repo https://onedrive.live.com/?authkey=%21AEqdv9mLc8ZIkzY&cid=B043083BA0F1203F&id=B043083BA0F1203F%2113828&parId=B043083BA0F1203F%212068&action=locate

**Comment by exzilexv** [comment]
Cool stuff! @Greenbaburu

**Comment by nix87** [comment]
Great stuff Greenbaburu +1

**Comment by mancuniancol** [comment]
@scakemyer, it is really easy for me. I have already coded that settings. Name or settings.cleanName. I will leave for the moment the colour name. It could be changed anytime :)

**Comment by mancuniancol** [comment]
@Greenbaburu, yeah it really is great your job.

**Comment by Greenbaburu** [comment]
Thank's guys!

**Comment by scakemyer** [comment]
So awesome I had to get it into the hotfix release, couldn't help it ;)

**Comment by scakemyer** [comment]
Closing this one, sorting is in #191 and we can open a new one for other upgrades and changes. Nice job folks
