### ISSUE TITLE
Be able to select per movie/tv show to save the file

### ISSUE THREAD

**Issue by zorg1977** [scakemyer/plugin.video.quasar#173]
Be able to open a dialog box before playing the content to select if should be saved or not (instead of a all or nothing feature).
The content will be saved in the location specified in the preferences.
This feature (the popup window) could be enable/disable globally through Quasar preferences ("Per movie save window [true|false]")

**Comment by ShlomiD83** [comment]
https://github.com/scakemyer/plugin.video.quasar/issues/14
