### ISSUE TITLE
can't proceed to Season>episode list Tv shows "Unforgotten" and "Horace and Pete" 

### ISSUE THREAD

**Issue by pitecantropo** [scakemyer/plugin.video.quasar#179]
After searching for tv shows "Unforgotten" or "Horace and Pete" cannot enter beyond the title to seasons and episode list. 

Checked with both windows (paste below) and mac.

http://pastebin.com/4f3LmqgY

**Comment by scakemyer** [comment]
Please no pastebin, it's an awful site, the SourceForge of pastebins. Use http://xbmclogs.com/ or add your file directly in the issue.

**Comment by pitecantropo** [comment]
here is the log.

http://xbmclogs.com/pwqctkla9

**Comment by scakemyer** [comment]
The show is missing an ID. This should be handled better but there's nothing we can do about it other than that. Other searches return valid results?

**Comment by pitecantropo** [comment]
So far i've only noticed this behavior with these two shows. 
Thanks for your help and response.

**Comment by pitecantropo** [comment]
This is now fixed since update to v0.9.20.
Many thanks.

**Comment by scakemyer** [comment]
Great, good to know :)
