### ISSUE TITLE
Keeps asking me to restart and doesn't show addon loaded at the beginning

### ISSUE THREAD

**Issue by deusbraga** [scakemyer/plugin.video.quasar#18]
Keeps asking me to restart and doesn't show addon loaded at the beginning. I've already tried restarting kodi, rebooting the pc and reinstalling in a fresh version of kodi. To no avail.

**Comment by scakemyer** [comment]
How big is the zip file you downloaded?

**Comment by deusbraga** [comment]
1.13mb..

**Comment by deusbraga** [comment]
please  forget this problem. I feel so dumb right now...

**Comment by scakemyer** [comment]
Don't worry, you're far from the first one. The Download section on the front page now says **Do NOT use the Download ZIP button on this page.** to try and avoid this issue.
