### ISSUE TITLE
Android TV : can't open torrent file

### ISSUE THREAD

**Issue by Kant73** [scakemyer/plugin.video.quasar#187]
On my Nvidia Shield TV, I can't open a torrent file that I downloaded on my SD card. I have a HTTP Error 500 Internal server error when I try to open the torrent file and quasar crash. I'll provide logs when I can ;-)

**Comment by MrLegendary** [comment]
I got the same error when trying to download subtitles. You got a fix yet?

**Comment by felipejfc** [comment]
+1 for problem downloading subtitles, does not work on my firetv

**Comment by MrLegendary** [comment]
It has something to do with write permissions on my nvidia shield tv. Haven't figured out how to fix it yet. I'll let ya know when I know more.

**Comment by felipejfc** [comment]
If I remember it well, on my firetv it also was a problem with permissions, I've collected some logs once but they've expired, I'll collect again later.

**Comment by scakemyer** [comment]
Fixed by requiring a writeable download path. Subs are a different issue, see scakemyer/quasar#13
