### ISSUE TITLE
sliding/moving torrent names

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#190]
Can you bring back moving torrent names when it's too long to stay at once in torrent stream view dialog? This stopped after dialog changes, untill that in old dialog it was present. Sometimes is hard to see which encode is movie before you press play.

**Comment by m4xc4v413r4** [comment]
What resolution are you seeing this at? I usually see the full length of it with plenty of room to spare :/

**Comment by nix87** [comment]
1280x720

Maybe could be that. I didn't think about resultion that could be reason?

**Comment by m4xc4v413r4** [comment]
Maybe, I'm gonna test it out in a few minutes.

**Comment by m4xc4v413r4** [comment]
Mmh, didn't have a chance to test at 720p but even at 1440x900 I can still
see the entire names.

**Comment by nix87** [comment]
Nevermind bro, thanks for your trying anyway +1

It's just happens occasionally, not every time anyway.

**Comment by m4xc4v413r4** [comment]
ok, i tried a million different resolutions, including using the monitor on it's side so that vertical was bigger than horizontal, and only in VERY small sizes did i get the text getting off screen and it scrolled :/

Can you take a picture of your case so i can see it better? :) It's strange that it happens to you since the dialog with the sources seems to scale with the windows, as does the fonts in it.

**Comment by nix87** [comment]
It's not Quasar fault. Some providers just cut full name of torrent so I was thinking it's problem in dialog but it isn't. And really it doesn't matter it happens just on some of them (torrents).

btw. My Kodi is installed on other computer who I use just for Kodi and I connected him to the my hd ready lcd so it doesn't have connection with this PC on whom I writing now :)

**Comment by m4xc4v413r4** [comment]
Ok, if it isn't a problem with Quasar then @scakemyer can close this problem :)

**Comment by scakemyer** [comment]
Fixed in scakemyer/quasar@390d733

Torrent names had to be truncated for the first iteration of the two line Choose stream dialog, which isn't needed anymore with i9's upgrade to XML based dialogs since lines are properly split. You'll get the full / sliding names again in the next version.
