### ISSUE TITLE
Resolution preference

### ISSUE THREAD

**Issue by m4xc4v413r4** [scakemyer/plugin.video.quasar#191]
What do you think of having a resolution preference setting that would better choose the source when "Choose stream automatically" is On?

What i mean is, right now, when "Choose stream automatically" is On, Quasar goes for the source on the top of the list (which is the one with the most Seeders), but some times you have a better resolution with only a few Seeders less, so that one is actually the better choice since you still have more than enough seeders but have a better resolution.

So why not just configure the providers not to show the lower resolution?
Well, because in many occasions I've encountered over the years of using this kind of addon, if you just go for 1080p for example, it isn't always guaranteed you'll even find any results, 720p usually has more results, especially in old movies, less known or less popular movies, and obviously, tv shows. Same for 480p, some times you can only find some old episodes in 480p.

Personally i don't mind opening the window and choosing for my self, but when someone around here wants to use my htpc, they don't know wth those things are and how they work, they know how to click the remote up and down and on the OK button to start xD

Is this even something that would be done on Quasar? Or would it be best to do on the providers? Or maybe do this on Quasar and remove the resolution filtering on the providers?!?! I donno...

I think the best would be to have a preference list, as in:
1.1080p 2.720p 3.480p 4.(nothing here for me xD)
Someone that doesn't have hardware for 1080p for example could have it like:
1.720p 2.whatever 3.blabla 4.bananas

It would need "rules" to make these choices, obviously.

Well, above a certain number of seeders it gets irrelevant that this one has 3000 and the other has 2000, you'll most probably get full speed on both so at high seeders it should just choose the resolution of your preference and ignore if one has double the seeders or not.

At low seeders, the higher seeder number should continue to be the optimum choice, if one has 5 and the other has 2 it's usually a huge difference.

For the rest of them it could calculate a simple % or something of the sorts to choose, for example:
source 1 - 480p - 151 seeders
source 2 - 720p - 135 seeders
source 3 - 1080p - 117 seeders
.
Preferences go like 1.1080p 2.720p 3.480p for example.
In this situation, 1080p is below 720p and 480p so they have to all compare to each other.
So if the % was, let's say 80, 80% of 151 is ~120, which validates source 2 (which is higher than source 1 in terms of preference) as the better source, as it has over 120 seeders, but 80% of 135 is 108 which validates source 3 as the better source (once again because it is the highest preference of the 2 compared).
In this example, if source 3 had 105 seeders for example, source 2 would have been chosen since it's the highest on the preference list that doesn't break the "rule".

Another different example.

source 1 - 480p - 181 seeders
source 2 - 1080p - 153 seeders
source 3 - 720p - 120 seeders

80% 181 is 144, source 2 is better and that's it, because source 2 is already the 1st preference.

Yeah, i know i suck at explaining this crap xD It was like a second in my head and then i looked at the monitor and it was a wall of text...

**Comment by hfmls** [comment]
this could be cool

**Comment by scakemyer** [comment]
Yeah you kinda suck at explaining it, but I get the gist of it ;) There's definitely room for improvement, and I'm pretty sure this should be in Quasar and not the providers.

**Comment by Magic815** [comment]
So I have some ideas in regards to this. Whether or not some or all of this should be implemented in the providers or in Quasar is up for discussion.

I think we want to have two categories with settings: limits and preferences.

For limits, I could see max size, resolution, and min seed count being useful. For users on smaller devices with finite space, they could set a hard limit on the max size allowed for searching. Setting default for max size is blank or zero - meaning no limit. For resolution, the settings could have three check boxes - one for 1080p, 720p, and 480p. All are on by default, but can be switched off if the user doesn't want one or some to be searchable at all. For min seed count, it would be defaulted to zero (or 1 if Quasar only pulls seeded torrents in the first place). But then the user can raise the min limit to something higher if they want.

Now we get to preferences. I could see Quasar having three main options. 'Seed Driven', 'Resolution Driven', and 'Balanced'. Correct me if I'm wrong but Quasar right now just picks the torrent with the highest seed count, right? If so, that's what 'Seed Driven' would do. 'Resolution driven' would simply pick the highest resolution available (although it would grab the highest seeded torrent from within that resolution tier). So a 1080p, 4 seed torrent would be picked over a 720p, 50 seed torrent. Then lastly, with "Balanced", we'd have to come up with some sort of formula to balance seed count and resolution. @m4xc4v413r4's original post gives one suggestion on how to do it, but we could think more about how we want the formula to work exactly.

Thoughts?

**Comment by scakemyer** [comment]
Most of the limits are already implemented in providers except for seed count, and I think it makes sense to keep it that way. Seed count is determined after querying the trackers once results are received, so only that minimum limit would go in Quasar.

As for the sorting, resolution preferences and fancier "best stream" rules, that's definitely in Quasar. Implementing "resolution driven" (with secondary sorting by seeds) and "seed driven" (current behaviour) options is trivial. The "balanced" or "rule driven" sorting is a little trickier, but I like @m4xc4v413r4's proposal as it's also relatively simple to implement, and could be configured with a single setting of "Percentage of seeders required to choose next resolution" (on top of the resolution preferences themselves).

Going over steeve's code, there's already a kind of quality sorting when choosing stream automatically, implemented [here](https://github.com/scakemyer/quasar/blob/master/providers/sort.go), which assigns a quality factor based on resolution^3 + rip type. This is only used for movies and not episodes, so movies actually auto-choose the highest resolution as it stands, not the highest seeders, but episodes do. That being said, I'd rather change this to our proposed rule-driven sorting, because this one looks fancy but isn't really doing anything more than getting the highest resolution + best rip type, but could also be used as the basis for our resolution (quality) sorting.

**Comment by Magic815** [comment]
Regarding limits: gotcha, makes sense.

You bring up a good point, though. Would you want to allow for separate sort settings for Movies and TV Shows? It might be nice to let the user sort each category differently.

**Comment by scakemyer** [comment]
That too, yes.

**Comment by m4xc4v413r4** [comment]
Glad to already see improvements to the idea :)

Yeah, size limits and keyword ignore and preference already exists on the providers.

I really like the 3 main options thing with the seed, resolution, balance choices.

**Comment by scakemyer** [comment]
Done, will be in v0.9.22 shortly.
