### ISSUE TITLE
Season search

### ISSUE THREAD

**Issue by tstrul1** [scakemyer/plugin.video.quasar#195]
It would be great if I could right click on a specific season and select "choose stream" and search for the whole season (season pack)

**Comment by hfmls** [comment]
Yes,  this

**Comment by ofiryaish** [comment]
indeed!

**Comment by likeitneverwentaway** [comment]
Awesome! Would it be possible to "assign" a specific torrent to a season? I'm not sure how Quasar handle multiple files but that would be great.

**Comment by scakemyer** [comment]
Included in the upcoming v0.9.23, it's now up to the providers to support the `search_season` method.

**Comment by mancuniancol** [comment]
I've tried to implement that in 1337x, but I don't get any way to make it work.  I've added the search_season function but the provider is not called :P Or I am missing something.

**Comment by scakemyer** [comment]
Added `search_season` as last parameter to `provider.register` ?

**Comment by mancuniancol** [comment]
I've forgot that. I shouldn't code after party hehhe

**Comment by rik91** [comment]
There is url for test like this  ?
http://localhost:10001/provider/<PROVIDER_ID>/show/<TMDB_ID>/season/<SEASON>

**Comment by mancuniancol** [comment]
@scakemyer, I confirm that registering the search_season works.

**Comment by tomtomclub** [comment]
Thanks men

**Comment by ofiryaish** [comment]
I am yet to understand how to search for season
can someone explain?

**Comment by mancuniancol** [comment]
It is easy, you just use the contextual menu when the list of season appears in Quasar. It will find for season pack torrents

**Comment by ofiryaish** [comment]
if i understood- enter the tv show season list, right click on the season which i would like to watch, choose "season pack torrents". if the answer is yes then it's not showing me this option. 
thank you

**Comment by likeitneverwentaway** [comment]
After opening the contextual menu on a season you should click on "Choose stream".

**Comment by ofiryaish** [comment]
it show me "no links were found" although i got alot of providers. how it can possible?

**Comment by mancuniancol** [comment]
What is it your time out settings in Quasar?

**Comment by mancuniancol** [comment]
Or it might be there isn't season package available

**Comment by ofiryaish** [comment]
default. i now changed it to 30 sec, and it didn't change nothing. "no links were found" came up after 2-3 sec.

**Comment by rik91** [comment]
Tout provider are up to date ?

**Comment by ofiryaish** [comment]
Or it might be there isn't season package available- 
not possible, i checked more then 20 popular tv shows.

**Comment by ofiryaish** [comment]
rik91- they up to date.

**Comment by mancuniancol** [comment]
Only with version 1.3.0. But it is better to follow this conversation in other place, because it is out of the topic

**Comment by ofiryaish** [comment]
where i can talk with you? 
version 1.3.0 of what? the providers?

**Comment by mancuniancol** [comment]
Github.com/mancuniancol or tvaddons

**Comment by ofiryaish** [comment]
version 1.3.0. of what?

**Comment by MrLegendary** [comment]
Version 1.3.0 of [https://github.com/mancuniancol/script.quasar.1333x-mc](url)
