### ISSUE TITLE
quasar daemon not starting

### ISSUE THREAD

**Issue by entproject** [scakemyer/plugin.video.quasar#196]
Kodi 15.2 Windows 10 x64 system

Since the update to 0.9.12, quasar daemon is not starting in my machine. I can open the video addon and it works normally but when I click for a torrent using the providers, I don't get any result from the search.

I had installed 0.9.10 everything worked normally but since the update daemon is not starting. Same is for the latest 0.9.16 version. 

Log from latest 0.9.16
http://pastebin.com/raw/ixYLvTEG

If I unistall it and return to 0.9.10 everything works fine.
here is the log from 0.9.10 version that works normally
http://pastebin.com/raw/S3VBLxvN

**Comment by lcaleixo** [comment]
Look issue #142 
test now v0.9.17

**Comment by scakemyer** [comment]
Daemon is starting properly in both your logs, and it shows 0.9.15 not 0.9.16 but that's besides the point. There's no issue here.

**Comment by entproject** [comment]
Yes it caused by the greek translation

Problem solved
