### ISSUE TITLE
Better CinemaVision integration - background initial buffering

### ISSUE THREAD

**Issue by likeitneverwentaway** [scakemyer/plugin.video.quasar#197]
The way CinemaVision works is by analyzing the file's metadata, so if the codec is aac it will show a little bumper video corresponding - awesome! But you have to add your movie to the queue and then launch the sequence from CV. Of course this doesn't work with Quasar as opening the torrent selection is considered starting the movie for Kodi.  

If choosing the stream would only launch the first buffering in the background (notification style, exactly like when exiting a movie and download is still going) and then when it's ready another notification saying "Movie -  Added to queue" then I believe this would work (and would be great overhaul).

I don't know if it's the best idea, but the basic idea is to separate the initial buffering from actually launching the file, so Kodi will only considerate it's a video file when it actually is.

Thanks for your amazing work on this project!

Edit : so to make it a little bit clearer, my request would be:

- have an option to disable auto playing the movie, so the initial buffering would be in the background like any other download
- when the buffering is finished the movie is added to the queue

Athough I figured this might not be as simple as that since you can't add a torrent to the queue, so is it possible to make it so ?

**Comment by m4xc4v413r4** [comment]
Sounds nice

**Comment by likeitneverwentaway** [comment]
Hey @scakemyer I rephrased a little bit my idea, any thought ?

**Comment by scakemyer** [comment]
This will be covered by #253, but you described the desired process very well, basically buffering in the background and starting to play the file only when it's ready.
