### ISSUE TITLE
Insufficient free space check requires total size available even on resumed downloads

### ISSUE THREAD

**Issue by scakemyer** [scakemyer/plugin.video.quasar#2]
Bailing out was commented in scakemyer/pulsar@8225ffd for the time being. Need to move the check after either `status.GetTotal_done()` or `status.GetAll_time_download()` gets populated, so as to get an accurate reading on the free space needed with `torrentSize := btp.torrentInfo.Total_size() - status.GetTotal_done()`

**Comment by i96751414** [comment]
We should really work on this. I also think it should be fixed on v0.9.1, somehow I see this as a dangerous bug

**Comment by scakemyer** [comment]
Good point.
