### ISSUE TITLE
Opening stream mask remains on the foreground and nothing happens

### ISSUE THREAD

**Issue by Filosofos** [scakemyer/plugin.video.quasar#20]
Quasar mask with a note "Opening stream" remains open after choosing for a movie to be played. The following error appears on the log file:
"ERROR: CPythonInvoker(167, /storage/.kodi/addons/plugin.video.pulsar/navigation.py): script didn't stop in 5 seconds - let's kill it"

This happens only to certain cases and maybe it is a problem related to trackers (i saw a few of these "Tracker udp://trackername.com:6969" is not available because: Request timed out), but the mask was there not doing anything, so i had to kill it myself and search for the log file to find the error.
In order to bypass the error, i had to add some extra options to the providers which actually worked.

I can provide logs if needed.

**Comment by scakemyer** [comment]
Logs would be great, though I'm pretty sure I've seen the same problem.

**Comment by Filosofos** [comment]
Log sent through pm on the forum.
Thank you!
