### ISSUE TITLE
Option to show Original Title

### ISSUE THREAD

**Issue by m4xc4v413r4** [scakemyer/plugin.video.quasar#200]
Could we have an option to show the original titles instead of the translated ones?

Not everyone would want one OR the other, so the best choice would be to have an option to turn this on. Default should probably be off.

I just remembered this because of the update you just released, I was testing it and found it strange that now all the movies have strange names for me.

**Comment by scakemyer** [comment]
Sounds like a good idea. Plus you confirmed that this fixes the issue about titles not being translated ;) So having the option to choose either one will be the way to go.

**Comment by m4xc4v413r4** [comment]
Yeah, it definitely fixed it xD

**Comment by scakemyer** [comment]
hahah thanks for the laugh

**Comment by tomer953** [comment]
+1, right now i'm using a workaround in my skin:
https://github.com/tomer953/skin.phenomenal/blob/57a8fcc2c3bcabbbafe97bb9fd544c6eb3128951/1080p/Includes_Variables.xml#L343

but I think that should be in the addon settings instead.
b.t.w, if you will implement it, please try to fallback to the title, when the original title is empty.
thanks.
