### ISSUE TITLE
I can't hide the notification saying Quasar is downloading a torrent

### ISSUE THREAD

**Issue by NerosTie** [scakemyer/plugin.video.quasar#201]
It's about the notification at the bottom right of the screen (on OSMC) saying Quasar is downloading a torrent. Because it still here when the movie is playing, I want to hide it. 

So, I unchecked the option `background handling of torrents` and the notification disappears... but if I launch an other video or if I reboot, it's here again!

**Comment by scakemyer** [comment]
You first issue of background dialogs appearing over your movie is a skin issue. As for the second one, go in the Torrents section and delete the previous one that got there when you had Background handling enabled and that will solve your problem. The option is working correctly.
