### ISSUE TITLE
Add option to view download percentage one per X percent 

### ISSUE THREAD

**Issue by yakirp88** [scakemyer/plugin.video.quasar#202]
Is it possible to add option to select that the download percent message will show only once per few percent by selection?

**Comment by scakemyer** [comment]
I don't think that's a good idea. A lot of work to implement for very little benefit, and I'm pretty sure it would just be annoying. I don't think adding an option to disable background progress dialogs would be a good idea either.

**Comment by yakirp88** [comment]
But it notify always even while playing a video.

**Comment by scakemyer** [comment]
That's a skin issue, they don't show on properly coded skins while playing.

**Comment by yakirp88** [comment]
Ok thanks

**Comment by scakemyer** [comment]
Which skin are you using? Might help to know which ones are problematic for other users, or if I'm actually wrong and it's the Kodi version or something else.

**Comment by yakirp88** [comment]
Eminence 2

**Comment by scakemyer** [comment]
That must be it then. Please try with Confluence just to confirm, and if it does hide the background progress then it's definitely the skin.

**Comment by yakirp88** [comment]
With confluence it work fine

**Comment by scakemyer** [comment]
Sorry then, skin issue. Hope those devs can fix it.
