### ISSUE TITLE
Add download option to context menu

### ISSUE THREAD

**Issue by yakirp88** [scakemyer/plugin.video.quasar#203]
It will be great to add download button.

**Comment by NoGood** [comment]
Yes I would also like to see this option. I have a very spotty connection and I often get a timeout when downloading larger mediafiles. Shows are not a problem, movies always are

**Comment by XayOn** [comment]
I've been working on something way lighter than this (completly written in python) and I was planning on implementing a stream + download button, you might be interested in that idea =)

(And yep, it's just a 'when finished, move it to downloads folder + don't delete it)

**Comment by wlbe4** [comment]
It would be great if that new Download option will allow to download a complete season.
Thanks.

**Comment by scakemyer** [comment]
Implemented part of it a few months ago, but adding a torrent is currently too tightly coupled with the player so it'll need more work.

**Comment by scakemyer** [comment]
Sorry to say I'll be skipping this one... the context menu is already overcrowded and I really don't feel like adding yet another "add torrent" handler for this particular use case. Using background handling (which will probably disappear as a setting and "just work" depending on the keeping/deleting settings) to start a stream, cancelling it right away and letting it download, or using the web UI to either just add a torrent are already perfectly valid ways to achieve this.
