### ISSUE TITLE
Global search results use outdated formatting

### ISSUE THREAD

**Issue by yakirp88** [scakemyer/plugin.video.quasar#204]
When searching the source selection looks like it was in pulsar and not like the new selection screen

**Comment by scakemyer** [comment]
Nice catch, will fix.

**Comment by yakirp88** [comment]
Thank. You are doing amazing job

**Comment by scakemyer** [comment]
Just noticed something... it's a directory listing, not the same as the previous Pulsar dialog for streams. I agree it doesn't look as great though, so the formatting could be improved, but it's just not the same thing and won't be either.

**Comment by yakirp88** [comment]
So you say it is impossible to make the source selection like when navigating through menus?

**Comment by scakemyer** [comment]
I'm not saying it's impossible, just saying it's currently not using the same thing, a directory listing vs the custom dialog for stream selection. I'll see how easily I can make it use the dialog as I'd also prefer that approach.

**Comment by yakirp88** [comment]
Thanks sounds greay

**Comment by m4xc4v413r4** [comment]
This man works 24/7 o_O
