### ISSUE TITLE
JSON parsing improvments

### ISSUE THREAD

**Issue by zorg1977** [scakemyer/plugin.video.quasar#212]
According to these benchmarks (http://artem.krylysov.com/blog/2015/09/29/benchmark-python-json-libraries/, https://blog.hartleybrody.com/python-serialize/), JSON performance may be better using ujson as a drop in replacement of json (and simplejson).

**Comment by scakemyer** [comment]
Both ujson and python-rapidjson use a C++ library with Python bindings, and I don't want to add yet another dependency to cross-compile for all platforms unless it's absolutely necessary. Most of the JSON parsing is done by the Quasar daemon anyway, so it's only the navigation items that get sent to the add-on itself that gets parsed which is quite minimal already. It's just not worth the trouble and possible reliability problems of having to cross-compile those.
