### ISSUE TITLE
Quasar causing shutdown crash on my Kodi setup.

### ISSUE THREAD

**Issue by ScottishLad** [scakemyer/plugin.video.quasar#214]
Hoping someone can help. Firstly loving Quasar, keep up the great work.

I am running latest version of Quasar on my Android Lollipop M8s+ box. Running Kodi 15.2

Since installing Quasar every-time try close or shutdown Kodi, it crashes on shutdown screen and I need to force close Kodi. If I disable Quasar, and then try shutdown works first time every-time. Hoping someone can help me resolve?

**Comment by korenziv** [comment]
Hi @scakemyer,

same problem as ScottishLad

from day one, when I using Quasar, I faced with Kodi Exit problem.
I will very appreciate if you can look in my log and see if its Quasar related or not.

Thank you very much for your help till today, Ver 0.9.17 working great.

http://pastebin.com/sJDJwwLP

**Comment by scakemyer** [comment]
Please use http://xbmclogs.com or just drop the logs in the issue next time, pastebin is a bad website and it's using CloudFlare

**Comment by scakemyer** [comment]
The shutdown sequence was made a lot cleaner and improved a lot in the last few versions, I'll need more complete logs to look into this.

**Comment by korenziv** [comment]
HI @scakemyer 

attached 
http://xbmclogs.com/p1on9lqwj

Thank you.

**Comment by scakemyer** [comment]
Does v0.9.22 fix the problem?

**Comment by korenziv** [comment]
Hi Scakemyer. 

Its seems like it ok. 
I will folow it this week and update if its OK.

Thank you.

**Comment by ScottishLad** [comment]
Mines seems to still crash. It also crashes when try disable the addon too.

Can you confirm how I go about doing log so I can upload?

**Comment by korenziv** [comment]
Yes. I still have this issue. 
New Kodi installed from sceatch.

**Comment by scakemyer** [comment]
Then new logs please, as I can't replicate this issue anywhere I try.

**Comment by korenziv** [comment]
attached log.
just crashed ;(
http://pastebin.com/LsD8rGd4

**Comment by sling86** [comment]
Also happening for me on windows 10: http://pastebin.com/Fn2emUNq

**Comment by scakemyer** [comment]
http://xbmclogs.com/ please. I'll change the return code to force 0 as you did, if that keeps Windows from complaining.

**Comment by ShlomiD83** [comment]
Changing that line actually worked, didn't crash at all yesterday on win 7.

**Comment by bramgod** [comment]
i have a nvidea shield tv , and im facing this problem to i can't close kodi because of quasar 
what can i do?
replace a file on my shield tv or so?
