### ISSUE TITLE
More information in torrents list

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#215]
I was wondering is it possible to implement more info about seeding torrents? Like from which tracker torrent is downloaded, or how much is currently seeded, or seeding time. It woiuld be easier to follow ratio and seeding with those info presented. :)

**Comment by m4xc4v413r4** [comment]
More seeding control would be nice, I always like to seed to at least 2:1, unless it's seeding really fast, then I'll just let it seed for a day or so, with my upload speeds it'll go to 10's:1 easily.
