### ISSUE TITLE
Adding support to play torrent file from local files.

### ISSUE THREAD

**Issue by mancuniancol** [scakemyer/plugin.video.quasar#22]
I am wondering if it is possible to add the support to play torrent file from local storage.

**Comment by scakemyer** [comment]
@i96751414 Did you mention you already had made progress regarding this?

**Comment by Palatosino** [comment]
You already have "torrent2pulsar" that I supose that will be very easy to modify to be "torrent2quasar"

**Comment by i96751414** [comment]
Nope, but I can work on this tomorrow

**Comment by scakemyer** [comment]
My bad, confused this with the multi-file torrent support.

**Comment by i96751414** [comment]
@scakemyer I'm currently working on this

**Comment by mancuniancol** [comment]
Great

**Comment by scakemyer** [comment]
Included in v0.9.9, enjoy :)

**Comment by mancuniancol** [comment]
Great, thanks
