### ISSUE TITLE
Custom dir for shows and movies 

### ISSUE THREAD

**Issue by cali4nick8** [scakemyer/plugin.video.quasar#222]
It would be good to have the option to choose different library paths for shows and movies. I have them in different places, so when I choose to add a show to the library it creates a new folder called shows inside my TV folder.

**Comment by hfmls** [comment]
Yeah

**Comment by nix87** [comment]
I think that option is already there. I decided where library folder would be in my PC and i called it quasar library and then in that folder Quasar automatically creates movies and tv show folder. Ok you can't select strictly movie and tv show but what is the difference when you can create one quasar library folder and put it where you want?

**Comment by scakemyer** [comment]
So this is about library integration paths, which already creates its own Shows and Movies subfolders. @i96751414 can pitch in on this, but this just seems redundant, and more trouble to implement than what little benefit it would bring. Library integration just creates .strm files, so make a symlink in your TV folder if you so want to have them show in there.

**Comment by cali4nick8** [comment]
Hi! Thanks for replying. 
My question was actually quite simpler. In the options there is an option to choose library path. My suggestion would be to have two options. One for TV and another for films.
