### ISSUE TITLE
"Navigation Error:HTTP" when trying to add TV show to library

### ISSUE THREAD

**Issue by dtsexpert** [scakemyer/plugin.video.quasar#228]
Got the "Navigation Error:Http" when trying to add TV show to library. The library location is full read/write permission (internal memory of the Android Box)
Android 5.1.1, Quasar 0.9.19, Kodi 14.2
Search via TV is fine, playing stream is fine. Just the above error prohibiting add the series to the library.
When you have time, kindly please check.
Once again, thanks so much for everything you coders have done.

[log.txt](https://github.com/scakemyer/plugin.video.quasar/files/133875/log.txt)

**Comment by scakemyer** [comment]
Fix is almost ready, along with some serious clean-up of variable names for IDs. The mix of TMDB / IMDB / TVDB IDs was a real mess.

**Comment by hfmls** [comment]
good to know, thank you for that

**Comment by trongthuan0311** [comment]
Can not update to 0.9.20 althought deleted QuasarDB.json, it's crashed and restart everytime

**Comment by scakemyer** [comment]
Fixed in v0.9.20

**Comment by dtsexpert** [comment]
@scakemyer 
I'd like to confirm that the fix works great.
For other user,
Note that you need to use the TMDB (The Movie Database) as scraper. Install it if needed, then select TMDB as default scraper. TVDB is no longer work.

**Comment by Jizar07** [comment]
TMDB is not working either, having trouble connecting to remote server
