### ISSUE TITLE
Provider priority results

### ISSUE THREAD

**Issue by corrpel** [scakemyer/plugin.video.quasar#229]
It would be great to have a priority regarding the results for providers, especially when using autoplay.
For example, i have rarbg with additional word (dts), that provides the best quality available, since also the video bitrate is high on this videos. Also, i am blocking yify files in most of providers. It is not on my taste of quality. So the way i see it, is ordering this way:
Display the first (one result by seeders) result of every provider by providers sorting, then have them bulk. You can give a color to the ones by priority and another for the bulk ones.
So for better understanding, i'll give an example:
I have 3 enable providers:rarbg, kickass, 1333x (in order of priority).
For kickass, i will block files with yify, for rarbg i will allow only the ones with dts and for 133x i will leave it default. every addon is configured for 10 sent torrents to pulsar in results.
So, from my feature request, the result should be like this for movie "test":
1. 100/32 Test.dts - rarbg
2. 3020/500 Test.whatever - kickass
3. 4000/100 Test.yify - 1333x
<------------------------------------------------>
4. 10302 / 5034 Test.whatever - kickass
5. 9966 / 4345 test.whatever - kickass
6. 6500 / 543 test.blabla - 1333x
7. 5200 / 4233 test.1080p - rarbg
......
30. 0/0 test.480p - kickass

What do you think about it?

**Comment by scakemyer** [comment]
Duplicate / very related to #191
