### ISSUE TITLE
Movies Names sometimes appears as Gibrish when the languge is Hebrew

### ISSUE THREAD

**Issue by meijin007** [scakemyer/plugin.video.quasar#23]
(Don't know if its happens with other languages, Doesn't happen in English)
see attached PS. I think it's since trktv API change.
![quasar](https://cloud.githubusercontent.com/assets/4030466/12697513/976071d6-c78e-11e5-8122-59030340557a.jpg)

**Comment by scakemyer** [comment]
Can you confirm this is caused in Quasar or if it's from an external API?

**Comment by meijin007** [comment]
Happens also in Quasar. How can I find out if its from the external API?

**Comment by i96751414** [comment]
I think this is not a Quasar issue... Maybe a trakt issue?

**Comment by meijin007** [comment]
I think the trktv api change, and wasn't update in the daemon. No idea how to verify

**Comment by meijin007** [comment]
I re-checked it. seems to happen only for movies. any idea how to isolate the problem?

**Comment by i96751414** [comment]
@meijin007 I would like to help you, but it really seems to be a trakt issue

**Comment by scakemyer** [comment]
Seeing the same issue in a VM, using english, and also only in movies...

**Comment by scakemyer** [comment]
This was reported first but I'll close as a duplicate of #82 since the problem seems to affect more than just Hebrew
