### ISSUE TITLE
File name when sent from "Play to kodi" or android client

### ISSUE THREAD

**Issue by corrpel** [scakemyer/plugin.video.quasar#230]
This issue was also in pulsar version. Currently the chrome extension "Play to kodi" was updated to support quasar. The issue is if you play a magnet using this chrome extension the name of the video if you click info is "play". So the infolabel is not populated correctly. This will also happen on yatse when they will update their app for quasar. The real issue is when looking for subtitles with other addon then quasar, you will get subtitles for the word "Play" instead of the movie name. Also in "quasar" subtitle addon you will get aditional "Play..." movies subtitle. Please look into it, it will be great to have a fix for this and i am looking for it for a very long time. Thank you!

**Comment by m4xc4v413r4** [comment]
Yeah, this "problem" has been with Pulsar since day 1 too, it happens when you send a link to be opened from anywhere outside of the addon it self. For example that chrome extension, or from a remote app on your phone.

It's not a pressing concern but would be great to see it fixed some day.

**Comment by scakemyer** [comment]
Closing for #256
