### ISSUE TITLE
Providers receive the translated TV Show names causing no results to be found

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#234]
Hi there, since version .18 all my torrent search and stream are made in portuguese (my native language) i already tried the new option to use original name but it isn't working.

Any idea how to fix it?

**Comment by ShlomiD83** [comment]
same here with hebrew. not getting links for some tv shows cause of that i believe.

**Comment by scakemyer** [comment]
Ok I get what you mean, will look into it, but your question is actually the opposite of your question...

**Comment by lcaleixo** [comment]
I think I have a similar problem.
Is configured to pull the original title.
But he pulls the translated title and does not find fonts or torrents

**Ex:**
![kodi3](https://cloud.githubusercontent.com/assets/16961756/13117724/e555a1be-d57f-11e5-9b55-b05c8e571037.jpg)

**Now I ask to pull the title "SUPERNATURAL" ..**

![kodi](https://cloud.githubusercontent.com/assets/16961756/13117801/2a0abbb4-d580-11e5-952b-58e960e6ed04.jpg)

**He translates and pulls the title "SOBRENATURAL" ...**

![kodi2](https://cloud.githubusercontent.com/assets/16961756/13117914/9f4d649e-d580-11e5-8a61-04845539ceba.jpg)

**Finally he returns without finding anything ..
For "SOBRENATURAL" does not exist in searches...**

![kodi4](https://cloud.githubusercontent.com/assets/16961756/13118185/c9ea379e-d581-11e5-8adc-0575b1bbc320.jpg)

**Comment by ShlomiD83** [comment]
i have the same problem with "The Walking Dead". I see that you dont have episodes name, same here, do you have trouble with subtitles too?

**Comment by lcaleixo** [comment]
YES.... NO SUB TOO...

![kodi5](https://cloud.githubusercontent.com/assets/16961756/13118882/210584d6-d585-11e5-95e2-fd35060daaa1.jpg)

![kodi6](https://cloud.githubusercontent.com/assets/16961756/13118886/23547102-d585-11e5-8f08-602fafdeed7c.jpg)

**Comment by scakemyer** [comment]
@lcaleixo GOING ALL CAPS IS THE BEST WAY TO MAKE SURE I TELL YOU TO GO FUCK YOURSELF WITH YOUR ISSUE

You're also lucky I want to help other non-english speaking folks. I've had the 5-lines fix for this issue since yesterday, ALTHOUGH NOT YOUR SUBS YET, but decided to take a nap instead.

**Comment by lcaleixo** [comment]
@scakemyer 
Calm friend ..
Just forgot the caps lock connected ..
I did not want to call attention or being rude.
I apologize...
And thank you for looking at the problem ..

**Comment by tomtomclub** [comment]
@LCSLEIXO Lol subs work men try install New 
try new subs addon works here

**Comment by hfmls** [comment]
Hi there, so, i have an update on this issue, it is fixed now but here is the thing. Shows like dragon ball super and naruto shippuden are also in native language so it appears crazy chars or just random boxs as letters :sweat_smile:  Is there any way we could add exceptions like those two?

**Comment by lcaleixo** [comment]
@hfmls 
I downloaded the 0.9.21 version and let the option marked "prefer the original title" ...
So it worked for me ...
My language portuguese/brazil

**Comment by m4xc4v413r4** [comment]
@hfmls I've always had that problem, like since pulsar was released, any anime just shows boxes as the name.

**Comment by hfmls** [comment]
it was working ok before, either way, no problem.

**Comment by scakemyer** [comment]
I don't think there's anything I can do about languages not supported by the character set for your language. Providers are supposed to receive the original title regardless of the "Prefer use of original titles" setting, so the only solution is to not have that setting checked. Subtitles are also supposed to be using the original title regardless of that setting.

**Comment by Filosofos** [comment]
@scakemyer Trying to understand here if the last sentence in your post above should cover my problem mentioned in #95.
I still get wrong results when other subtitle addons are used than quasar's. And quasar brings subs in all languages and not in the only one i have pre selected in KODI's settings. Is that a known issue to you or should i open a new issue?

**Comment by scakemyer** [comment]
I haven't looked into subs yet, and yes it's a different issue, #95 being one.

**Comment by Filosofos** [comment]
Ok, thank you for the answer.
