### ISSUE TITLE
Episode names not showing correctly

### ISSUE THREAD

**Issue by infinicode** [scakemyer/plugin.video.quasar#239]
I've started using Quasar version 0.9.20 under Kodi 15.2 and Ubuntu Wily, and I've noticed that the tv shows episodes are not displayed correctly. With pulsar they used to show as:
1x01 Blablala
1x02 Blublublu
1x03 Bliblibli

With Quasar some of the episodes are missing the season and episode number information. Find attached screenshot while browsing the the six season of The Walking Dead.

The daemon seems to be working ok, as the JSON seems to be fine (screenshot attached too). 

Maybe this bug is related to [#82](https://github.com/scakemyer/plugin.video.quasar/issues/82)?

![img_20160217_201845](https://cloud.githubusercontent.com/assets/1757109/13122658/64c2ea46-d5b8-11e5-8869-1524aacc43dc.jpg)

![json](https://cloud.githubusercontent.com/assets/1757109/13122673/711b8d20-d5b8-11e5-8359-1526075d5ebb.png)

**Comment by infinicode** [comment]
This seems indeed to be a duplicated of #82. Upgrading to a newer version of Kodi fixes the problem.

Version of Kodi with the error: 2:15.2~git20151101.0902-final-0wily
Version of Kodi without the error: 2:16.0~git20160205.0918-rc3-0wily

**Comment by scakemyer** [comment]
It's a duplicate indeed, but thanks for the great investigative work so far :) I'm also seeing the same, for both movie names and episodes (nice screenshot in the other issue, really looks like she's wondering "wtf are those scrambled titles").
