### ISSUE TITLE
Add mark as watched

### ISSUE THREAD

**Issue by peer23peer** [scakemyer/plugin.video.quasar#24]
First of all great work everybody working on this plugin after Steeve stopped and Pulsar came crumbling down so did my sanity ;-)

Could it be possible to add a "Mark as watched" option?

cheers
Jelle

**Comment by meijin007** [comment]
duplicate with: https://github.com/scakemyer/plugin.video.quasar/issues/16

**Comment by peer23peer** [comment]
my bad, sorry for not searching first.

**Comment by scakemyer** [comment]
Turns out, this isn't the same as marking strm files as watched... Mark as watched is missing from Quasar itself.
