### ISSUE TITLE
New providers icons set

### ISSUE THREAD

**Issue by Greenbaburu** [scakemyer/plugin.video.quasar#245]
If will see something weird, tell me please.
Sorry for my hilariuos and robotic english! :)
![iconset](https://cloud.githubusercontent.com/assets/8045152/13144920/b75a7874-d64d-11e5-816f-0740475f6aa9.jpg)

(Already sent to Mancuniancol)

**Comment by tobiasvandriessel** [comment]
That looks amazing, great job!

**Comment by hfmls** [comment]
awesome! thank you for your work

**Comment by nix87** [comment]
I can't describe how amazing this is.

Amazing work, can't wait to see them in Quasar.

**Comment by scakemyer** [comment]
Just to be clear, none of those are **in** Quasar except the generic multi-cloud icon. Please keep provider-specific stuff elsewhere.
