### ISSUE TITLE
No episode titles for languages that have no translations on TMDB

### ISSUE THREAD

**Issue by ramiyohay** [scakemyer/plugin.video.quasar#249]
Hi ,
My Kodi is in Hebrew language and since version 0.9.19 , there are no episode titles. I think that also the subtitles search is affected.

All I see is for example 01X01 , 01X02 and etc.

**Comment by ShlomiD83** [comment]
same here. with movies everything is ok, finds subtitles in a sec.
but with tv shows only quasar's subtitle addon is finding something..

**Comment by lcaleixo** [comment]
test version 0.9.21...
I will test too now..

**Comment by ShlomiD83** [comment]
allready tested, i see the episodes name only if i switch to kodi in english.

**Comment by lcaleixo** [comment]
I downloaded the 0.9.21 version and let the option marked "prefer the original title" ...
The titles appear in English ..
So it worked for me ...
My language portuguese/brazil kodi

**Comment by lcaleixo** [comment]
@ShlomiD83 
you're right..
same here.
My language kodi portuguese/brazil

**Comment by KillerJoeBR** [comment]
I'm not home to test it but it was something that was bothering me. I use the Prefer Original Title option and my language is portuguese/brazil. The movies section is fine. But the series i guess it wants the translated title and if there isn't one it stays empty. My suggestion is to have english titles as a fallback option in case there isn't a translated title yet. 

But my personal option would be to have the option for "use original titles" for tv series aswell.

**Comment by m4xc4v413r4** [comment]
Haven't used my htpc in a couple of days, went to check now, it updated Quasar to the latest, I think I had 19 or 18 maybe, and this is happening to me too.
No descriptions on episodes and no titles.

Movies are fine and everything other than episodes on TV shows is fine. Portuguese here.

Oh but episodes are just fine if I add the show to library and open through library, it's just happening inside Quasar...

Is this somehow related to that tmdb api key problem?

Also I noticed something else that I don't know if it's related, I tried adding the show Shameless to the library but for some reason the system isn't diferenciating Shameless US from Shameless UK, and it's adding the wrong show, it used to do it just fine before today.

**Comment by Wesleyl89** [comment]
I've got the same problem here. The subtitle search also just use the title for example "9x12", and it will find every episode with 9x12 in the name.

**Comment by scakemyer** [comment]
@KillerJoeBR is right, TMDB returns movie titles when the language isn't available, but returns an empty string for title and overview in the same situation for shows and episodes, which is pretty inconsistent behaviour. This means we'd have to check for available translations first, English or not since the same could happen for non-english shows requested with "en", and all of this would doubling the number of requests per page... The other option is to just not request a specific language, basically acting as "prefer use of original title". Since it says "prefer" in the option's name, I think it's an acceptable compromise for shows so it doesn't take twice the time to list them.

**Comment by scakemyer** [comment]
Sorry only episodes return empty strings, shows return original name when language isn't available. So this can be properly fixed.

**Comment by scakemyer** [comment]
Except even for shows that report available translations, names and overview are more often than not empty... Still, easy fix on its way :)

**Comment by ShlomiD83** [comment]
in some shows it's still empty and not getting english episode names and description while using hebrew i'm afraid.

**Comment by ShlomiD83** [comment]
is it possible for tv shows to use tvdb instead of tmdb? with tvdb we get episode names, description and subtitles with no problem.

**Comment by KillerJoeBR** [comment]
I can confirm that it's true. It's less often than before but there is some shows without episodes names. I think Arrow is one of them.

**Comment by ShlomiD83** [comment]
arrow is fine over here, big bang theory and shannara chronicles for example are missing epiose  names and description. i set my library to use tvdb and it works perfectly, names and subtitles as well.

**Comment by KillerJoeBR** [comment]
I guess it depends of the language: Arrow for me:

[Arrow](http://i.imgur.com/LW3I6iD.png)

**Comment by ShlomiD83** [comment]
i guess it does, lets wait for scakemyer..

**Comment by scakemyer** [comment]
Clear your caches, probably restart Kodi also, had to do both to test the fix.

@ShlomiD83 what you end up having in your library has nothing to do with Quasar but your scraper, please don't mix the two when reporting issues.

@KillerJoeBR does the first episode have its name translated then others empty?

**Comment by ShlomiD83** [comment]
Cleared cache and restarted kodi alot of times and nothing changes.

**Comment by KillerJoeBR** [comment]
@scakemyer 

Before the update there were some series with entire season (the most recent one) without episodes names and descriptions. Now i tried an lot of them and most have episodes names and descriptions but there are some like The Arrow , the flash, s.h.i.e.l.d. that two or more episodes have names and description and then all the rest have no episode names. But a few have description but no title.

Tried with kodi in english and there is no issues. But back to portuguese and the same issue occurs. But like a said its much less than before. If you need a log i can get one.

Thanks

**Comment by scakemyer** [comment]
That makes sense, so it's mainly an issue with inconsistent translations for shows that report having them, or after the last fix, that have a season's first episode title translated but not others. I'll implement a better fix, looping through each episode to check if there's a translated title is cheap enough to be worth it.

**Comment by ShlomiD83** [comment]
@scakemyer all i was asking if quasar can use tvdb for tv shows because it seems to working well (or better) than tmdb, wasn't trying to mix them or confuse anyone.

**Comment by scakemyer** [comment]
We just switched from TVDB to TMDB, and not going back. TVDB has its own inconsistencies and issues, shows and season listings themselves were already using TMDB but not episodes and actual season data,there was too much overhead querying both for basically the same data, and the mixed implementation was messy. TVDB is also behind CloudFlare which causes lots of users to not be able to reach it. You're free to use TVDB as your scraper when adding shows to your library.

**Comment by ShlomiD83** [comment]
OK, thank you for the quick answer, got it now. :)

**Comment by KillerJoeBR** [comment]
Just wanted to say that i think everything is working great now. Tried a lot of series and didn't find any episode name missing.

Thanks, good work
