### ISSUE TITLE
Configurable, or higher, overall timeout value for torrent play

### ISSUE THREAD

**Issue by bluenote73** [scakemyer/plugin.video.quasar#253]
I use a SOCKS connection to a VPN which tends to result in a little more lag time to get torrents up to speed.  I find that on lower-seeded torrents this can end up meaning that the initial buffering phase hasn't reached 100% before Quasar complains and calls a timeout.   I recognize this may not be something that everyone needs to change, so it may not make sense to be configurable, but presumably at the least a little higher wouldn't hurt anyone?

**Comment by scakemyer** [comment]
I've looked into this before, there's just no way of controlling that timeout since it's on Kodi's side. This will also need the refactoring of starting torrents, can't remember in which issue I mentioned that, but basically choosing the stream and buffering before calling PlayMedia, instead of calling that to trigger the whole process.

**Comment by NoGood** [comment]
Would it be possible to not have a buffer at all and just start the streaming. I would rather start / pause manually and wait. Instead of start / buffer / timeout.

**Comment by bluenote73** [comment]
I imagine no buffer would make everyone else miserable.  Maybe the 'handle in background' setting which I don't currently use is a way around this though, I don't fully understand how that works so I'm going to test it out.

**Comment by bluenote73** [comment]
To clarify - if I can hit play a second time, and the torrent has already got up to a walking start it may now have the critical mass necessary to keep a speed and get past the timeout.

**Comment by NoGood** [comment]
I meant to say that the no buffer option would only be available as an
advanced (are you very sure?! ) option. Buffering works fine, just not for
me in some cases. Apparently not for bluenote either so that's why I
suggested this. :)

**Comment by bluenote73** [comment]
The problem is if scakemeyer added a configuration option every time two people wanted something nobody else needed, you wouldn't be able to use the app because it would be so full of options and he'd never get to work on anything worthwhile.  It's kind of silly that Kodi does that from their end though, IMO it should be a call with a specified timeout integrated into it.

**Comment by bluenote73** [comment]
Ok, so it's not ideal, and unfortunately doesn't really suit my main use case [elderly non technical relatives] but, for you and I and others, enabling the 'handle in background' setting, waiting for the timeout, and then going to the 'torrents' option, you can then select the timedout torrent which is continuing to download. 

Im not clear what happens when the torrent finishes, I assume you now have to manually manage and delete them through the app which isn't ideal, but at least it's a way to make something playable. 

Maybe a context menu item "Start torrent and send to background" item that would launch the torrent in background mode would be a decent workaround.

**Comment by scakemyer** [comment]
That context menu will be implemented for #203, and managing the deletion of torrents from background handling in #147 :) As I said the timeout itself can only be fixed by refactoring the way we launch/play torrents in the first place. I've already spent quite some time trying to do just that, but so far it was causing more problems than it was solving so I'll have to revisit this when I have a chance.

**Comment by bluenote73** [comment]
I see it's necessary to not just search the issues but actually read all of them before writing a new one:)
Thanks scakemeyer :)

**Comment by scakemyer** [comment]
Yeah ;) but this one is quite valid nonetheless. Keep it open, it's the one for that refactoring of launching torrents now :)

**Comment by incredulity** [comment]
> SOCKS connection to a VPN

From the same provider?  Same address?  Same geographic region?

I have successfully combined Socks5 in Quasar settings with TorGuard (not TOR) OpenVPN client from same geographic region without heavy throughput limitation.


> Would it be possible to not have a buffer at all and just start the streaming. 

This seems problematic.

> I would rather start / pause manually and wait.

Beyond that I would like an onscreen notification that my Quasar Media is ready to play.

**Comment by scakemyer** [comment]
Can't believe this was basically a one line fix all along... :man_facepalming:
