### ISSUE TITLE
Pass some infolabels to VideoPlayer window

### ISSUE THREAD

**Issue by tomer953** [scakemyer/plugin.video.quasar#256]
Hey, Great job, and thanks for your hard work.

I wonder if it possible to include the following infolabels in the VideoPlayer window:
* VideoPlayer.Plot
* Player.Art(poster) - for movies
* Player.Art(tvshow.poster) - for tv shows

I think that right now only Player.Art(thumb) is set, but it will help me as a skinner if you will add those I mentioned too.

**Comment by scakemyer** [comment]
It'd be great if you could test this before the next release, otherwise let me know after the next one.

**Comment by likeitneverwentaway** [comment]
I've been experimenting for quite some time (few hours...) and I think there is not much improvement to be made. I was getting weird results when bringing up the player control : the poster was ok but displayed as if it was a thumbnails, so only a little bit was visible. I tested pretty much every combination I could find on the wiki without success, while when opening the stream with genesis the poster would be in the correct format...

So I thought there would be a better way but in the end it's my skin that's causing the problem, everything's ok in confluence, for the movies.

lI have no idea why but I can't get setArt to work, it seems the only solution would be :

`thumbnailImage=xbmc.getInfoLabel("ListItem.Art(tvshow.poster)")`

**Comment by tomer953** [comment]
@scakemyer  ,Thank you!

I tested your fix, and I found the following results:
I will split the test into 4 parts: movies with\without auto play option, and same for tv shows.
VideoPlayer.Plot - is always working. (great!)
about the art: when you choose to auto play movie\episode it's working great.
however, when you manually pick a stream via the dialog - only the "thumb" is set, and no poster\tvshow.poster as I asked. Actually i'm not surprised from that behaviour because IIRC it was the same in Pulsar from steeve.
so let me know If another test is needed.

@likeitneverwentaway , as long scakemyer will set the right parameters, it's completely up to your skin how it will display... for example, in my skin I prefer to display tvshow poster instead of the thumb of the episode. so I check for the tvshow.poster first, and fallback to the thumb If needed...

**Comment by likeitneverwentaway** [comment]
Did some more testing, it actually depends on 3 things : if are opening your media from the context menu, from your library, and if the torrent is chosen automatically. After extensive testing here are my results :

- library : doesn't work. No matter if Quasar is set to auto, and you don't have the context menu to choose in the library 
- opening from the context menu : never works (the media is no more selected, so ListItem doesn't work anymore ?)
- from the addon: everything's good, whether or not it's auto

If I perhaps have a clue why context menu breaks ListItem I have no idea why it doesn't work in the library.

**Comment by scakemyer** [comment]
I'll include the current changes in the v0.9.23 release, but leaving this open to improve on it, and a few related issues : #230, #199, #95

**Comment by likeitneverwentaway** [comment]
After some research the poster not showing up from library is because of setResolvedUrl, that works differently with strm files. I've been looking for a workaround but could not find any. [Here](http://forum.kodi.tv/showthread.php?tid=240253&pid=2119470#pid2119470)'s a post that explains the problem.

**Comment by scakemyer** [comment]
Anything left to fix here?

**Comment by corrpel** [comment]
@scakemyer i'll check latest version .93 and update :)
thank you

**Comment by corrpel** [comment]
#230 - much better but still the same (before the infolabel was "play" now is "quasar").
so another subtitle addon will search for "quasar" subtitles (with quasar addon, subtitles will search for additional "quasar" instead of play - faster ~50 result instead of ~500).
#338 - nothing different here. the movie is labeled as "play" and ~500 result of "play.blablabla" movies are returned.
the rest is ok.

**Comment by scakemyer** [comment]
To be honest I simply don't have any solution in mind for those two, and we can't replace the "play" url with random stuff either.

**Comment by corrpel** [comment]
@scakemyer ok good to know that; to avoid searching for everything else in quasar sub addon other that the movie played, can you pass "quasar.surge.sh" instead of "quasar" or "play" as infolabel?
This sequence cannot be found on "opensubtitles.com".i know that the original quasar sub addon is working with opensubstitle in background.
thank you!
I will test how it is working.

**Comment by scakemyer** [comment]
That's just not how it works... we don't just "pass" infolabels, and in those two cases they're just a magnet link added to that "play" endpoint that Quasar uses and provides, so there's no infolabels at all to work with.

**Comment by scakemyer** [comment]
@likeitneverwentaway, @tomer953 let me know if there's anything missing / not as it should for thumbnails and poster art

**Comment by ShlomiD83** [comment]
https://github.com/scakemyer/plugin.video.quasar/issues/199
how about this? can't be done?

**Comment by scakemyer** [comment]
Same thing with that one, there's just no way to magically add infolabels to a magnet link or torrent file alone. I'll be looking into what could be done with the `dn` URI parameter of magnet links, and maybe a custom `title` parameter for third-party add-ons that use the `play` endpoint.

**Comment by likeitneverwentaway** [comment]
When I was trying to get it work I saw that you could add infondirectly to the player. But I couldn't figure out what's the player in your code.

**Comment by scakemyer** [comment]
It isn't called directly, not yet at least, we're still using PlayMedia links until #253 and #203

**Comment by ShlomiD83** [comment]
Is it possible for movies to have the year next to the name both in the categories and video player? Some subtitle addons dont find results if there's no yeat specified.

**Comment by scakemyer** [comment]
@ShlomiD83 finally, fixed in 3d104ac...

**Comment by ShlomiD83** [comment]
@scakemyer thanks for alll your hard work..
