### ISSUE TITLE
Add support for linux_arm64

### ISSUE THREAD

**Issue by meijin007** [scakemyer/plugin.video.quasar#26]
need for amlogic S905 etc.

**Comment by meijin007** [comment]
Is it evolving changes in the cross-compiler?

**Comment by scakemyer** [comment]
Yes, in all projects actually. From cross-compiler, to libtorrent-go, to quasar, and finally the plugin. But at least it's easier than ever to test compilation with the Travis builds.

**Comment by itvalentino76** [comment]
Have the same problem on an s905 box , too bad that all the power of 64 bits linux cannot be used on best plugin that exists - any chance to get this done?

**Comment by scakemyer** [comment]
Is linux_arm working at least?

**Comment by itvalentino76** [comment]
Yes, of course, I am on an 905 on dualboot lollipop with linux arm 64 bits - it flies, , watch the way it work on s805 (linux32) here: https://m.youtube.com/watch?v=Kib3EYsLX8M

**Comment by itvalentino76** [comment]
If you need any testing on linux arm64 , please let me know.

**Comment by Stane1983** [comment]
Hi. Yes, I did Buildroot based Linux for Amlogic aarch64 and Kodi is running on it just fine (I'm talking about same thing as @itvalentino76). Quasar needs aarch64 compiled daemon to work.

**Comment by scakemyer** [comment]
Thanks for clarifying, as I meant if the linunx_arm version of Quasar was working or not.

**Comment by itvalentino76** [comment]
Linux_arm Quasar 32bits working perfectly on 32 bits mediaboxes, I thought you were asking about linux_arm generally

**Comment by itvalentino76** [comment]
Hello, I saw that quasar is growing bigger and bigger. Any chance to see the linux arm x64 at work?

**Comment by atomtm** [comment]
@itvalentino76 do you have to make any special configs for you mediabox to get quasar to work? I have a s812 android 4.4.

**Comment by itvalentino76** [comment]
@atomtm - we are talking here about linux on arm at 64 bits and you ask about android kitkat on 32 bits??
Btw, any updates on this?

**Comment by meijin007** [comment]
@scakemyer Now that we are going to have the raspberry pi 3... :)

**Comment by itvalentino76** [comment]
Underhood info , interesting - any new dev on this?

**Comment by scakemyer** [comment]
[![it's happening!](https://i.imgur.com/vwMin.gif)](https://github.com/scakemyer/cross-compiler/commit/8f55f1380756d36d99acbdc85e8481648cbc7c60)

**Comment by scakemyer** [comment]
Closing, it's in v0.9.24 along with linux_armv7 support.

**Comment by dtsexpert** [comment]
@itvalentino76 any link for setting up dual boot to linux?
I have a Tronsmart Vegas s95. QUASAR works great on 5.1.1, wanna to play around with Linux
Thx

**Comment by itvalentino76** [comment]
@dtsexpert - it is not on tronsmart the dual boot, sorry - try here:
http://www.dotsmart.ro - real 64 bit box, dual boot

**Comment by itvalentino76** [comment]
@scakemyer - I thank you a lot, I will try it tonight and get back to you
