### ISSUE TITLE
Wrong resolution in streams dialog

### ISSUE THREAD

**Issue by ShlomiD83** [scakemyer/plugin.video.quasar#261]
is this a quasar issue or provider?

**Comment by entr** [comment]
I noticed that too.

**Comment by scakemyer** [comment]
HDTV defaults to 480p, but should be overwritten by 720p or 1080p when specified in the filename. Code seems fine so I'm not sure what's causing this, but will look into it some more.

**Comment by scakemyer** [comment]
Finally fixed this bugger... it was only with combined results, so picking up the resolution from different names, hence the discrepancy we were seeing.

**Comment by ShlomiD83** [comment]
unfortunately the issue isn't fixed :/
[IMG]http://i65.tinypic.com/2nm3ipz.png[/IMG]

**Comment by scakemyer** [comment]
I can't even... :fire:

**Comment by scakemyer** [comment]
Here, try to trip it up... https://play.golang.org/p/RFjr11c87M

It's certainly not the tag matching... I'm guessing another kind of conflict just like with combined results...

**Comment by scakemyer** [comment]
Anyway... not a case of regular expressions here, just simple overlooked logic I thought was working a certain way but wasn't. Making sure it'll use the highest resolution found now.
