### ISSUE TITLE
Can't Get rid of this error

### ISSUE THREAD

**Issue by Jizar07** [scakemyer/plugin.video.quasar#263]
First off.... Amazing Job on Reviving Pulsar (Quazar)..... while others keep whining like babies because of Genesis... I'm jumping in Joy because of "YOU". Even b4 XBMC came around, I used Torrents as my main Media outlet.  Again.... Great Job.

Now... the problem I'm having... and trust me... I've have been searching and reading posts and more post about this for the past 3 days, I've tried every suggestion out there, and even went thru all my shows (120 of them) one by one in order to make it work (because of the problem Kodi is having with TMDB server for TvShows) ... and it did, I finally have all my TvShows working fine.

But for Movies.... OMG!!!! I even reformatted my PC (Just Kidding, I did because I got a new SSD drive), but yeah... I reinstalled everything from the start, and still can't get this dammed "Http Error" out of the Movies. 

please Help.....

Using Kodi 16 Jarvis RC3 on Windows 10
I have TMDB set for movies and TvShows folder
I use "Quasar Trakt List Subscription" to import my library.

Last Log Error:  http://xbmclogs.com/pt4ywfdhx#

**Comment by scakemyer** [comment]
There's your issue, an extra `links` in the URL:
```
Requesting http://localhost:65251/movie/293660/links/links
```

**Comment by scakemyer** [comment]
This is obviously an issue with the Trakt list subscription add-on (or rather its `script.module.mctools` dependency, missing the same replacement as `/play` around [here](https://github.com/mancuniancol/script.module.mctools/blob/master/lib/tools2.py#L949)

**Comment by Jizar07** [comment]
ok, but can we fix it?

**Comment by scakemyer** [comment]
Not in Quasar. Sent a PR for it mancuniancol/script.module.mctools#2
