### ISSUE TITLE
Search from anywhere using a key

### ISSUE THREAD

**Issue by corrpel** [scakemyer/plugin.video.quasar#264]
Can we have the possibility to search from any listed item to quasar?
For example, i have a .strm file containing a magnet but the quality is too low or too few seeders.
What we want to do here is assign a key to search the text in the label in Quasar addon.
I tried doing the following but the imdb number is not replaced with the real number items from my library:
<yellow>PlayMedia(plugin://plugin.video.quasar/movie/$INFO[ListItem.IMDBNumber]/links)</yellow>
The yellow key on my remote should execute the above script, but instead of imdb number the "$INFO[ListItem.IMDBNumber]" is used.
Can we make it better and have a search by name?
For example, for tvshows:
<yellow>PlayMedia(plugin://plugin.video.quasar/moviesearch/**listedtext**)</yellow>
<blue>PlayMedia(plugin://plugin.video.quasar/tvshowsearch/**listedtext**)</blue>
And both of them callup the quasar + providers to look for the listed name.
This means that we will be able to search from any addon also.
Thank you!

**Comment by scakemyer** [comment]
Use what Quasar itself uses:
```
plugin://plugin.video.quasar/movies/search?q=text
plugin://plugin.video.quasar/shows/search?q=text
```
For `.../links` (and `.../play`, use the TMDB ID, not the IMDB code.

**Comment by corrpel** [comment]
@scakemyer i managed to have something but my main issue is that for two word search, a "+" sign is needed instead of a "space". Any point how can i use 'two words" instead of 'two+words'?
Thank you.

**Comment by KillerJoeBR** [comment]
@corrpel Could you please give an example of how to do this? Where should i place this code? And what exactly should i write for it to work by pressing the letter "q" for example?

Thanks

**Comment by KillerJoeBR** [comment]
I guess it depends of the language: Arrow for me:

[IArrow](http://i.imgur.com/LW3I6iD.png)
