### ISSUE TITLE
Add user configurable option to automatically remove torrent file, if and when the video is 100% downloaded and/or watched

### ISSUE THREAD

**Issue by kiat-huang** [scakemyer/plugin.video.quasar#265]
If this is already a feature and I've missed it - apologies!  

I envisage the location of the option in the usual Quasar configuation panel, under General.

Great work btw.

**Comment by nix87** [comment]
yes it is, it's already there just don't select keep after download or something like that :)

**Comment by scakemyer** [comment]
Exactly, and auto-delete with background handling enabled is in #147
