### ISSUE TITLE
Bug or feature: After 0.9.22 it is required to set download path?

### ISSUE THREAD

**Issue by endlessterror** [scakemyer/plugin.video.quasar#267]
First, a *HUGE THANK YOU* to the developers here: awesome work fellas, I'm certain we all appreciate the quality and quantity of the coding involved! Please keep it up!

Now my question: I was aware that there was a download path configuration option on pulsar/quasar. I never configured it, however everything worked. Now, on 0.9.22 I can not download anything, if the download path is not set.

Is this how this should work or is it a bug? If it is a new feature, could you please consider providing a *safe* default for it, to avoid having the user figure out which path to select?

Thanks again for all the hard work done1

**Comment by tomer953** [comment]
https://github.com/scakemyer/plugin.video.quasar/issues/255

**Comment by endlessterror** [comment]
Thanks mate, so it is a feature after all.

I must agree with the issue's poster on #255 though: requesting the user to configure a default path can only easily done a newbie nuts. And even I consider myself to be better than the average Joe, I could not make heads or tails of this feature; I lack the knowledge of what would be a safe path to configure on my openelec-based raspberry.

@skacemyer please consider having a default path already set!

**Comment by i96751414** [comment]
Yeah, a default path would be nice. Maybe userdata/addon_data/plugin.video.quasar/some_path

**Comment by endlessterror** [comment]
Can't figure his to edit my post, so I'll just have to ping the brains here:)

@scakemyer please consider having a *default* path set!

**Comment by scakemyer** [comment]
A default path will only cause more trouble, whether it's not writeable by the daemon on all setups or lots of users wondering where it is, why their local storage is getting full and they can't delete the files, and so on. The setting ensures we have a writeable path, known to the user, and set explicitly for Quasar and/or other downloads. Sorry but case closed guys, it's very little effort to put in to use the add-on.

**Comment by jzane001** [comment]
I'm a first time user of the Fire stick and can't figure out how to make a folder for a download path for quasar. Says it has to be writeable. Can anyone help me
