### ISSUE TITLE
Quasar blocks IPTV addon (Movistar + Spain)

### ISSUE THREAD

**Issue by pikomule** [scakemyer/plugin.video.quasar#268]
Hi, thanks for all your work. In recent updates QUASAR has stopped working my channel MOVISTAR + SPAIN. The channels use this format:

rtp://@239.0.0.57:8208
rtp://@239.0.0.103:8208
...
...

QUASAR disabled, the channels return to work.

Movistar +, is an Internet company and TV.

Tell me if I can help you with something to solve the problem. Cheers

**Comment by scakemyer** [comment]
Sorry but neither the protocol, IPs or port has anything in common or related to Quasar, and nothing about them changed in recent (or even older) updates. I'm afraid your issue lies somewhere else.

**Comment by pikomule** [comment]
I tried on a TV Android and Windows 7 64-bit. Quasar once started, the channels do not work. No it can be, but quasar affects somehow RTP

**Comment by scakemyer** [comment]
The only thing that would is libtorrent, and there's not a single mention of RTP anywhere in its code or issues.
