### ISSUE TITLE
Compile quasar with libstdc++.so.6.0.19

### ISSUE THREAD

**Issue by qianc** [scakemyer/plugin.video.quasar#269]
The current compiled version of quasar can unfortunately not run on any Qnap NAS devices, or other Linux versions that are missing libstdc++ 6.0.20 (for example CentOS 7). If quasar could be compiled with libstdc++.so.6.0.19 instead, it would probably work.
The issue is the same with both x86 and x64 versions.

The following error is shown in kodi.log:

```
NOTICE: [plugin.video.quasar] System information: linux_x64 3.12.6
NOTICE: [plugin.video.quasar] Kodi build version: 15.2 Git:02e7013
NOTICE: [plugin.video.quasar] OS type: Linux
NOTICE: [plugin.video.quasar] uname: ('Linux', 'XXXX', '3.12.6', '#1 SMP Sat Jan 30 16:13:59 CST 2016', 'x86_64', 'x86_64')
NOTICE: [plugin.video.quasar] quasard: starting quasard
NOTICE: [plugin.video.quasar] Deleting stale files set([])
NOTICE: [plugin.video.quasar] /root/.kodi/userdata/addon_data/plugin.video.quasar/bin/linux_x64/quasar: /opt/mykodi-15.2/mykodi_lib/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by /root/.kodi/userdata/addon_data/plugin.video.quasar/bin/linux_x64/quasar)
```

Please note that this is the same issue as [#111](https://github.com/scakemyer/plugin.video.quasar/issues/111) but better described.

**Comment by fralik** [comment]
Agree!
I solved it on Ubuntu 14.04 by using additional repository as described here: http://askubuntu.com/questions/575505/glibcxx-3-4-20-not-found-how-to-fix-this-error

**Comment by scakemyer** [comment]
Sorry but I won't be downgrading the compilers or toolchains. Feel free to fork the [cross-compiler](https://github.com/scakemyer/cross-compiler) project, do so in there, and rebuild those along with libtorrent-go and the quasar daemon.

**Comment by rafal-krypa** [comment]
Please reconsider reopening and actually fixing this bug.
It prevents Quasar from running on the latest LTS version of Ubuntu (14.04), which is still well supported by Kodi. You can see (https://launchpad.net/~team-xbmc/+archive/ubuntu/ppa) that official Kodi PPA provides up to date packages for Ubuntu 14.04 (Trusty Tahr). With this bug, users of Ubuntu Trusty need to perform hacky workarounds, too difficult and dangerous for casual users.

**Comment by Matthias84** [comment]
Same for Linux Mint 17.3 rosa. Upgrading libstdc++ is pretty ugly and has sideeffects on a lot of installed tools and drivers.

I'm not familar with GOlang but isn't it possible to switch the compiler target?
