### ISSUE TITLE
Provider result URI needs additional resolving

### ISSUE THREAD

**Issue by entr** [scakemyer/plugin.video.quasar#271]
I don't know how common is that but as I am new to kodi development it puzzles me.

The provider I am trying to implement is basically a web scraper. I managed to put together the search query using the `def search()` method easily but results don't provide magnets directly, only links to (singular) torrent pages which magnets can be extracted from. 

My question exactly is - Can I feed the Provider result URI with non-magnet links which ideally are handled by the provider itself (like quasar handles plugin://plugin.video.quasar/ calls)? I don't really know what is the best approach to tackle this. Any help appreciated. Thanks

**Comment by nix87** [comment]
Mancuniancol can help you with that ;) He is amazing for creating providers.

**Comment by entr** [comment]
Pinging @mancuniancol

**Comment by mancuniancol** [comment]
You can check this provider.
https://github.com/mancuniancol/script.quasar.1333x-mc/blob/master/main.py
 I've created a function "getlinks" to find the torrent for each link.

**Comment by scakemyer** [comment]
No provider-specific issues / links please.

**Comment by mancuniancol** [comment]
Sorry, I was answering from my phone, I didn't realize that it is Quasar. Sorry
