### ISSUE TITLE
Request: Allow Library path be set on a network share

### ISSUE THREAD

**Issue by johnnyslt** [scakemyer/plugin.video.quasar#273]
Allow Library path be set on a network share eg: ftp,sftp, so we can use the same  Quasar.json file, on other devices with Kodi.

**Comment by becharabechara** [comment]
you can actually auto mount the network share folder into a root file for example /media/cifs and then when you mount it you choose this as the download/library path

sudo apt-get install cifs-utils
sudo mkdir /media/cifs
sudo nano /etc/fstab
//networksharedlocation/public /media/cifs cifs guest,uid=1000,guid=1000,iocharset=utf8 0 0
or
//networksharedlocation/public /media/cifs cifs username=<your-username>,password=<your-password>,uid=1000,guid=1000,iocharset=utf8 0 0
sudo umount /media/cifs
sudo chown osmc:osmc /media/cifs
sudo chmod 755 /media/cifs
cd /etc
sudo nano rc.local
sleep 30 && sudo mount -a
(add this before exit 0)
sudo reboot
