### ISSUE TITLE
[FEATURE] If no torrents match name, dig in torrent-file to find the name

### ISSUE THREAD

**Issue by SVQTQ** [scakemyer/plugin.video.quasar#277]
Hello

First off I'd like to thank you for your work and keeping it up to date.
I am not sure as to whether I am posting in the correct repository for this request, if not just tell me and I will move it.

I was recently looking for a torrent, which did not show up (only seaon x, not S0XE0X).
So I was wondering if it is possible to dl the torrent, then look inside it for a matching name.

**Comment by scakemyer** [comment]
Solved by #195, there'll be no searching within torrents' files since they need to be opened for that and it be awfully expensive and wasteful to do so.

**Comment by SVQTQ** [comment]
Ok, I'll try that feature out.

So if I understand correctly it is not possible to just 'browse' the torrent (metadata) without completely downloading the torrent-file first?
Could you guide me to the code where torrenthandling is done, please?
