### ISSUE TITLE
Searches causes Quasar to crash when pagination is disabled

### ISSUE THREAD

**Issue by lrrosa** [scakemyer/plugin.video.quasar#279]
When pagination is disabled and I search for any movie or tv show this causes Quasar to crash.
I'm using Quasar 0.9.23.

Log:
--------------------
[kodi_log.txt](https://github.com/scakemyer/plugin.video.quasar/files/139407/kodi_log.txt)

**Comment by scakemyer** [comment]
I'll be removing the option to paginate or not and replace it with a Results per page setting, with a reasonable upper limit.

**Comment by lrrosa** [comment]
I agree with this. That would be better.

**Comment by lrrosa** [comment]
Well, don't know why, but for me it still defaults to 20 results per page no matter what value I put in "Results per page". In settings.xml the value of results per page is correct.

Is there anything in the logs I could share with you?

**Comment by frankclaassens** [comment]
I'm experiencing the same issue as @lrrosa. Results per page set to 50 in settings.xml on OSX. Also tried it on my nvidia shield tv, same result, it never returns more than 20 results per page. 

Can you confirm this was fixed? Perhaps it regressed?

**Comment by scakemyer** [comment]
Not the same issue, see #468
