### ISSUE TITLE
Stream directly from RAM/memory possible?

### ISSUE THREAD

**Issue by amivit** [scakemyer/plugin.video.quasar#282]
I'm concerned with the health of my SD card running OSMC (kodi) on my raspberrypi. I realize I could plug in a usb-thumbdrive, but I don't have one atm and was wondering if quasar could let me stream entirely from memory, without having to write anything to storage.

Is this idea feasible or possible already? Or the underlying tech of the BitTorrent-engine will not let you do this?

**Comment by m4xc4v413r4** [comment]
Pretty sure this has to be done in kodi. You can change the advanced settings file to basically just use ram.

**Comment by ShlomiD83** [comment]
torrents don't work that way, files must be downloaded to sd/hdd/ssd or whatever and from there it's being cached by kodi.

**Comment by scakemyer** [comment]
But I suppose it's possible, just not from Quasar or libtorrent themselves. Create a ramdrive, set as your download path, enjoy. Your problem is that there's certainly not enough RAM on a raspberry for that.
