### ISSUE TITLE
Navigation error : Connection refused

### ISSUE THREAD

**Issue by hugocroch** [scakemyer/plugin.video.quasar#285]
Hi,
I installed Quasar on my raspberry Pi with the version 0.9.23 without any problem.

Unfortunately, every time I try to go in Quasar, it fail and notify me with a message : "Navigation error:UrlError(error(111,'Connection refused'))"

Is there something I forgot to do? Is it a known issue?

Thanks

**Comment by scakemyer** [comment]
If it installed without any problem, then just wait for the notification about the daemon having started.
