### ISSUE TITLE
Quasar subtitle options

### ISSUE THREAD

**Issue by glorifiedg** [scakemyer/plugin.video.quasar#289]
How about implementing the ability to customize quasar subtitle search like, for example, specify what language to show first?

**Comment by nix87** [comment]
That's already Kodi do.

**Comment by glorifiedg** [comment]
oddly quasar subtitles are not showing as per my kodi prefs. Will dig into it again.

**Comment by dtsexpert** [comment]
Go to system, setting, vdeo, subtitles. You can set Quasar as the dedault sub addon, style, font siz, languages...

**Comment by scakemyer** [comment]
No issue here, Kodi settings for subtitles are separate from interface language, that's all.
