### ISSUE TITLE
Add possibility to search in one provider

### ISSUE THREAD

**Issue by Palatosino** [scakemyer/plugin.video.quasar#29]
One thing that I always miss is the possibility to search in one provider, like if I go to the provider's web and do a search.

We can use the "general" search, but it searchs in all the providers and merges the results. I want something that permits me to do a search in X web (done by a providers) and shows me all the results to select one (manually)

**Comment by m4xc4v413r4** [comment]
Why don't you just click to choose the file, get the list and do it that way?
The list already shows you what provider a file is from...
