### ISSUE TITLE
quasar no links found

### ISSUE THREAD

**Issue by becharabechara** [scakemyer/plugin.video.quasar#290]
i am currently using the 0.9.23 version and i auto mounted a network location to a /media/cifs folder and i am using it as download path but for some reason weither i chose tv shows or movies i get an error message "quasar no links were found" then all the providers i installed display links but i can't chose a stream neither automatically nor manually.

**Comment by dtsexpert** [comment]
As i remember, quasar does not work with network storrage. Use internal storrage.

**Comment by becharabechara** [comment]
i already tried internal storage and external usb and network but i am able to chose these folders since i modified their permissions and auto mounted them, but i always get the quasar no links were found problem

**Comment by scakemyer** [comment]
No links found has nothing to do with storage, and if you're seeing links then you can't be getting that notification, the code says so and you don't provide any logs to back your claim. Even if you did, this is related to providers and you won't be getting any help with those here.
