### ISSUE TITLE
Same tracker, different results, why?

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#292]
Hi there, so i've been loving quasar so far, but i find sometimes hard to understand this that happens to me, for example.

I search tvshow "Regular Show" in Quasar and use like 10 providers and i get almost no results.

Then i try torrent using kickass tracker and it gets me huge results, why is this?

I use kickass also in quasar.

Screenshots added:

Torrenter:

![screenshot000](https://cloud.githubusercontent.com/assets/1534438/13238687/bcfd1ae8-d9cc-11e5-819c-6648f7ee6faf.png)

Quasar:

![screenshot001](https://cloud.githubusercontent.com/assets/1534438/13238678/b3cff15c-d9cc-11e5-8cdb-e2075f29e350.png)

i even tried searching entire season and no luck :|

**Comment by hfmls** [comment]
even tried changing url https://kat.cr/ to other that work for me and same.

**Comment by KillerJoeBR** [comment]
Well for starter you are not making the same search. In torrenter you are searching  "regular show"  and getting results for any episodes and movies etc. While in quasar you are searching for a specific episode. Of course you gonna get fewer results. 

Also having a lot of providers can be harmful. I think 4 providers is enough.

**Comment by scakemyer** [comment]
What's so hard to understand about no provider-specific questions?
