### ISSUE TITLE
Trakt.tv scrobble

### ISSUE THREAD

**Issue by doludizgin** [scakemyer/plugin.video.quasar#297]
Trakt is not finding the scrobble when playing from quasar.

Think it has to due with the 20% and other gibberish in filnames.

Maybe output the moviedb title to trakt.

**Comment by scakemyer** [comment]
#16 #31

**Comment by scakemyer** [comment]
Added in v0.9.31

**Comment by hfmls** [comment]
:) thank you very much for this

**Comment by eidermar** [comment]
I was trying everything I could think of to get this work but whatever I do this doesn't seem to work for me. I'll provide logs if you want but I checked several times and the only thing regarding this issue in the logs is the absence of any entries (I wouldn't even know what exactly the process is you need to see in the logs?). I made sure that scrobbling works from other sources. I went through the authorization process for the trakt plugin and quasar multiple times, checked the settings, uninstalled reinstalled trakt & quasar - nothing. First I thought it was only failing when I started playback from the library, but it doesn't matter actually. I couldn't swear but I thought when you first implemented the feature it was working for me (and made me very happy). 

Am I the only one having this problem? Anything obvious I'm not seeing?

**Comment by scakemyer** [comment]
We can't see what you can't see without logs...

**Comment by hfmls** [comment]
yeah for me doesn't work either :( gonna try get some logs. don't know is how/where can i log this "error"
