### ISSUE TITLE
Infolabel not populated if I launch a movie from the library using Quasar

### ISSUE THREAD

**Issue by NerosTie** [scakemyer/plugin.video.quasar#300]
If I add a movie to the library with Quasar then I launch it from the library, the infolabels are not populated, so the title of the movie is its ID from the .strm file.

However, I don't have this issue with TV shows.

**Comment by ShlomiD83** [comment]
Same problem here, only with movies from library. happy to provide log if needed.

**Comment by likeitneverwentaway** [comment]
See #256, e8b7a45

It worked for me a couple hours ago, without using the context menu. The strm file was scraped with universal movie scraper.

**Comment by ShlomiD83** [comment]
Let it choose stream automatically and it will work? Will try that..

**Comment by ShlomiD83** [comment]
i'm afaraid it didn't work, did you make any changes beside copying the navigation.py file and using UMP as scraper?

**Comment by likeitneverwentaway** [comment]
Nope, just tried again: pressed enter on my movie, chose the stream, and the title, director, ratings etc were all here.

**Comment by ShlomiD83** [comment]
thank you, it works now.
