### ISSUE TITLE
Library TVshows refresh

### ISSUE THREAD

**Issue by klkos** [scakemyer/plugin.video.quasar#301]
Thanks for great job!

I added some TVshows into library. It is OK. But when new series are out, they are never shown in  there. Library is never refreshed by new series. It shows only those series, that were available at the moment of  adding a TVshow into library.

Can this issue be improved?

**Comment by NerosTie** [comment]
I think you can refresh the library after every reboot with the option (in Kodi): parameters -> videos -> library -> refresh the library at startup.
Or you can refresh a TVshows to find new content manually.

**Comment by nix87** [comment]
that is not Quasar issue, that Kodi should do.

As NerosTie said you should find that option in Kodi and turn that on.

**Comment by klkos** [comment]
Thanks for the tip. Going to have a try.

**Comment by hfmls** [comment]
just press left in tv show list and press refresh
