### ISSUE TITLE
The files are not deleted if the torrent was launched from the library

### ISSUE THREAD

**Issue by NerosTie** [scakemyer/plugin.video.quasar#302]
If I launched a movie or a TV shows from the library (added with Quasar), the files are not deleted after it ends or a reboot. No issue if I'm using Quasar "normally".

**Comment by ShlomiD83** [comment]
tested what you said and files were deleted. are you sure "background handling" and "keep files after playback/download stops" are not checked?

**Comment by NerosTie** [comment]
Yes, these 2 options are unchecked.

But actually, it works. 

In fact, files remains when Quasar or Kodi crashs and this happens when I launch something from the web interface called Arch.

So, I don't know, is it still an issue?

**Comment by scakemyer** [comment]
Doesn't look like it.
