### ISSUE TITLE
experiment with private trackers :)

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#305]
I just did one experiment with one of my private trackers and it's shows successful at some point. :)

I took one torrent from one solid hd tracker, I copied torrent url in Quasar and Quasar starts to play it without a problem, but when I saw peer list for that torrent next by my username in client list it shows Quasar/"v. 0.9.23"???

I thought it should be libtorrent cause Quasar uses that torrent client. I mean above all Quasar isn't torrent client right?

I didn't want to download more then a couple of MB's because possible DHT problem and don't want to risk ban or some warning so this was just for quick testing to see if it works.   

Anyway I think it shoudn't be problem with client list name as long as user follow tracker rules, seeds enough, keep good ratio and be good to the community :)

**Comment by scakemyer** [comment]
Thanks for the report, good to know we're not far from official support of private trackers. This goes with #38.

As for the client name, it's indeed set as "Quasar/<version>" which I believe is correct, since libtorrent isn't a client but a library, the client *is* Quasar.
