### ISSUE TITLE
quasar keep crushing

### ISSUE THREAD

**Issue by yanivz** [scakemyer/plugin.video.quasar#308]
i am using windows 10 64 bit, 6gb ram, intel i3. since installing quasar it keep crushing . i've reinstalled and nothing changed 

[kodi.zip](https://github.com/scakemyer/plugin.video.quasar/files/146299/kodi.zip)

**Comment by corrpel** [comment]
yes, mine is crashing a lot; i had to revert to x.19 to have it stable; i believe that is still under the 1.x release, so this should be present a lot until then;

**Comment by yokod** [comment]
had the same issue , solved it by deleting all the of the pulsar plugin . from both the userdata and addons folders

**Comment by scakemyer** [comment]
Just your Windows firewall blocking JSON-RPC requests from the daemon to the add-on.
