### ISSUE TITLE
Heores rebon tv get eroer

### ISSUE THREAD

**Issue by yigal33** [scakemyer/plugin.video.quasar#309]
The tv show get eroer
Thanks.

**Comment by dtsexpert** [comment]
What error? Likely this is related to provider.

**Comment by ShlomiD83** [comment]
![screenshot000](https://cloud.githubusercontent.com/assets/17053215/13352970/a9f5ab98-dc99-11e5-9dbd-5e52fda897a5.png)

**Comment by yigal33** [comment]
https://ci5.googleusercontent.com/proxy/4ykL_gHRH8DEdnG0fxDhCIviZcICGRrz149Qr18fOHEXmWwI2n7h54EcZrvMfxm135vfjwOnZyq7c-zoqxbpSG_zKYhQAWeasJP1lYVS_cty1WMIcRhrwGxodGpAj7RUKc1f5U6TcDVsAjajdmzUw4sG3qYQCuASJg9-=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/17053215/13352970/a9f5ab98-dc99-11e5-9dbd-5e52fda897a5.png
בתאריך 26 בפבר' 2016 0:19,‏ "dtsexpert" <notifications@github.com> כתב:

**Comment by yigal33** [comment]
https://ci5.googleusercontent.com/proxy/4ykL_gHRH8DEdnG0fxDhCIviZcICGRrz149Qr18fOHEXmWwI2n7h54EcZrvMfxm135vfjwOnZyq7c-zoqxbpSG_zKYhQAWeasJP1lYVS_cty1WMIcRhrwGxodGpAj7RUKc1f5U6TcDVsAjajdmzUw4sG3qYQCuASJg9-=s0-d-e1-ft#https://cloud.githubusercontent.com/assets/17053215/13352970/a9f5ab98-dc99-11e5-9dbd-5e52fda897a5.png

**Comment by ShlomiD83** [comment]
"the shannara chronicles" gives the same error.

**Comment by hfmls** [comment]
the error in first place was when i gave heroes another try.... ^^

**Comment by tomtomclub** [comment]
Herpes 2006 works here  test  1,2,3.4  sesona
Clearing your cache

**Comment by tomtomclub** [comment]
Sorry  men heroes

**Comment by yigal33** [comment]
Heroes 2006?
I said heroes rebon 2015.

**Comment by scakemyer** [comment]
leran ot tpye
