### ISSUE TITLE
strm files refresh

### ISSUE THREAD

**Issue by klkos** [scakemyer/plugin.video.quasar#310]
I am wondering if *strm files should be refreshed automaticaly in library folder?
Some time ago I added a tvshow into library.
At the moment there are new series, but my library folder does not contain any fresh *strm, related to new tvshow series.
Is it my failure in settings?
If the issue is OK due to quasar spec, can this be improved?

**Comment by razer1s** [comment]
the same

**Comment by scakemyer** [comment]
Library already gets updated every 8 hours, can also be updated manually, and the feature is working just fine.
