### ISSUE TITLE
Many problems

### ISSUE THREAD

**Issue by mtnsaa** [scakemyer/plugin.video.quasar#311]
I'm sorry for the negative feedback but I can't run Quasar at all on OS X El Capitán. Pulsar and earlier versions of Quasar worked great but for the past weeks it's nothing but errors. I will try to revert back but not sure which version will work.

http://pastebin.com/tVu2vXNi
http://pastebin.com/MTsX9dHM

From Connection Refused, URL Errors to Torrents not deleting on my folder path, sessions already finished downloading again when you open Kodi (I'm talking about 10 movies at the same time), etc.

Please help! You are doing a wonderful job but I don't understand what's happening, I have a very clean installation, practically just Quasar.

Thanks in advance.

**Comment by bluenote73** [comment]
Turn off your 'background handling of torrents' and remove those torrents using the context menu for a start.  This should be posted in the forum thread, not here.

**Comment by mtnsaa** [comment]
Thanks, already did that but they told me to post it here. I've also tried deleting the torrents but when I play new ones it happens again.

**Comment by scakemyer** [comment]
Can't help with logs on pastebin, and yes just disable background handling if you can't deal with deleting torrents. Versions before 0.9.19 won't work because of the MovieDB API key that was revoked, and neither will any version of Pulsar.
