### ISSUE TITLE
Finding hang on kodi 16.0 and rpi2

### ISSUE THREAD

**Issue by lgdolman** [scakemyer/plugin.video.quasar#312]
Starts without error but fails to begin the download. Shows peers/seeds as -1 and speed as 0. Occurred following the latest osmc update from 15.x to 16.0. Nothing obvious in the log file either unfortunately.

**Comment by scakemyer** [comment]
Can't help then.

**Comment by lgdolman** [comment]
Further experimentation provided insight it was failing due to using TOR as the SOCKS proxy. Disabling fixed my issue but causes issues with providers thanks to court blocks. I've set up packet logging and I'm going to do a little debugging now.
