### ISSUE TITLE
enhancement - Settings to disable/enable categories

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#314]
Just something i thought right now. Could be something for the tuture. When i select movies i could let enabled only "Trakt Trending", "Popular" and "Recent" and disable all the rest for example. This way it would be easier to navigate, specially when i configure it for newbies.

Thanks (its been quiet here for the last few days)

**Comment by m4xc4v413r4** [comment]
Why not just link directly to it then? That's what I would do for "newbies". Because, if people are really that dumb that they can't choose, better just not give them a choice.

**Comment by scakemyer** [comment]
Too much trouble to keep the state of all categories, and not a fun feature to implement, sorry.
