### ISSUE TITLE
Question: (problem) Download speed too low?

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#316]
Hi there, asking if anyone has download speed problems since 2..3 days ago?

Usually i downloaded everything at 1.5...2mb now i can't get over 50kb's ? :|

no idea what happened, i did 0 changes.

**Comment by tomtomclub** [comment]
Yes reboot your router modem

**Comment by hfmls** [comment]
All good now,  strange

**Comment by m4xc4v413r4** [comment]
I'm sorry man, but people need to stop coming here to post shit like this... If it's not a Quasar issue then it doesn't belong here, and this clearly couldn't be a Quasar issue.

There's a forum people can go to. This isn't a forum and people are treating it like one, half the people here created an account on github to come post "threads" and it's getting out of hand.
