### ISSUE TITLE
Filter h265 and porn

### ISSUE THREAD

**Issue by glorifiedg** [scakemyer/plugin.video.quasar#317]
I use a raspberry pi which means It can't decode h265. Being an increasing popular format that happens to be selected on streams, would be awesome of there was an option to exclude h265. 

Second, I was looking for sources on dirty grandpa movie and got porno movies. Any chance of filtering porno?

**Comment by ShlomiD83** [comment]
You can exclude x265/h265 in the provider settings.

**Comment by m4xc4v413r4** [comment]
That is all done on the provider, quasar has nothing to do with it.

**Comment by glorifiedg** [comment]
Quasar now has the ability to prioritize by seeder/quality etc which was a provider feature. Why not integrate this also?

**Comment by m4xc4v413r4** [comment]
No, that wasn't a provider feature.

**Comment by bluenote73** [comment]
put your filter words into the provider settings.
