### ISSUE TITLE
Still keeps files after playback or download stopped

### ISSUE THREAD

**Issue by eSkRo32** [scakemyer/plugin.video.quasar#318]
Hi there, and thank for this amazing Quasar addon!!

but here, I made sure the option to keep files after playback or downloads stop is not enabled!,
But movies are still located in my download path after playback or download stopped so quasar is not deleting them ...

Dont want my SD card to fill up with quasar movies :/

Im on a Raspberry Pi2 running "OpenELEC-RPi2.arm-6.0.1.img" (Kodi 15.2)

Any fix for that would be really appreciated!
thanks!!

**Comment by tomtomclub** [comment]
Men I you use torrent don't  hit en run seeds your movie en If you see finish  remover it drom your list but .  But seed men please

**Comment by eSkRo32** [comment]
i dont mind seeding but my SD card is 16GB can fill up too fast
if nothing can be done to somehow delete the files to make room 
for other movies once my download path hits lets say 10GB or something...
Kodi needs disk space to function properly :/

**Comment by tomtomclub** [comment]
Yes you  can put it in usb stick or remover it torrent see torrent and klik it remover it . But buy oneens usb stick  en put your setting  to usb safe it works fine thanks men fouf seeding

**Comment by tomtomclub** [comment]
Oh context menu you see torrent you can remover it klik on it

**Comment by eSkRo32** [comment]
i get what your saying, thanks for helping,
but still, i'd like to go back to my original post asking this,

I made sure the option to keep files after playback or downloads stop is not enabled!,
But movies are still located in my download path after playback or download stopped so quasar is not deleting them ...

thus, i dont want my SD card to fill up with quasar movies :/

thanks!!

**Comment by KillerJoeBR** [comment]
You need to disable "Background handling of torrents". It's on by default. This way you keep seeding after you hit stop. Disable it and then the torrent will be deleted immediately

**Comment by eSkRo32** [comment]
Wow thanks KillerJoeBR! 
This worked! 

But whats the "keep files after playback or downloads stop" for then? Because it still keeps the files if its disabled and when background handling is enabled at same time.. 

Get's confusing :P
