### ISSUE TITLE
add mipsel

### ISSUE THREAD

**Issue by sergiojess** [scakemyer/plugin.video.quasar#322]
Hi
Could you please add mipsel?
Thanks and regards

**Comment by Evoxx** [comment]
I join the request to add support for Mipsel devices. Thank's for your hard work

**Comment by Edu1971** [comment]
I join the request.

thank you very much.

**Comment by CyberSoftx** [comment]
i join too many thank for all.

Regards!!!

**Comment by scakemyer** [comment]
Golang only supports mips64

**Comment by CyberSoftx** [comment]
so is not possible make it work on our reciever?
