### ISSUE TITLE
Quasar For vu+ receivers?? 

### ISSUE THREAD

**Issue by Albertron86** [scakemyer/plugin.video.quasar#323]
Hi, i use your plugin in Windows kodi and its perfect. Also I have a receiver vu+ SOLO2 based on Linux , but does not work any press plugin. Mipsel can be implemented in git , then to compile the addon? It would be great

**Comment by oscarfl** [comment]
These receibers use mipsel chip set

**Comment by CyberSoftx** [comment]
one more here for sign request.

Regards!!!

**Comment by scakemyer** [comment]
#322
