### ISSUE TITLE
Python bs4 module not found - Raspberry Pi2

### ISSUE THREAD

**Issue by MattMuffin** [scakemyer/plugin.video.quasar#325]
Hello,

I got this issue:

20:55:43 792.933350 T:1557132320  NOTICE: -->Python Interpreter Initialized<--
20:55:56 806.383362 T:1449128992  NOTICE: Previous line repeats 9 times.
20:55:56 806.383789 T:1449128992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named bs4
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/script.quasar.extratorrent-mc/main.py", line 6, in <module>
                                                import common
                                              File "/home/osmc/.kodi/addons/script.quasar.extratorrent-mc/common.py", line 12, in <module>
                                                from bs4 import BeautifulSoup
                                            ImportError: No module named bs4
                                            -->End of Python script error report<--
20:56:02 812.332153 T:1352660000  NOTICE: -->Python Interpreter Initialized<--

solved it by doing: sudo apt-get install python-bs4

Maybe add it to the dependencies?

**Comment by scakemyer** [comment]
provider issue
