### ISSUE TITLE
2 Feature request (back from stream, and Save this file for future)

### ISSUE THREAD

**Issue by compyy** [scakemyer/plugin.video.quasar#329]
Hi,

This is great plugin i have 2 requests which i am missing badly.

1. Back from stream, its like when you use any specific stream and there are not enough seeders or download is slow, then there is no back button you have to cancel the stream and recall all providers again and select the stream, for me it would be better if you press cancel it should take you to previous button where all streams were already searched and you can select other.

2. I have disabled the feature of saving files after download as i dont want to keep them on my drive but sometime if you are downloading a big file or watching a movie and after 30 minutes you want to stop it or want to see it later then you need to stop the movie or pause but if movie stops  all downloaded movie is lost, there should be a feature during the movie play where you can mention that dont delete this movie specifically if play stops.

Thanks.

**Comment by scakemyer** [comment]
Sorry but I'll have to say no to both. They're good ideas, but would be a quite a pain to implement with little benefit. I'll still keep 1) in mind, but 2) would mostly be covered by #14.

Also, don't make two feature requests in one issue, it'd make tracking progress of those features a real mess.
