### ISSUE TITLE
Not absolute number in anime

### ISSUE THREAD

**Issue by mancuniancol** [scakemyer/plugin.video.quasar#330]
Hi, I'm trying to watch anime using Quasar.  However, they use absolute numbering instead of the S00E00 format.  I am not sure when the absolute numbering disappeared from the payload.  I would like to know if it is a regression or that information is not available anymore in the source database.

**Comment by scakemyer** [comment]
That's right, TMDB doesn't provide absolute numbers, so it was removed in scakemyer/quasar@2ac4c2e ([here](https://github.com/scakemyer/quasar/commit/2ac4c2e14faa830b36c21900cabfe57bc95e7875#diff-3feb4090c66f18c0827390b575bb42afL130) more specifically) until I could revisit that and find a better solution, as it was even marked with `FIXME: This can crash`... Shows were going from TMDB IDs, to loading data from TVDB, back to finding the TMDB show by ID, reloading the show from TMDB, checking if from Japan and with Animation genre, and finally using the absolute number from TVDB.

Now we simply have the show data from TMDB, so no need for all that back and forth if we still want to use JP+Animation as what determines an Anime, but we don't have an explicit absolute number, unless episode numbers for those in TMDB already are absolute.

So we have a few options:
- Check for JP+Animation like before, query TVDB when so and the external ID is available to get the absolute number. Slight overhead but not as bad as it was, and only affects those matching shows.
- Also check for JP+Animation, but just send absolute_number as "true"
- Same again, but do season * episode and hope it's the right absolute number
- Send OriginCountry + Genre in payload and let providers choose how to handle episode numbers

Choose your poison :)

**Comment by seltun** [comment]
I would suggest implementing Option 1, seems to be the most reliable.

**Comment by scakemyer** [comment]
I agree, it'd match the previous behaviour while still being less wasteful than it was. I also noticed that the original titles in Japanese are being sent in the payload, where previously the TVDB SeriesName was probably the english name.

**Comment by mancuniancol** [comment]
It is working perfect.  Thank you

**Comment by hfmls** [comment]
sorry the off topic,how can you watch anime?
because for me naruto and dragon ball super appear as random chars.
so it can't find any new episodes.
