### ISSUE TITLE
TV SHOWs files saved problem

### ISSUE THREAD

**Issue by korenziv** [scakemyer/plugin.video.quasar#332]
Hi,
ver 9.24
in setting the save after download and torrent manege in backround are not marked but still the media i see are saved in the path.
attaced log:
http://pastebin.com/A7J5rmFt

**Comment by scakemyer** [comment]
Use http://xbmclogs.com/ please

**Comment by korenziv** [comment]
attached:
http://xbmclogs.com/pyaoqxpgd

**Comment by scakemyer** [comment]
sorry but there's no issue here
