### ISSUE TITLE
plugin quasar x86 not work on windows 7 x86

### ISSUE THREAD

**Issue by germanlt68** [scakemyer/plugin.video.quasar#334]
kodi 14.2
plugin quasar x64 on windows 7 x64 ok!
plugin quasar x86 not work on windows 7 x86
install, configure and not work

[my_kodi_log.txt](https://github.com/scakemyer/plugin.video.quasar/files/155613/my_kodi_log.txt)

**Comment by scakemyer** [comment]
try updating Kodi, 14.2 is getting old
