### ISSUE TITLE
The option to present the overlay doesn't stick

### ISSUE THREAD

**Issue by ltrindade** [scakemyer/plugin.video.quasar#336]
I have changed several times the option to not present the overlay on the bottom right corner while loading the stream, but it's always returning to be on. Or better, the option on Quasar settings appear as off, but when i stream the overlay appear always.

I'm using latest version of Quasar on RPi2, on OSMC.

**Comment by scakemyer** [comment]
overlay status != download status, and the download status appearing while you're watching is a skin issue
