### ISSUE TITLE
Infolabel not populated if I launch a movie or TV show from the library's widget using Quasar

### ISSUE THREAD

**Issue by NerosTie** [scakemyer/plugin.video.quasar#338]
Same bug as https://github.com/scakemyer/plugin.video.quasar/issues/300

As @ShlomiD83 says, it works if I launch the movie from the library but the infolabels are not populated if the movie is launched from the library's widget.

EDIT: actually, it's the same thing for TV shows too.

**Comment by scakemyer** [comment]
See #256
