### ISSUE TITLE
Automatic add movies and tv shows to library

### ISSUE THREAD

**Issue by BTopbas** [scakemyer/plugin.video.quasar#340]
Just now i found add how to local lib. I select movie or tv shows in quasar and select add/remove to library. How can add all movies or tv shows? And quasar need automatic add new tv show episodes. Maybe check every 5hour and add automaticly local library? I think this is big issue.

**Comment by entr** [comment]
Seems complicated.

**Comment by m4xc4v413r4** [comment]
What do you mean, add all movies and TV shows? That's not what it is for, if you want a list with every movie and TV show just use Quasar, why do you want them all on library?

Not to mention you would be there waiting for a month to get them all to query TMDB.

About new episodes getting added, they do already. Quasar adds them, then Kodi needs to refresh the library, which it usually does when we go to the main screen.
