### ISSUE TITLE
Unable to resolve torrent file error

### ISSUE THREAD

**Issue by mancuniancol** [scakemyer/plugin.video.quasar#341]
I am getting error for this particular site.  If I use the link in my browser, I get the torrent without problem.  I don't know why Quasar is unable to do it.

`06:20:36 T:11300  NOTICE: [plugin.video.quasar] ERRO  linkssearch  ▶ func1            Unable to resolve .torrent file at: www.nyaa.se/?page=download&tid=508752`

**Comment by drake0101** [comment]
I see that Nyaa.se uses Cloudflare which can block certain IPs, or require solving a captcha. If you are using proxy server, maybe Cloudflare doesnt like its IP?

**Comment by drake0101** [comment]
I just checked it on my Kodi16 + Quasar 0.9.25. I used "Add Torrent" in Quasar's Main Menu. Everything worked fine, torrent downloaded, video file buffered and its now downloading rest of the file and playing.

**Comment by Rick7C2** [comment]
I'm not sure why this was closed without any solution. I am now having the same problem out of no where. Same error as @mancuniancol

**Comment by kavuraki** [comment]
Any solution for this issue?
