### ISSUE TITLE
Just hide download progress indicator when playing with background handling enabled

### ISSUE THREAD

**Issue by zorg1977** [scakemyer/plugin.video.quasar#343]
Everything is in the title: background handling is a nice feature. The only drawback is the download indicator displayed while playing the file. Is it just possible to detect that the content is currently playing, and in this case, don't refresh the background window where the progress indicator is displayed, but instead close/hide it? (hide doesn't seem to be an option when looking at the API, so maybe just close the window should be enough).

I'm sure most of us will re-enable bg handling if this hide/close option exists.

**Comment by scakemyer** [comment]
This is a skin issue, those are standard background progress dialogs and it's the skin's job to hide them when playing. File this issue with your skin developer.
