### ISSUE TITLE
TV Show info being looked up using TMDB

### ISSUE THREAD

**Issue by 4ndrew2** [scakemyer/plugin.video.quasar#344]
Should this be corrected to use TVDB instead? or hve the option to change between the two?I had to manually add the last few ep of a show called Tosh.0 on TMDB myself and clear quasar cache to see the new episodes. My tv library folder is set to TVDB as source content also. 

When searching TV shows it also looks like it parses TMDB instead of TVDB

**Comment by m4xc4v413r4** [comment]
It is using tmdb on purpose. It was changed to it and I doubt it will go back.

**Comment by scakemyer** [comment]
See #164 and #249 ([this comment in particular](https://github.com/scakemyer/plugin.video.quasar/issues/249#issuecomment-186682080))
