### ISSUE TITLE
No links found

### ISSUE THREAD

**Issue by MattMuffin** [scakemyer/plugin.video.quasar#345]
Hello,

I reinstalled using the latest arm7 version from here (0.9.25) due to the error "Quasar binary not found".

I've added a few providers and tried a couple of searches.

It does not matter which provider(s) I use, I always get "no links found" message.

While digging into the debugging and logs I noticed that all the providers end up with the same message: "Provider script.quasar.xxxx was too slow. Ignored"

18:27:14 3973.540527 T:1611658224  NOTICE: [plugin.video.quasar] WARN  AddonSearcher script.quasar.yify-mc ▶ call             Provider script.quasar.yyyy was too slow. Ignored.
18:27:14 3973.543945 T:1732977648    INFO: CPythonInvoker(95, /home/osmc/.kodi/addons/plugin.video.quasar/navigation.py): script successfully run
18:27:14 3973.557129 T:1611658224  NOTICE: [plugin.video.quasar] WARN  AddonSearcher script.quasar.eztv-mc ▶ call             Provider script.quasar.xxxx was too slow. Ignored.
18:27:15 3973.889648 T:1732977648    INFO: Python script stopped
18:27:15 3973.890381 T:1732977648   DEBUG: Thread LanguageInvoker 1732977648 terminating
18:27:15 3973.904785 T:1958224432   DEBUG:  WaitOnScriptResult - plugin exited prematurely - terminating
18:27:15 3973.906006 T:1958224432   ERROR: PlayMedia could not play media: plugin://plugin.video.quasar/movie/286217/links
18:27:15 3973.916748 T:1958224432   DEBUG: ------ Window Deinit (DialogProgress.xml) ------

Any idea why this error shows up? Any way to dig deeper into the debugging?

Thanks

**Comment by m4xc4v413r4** [comment]
"No provider talk here" is pretty much the rule.

**Comment by ShlomiD83** [comment]
@m4xc4v413r4 you're right, but this can be solved only in Quasar settings beacuse only from there you can increase the providers timeout..

**Comment by MattMuffin** [comment]
I'll review the timeout thing and let you all know. Thanks ShlomiD83 for not being a rule abiding freak.

**Comment by MattMuffin** [comment]
@ShlomiD83 thanks fro the hint, that was spot on. I also disabled the health check on a provider. I'll re-enable it once things get more stable.

**Comment by m4xc4v413r4** [comment]
Disabling health check isn't going to do any good. And needing to up the Timeout probably means you're using too many providers for your machine's power.

**Comment by MattMuffin** [comment]
@m4xc4v413r4 Thanks for the info. I'm using one provider (EZTV if you'd ask) on a RPI2.

**Comment by palula** [comment]
Just so you know, I think EZTV is a provider mainly used for TV Shows, so it may not work fine when searching or movie streams, @MattMuffin.

**Comment by MattMuffin** [comment]
@palula yes you are right. I tested both movies with KickAss and TV shows with EZTV.
