### ISSUE TITLE
Recently added TV Shows

### ISSUE THREAD

**Issue by Grintss** [scakemyer/plugin.video.quasar#346]
I've seen scakemyer say this is working and close issues, however it is not working.  You can run a library update all you want but it's not going to show new shows if the strm files are not present.  On Android 4.4.4 with Kodi v16, Quasar does not add new strm files to the library folder after you initially add the show.  I can provide logs if needed.

**Comment by m4xc4v413r4** [comment]
Then provide them. 

The only way this happens is if it is androids fault, because I tested in multiple systems and it works just fine, every time a new episode comes out I have it in my library.

**Comment by Grintss** [comment]
Are there any other logs apart from the Kodi.log that I should upload?  Have you tested on Android 4.4.x?

**Comment by scakemyer** [comment]
It's working on kitkat, I don't check logs on pastebin, and yes, also closing this issue, sorry mate.
