### ISSUE TITLE
.strm files are created for unreleased episodes

### ISSUE THREAD

**Issue by johnnyslt** [scakemyer/plugin.video.quasar#347]
I think the function that creates .strm for tv shows, doesn't check if the episodes are already aired, and creates a .strm file regardless. This appeared since the migration to TMDB.

eg: The Flash S02E16 will be aired on 23 March, but a .strm file is already created for it (see pic)

![screenshot000](https://cloud.githubusercontent.com/assets/1221249/13548659/0a6e31ec-e2fe-11e5-8d0a-8bf30e0705e0.png)

**Comment by hfmls** [comment]
Yeah notice that too

**Comment by scakemyer** [comment]
It does check if the episode was already aired. I double-checked with The Flash, and episode 16 isn't being added initially or during updates, which means you updated while the episode had an incorrect date in TMDB itself. #107 will be the way to fix this.
