### ISSUE TITLE
problem with library tv shows

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#349]
I just found out that if you running tv show from library there is no choose stream option when you want to choose by seasons? Is this Quasar fault or is there need something to do in providers?

**Comment by scakemyer** [comment]
Neither, we can't control context menus in your regular library.

**Comment by nix87** [comment]
Ok.

Can you give back the option that strm file search by episode or season then? The thing is that some torrent sites won't give you results just for episode search, it need to be season search and in library season search won't work. Some sites now become useless for tv shows and that wasn't the case before.
