### ISSUE TITLE
unable to find quasar binary v.0.9.24 and 0.9.25

### ISSUE THREAD

**Issue by XanderCam** [scakemyer/plugin.video.quasar#351]
Hi
I am currently running OSMC on Raspberry Pi 2.

Quasar v. 0.9.23 runs perfectly.
When updating to **0.9.24** and **0.9.25** using the official (and unofficial) repository I get the error: "unable to find quasar binary".

Reverting back to 0.9.23 and everything works fine again.

Please advice

**Comment by MrLegendary** [comment]
Log please. Do you use the armv7 zip?

**Comment by m4xc4v413r4** [comment]
Next time you need to search for solutions first instead of doing yet another post about this.

You need to manually update to the latest version.

https://github.com/scakemyer/plugin.video.quasar/releases/tag/v0.9.25

**Comment by scakemyer** [comment]
Answer is right in the release notes, details in #331
