### ISSUE TITLE
Clicking most popular makes Quasar crash

### ISSUE THREAD

**Issue by MrLegendary** [scakemyer/plugin.video.quasar#352]
Anyone know how to fix this? 
[Here](http://xbmclogs.com/p5k0sbaeh)'s my log.

**Comment by m4xc4v413r4** [comment]
Was it working before at some time?

Damn that's an old version of openelec and kodi :)

**Comment by scakemyer** [comment]
Only solution here is to upgrade your setup, or try the linux_armv7 package, since there's nothing in this log to debug; it's just crashing for no apparent reason.

**Comment by MrLegendary** [comment]
Yes it worked a few days ago. I tried it on several devices with fresh installs. Doesn't work on Isengard, Jarvis and Krypton for me. It's not a big deal because I use most popular on trakt now, but I thought you'd wanna know.
