### ISSUE TITLE
Quasar crash on Windows 10 with versions 24 and 25

### ISSUE THREAD

**Issue by ofiryaish** [scakemyer/plugin.video.quasar#353]
i got windows 10 and kodi 16 and quasar is crashing non-stop when trying to enter the addon. the 23 version works fine.
i don't know how to upload the log in kodi 16. so if someone can explain it to me, i will send the log

thank you

**Comment by m4xc4v413r4** [comment]
http://kodi.wiki/view/Add-on:Kodi_Log_Uploader

**Comment by ofiryaish** [comment]
i don't know how to upload the log file in this site, so i uploaded it to other site:
http://www.filedropper.com/kodi

the problem is still occurring in the 26 version.

**Comment by m4xc4v413r4** [comment]
How about opening the link I gave you and reading?

**Comment by scakemyer** [comment]
Wasting our time... reboot your Windooze and GTFO

**Comment by ofiryaish** [comment]
why to use such language? 
do you think i didn't try to reboot the computer?
 m4xc4v413r4, 
I tried to use the add-on, but it showed me an error so i thought it doesn't work. today i tried again and it succeed (there were a probably a problem with the connection of the site).
so here is the log:
http://xbmclogs.com/p1mouwwxd
