### ISSUE TITLE
strm file to search by season or episode or if it's possible by both?

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#354]
Can you give back the option that strm file search by episode or season? The thing is that some torrent sites won't give you results just for episode search, it need to be season search and in library season search won't work. Some sites now become useless for tv shows and that wasn't the case before.
Before season search was implemented one particular good site was giving results for tv shows and now because Quasar search only by episode through library it won't give anything.

**Comment by scakemyer** [comment]
I can't understand a fucking word you're saying. Go home, you're drunk.

**Comment by mancuniancol** [comment]
I am solving that request to provider level.  Some sites work better searching by season (season #), instead of episodes (S00E00).  With the introduction of season_search, I've separated both ways.  But, some people are missing the old way to search.  I am adding an option which allows the user to choose.

**Comment by nix87** [comment]
Hahahahaha I wasn't drunk, but sleepy maybe :P 

Anyway mancuniancol solve the problem, now everything works like before.

Thanks  mancuniancol and sickmayer for doing amazing job for this addon +1

**Comment by scakemyer** [comment]
hahah thanks, even if I still don't have a clue what this was about

**Comment by nix87** [comment]
It was about one provider (I'm avoiding that word here cause I don't know it's forbbiden or not) :D 

There is one Ruhunt provider who can search tv shows only by season. E.g. providers usually search tv shows by episode number like "Vikings S02E01" but with some like Ruhunt that can't work it need to be "Vikings Season 2" and then it will give you results. Before season serach implementation in Quasar, Ruhunt was seraching by seasons, but that was changed soon after season search was implemented. 

Season search is really great option to have but since it won't work from library for some users, like me, who likes to keep movies and tv shows there and playing it from there it's quite useless, sadly.

But now mancuniancol implemented option for user to choose what provider should search.. episode or season so with that everything will be even better then before ;)
