### ISSUE TITLE
auto update to 9.26 failed on windows, android phone, rpi 2 and 3

### ISSUE THREAD

**Issue by deusbraga** [scakemyer/plugin.video.quasar#355]
Hi there, I don't know if you are aware of this but the automatic update is failing?
Do you require logs?

**Comment by scakemyer** [comment]
Yes, logs or it didn't happen. Auto-updates are working fine on every device I tried.

**Comment by deusbraga** [comment]
close it and forget it. In my phone it updated automatically a second ago, after it failed a couple of times before. In the RPis and the pc I've manually updated after failing a couple of times, maybe the servers were too busy.. ANyway, crysis adverted. thanks for the answer

**Comment by scakemyer** [comment]
My guess is that the GitHub API was failing to return the latest tag/release. Logs would still be welcome to handle those failures a little better.
