### ISSUE TITLE
Daemon:IOError

### ISSUE THREAD

**Issue by joodle** [scakemyer/plugin.video.quasar#356]
Hi, 

I just got this error all of the sudden after it updated to the latest version (26). I Uninstalled everything, and reinstalled the latest one via zip, but it keeps getting the same error. 

Running on a raspberry 3.

**Comment by joodle** [comment]
Exact error is Daemon:IOError(22'invalid argument')

**Comment by MrLegendary** [comment]
Don't think they can help you without a log.

**Comment by scakemyer** [comment]
Exactly, an error message is totally useless without logs. And got many reports that everything's working perfectly fine on Raspberry Pi 3, no errors and faster than ever.
