### ISSUE TITLE
Keep ".torrent" files option 

### ISSUE THREAD

**Issue by AaronCompNetSys** [scakemyer/plugin.video.quasar#357]
Enhancement.
Add option "Keep .torrent file in the downloads directory", which depends on existing option to be checked, "Keep downloads".

I prefer to seed files using my local seed box that is low power, my HTPC does not stay powered on.  If Quasar also kept the metadata in file form (the torrent file) then users could easily have their own background download/seed process setup.

As an example, I would push all data from the Quasar download folder once a day to the seed box and allow it to pick up .torrents and recheck hashes.

**Comment by incredulity** [comment]
Where are torrent files stored now?  Could you not share [NFS] that directory and cron grab them yourself?

**Comment by AaronCompNetSys** [comment]
I can't find them but I would assume its written to disk somewhere instead of just RAM.

**Comment by mozzymoz** [comment]
@AaronCompNetSys the torrents are stored in the configured Download path in the Addon settings

**Comment by AaronCompNetSys** [comment]
@mozzymoz I just checked my 0.9.36 version, and the torrents are not saved in the configured path.  There is a fastresume file that may contain the torrent, but I do not know how to extract the .torrent file from it.

**Comment by mozzymoz** [comment]
@AaronCompNetSys Sorry my bad. I didn't realize they were fastresume files
