### ISSUE TITLE
Multi-files torrent support by plugin URL

### ISSUE THREAD

**Issue by TheWizIL** [scakemyer/plugin.video.quasar#36]
Hello.

It will be great if we could play torrent file directly with index file in torrent.
Like: plugin://plugin.video.quasar?url=http://aa.com/aa.torrent&index=10
So this link will get url torrent and play file index 10 as show in torrent file structure.

I saw it working on script.module.torrent2http (https://github.com/DiMartinoXBMC/script.module.torrent2http)

Good day.

**Comment by scakemyer** [comment]
Duplicate of #17, except maybe the index in url

**Comment by i96751414** [comment]
The index thing is a great idea. I will work on this later

**Comment by scakemyer** [comment]
Implemented in scakemyer/quasar#9 by @i96751414
