### ISSUE TITLE
Icons/Categories missing description

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#360]
[Screenshot](http://i.imgur.com/C5hssUZ.png)

In the last update i get just the first categories names and then it's all blank. The genre categories. The icons are still there, but the desciption (label) is missing

**Comment by scakemyer** [comment]
Thanks, seeing the same and was just wondering if it was due to what I was working on (Trakt lists!) or the previous update.

**Comment by scakemyer** [comment]
This doesn't make any sense... nothing changed for genres, icons need the right genre ID to show up, and list items are fine...

**Comment by scakemyer** [comment]
Fucking TMDB... passing `language` (no pun intended) now returns `null` for the `name` field... So either they fucked something up, or someone deleted all translations for genre names.
