### ISSUE TITLE
Different results when using 3 providers instead of 2

### ISSUE THREAD

**Issue by eSkRo32** [scakemyer/plugin.video.quasar#364]
Not sure if this has been talked already as i can't seem to find anything on it.

Is this normal? 
Shouldn't quasar show the same number of results for a provider
if using 2 or 3 different providers??

thanks guys!!

**Comment by MrLegendary** [comment]
You can't ask provider related stuff here. I think you need to be here: http://github.com/mancuniancol

**Comment by scakemyer** [comment]
Sigh...

**Comment by scakemyer** [comment]
Sorry @eSkRo32, the discussion is valid but keep specific providers out of it

**Comment by scakemyer** [comment]
So, this is related to the limit for total results and how fast / when each provider returns links. I'm sure some improvements could probably be made here.

**Comment by eSkRo32** [comment]
sorry for that, 
i did opened a ticket issue for providers issue over at mancuniancol's github.

its just that im not sure if its a quasar issue or a provider issue :/

**Comment by scakemyer** [comment]
That one is mostly Quasar, hence why I re-opened it ;)

**Comment by eSkRo32** [comment]
oh ok thanks :)
So what can we do for that?
thx

**Comment by mancuniancol** [comment]
You need to increase Quasar time out and usually it fix the problem

**Comment by eSkRo32** [comment]
sorry mancuniancol, thought it was a quasar provider.
this can be done in the settings of quasar?

**Comment by mancuniancol** [comment]
Yes, in Quasar's settings.

**Comment by mancuniancol** [comment]
If it works for you, please, let us know. Because, this is not really an issue. It is more tweaking configuration.

**Comment by eSkRo32** [comment]
sweet thanks will try that once im at home 
cuz at work there's no way :/

i'll let you guys know 4sure!
sorry bothering you 2 :/

**Comment by mancuniancol** [comment]
Pas problème

**Comment by eSkRo32** [comment]
and after tweaking Quasar's time out,
is there a setting for increasing the limit for total results?

thx

**Comment by mancuniancol** [comment]
In Each provider. By default, it is 10.

**Comment by eSkRo32** [comment]
wonder if i should ply with that or mostly wont change the main issue,, hhmmm,,,

**Comment by mancuniancol** [comment]
But, you should go to a forum. This place is more for bugs and request. Not support.  Sorry.

**Comment by eSkRo32** [comment]
ok, i'll just post my results here after tweaking to let you guys know at least,
thx alot!

**Comment by eSkRo32** [comment]
Hi guys sorry for the delay, 
well out of luck..

I get mixed results when playing with time out setting. 

Sometimes i get some lets say 720p results in list and sometimes  for the same provider that showed me 720p it doesnt show in list anymore. 

But when using just 2 all results are ok. 

Add a 3rd one results will differ...

**Comment by mancuniancol** [comment]
That means the same, your system is too slow to deal with 3 providers. The only way to increase your time out. Sorry

**Comment by eSkRo32** [comment]
It doe that on my Galaxy S4, my Triple-core HTPC with dedicated GPU and on raspberry Pi 2.
I have a 30 mb/s internet connection. 
:/

**Comment by mancuniancol** [comment]
What is your time out values?

**Comment by eSkRo32** [comment]
I tried many its insane, 
from 4 seconds all the way to 60 seconds.

**Comment by eSkRo32** [comment]
Farewell, thanks

**Comment by mancuniancol** [comment]
Just google providers kodi
