### ISSUE TITLE
Quasar should auto-clean upon startup

### ISSUE THREAD

**Issue by endlessterror** [scakemyer/plugin.video.quasar#366]
This is a (critical for systems with small storage, like raspberry etc) '''enhancement''' request.

Reasoning: quite a few Raspberry boxes out there are running with 8Gb/16Gb SD cards for storage space. When Quasar crashes, downloaded files stay there. It takes a small number of crashes for the download-designated directory to fill up.

Things are bit more complicated since Quasar might (not sure here) utilise the same (download) directory for temporary files. 

Proposal: 

- at each quasar startup, delete all temporary files. This means that quasar should be able to **identify its own temporary files** for proper housekeeping

- if and only if "keep files after download" is **unset**, then delete also all **downloaded material** in the download path. 

I have at least a couple of friends that did not understand that their SD cards became full due to quasar crashes. Deleting the contents of the download dir did the trick. 

Inherent dangers: quasar **should not** blindly delete all contents of the download dir. This is especially true if the user has elected to use one of the kodi directories (eg, backup) as a download dir. 

On a related note, I must again stress the need to have a reasonable download directory default for quasar and quasar alone. I know it has been discussed again and closed without any action, however for small systems the user should choose a download path '''wisely'''. Leave a user to wisely select a download path, to open all sorts of cans of worms ;)

**Comment by joodle** [comment]
Or put a USB stick in the raspberry pi, will save your SD cards life as well :p

**Comment by endlessterror** [comment]
Keep it simple dummy :p

Seriously now, been there, tried that in about 10 installations: USB proved to be much faster, albeit much more prone to corruption.

One could of course install a small HDD, or connect to a NAS etc. Cost increases.

This should be fixed at the source. No need to introduce additional configuration complexity to the user, nor require the presence of additional hardware.

**Comment by m4xc4v413r4** [comment]
Just wondering, is your system crashing so often that this becomes a problem?
If so, why not fix that since it's clearly not normal?!

**Comment by tomtomclub** [comment]
Wahh I never have  enny  issus but I don't use rasberry slow

**Comment by KillerJoeBR** [comment]
Android boxes usually have low RAM and low storage. So it sometimes crash because it's low on RAM or storage (and other issues). And if it's running Quasar during that, one crash can lead to no storage space after it. 

Pulsar usually to crash all the time in my FireTV and i needed to delete the files manually. Quasar crash much less (i can't remember the last time it did actually) but i guess this feature would be useful for us who run Quasar on low powered boxes.

**Comment by endlessterror** [comment]
@m4xc4v413r4 it's just like @killerjoebr says. In fact, I did not encounter crashes almost at all with other add-ons. Quasar crashes quite frequently, especially when searching for subtitles.

Don't know if this is a coding issue or a rpi deficiency. With all things RPI managed with grace I'd say it's perhaps the former.

In all cases we are perhaps out of topic here. The thing is that quasar should perform some house cleaning. This is feasible IMHO.

**Comment by endlessterror** [comment]
Due to #387, perhaps Quasar upgrades should also clean cache files upon first run.

**Comment by scakemyer** [comment]
Good proposal if it wasn't for being so know-it-all about what **should** and **shouldn't** be. There are bits of something useful in all those words, and valid points, but still closing in favor of #361. Feel free to contribute to those coding issues next time, otherwise your humble opinion about what is feasible is rather useless and quite insulting also. Points for a well written essay though, that was refreshing ;)

**Comment by endlessterror** [comment]
First, If you feel insulted, please don't be; I was trying to explain thoroughly what needed to be done, and then even more clearly why **I** feel this has to be done. So that explains the IMO in IMHO. "H" comes from the fact that I am not a programmer. Not any more and not for years.

Bottomline, is that I am afraid you've misread the attitude of my message here. If I was sure what would have to be done, my post would definitely sound like "you're doing it wrong". And not, in fact, selecting words like "proposal" to describe my mind...

Just want to set the record straight here regarding to what I think and what I have to offer. Just my way I could contribute to a good (and I am no ass-licking here) project. There is no need to alienate me and other users/bug reporters, just because they feel strong about what they tjhin

**Comment by stupidusername** [comment]
I placed this code on /storage/.config/autostart.sh to solve this issue for now

(find /storage/videos/quasar/* -not -path "/storage/videos/quasar/Torrents*" -delete) &
