### ISSUE TITLE
Select torrents dialog skinning

### ISSUE THREAD

**Issue by xdeee** [scakemyer/plugin.video.quasar#367]
Is that possible to display Select torrent dialog (_DialogSelectLarge.xml_) using current installed skin?
Current dialog looks ok with Confluence but we have some nice skins like Experience 1080.

And Kodi 17 uses brand new default skins and I suppose quasar should support it.

Thank you.

**Comment by scakemyer** [comment]
That's not how add-on skins work. We'll update the look to the new default skin but that's all we can do.
