### ISSUE TITLE
'No links found'

### ISSUE THREAD

**Issue by twicejr** [scakemyer/plugin.video.quasar#369]
I don't know what happens exactly, but, I have got internet, everything on osmc works.
Quasar worked perfectly, until now, suddenly. Maybe after a apt-get update on OSMC?

The log looks very strange to me, because all providers are first too slow, and then all links are blocked by keywords, or so it seems.

All video types are accepted, except for trailers. They are blocked.

[close please, sorry, url log removed]
`

**Comment by entr** [comment]
Increase provider timeout in Add-on settings or disable slow providers. Some providers perform significantly more http requests thus take more time to complete. As you can see they still pass results to Quasar but are already ignored because Quasars timeouts on them.

**Comment by twicejr** [comment]
I already upped it, and it's fast on every other thing the pi 3.
But will raise it even more and try

**Comment by twicejr** [comment]
THanks, it solved it, very strange that this issue only occurs now, and it worked perfectly before!

**Comment by entr** [comment]
You forget the fact provider response time depends on how much it's loaded at the time. In rush hours some may become quite slow.
