### ISSUE TITLE
Movies & TV Shows listing customization

### ISSUE THREAD

**Issue by RikrdoPC** [scakemyer/plugin.video.quasar#374]
Lets say I mainly use the add-on as a streaming service it self without any library integration, since Trackt.tv has been incorporated to the lists (which is awesome btw), would it be possible to configure or customize the quasar menus (for Movies & TV Shows) to shown only what I mainly use? I'm more of a Trakt.tv user and have never really liked the TVDB listings, also there are some different artwork behaviors between them that can seem odd in some/most skin views.

**Comment by m4xc4v413r4** [comment]
The library integration is still streaming. It's exactly what you're saying you want, a customized list with just what you like to watch.

**Comment by RikrdoPC** [comment]
Well kind of.. I mean yeah I understand I would have only what I've added to the library and its still streaming, but that wasn't my point, Im not talking about the specific movies or tv shows but about the lists, for example the popular, trending or most watched etc trakt lists which I often use and am familiar with.

**Comment by scakemyer** [comment]
Sorry that's just not going to happen, this isn't like a skin that can shuffle menu items around.
