### ISSUE TITLE
Cookies Payload

### ISSUE THREAD

**Issue by mancuniancol** [scakemyer/plugin.video.quasar#376]
I want to send the cookies that I get from private sites to allow Quasar to download the torrent file.

I've tried with the provider.append_headers method without success. In the return payload, I've added the uri=provider.append_headers(torrentfile, {"Cookies" : myCookiesInStringFormat }

But, Quasar doesn't download the file.  Could you give me some information why it is not working, please?

My other approach is to download the torrent and to give it to Quasar:  uri = "c:\download\1.torrent", but it doesn't work neither.

It seems that Quasar transform the torrent to magnet and it doesn't work with private torrents.

I do the same  procedure in Torrent V2 and the file is downloaded without any problem.

Thanks in advance.

**Comment by entr** [comment]
What I do is `cookielib.LWPCookieJar.save()` to file on a successful login then `cookielib.LWPCookieJar.load()` for every following request and it works fine. Haven't tried downloading an actual .torrent though.

**Comment by mancuniancol** [comment]
I don't understand your post. I am not asking how to save cookies. How I keep the session open for Quasar to be allowed to download a torrent if it is the provider which opened the connection?

**Comment by mancuniancol** [comment]
@entr if you read the Quasar's provider documentation, you will understand that I am talking about.

**Comment by mancuniancol** [comment]
I am not too ignorant not to know how to handle cookies in python.. :)

**Comment by entr** [comment]
Wow, no offense. Really not implying you are. Just saying how it worked for me. not having to perform POST every time a provider is used. Too frequent logins may attract unwanted attention.

If you explicitly rely on provider requests methods why don't you just POST/GET with with_cookies=True. I'm guessing here but it looks like it manages the cookiejar for you.

**Comment by mancuniancol** [comment]
Sorry, I didn't know that you were talking about that flag. But, the problem is not in the provider. It is between the provider and Quasar.

**Comment by mancuniancol** [comment]
When the provider returns the payload to Quasar, it sends the uri with the torrent. That works perfect for anonymous downloads. But, for private sites, Quasar is blocked. 
Or how could I use that flag to send the right cookies from each provider?

**Comment by entr** [comment]
I see. It seems undocumented but `prodiver.with_cookies(url)` seems to do the same as `prodiver.append_headers({"Cookies": "..."})` but for the cookies part only and using provider's jar... if that's helpful.

**Comment by mancuniancol** [comment]
The only way is using the provider.append_headers method to attach the cookies info to uri. Or, do you know how to bypass that with cookielib?

**Comment by mancuniancol** [comment]
Yes, but you need Quasar has implemented that. Now, I think you understand my question. :)

**Comment by mancuniancol** [comment]
Then your suggestion of use cookiejar doesn't apply. That why I thought that you were joking the first time.

**Comment by scakemyer** [comment]
Reopening #38, I suspect support for cookies or at least clearer instructions on how to set them is part of the issue.

**Comment by nix87** [comment]
You are probably right about cookies. Look what I'm found, maybe it could be helpful for issue?

http://dentoo.info/shop/index.php?option=com_content&view=article&id=57&Itemid=94
https://forum.utorrent.com/topic/49190-private-trackers-add-by-url/

So I belive cookeis indeed could be the problem.

**Comment by nix87** [comment]
Is there any progress on the subject yet??

:)

**Comment by scakemyer** [comment]
The header name for cookies is just `Cookie`, not plural... Everything seems to be in place other than that.

**Comment by scakemyer** [comment]
@mancuniancol can you try with `prodiver.append_headers({"Cookie": "..."})` ? If it works it's been a costly typo ;)

**Comment by nix87** [comment]
Hmm but still Quasar player won't play torrents from private trackers. It could be problem in poviders but isn't that Quasar should play torrents when you manually play a torrent from a player? I download torrent from tracker and then go to Add Torrent, File, and locate downloaded torrent and try to play but it won't work. Something blocking download? On the other hand when I do the same just for public ones there is no problem at all. Hence probably that's why providers have problems with privates in the first place and works ok with public ones.

**Comment by mancuniancol** [comment]
@scakemyer, I've enabled the support for private providers inside of Magnetic using LWZCookiejar and it seems to work without changing the payload to Quasar.

**Comment by nix87** [comment]
It's no use still Quasar blocking those kind of torrents. I'm sure there must be way to make it work. If Torrenter ot YATP can open those I really don't see the reason why Quasar hanging?
