### ISSUE TITLE
Quasar crashes on Windows 10 since version 24

### ISSUE THREAD

**Issue by ofiryaish** [scakemyer/plugin.video.quasar#380]
I opened an a topic about this issue, but there were some misunderstandings. therefore, i opened it again. 
here is the logs:
http://xbmclogs.com/p1mouwwxd

And yes, i did reboot my windows.

**Comment by JoaoEdu93** [comment]
I installed Quasar on Windows 10 and it crashes at startup. I also installed on Windows 8.1 and it works, so I think the problem is on Windows 10.
Here is my log: http://xbmclogs.com/pldrzg7ux

**Comment by scakemyer** [comment]
Thanks for the logs guys, unfortunately it's not showing anything that could help, no stacktrace or anything. @ofiryaish you also said:
> I tried to use the add-on, but it showed me an error so i thought it doesn't work. today i tried again and it succeed (there were a probably a problem with the connection of the site).
So which is it, still crashing or it works for you now?

**Comment by ofiryaish** [comment]
Yes, I talked about the log-uploader add-on, not quasar. 
for now my solution for quasar is to use the 23 version, but it's annoying to know that you can't update it.

**Comment by scakemyer** [comment]
Well, some other dev running Windows 10 will have to fix this, because I only have a VM with Windows 7, and don't really give a shit about Windows anyway. Get a real OS.

**Comment by ofiryaish** [comment]
scakemyer,  what is the meaning of this message?
"<urlopen error [Errno 10061] No connection could be made because the target machine actively refused it>"

**Comment by scakemyer** [comment]
Your Windows 10 firewall is blocking calls between the daemon and the add-on.

**Comment by ofiryaish** [comment]
how it can be if the firewall is off?

**Comment by Greenbaburu** [comment]
Ofiryaish, wait the "Quasar Daemon has started" (20 seconds?) message and then launch Quasar.

**Comment by ofiryaish** [comment]
I am waiting but the message i get is that Quasar has crashed and it's resting.

**Comment by Greenbaburu** [comment]
Try a stable version of Kodi, not an Alpha

**Comment by ofiryaish** [comment]
I used each version from the 15th one, and always get the same error. 
something is wrong with windows 10. i don't know why i installed it from the first place. but now, for me there is not going back' so i am trying to find a solution.

 scakemyer, i don't understand why you closed the topic, maybe there are other people who capable to find a solution.
