### ISSUE TITLE
Randomly video crashing while watching

### ISSUE THREAD

**Issue by sdiego** [scakemyer/plugin.video.quasar#381]
Hello,
I'm facing some problems while watching a tv show or a movie in Quasar.
It randomly freezes and closes the video, it happens for 20 times in a 30min video, making it really annoying to watch!

Can you identify the cause? It started to happen about 2 weeks ago.
Here's the log with one freezer and crash:
http://xbmclogs.com/panpajjre

And here's with several crashes:
http://xbmclogs.com/pquu4n9tm

**Comment by scakemyer** [comment]
Only the Kodi video player is stopping here, there's not a single Quasar crash in those logs. There's nothing for me to debug here. Try increasing cache values in your advancedsettings.xml. That and wasn't Kodi 16.0 released about two weeks ago?
