### ISSUE TITLE
Possible bug with limit upload speed after buffering ?

### ISSUE THREAD

**Issue by XanderCam** [scakemyer/plugin.video.quasar#382]
I have come across a possible bug (or I might be misunderstanding).
When I activate the upload speed limit and choose "after buffering" I would think that this would only apply to Seeding (after 100% download is complete).

Is it so, that this also should affect buffering while pausing a stream (before 100% is reached) ?
A.k.a before seeding begins?

**Comment by scakemyer** [comment]
You're misunderstanding, but it should read as "after initial buffering". See #6
