### ISSUE TITLE
Option to disable UPNP & NATPMP

### ISSUE THREAD

**Issue by rosskopf** [scakemyer/plugin.video.quasar#385]
Hi,

is it possible to disable those 2 options, because i'm using openvpn connection and i don't need to open the ports on my router.
I could disable UPNP on my router but then i have problems with my ports on my xboxone, ps4 & ps3 because some are use the same ports...
it would be very handy.

Thanks!

**Comment by incredulity** [comment]
I have disabled such 'features' on my router.  I would like an option to disable them in quasar to reduce resource consumption.

**Comment by rosskopf** [comment]
Thanks :)

**Comment by scakemyer** [comment]
You're welcome! It'll be in 0.9.43 later tonight.

**Comment by rosskopf** [comment]
I see i can give u a beer for this asome addon, but i don't have bitcoins. Is it possible thru paypal?

**Comment by scakemyer** [comment]
PayPal is inherently traceable, and while I'm confident about the legality of the add-on I simply don't want to take any chances. If you don't already have a VPN, or don't mind getting another one, a TorGuard subscription using the link on the website is all there right now. Thanks for even just considering! :)

**Comment by rosskopf** [comment]
oh,oke, i understand.
i see what i can do with bitcoins.
