### ISSUE TITLE
QUESTION: Wich p2p player is used in quasar?

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#388]
Hi there, i got a question, just out of curiosity, no doubt quasar work done is amazing, but today i tested torrenter v2 (been a while since i last used it) and there was one thing that got me intrigued, torrenter uses torrent2http (libtorrent via http) and i asked myself if the same would be possible with quasar?
https://github.com/steeve/torrent2http
why i ask this is because the prebuffer speed and peer connection in torrenter is way way faster then the currently being used with quasar. After i pick a torrent i go from 0 to 1mb/s in 3 seconds, and in quasar it takes like 5-10 seconds. Also in torrenter getting full seeds/peers connection is almost instantly. 

If anyone could replicate to confirm i would appreciate.

i don't know if this is a stupid question, but just questioning because i found this speeds kinda cool.

**Comment by endlessterror** [comment]
AFAIK, quasar uses libtorrent.

**Comment by scakemyer** [comment]
torrent2http is two years old, it's the ancestor of libtorrent-go. Stick with torrenter if you find the speeds that much better.
