### ISSUE TITLE
error downloading subtitles with quasar subtitle service RP 3 Openelec

### ISSUE THREAD

**Issue by Kiralina** [scakemyer/plugin.video.quasar#389]

**Comment by tomtomclub** [comment]
Work here but I don't use crapie rpi  
But remover sub addon en try install subs addon wan more time

**Comment by Kiralina** [comment]
Quasar subtitles service is installed with Quasar, not as a separate addon, so there's no way of uninstalling and reinstalling it separately.

**Comment by tomtomclub** [comment]
Oh oké sorry men. but. You can install opensubs  I never Just
Qwesar subs,  but kodi repo opensubs

**Comment by scakemyer** [comment]
learn to type @tomtomclub, it's fucking painful trying to read your verbiage
