### ISSUE TITLE
"0" should be gould value for various ratios / speeds

### ISSUE THREAD

**Issue by krzynio** [scakemyer/plugin.video.quasar#392]
Quasar daemon uses "greater than" condition to set or not various settings. I think that "greater than or equal to" should be used.

**Comment by scakemyer** [comment]
And double the amount of settings? Because we'd need both an "enable" and "value" for every single one in that case and settings are already getting bloated. So no, 0 means "not set" or libtorrent default.

**Comment by krzynio** [comment]
Maybe you can compare strings so empty would not be the same as zero. Problem solved

**Comment by scakemyer** [comment]
They're not strings after integer settings are loaded. There's nothing to gain here, ratios and speeds that are not set / 0 value already behave like they were 0 by not being set.
