### ISSUE TITLE
Trakt http: error

### ISSUE THREAD

**Issue by lordjg** [scakemyer/plugin.video.quasar#393]
Hi guys i've receiving an http error each time i try to access or add something to trakt.
I've sync the trakt and quasar several time with the given code but i always get the error.

**Comment by gsrcobr** [comment]
Same here ( Quasar 0.9.28)

**Comment by gsrcobr** [comment]
Clearing addon cache it got automatically updated and now it's working (0.9.30) ;-)

**Comment by scakemyer** [comment]
#387
