### ISSUE TITLE
Trakt Lists - Library Integration

### ISSUE THREAD

**Issue by eidermar** [scakemyer/plugin.video.quasar#398]
All thumbs up for what you guys have done with this. With the last version even Trakt list integration found it's way into this gem. Although I'm already more than happy with the plugin as is, I'll leave a small and absolutely non-urgent feature request here nonetheless, maybe some might find it useful too. 

Before Quasar we were able to integrate Trakt lists into the Kodi library via third party scripts for playback with Pulsar. As library integration is already part of Quasar and now also Trakt, the ultimate thing would be a combination of the two features natively. User specified Trakt list that automatically integrate into the library and update regularly. I wouldn't even mind if it wasn't for the watched status, widgets and some other smaller features that are convenient with Kodi's native library and add to the experience. 

Thanks for lending your ear!

**Comment by deusbraga** [comment]
I was about tobwrite the precise same thing. Thank you for phrasing my thoughts an needs. I feel it must be the last two things quasar is missing (just my opinion) to truly become legendary. I would love to add my custom list to it, add it to the library an then have it update the tv shows automatically

**Comment by scakemyer** [comment]
Seems there's always just two last things missing...

**Comment by m4xc4v413r4** [comment]
@scakemyer the life of a developer in one phrase xD

**Comment by hfmls** [comment]
i used to use that too, everytime i opened openelec addon would scan if my watchlist/collection list changed and added new tvshows or such and updated/scrobble.

**Comment by scakemyer** [comment]
It is done. Coming up in 0.9.39 shortly :)
