### ISSUE TITLE
Quasar subtitle service

### ISSUE THREAD

**Issue by Kiralina** [scakemyer/plugin.video.quasar#400]
On raspberry pi 3 with openelec 6.0.3 ,quasar subtitles service gives me "failed to download subtitles" error, with the latest quasar build.  Opensubtitles work fine.  

Kodi and Quasar are in English and I only search for English subtitles.

On my android tablet, quasar subtitle service works with no errors.

Thank you for this amazing addon.

Later edit:
I have the download path set via smb to an external HDD connected to the router, for my RP3 and it seems this is causing the problem. The android tablet has internal storage download path. 

On RP3 if I go in the audio and subtitles settings while playing the movie and search for them, they are there, so they are downloading, but not directly on the movie. It is a bit strange, because all worked fine in previous versions of Quasar, with the same download path. This is not my finding. I got help on the Kodi forum.

**Comment by scakemyer** [comment]
So, just smb issues, nothing in Quasar is actually causing this. As it was mentioned countless times, external drives and smb mounts aren't recommended, let alone supported, even if they might work in some cases.
