### ISSUE TITLE
Request/Question: Import trakt Collection/watchlist supported?

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#401]
Hi there, i noticed when i enter quasar i can go into my watchlist or collection list (trakt), but importing tvshows is still manually 1 by 1 right?
Please just confirm this, don't know if i am missing the option to import all.

If not, would it be possible in future to add option to import entire collection/watchlist?

thank you very much.

**Comment by scakemyer** [comment]
#398
