### ISSUE TITLE
Files not deleted on Windows 10

### ISSUE THREAD

**Issue by korenziv** [scakemyer/plugin.video.quasar#414]
Hi @Scakemyer,
Files not deleted after finished to see a series tv shows. In the setting the save stream is closed. and the Handle torrens in backround closed also.
in addithin: After i see one episode and want to see addithinal one the quasar dont work.

Win10 64 bit. (I see some posts with crashes problem with guys with same WIN 10 64bit)

I think this is the reason the Kodi still crashed with Quasar in my PC. 

http://xbmclogs.com/psuvm6wli

**Comment by scakemyer** [comment]
Thanks for the logs but I can't see anything in there causing the problem, the logs cut before you try to watch something else.

**Comment by korenziv** [comment]
What about the not deleted file

**Comment by scakemyer** [comment]
What about it? I can't magically figure out what happened.

**Comment by korenziv** [comment]
I thoght it seems in the log. 
I saw some errors there. But if you say so you no so :)
I dont know to read logs. 

Thanks.

**Comment by tomer953** [comment]
enable debug log, then try to stream 1-2 episodes (skip to the end of the stream...) - if the files are keep stacking - post the log here.
sounds like permission issue to me...
