### ISSUE TITLE
Option to disable seeding after a download completes

### ISSUE THREAD

**Issue by fellenberger** [scakemyer/plugin.video.quasar#415]
Would like the ability to disable automatic seeding of a torrent after it has been downloaded.  While streaming a movie/tv show, seeding has the ability to commence when the download completes before I finish watching the video.  I already ensure that the download is *not* saved after I finish watching it, but would be good to allow one to stay under the radar from a seeding perspective.  Currently using 0.9.32 on Kodi 16.0 on a Fire TV Stick and loving it.  Thanks for all of your great work with this app!

**Comment by scakemyer** [comment]
You can set your seeding limits when using background handling, but when you're not, you seed while watching, that's how it is and it's the least you can do to not be a total leecher. I'm glad you enjoy the add-on, but adding that option would make Quasar a pretty bad client.
