### ISSUE TITLE
Unable to fast forward through a video even if the entire file has been downloaded first (and seeding)

### ISSUE THREAD

**Issue by fellenberger** [scakemyer/plugin.video.quasar#416]
FireTV Stick + Kodi 16.0 + Quasar 0.9.32

When I choose a TV show or movie to stream, I am unable to fast forward to the middle of the video, even if I wait for the entire download to complete.  Should not have a buffer or video fragment issue in this case.  Video just freezes after forwarding through about 1-2 minutes of the stream.  When I press play after that, I can still hear audio but the video remains frozen.  Have to press stop to clear out and choose something else.  Seems intermittent but very common as once I was able to fast forward well over an hour into a movie without issue.

**Comment by nix87** [comment]
That could be Kodi broke also. I use to have that kind of problems with physical copy on my Kodi and after I try to skip some video, video just got frozen. I mean it could be Quasar in your case but I'm just sayin that could be Kodi also?

**Comment by scakemyer** [comment]
That's Kodi, and can depend on many things, like which hardware acceleration option you're using. I've had the same thing happen with OMX, and not with MMAL. I don't know what's available when using a FireTV stick, but Quasar itself doesn't play or fast forwards your files, Kodi does. When you *once were able to*, was it on Kodi 15.2? You need to keep in mind Kodi was also updated recently. Provide some logs and if there really is an issue with Quasar here I'll be happy to reopen this.
