### ISSUE TITLE
Explanation for seeding stats?

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#418]
As I mention it's not a issue it's just a question probably for scakemyer but if someone else know he can answer as well ;)

In Torrents part in Quasar those 2 stats eg. 0.10/1 and 0.10/1(0) what those supposed to show? I mean I know it's something about ratio but there is two indicators and I'm confused which one is about how many you uploaded that torrent and what is that other indicator?

I made picture for better explanation if needed as well :)
http://i64.tinypic.com/155tjmg.jpg

**Comment by scakemyer** [comment]
Seeding ratio, Seed time ratio and Seed time in parenthesis :)
