### ISSUE TITLE
private trackers blocking??

### ISSUE THREAD

**Issue by lyanko** [scakemyer/plugin.video.quasar#421]
Hi, first of all I wanna thank to all people who are responsable for this amazing addon. I'm using Qusar very much and he is my favorite addon.
I wanna ask one thing though. Why Quasar have problems with private trackers so much. I have couple of ones and every tracker I tried Quasar can't download torrents from them? 
I read that other torrent streaming addons like kmedia torrent or torrenter are doing fine with those kind of torrents so what is difference between Quasar and those?  Did someone know what should be done to make Quasar work with private trackers?

**Comment by Alan365** [comment]
Your not alone i have the same problem

**Comment by scakemyer** [comment]
See #38 #358 #376, we'll get there.
