### ISSUE TITLE
Quasar in loop - updated / daemaon started

### ISSUE THREAD

**Issue by gsrcobr** [scakemyer/plugin.video.quasar#422]
Since 0.9.32 quasar enters in a loop showing "quasar addon updated", " quasar daemon started" and repeats each few minutes

**Comment by tomtomclub** [comment]
Same here rebooting 

http://pastebin.com/AE7x9G0y

**Comment by gsrcobr** [comment]
Yes, rebooting and crashing :(
Running Rasperry Pi 2 model b (512MB)

**Comment by tomtomclub** [comment]
Yes I use Intel asrock j1900 but the  same shit happens  on the wetek

**Comment by scakemyer** [comment]
There's no crash, reboot or anything in that log besides the daemon starting up and working perfectly fine.

**Comment by tomtomclub** [comment]
No way it show 50 crash log rebooting non stop I renove Qwesar en reinsrall all fine now but it happens on 2 kodi systeem starting on the same time running in to loop

**Comment by scakemyer** [comment]
well send logs of that happening instead of one where everything's working fine
