### ISSUE TITLE
Allow more ListItem details in generic search

### ISSUE THREAD

**Issue by entr** [scakemyer/plugin.video.quasar#424]
Quasar should allow a more detailed `xbmc.ListItem` in a generic search (neither movie or show). Depending on the provider `Thumb`, `Size`, `Duration`, `DateAdded` even `UserRating` may be available thus a more informed choice can be made.

https://github.com/scakemyer/quasar/blob/master/api/search.go#L34

**Comment by nix87** [comment]
Also it will be good if it's possible in the torrent list when seeding torrents that Quasar shows from which provider torrent is taken?

**Comment by scakemyer** [comment]
ListItems for those search results isn't the right way to display them in the first place. They'll be using the same dialog as Choose stream once I fix #204.
