### ISSUE TITLE
Quasar crashes, but solution #45 brakes my Ubuntu 

### ISSUE THREAD

**Issue by mkkyah** [scakemyer/plugin.video.quasar#425]
Hi,
Quasar is crashing at kodi startups as you heard from other users. I have found and applied the solution from issue #45, but it has broke my Ubuntu somehow.
I have a Max2Play image(Ubuntu 14.04) running on an Odroid U3 and after the fix Kodi failed to start.
It seems that I have libstdc++6 installed. Is there a way to repair it without ruining Max2Play?
Here is my log, I have posted it on the forum before: http://pastebin.com/eignCr5t
thanks

**Comment by Stane1983** [comment]
#45 is not solution. I pointed that out here https://github.com/scakemyer/cross-compiler/issues/1 but author decided to know better what LTS stands for and why system core parts are not updated on long term support OSes.

**Comment by mkkyah** [comment]
Thanks for pointing out. I couldn't find a solution and uninstalled Quasar. I hope he can find a solution for everyone here.

**Comment by scakemyer** [comment]
@Stane1983 LTS means the OS maintainers keep supporting older packages with security updates, it doesn't mean we all have to keep building new projects on old toolkits. Get over it.
