### ISSUE TITLE
Quasar add-on causing intermittent kodi freezing OpenElec

### ISSUE THREAD

**Issue by kostaboxon** [scakemyer/plugin.video.quasar#426]
Running Linux Arm7 Using OpenElec Kodi 15.2 .MXQ S805 Quadcore. I bring this to your attention as i have random kodi lock ups where the box stops responding to remote commands. It is frozen. Unplug re plug is only way to get box going again. Quasar works great apart from causing hanging issues at random in Kodi.
I DISABLED Quasar and ran the box for 1 hour flicking through the menus playing streams etc and the box never froze once. Re enabled Quasar and the freezing came on within 5 minutes. Disabled Quasar and the box stopped freezing.
Let me know if logs are required or your thoughts as to why this happens. I am not sure if Quasar can start the Daemon when Quasar is opened via addons rather than running on start up as this is an issue at the moment.
debug kodi.old.log:Taken after it froze. http://xbmclogs.com/prldmikfo

Turned back on debug kodi.log: http://xbmclogs.com/pgqmldd3l

**Comment by scakemyer** [comment]
Looks like you have a bunch of other memory-intensive add-ons, I think you're just running out of ram here.

**Comment by kostaboxon** [comment]
I will run some more tests and watch the ram. I think you could be right. I am going to uninstall some of the ones in my logs showing processes continuously. Thank you for the reply. I will report back with a solution as far as my issue goes.

**Comment by scakemyer** [comment]
Good plan. If that really is the issue, I think we'll have to establish a minimum available ram requirement.

**Comment by kostaboxon** [comment]
Okay i found a rogue "Dudehere process running" in addons system. I uninstalled it. Uninstalled the repo as well. Not needed. Have Quasar running with providers Enabled. No lock ups. I can only guess this was an issue but with all the constant URL resolver updates lately (including today) and problems caused by that update alone,  i can only hope. Some serious update issues with lots of addons lately.
Thank you for your time and help.

**Comment by kostaboxon** [comment]
Updated to Jarvis 16.1 OpenElec and confirm no more issues. I believe the rogue addon i wrote about above was the culprit. A lesson about add-ons. Only install what you use and nothing else.
I believe this issue can be closed. 
Again i praise you on your work with this great add-on.

**Comment by scakemyer** [comment]
Thanks. I've seen that damn "dudehere" in so many logs, no idea what it does but I'll keep that in mind next time I see that ugly ascii face ;)
