### ISSUE TITLE
External plugin interface - enable other plugins to delete quasar's torrent and downloaded content via strm file

### ISSUE THREAD

**Issue by ebol666** [scakemyer/plugin.video.quasar#428]
Hello!

Just a thought, I was thinking on better integration between quasar and [kodi file cleaner](https://github.com/Anthirian/script.filecleaner) . Basically, the cleaner detects if a file in kodi's video library was marked as watched and deletes it. With quasar, it just deletes the strm file, since only it is a part of kodi video library. It would be nice to have some kind of interface that we could call to delete the actual video content, using the strm file as input. What do you think?

**Comment by scakemyer** [comment]
strm files have no link to the video content, which may or may not already get deleted. Sorry but this doesn't make any sense for a variety of reasons.
