### ISSUE TITLE
Providers not listed

### ISSUE THREAD

**Issue by cadusouza** [scakemyer/plugin.video.quasar#429]
Please,

I have a Setup Box with Android 5.1.1 based on the Cortex-A9 processor.

I installed the KODI and is operating normally

When installing Quasar, on the part of providers I'm not having success.

I do the installation providers, but Quasar is not listed any installed provider and that the search does not return me any results.

Any idea what could be the problem?

Thank you.

**Comment by m4xc4v413r4** [comment]
We do not help with providers, there are no providers made here and there is no talk about providers here.
