### ISSUE TITLE
Revamp list view of available streams

### ISSUE THREAD

**Issue by Magic815** [scakemyer/plugin.video.quasar#43]
While this is mostly a cosmetic issue, the list view of available streams in Pulsar left a lot to be desired.

When Pulsar was set up to show all available streams, the list contained entries that were simply just long concatenated lines of info that contained seeders, leechers, size, name, and sometimes the provider. On a lot of skins, the entries became so wide that the text auto-scrolled and became hard to read.

I was thinking it'd would be great to try and parse some of the info out into a more readable format. Can size, resolution, and name all get parsed out? If so, maybe something like the following "multi-line" approach?

> ###  **Available Streams for "The Prestige"**

> **(76 / 24) 1080p [23.5 GB] - Kickass Torrents**
> _The.Prestige.1080p.BluRay.SPaRKs.mkv_

> **(51 / 12) 720p [12.7 GB] - Kickass Torrents**
> _The.Prestige.720p.BluRay.SPaRKs.mkv_

> **etc.**

I think step one would just be getting the entries to stop auto-scrolling so that they can be easily read. But then step two would be adding some polish to the view in a similar fashion to above.

**Comment by corrpel** [comment]
+1. I think file size shoud be first (in gb rounded), second rezolution and
3rd the file name

**Comment by nix87** [comment]
I think in future we could see that, but so far developers are focused on more tehnical features. I belive cosmetic changes will come later when all project become 100% stable.

But I must say it's a realy nice suggestion which I would like to see in future +1

**Comment by scakemyer** [comment]
I'm also really annoyed by this, so I'll be looking into this as soon as I can. However I'm afraid it might be a little complicated since we're using standard Kodi dialogs, and our options are limited in terms of how to display the information.

**Comment by hfmls** [comment]
i would like this too. size is more important sometimes doesn't even show up

**Comment by corrpel** [comment]
+1 yep only seeds are more important that the size.
So, we can keep the dialogue and use it like this:
[seeds,filesize(GB),torrent-name,provider**<1>**]

**<1>** - use only the first two letters from each provider name words.

**Comment by hfmls** [comment]
yes, wider please

**Comment by scakemyer** [comment]
So that's started, but I'll work on a two-line display like @Magic815 proposed, that'll be much better

**Comment by corrpel** [comment]
@scakemyer were should we modify the fonts for size?
i tried replacing everything related to the fonts in addonwindow.py, but no luck so far

**Comment by scakemyer** [comment]
Have you tried passing it as a parameter in dialog.py instead of changing addonwindow.py?

**Comment by scakemyer** [comment]
I'm opened to suggestions regarding improving this, it was really just a first draft for the revamp, but I think it came out pretty good already.

**Comment by nix87** [comment]
I love it. this is amazing work on search list!

**Comment by corrpel** [comment]
It came out awesooooome!
