### ISSUE TITLE
Rate limiting when updating library causing crash

### ISSUE THREAD

**Issue by cali4nick8** [scakemyer/plugin.video.quasar#431]
Library integration is working well on my windows and Android devices but in Openelec it is not working. The shows don't update automatically into the library. On the other platforms, when I open Kodi the new episodes are there, but in Openelec not even after I update the library. Only if I delete them from the library and add them back again!

**Comment by joao-matos** [comment]
same here. tried scan and it keeps adding them, tried not scan and it's fine but when you add new items to the library they dont appear.

**Comment by m4xc4v413r4** [comment]
firstly.... LOGS PEOPLE, LOOOGGGSSS

secondly, @joao-matos why is every single thing on your list out of date?

Library integration is working just fine on my Openelec installation btw

**Comment by scakemyer** [comment]
No logs, typical "it's not working" without any actual detail, totally outdated versions... ¯\_(ツ)_/¯

**Comment by cali4nick8** [comment]
I don't know what happened, or if you made any changes for .33 but it is working now for the first time in many months :) thanks :)

**Comment by joao-matos** [comment]
eh eh the miracles of life.
some things i keep up to date others i use the maximum "if it;s working dont touch it" and test before upgrading.
I find a bit annoying when you want to watch a "..." and it just puff gone after an auto-update.

Thanks a million

**Comment by cali4nick8** [comment]
@scakemyer It is happening again. I don't know how to get the log, but when trying to update library I get a "GetShow bad status: 404". I can get a log, but can you tell me how to get it?
Thanks

**Comment by scakemyer** [comment]
Thanks for the logs. There was a 429 error also (rate limit exceeded) and a useful stack trace of a crash after that. This really doesn't seem related to OpenELEC at all. Will look into it when I have a chance.

**Comment by ShlomiD83** [comment]
I get that 429 error on windows also sometimes.

**Comment by hfmls** [comment]
i can confirm this too, if you need any logs i'll provide.

**Comment by JoseFSilva** [comment]
I'm on Ubuntu and this is also happening here. It was working last week though.
I can send log too.

**Comment by scakemyer** [comment]
This has nothing to do with OpenELEC, Ubuntu or library integration. The 429 error is about rate limiting, and while Quasar itself will stay under the limit, and those limits are per-IP, if you're sharing the same IP as other Quasar users, either on your own network or a VPN, then there's nothing else we can do about that. Only thing is to make sure it gets handled more gracefully and without crashing.

**Comment by cali4nick8** [comment]
@scakemyer and what about the "GetShow bad status: 404" do you have any news or reason for that?
Thanks

**Comment by scakemyer** [comment]
Is this still an issue? After refactoring the library integration (coming up in 0.9.61), I suspect there's still missing rate limiting around Trakt calls, and crashes might still occur when updating large libraries.

**Comment by ShlomiD83** [comment]
still getting 429 errors after clearing cache sometimes if that's what you mean.

**Comment by scakemyer** [comment]
Good to know, that makes sense. I'll work on that for 0.9.62, if you happen to have logs of that it'd be great. Any crashes or just 429 errors?

**Comment by ShlomiD83** [comment]
tried a few times with 0.9.61 and didnt get any errors, will update if the error occurs again.

**Comment by ShlomiD83** [comment]
according to the changelog theres no more indication that quasars library is updating or finished updating. is there any way to know without installing an external addon?

**Comment by scakemyer** [comment]
I think there's still a lot of confusion between Kodi's library and Quasar's... There basically never was any indication, other than that when Quasar would update, it would trigger Kodi's re-scan of its library, but I think you raise a valid point for those that would rather only rely on Quasar...

**Comment by scakemyer** [comment]
Updated the release notes, it will be back as an option in the next release, with better logic to handle re-scans of Trakt syncing and regular library updates.

**Comment by ShlomiD83** [comment]
thanks. i also notticed that the cache folder has alot more files now. is that because of the new boltdb library?

**Comment by scakemyer** [comment]
No, it's just mostly fixed ;)

**Comment by ShlomiD83** [comment]
the cache folder depeneds on how big my library is? thats the point?

**Comment by scakemyer** [comment]
It will, yes. Movies and TV Shows don't need to be re-queried every time, neither do episodes, but seasons do, at least right before a library update, or a few times a day at most to check for new episodes. For example, you only want to query a movie's informations once a week or so, maybe once a day, but the only thing that is likely to change is its iMDB rating, same for shows and episodes themselves. So with proper cache expiration, you always get relevant infos with minimal network queries, and everything's faster. We're getting there ;)

**Comment by ShlomiD83** [comment]
got it now, thank you :)
