### ISSUE TITLE
Fastresume files cause crash on Android

### ISSUE THREAD

**Issue by XanderCam** [scakemyer/plugin.video.quasar#432]
Every now and then streaming will crash. Once or twice during a movie. trying to restart the torrent, If I don't delete the torrent .fastresume file from the torrent folder, quasar keeps crashing.

**Comment by scakemyer** [comment]
Can't do shit without logs. And I seriously doubt fastresume files cause this, even if you solve your issue by deleting them.

**Comment by XanderCam** [comment]
How do you suggest I log this?
If you strongly believe that it's not the fastresume filed, then what could it be ?

In fact it's the same issue if I stop a streaming manually. And then try to resume it later without first deleting the fastresume, quasar crashes.

If I choose Yes, when Quasar asks: "there were chosen a torrent for this file, use it?", with the fastressume file intact. It crashes.

 Delering the fastresume file, solves it.

**Comment by i96751414** [comment]
In fact, fastresume is making quasar crash... Just try to play one torrent then stop it ando finally play it again (exactly the same torrent). It will crash.

**Comment by scakemyer** [comment]
@i96751414 nice to see you're still around! Just tried that again and no issue resuming a torrent so.. got logs?

**Comment by i96751414** [comment]
It seems that this is only afecting Android. Let me recheck this and then i'll try to solve this or send some logs.

**Comment by MrLegendary** [comment]
Yes. I have the same problem with my nvidia shield, but raspberry pi works great.

**Comment by i96751414** [comment]
```
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       [0mAdding torrent
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       [0mSetting save path to /storage/emulated/0/Quasar
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       [0mChecking for fast resume data in 13241fe16a2797b2a41b7822bde970274d6b687c.fastresume
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       [0mFound fast resume data...
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       [0mEnabling sequential download
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] [32mNOTI  libtorrent   ▶ logAlerts        [0mtorrent_added_alert: Mad Max Fury Road (2015) [1080p] added
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] [32mNOTI  libtorrent   ▶ logAlerts        [0mtorrent_resumed_alert: Mad Max Fury Road (2015) [1080p] resumed
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] [32mNOTI  libtorrent   ▶ logAlerts        [0madd_torrent_alert: added torrent: magnet:?xt=urn:btih:xxxxx
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ addTorrent       [0mDownloading TorrentName
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] INFO  btplayer     ▶ onMetadataReceived  [0mMetadata received.
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] panic: runtime error: invalid memory address or nil pointer dereference
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] [signal 0xb code=0x1 addr=0xb0 pc=0xb6705280]
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar]
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] goroutine 1522 [running]:
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] panic(0xb70b8508, 0x95808038)
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] 	/usr/local/go/src/runtime/panic.go:464 +0x370
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/bittorrent.(*BTPlayer).CheckAvailableSpace(0x95a38320, 0x3)
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/bittorrent/player.go:212 +0x13c
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/bittorrent.(*BTPlayer).onStateChanged(0x95a38320, 0xb60880f0, 0x95c39f4c)
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/bittorrent/player.go:380 +0x248
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/bittorrent.(*BTPlayer).consumeAlerts(0x95a38320)
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/bittorrent/player.go:429 +0x2dc
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] created by github.com/scakemyer/quasar/bittorrent.(*BTPlayer).addTorrent
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar] Traceback (most recent call last):
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 112, in run
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]     data = _json(url)
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 48, in _json
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 126, in urlopen
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 391, in open
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 409, in _open
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/bittorrent/player.go:134 +0xb14
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] System information: android_arm 3.4.67-cyanogenmod-g9220ae3
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] Kodi build version: 16.0 Git:2016-02-20-a5f3a99
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] OS type: Linux
22:54:01 T:18446744072071081600  NOTICE: [plugin.video.quasar] uname: ('Linux', 'localhost', '3.4.67-cyanogenmod-g9220ae3', '#1 SMP PREEMPT Tue Dec 22 17:20:02 PST 2015', 'armv7l', '')
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 369, in _call_chain
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 1161, in http_open
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 1134, in do_open
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/httplib.py", line 986, in getresponse
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/httplib.py", line 391, in begin
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]   File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/httplib.py", line 355, in _read_status
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar] BadStatusLine
22:54:01 T:18446744071952270464   ERROR: [plugin.video.quasar]
22:54:01 T:18446744072346882176   ERROR: PlayMedia could not play media: plugin://plugin.video.quasar/movie/76341/links
22:54:04 T:18446744072071081600  NOTICE: [plugin.video.quasar] quasard: starting quasard
```

Btw, a quick question: When does Quasar deletes those .fastresume files? Sometimes they are deleted and sometimes they aren't.

**Comment by scakemyer** [comment]
Thanks, will look into that. They get deleted along with libtorrent's torrentInfo when background handling is disabled, otherwise when manually deleting a torrent, but I'm pretty sure there's still a race condition I mentioned a while ago about fast resume data getting written after it was deleted, can't remember in which issue.

In this case here the error happens in CheckAvailableSpace, so it looks like some metadata isn't available yet when using fastresume files.

**Comment by nix87** [comment]
For me personaly it's not a big problem but since the issue is open I can say that in windows too fastrume crashes Quasar. If I choose from stream list one torrent and I start to download that, all is fine, the torrnet is downloaded after that he stays in client and seedind start but if I choose that torrent and try to play him Quasar craches. 

I can provide log file later, soon as I return home. ;)

**Comment by XanderCam** [comment]
My latest log:
en - failed to open source <http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml.md5>
14:13:10 7190.198730 T:1655698416   ERROR: CRepositoryUpdateJob[repository.quasar] failed read checksum for directory 'http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml'
14:13:12 7192.317383 T:1491071984  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/show/61378/season/2/episodes from ['plugin://plugin.video.quasar/show/61378/season/2/episodes', '27', '']
14:13:12 7192.345703 T:1421857776  NOTICE: [plugin.video.quasar] [GIN] 2016/03/28 - 12:13:12 |[97;42m 200 [0m|   15.950581ms | ::1 |[97;44m  [0m GET     /show/61378/season/2/episodes
14:13:13 7192.508789 T:1957413424   ERROR: container.setviewmode called with invalid number of parameters (should be: 1, is 0)
14:13:13 7192.550781 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/1/play
14:13:13 7192.555176 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/2/play
14:13:13 7192.559082 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/3/play
14:13:13 7192.563477 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/4/play
14:13:13 7192.566406 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/6/play
14:13:13 7192.569336 T:1386214384 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/7/play
14:13:13 7192.572754 T:1386214384 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/8/play
14:13:13 7192.576660 T:1386214384 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/10/play
14:13:13 7192.579590 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/11/play
14:13:13 7192.582520 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/12/play
14:13:13 7192.585449 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/13/play
14:13:13 7192.587891 T:1386214384 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/15/play
14:13:13 7192.590820 T:1386214384 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/16/play
14:13:13 7192.594727 T:1386214384 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/17/play
14:13:13 7192.597168 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/18/play
14:13:13 7192.599121 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/14/play
14:13:13 7192.600586 T:1655698416 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/9/play
14:13:13 7192.602539 T:1386214384 WARNING: CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.quasar/show/61378/season/2/episode/5/play
14:13:16 7195.971680 T:1421857776  NOTICE: [plugin.video.quasar] [GIN] 2016/03/28 - 12:13:16 |[97;42m 200 [0m| 25.822693622s | ::1 |[97;44m  [0m GET     /repository/scakemyer/plugin.video.quasar/addons.xml.md5
14:13:24 7204.396973 T:1613755376  NOTICE: ES: Client  from 192.168.1.2 timed out
14:14:12 7252.228516 T:1552937968  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/show/61378/season/2/episode/18/links from ['plugin://plugin.video.quasar/show/61378/season/2/episode/18/links', '28', '']
14:14:12 7252.244629 T:1421857776  NOTICE: [plugin.video.quasar] Searching links for TMDB Id: 61378
14:14:12 7252.252930 T:1421857776  NOTICE: [plugin.video.quasar] Resolved 61378 to Madam Secretary
14:14:12 7252.274414 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mResolving torrent files...
14:14:22 7262.044922 T:1373631472  NOTICE: [script.quasar.magnetdl-mc] http://magnetdl.com/m/madam-secretary-s02e18/se/desc/
14:14:22 7262.082031 T:1421857776  NOTICE: [plugin.video.quasar] [GIN] 2016/03/28 - 12:14:22 |[97;42m 200 [0m|     110.917µs | ::1 |[97;46m  [0m POST    /callbacks/606492121
14:14:22 7262.084961 T:1455412208  NOTICE: [script.quasar.yify-mc] <addinfourl at 1754997984 whose fp = <socket._fileobject object at 0x686f4cf0>>
14:14:24 7263.883789 T:1491071984  NOTICE: [script.quasar.torrentz-mc] https://torrentz.eu/search?f=madam+secretary+s02e18
14:14:25 7265.200684 T:1373631472  NOTICE: [script.quasar.magnetdl-mc] Accepted Keywords: ['480p', 'HDTV', '720p', '1080p']
14:14:25 7265.201172 T:1373631472  NOTICE: [script.quasar.magnetdl-mc] Blocked Keywords: []
14:14:25 7265.201172 T:1373631472  NOTICE: [script.quasar.magnetdl-mc] min Size: 0.0 GB
14:14:25 7265.201172 T:1373631472  NOTICE: [script.quasar.magnetdl-mc] max Size: MAX
14:14:26 7265.700684 T:1373631472  NOTICE: [script.quasar.magnetdl-mc] >>>>>>8 torrents sent to Quasar<<<<<<<
14:14:26 7265.769043 T:1421857776  NOTICE: [plugin.video.quasar] [GIN] 2016/03/28 - 12:14:26 |[97;42m 200 [0m|     186.684µs | ::1 |[97;46m  [0m POST    /callbacks/2085489512
14:14:26 7265.773926 T:1373631472  NOTICE: [script.quasar.magnetdl-mc] <addinfourl at 1759915664 whose fp = <socket._fileobject object at 0x512a59f0>>
14:14:26 7265.984863 T:1491071984  NOTICE: [script.quasar.torrentz-mc] Accepted Keywords: ['HDTV', '720p', '1080p']
14:14:26 7265.984863 T:1491071984  NOTICE: [script.quasar.torrentz-mc] Blocked Keywords: []
14:14:26 7265.985352 T:1491071984  NOTICE: [script.quasar.torrentz-mc] min Size: 0.0 GB
14:14:26 7265.985352 T:1491071984  NOTICE: [script.quasar.torrentz-mc] max Size: MAX
14:14:26 7266.390625 T:1491071984  NOTICE: [script.quasar.torrentz-mc] >>>>>>8 torrents sent to Quasar<<<<<<<
14:14:27 7266.447754 T:1421857776  NOTICE: [plugin.video.quasar] [GIN] 2016/03/28 - 12:14:27 |[97;42m 200 [0m|     111.073µs | ::1 |[97;46m  [0m POST    /callbacks/1414077723
14:14:27 7266.452148 T:1491071984  NOTICE: [script.quasar.torrentz-mc] <addinfourl at 1756883464 whose fp = <socket._fileobject object at 0x68938930>>
14:14:27 7266.644043 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mReceived 9 links.
14:14:27 7266.645508 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mScraping torrent metrics from 10 trackers...
14:14:27 7266.846191 T:1421857776  NOTICE: [plugin.video.quasar] [31mERRO  linkssearch  ▶ 1                [0mTracker udp://tracker.publicbt.com:80 is not available because: dial udp: lookup tracker.publicbt.com on 192.168.1.1:53: no such host
14:14:30 7269.846680 T:1421857776  NOTICE: [plugin.video.quasar] [31mERRO  linkssearch  ▶ 1                [0mTracker udp://tracker.openbittorrent.com:80 is not available because: Request timed out.
14:14:30 7269.851562 T:1421857776  NOTICE: [plugin.video.quasar] [31mERRO  linkssearch  ▶ 1                [0mTracker udp://exodus.desync.com:6969 is not available because: Request timed out.
14:14:30 7269.856445 T:1421857776  NOTICE: [plugin.video.quasar] [31mERRO  linkssearch  ▶ 1                [0mTracker udp://open.demonii.com:1337 is not available because: Request timed out.
14:14:30 7269.860352 T:1421857776  NOTICE: [plugin.video.quasar] [31mERRO  linkssearch  ▶ 1                [0mTracker udp://tracker.pomf.se:80 is not available because: Request timed out.
14:14:30 7269.864746 T:1421857776  NOTICE: [plugin.video.quasar] [31mERRO  linkssearch  ▶ 1                [0mTracker udp://pow7.com:80/announce is not available because: Request timed out.
14:14:30 7269.865234 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mSorted torrent candidates:
14:14:30 7269.866211 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mS:2400 P:948 Madam Secretary S02E18 HDTV X264-LOL - Quasar MC's [COLOR FF017BD4]Magnetdl[/COLOR] Provider
14:14:30 7269.867676 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mS:2019 P:1102 Madam Secretary S02E18 HDTV X264-LOL [ettv] - Quasar MC's [COLOR FF017BD4]Magnetdl[/COLOR] Provider
14:14:30 7269.873047 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mS:752 P:409 Madam Secretary S02E18 720p HDTV X264-DIMENSION [rartv] - Quasar MC's [COLOR FF017BD4]Magnetdl[/COLOR] Provider
14:14:30 7269.878906 T:1438634992 WARNING: CSkinInfo: failed to load skin settings
14:14:30 7269.924316 T:1957413424   ERROR: Control 32503 in window 13001 has been asked to focus, but it can't
14:14:30 7269.925293 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mS:585 P:185 Madam Secretary S02E18 HDTV X264-LOL [rartv] - Quasar MC's [COLOR FF017BD4]Magnetdl[/COLOR] Provider
14:14:30 7269.926270 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mS:563 P:223 Madam Secretary S02E18 HDTV XviD-FUM [ettv] - Quasar MC's [COLOR FF017BD4]Magnetdl[/COLOR] Provider
14:14:30 7269.927734 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mS:80 P:72 Madam Secretary S02E18 720p HDTV X264-DIMENSION [ettv] - Quasar MC's [COLOR FF017BD4]Magnetdl[/COLOR] Provider
14:14:30 7269.928711 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mS:73 P:74 Madam Secretary S02E18 1080p HDTV X264-DIMENSION [rartv] - Quasar MC's [COLOR FF017BD4]Magnetdl[/COLOR] Provider
14:14:30 7269.929688 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mS:18 P:8 Madam Secretary S02E18 720p HDTV X264-DIMENSION - Quasar MC's [COLOR FF017BD4]Magnetdl[/COLOR] Provider
14:14:30 7269.930664 T:1421857776  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mS:17 P:16 Madam Secretary S02E18 720p HDTV HEVC x265 RMTeam 720P HEVC » tv - Quasar MC's [COLOR FFFFB090]TorrentZ[/COLOR] Provider

**Comment by ShlomiD83** [comment]
don't know if it's the same issue. but got crashes today on windows when trying to resume a torrent.
deleted QuasarDB.json and the issue was resolved.

**Comment by nix87** [comment]
Yes I remember now where is the problem, Its been metioned after some Quasar release version but I forgot :facepalm:

You need to delete Quasardb.json in your library. At least for Windows that procedure solve the problem with fastresume.

**Comment by ShlomiD83** [comment]
i deleted my comment, didn't know if it was relevant to the issue. but deleteing Quasardb.json seems to solve my crashes, tried only from the library, maybe outside of the library it will still crash? didn't check it out.

**Comment by nix87** [comment]
I usually use stuff from my library so deleting quasardb.json do the trick for me. I checked couple of times and from when from library fastresu,e torrent works. I didn't check from quasar though.

**Comment by ShlomiD83** [comment]
99% of the time it works, but got a crash or 2 after resuming a file. it was "stalled" for couple of seconds and then a crash. i also noticed that the fastresume file are not always deleted even with background handling disabled.

**Comment by ShlomiD83** [comment]
just one quick update. i think it only happens when the fastresume file isn't deleted and you press "yes" when it says "A torrent was previously chosen, use it?".

**Comment by scakemyer** [comment]
Race conditions in both situations... when resuming and not getting torrent info quickly enough, then fastresume files getting written right after being deleted, but in both cases it works most of the time.

**Comment by ShlomiD83** [comment]
Tried to reproduce the problem yesterday and couldn't. Every time it worked fine. Very strange.

**Comment by scakemyer** [comment]
That's often the case with race conditions, sometimes you just can't seem to reproduce them. I'll eventually track down what causes this one using @i96751414's stacktrace.
