### ISSUE TITLE
What version do I need

### ISSUE THREAD

**Issue by RoystonB** [scakemyer/plugin.video.quasar#435]
Hi All,

I download a version of Quasar to Matricom G-Box q, but nothing will stream. The Buffer starts and builds up to 900Kbps and then dies down to 3Kbps, and then just sits there. 

There are several versions. What is the one that I need?

Android.... ARM, X86, X64........ Then Linux..... ARM, V7, 64, X86, X64 

Confused re the Quasar add-on, as the Kodi is Android but TVaddons isn't. 

Saw that in System Info/Hardware CP:ARMv7 Processor. Would that mean download Linux V7, oe what should I be looking at within my Settings/System info?

Any Info. most grateful.

**Comment by scakemyer** [comment]
If you get things buffering and all, you already have it working.

**Comment by RoystonB** [comment]
Thank you for a real stupid answer. Or can't you read English.

**Comment by scakemyer** [comment]
Sorry dipshit, try learning how to type before accusing others of not being able to read your verbiage.

Your buffer issue isn't related to which platform version you're running, it's related to storage, look around other issues about using a NAS or external storage. As for which version you're running, check your logs and fuck off.
