### ISSUE TITLE
Unable to find quasar binary

### ISSUE THREAD

**Issue by jayce996** [scakemyer/plugin.video.quasar#438]
hello, 
i know many poeple raised this problem, but i cannot make it working.
-did a fresh install from GIT directly with the package: plugin.video.quasar-0.9.33.linux_x86.zip
i'm working on a NUC i3 running with KodiBuntu
-did an installation with copy/paste the .bin file
nothing worked.
here are the log generated by Kodi: 
### 00:00:28 T:140366330001152  NOTICE: [plugin.video.quasar] System information: linux_x64 3.13.0-45-generic
00:00:28 T:140366330001152  NOTICE: [plugin.video.quasar] Kodi build version: 16.1-RC1 Git:46d1480
00:00:28 T:140366330001152  NOTICE: [plugin.video.quasar] OS type: Linux
00:00:28 T:140366330001152  NOTICE: [plugin.video.quasar] uname: ('Linux', 'HomeCinema', '3.13.0-45-generic', '#74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015', 'x86_64', 'x86_64')
00:00:28 T:140367224727552   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/
00:00:28 T:140367224727552   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/) failed

please help me, i'm really looking to use this software, it is really an amazing one!
thank you in advance

**Comment by scakemyer** [comment]
Can't do anything with this tiny part of your logs.
