### ISSUE TITLE
Quasar Crash on Kodi IOS 9.3

### ISSUE THREAD

**Issue by murilomulato** [scakemyer/plugin.video.quasar#442]
I tried to install the quasar by unofficial repository, and then kodi crashed and did not start more.

again installed kodi, and is working, how do I install the quasar in kodi for ios?

**Comment by i96751414** [comment]
https://github.com/scakemyer/plugin.video.quasar#supported-platforms

**Comment by nix87** [comment]
Glad to see you back i9, didn't saw your posts recently :)
