### ISSUE TITLE
Request regarding the "Overlay Status" 

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#443]
Hi,

Can you add an option for setting a timeout value in seconds when show this "Overlay Status" when playback is paused?
 Currently it shows this after ~4-5 seconds, but I want to control it for example 20 seconds.
•By the way, why when the download reach to 100% there is Download rate value? And another question, when it reach to 100%, the upload is still working?

Thanks, Great Addon!!!

**Comment by scakemyer** [comment]
The overlay status doesn't need a timeout value, it checks if the video is paused every second so if you're seeing it after 4-5 seconds then your device is probably just slow since it's a very inexpensive call.

Those are torrents so yes, download rate has a value when uploading to other peers, and you seed while watching or according to the limits you set for background handling.

**Comment by burekas7** [comment]
Thanks for the answer,
But the issue is that I don't want it to be shown after 1 sec, I want set it to be shown after specific time,
so according to what you said - to check if the video is paused every time as it will be set by user.
Is it possible to add this option? (Because now I disable it because it shows it on each pause, little annoying, but I do want to see the status for long pause)

Regarding the second issue, I noticed that when it reach to 100% both download and upload rates reduced to low rates then they was while downloading, is it should be like that? The upload should not stay as it was before it reaches to 100%?

Thanks again.

**Comment by scakemyer** [comment]
I get what you're saying about the delay option, I still don't think it's anywhere close to being a useful feature worth spending a few hours to implement and making sure it doesn't introduce new bugs.

DL/UL rates are just normal bittorrent traffic, that's all.
