### ISSUE TITLE
Providers start searching after 'no link found' message

### ISSUE THREAD

**Issue by alexandros04** [scakemyer/plugin.video.quasar#444]
When I try to load a video the providers pop-up message pops up after I get the no links found message. I.e. Searching starts too late. Also I have a rpi 1 and 2. Did clean install on both with xbian openelec and xbmc. Also picked arm and armv7 zips. Tries various providers

**Comment by scakemyer** [comment]
Try increasing the timeout for providers, it tries to adapt depending on a few factors but if you have too many trying to launch at the same time on a slow device, the timeout will be reached before any actual search takes place. That being said there's no such thing as "searching starts too late", usually just too many providers / slow devices / networking or website issues.

**Comment by XanderCam** [comment]
I had this issue.
Fixed with a timeout of 40 in the timeout for providers setting
