### ISSUE TITLE
Downloadfolder to winshare harddrive not working

### ISSUE THREAD

**Issue by XanderCam** [scakemyer/plugin.video.quasar#446]
Is there a reason quasar doesn't download (buffer) to my network harddrive (windows share).

I have a usb harddrive connected to my router. It is added as a filesource for the osmc library. However quasar will not use it as a buffer disk. How come ?

**Comment by XanderCam** [comment]
Update: I have set up the disk as the download path in quasar. But quasar is not using it, or accessing it

**Comment by scakemyer** [comment]
Answer is in the FAQ and various other issues about NAS and external storage.
