### ISSUE TITLE
Quasar saves files...

### ISSUE THREAD

**Issue by Martijnvanoijen** [scakemyer/plugin.video.quasar#447]
i run quasar on a RPI, it works good. Only problem i have is that quasar does not delete the files after i have watched something. This way the USB stick i have kodi running on is full no time.
The option to keep the files is not on.

Can someone help me with this?

**Comment by nix87** [comment]
I delete my downloads manually after some time, but that is on PC. I belive it could be problem when you running Quasar on RPI. Though Quasar works good on every platform he isn't convenient for all besides Windows.

**Comment by Martijnvanoijen** [comment]
i can also delete it manually but i have to start my pc, then i can delete the files through smb shares. 
I buyed a RPI so i didnt have to use my pc so i hope there will be a solution soon :)

**Comment by GuilleDF** [comment]
It has to do with the "background handling of torrents" setting. Disabling it and also disabling "keep files after playback" should delete the files when you stop watching.

**Comment by korenziv** [comment]
I have the same issue. Win 10. 

If I stop watching after few minutes the files deleted. 
But if i see till the mid\end of the episode the files not deleted.

**Comment by scakemyer** [comment]
what @GuilleDF said, these issues about not deleting files are getting old... #361 will solve some of it but people need to understand we're dealing with torrents and this is not Netflix.
