### ISSUE TITLE
zombie library items

### ISSUE THREAD

**Issue by joao-matos** [scakemyer/plugin.video.quasar#454]
Titles keep reappearing on the library after removing them.

v0.9.33
kodi15.2
OpenElec6.0.3
RPi2

It seems because they are inside a folder. After removing the title from the library context menu it leaves a folder. Then when the scan is triggered it detects a folder and searches for the movie with that tile repopulating the library metadata with that movie.

http://pastebin.com/TtbcCZ6n

**Comment by scakemyer** [comment]
You had a strm file left, makes sense that the next library update would pick it up. You need to remove them using the context menu in Quasar, otherwise they're still in it's own db and get added again. There's no way around this.
