### ISSUE TITLE
crash while viewing active torrents

### ISSUE THREAD

**Issue by incredulity** [scakemyer/plugin.video.quasar#457]
seems like there is a limit of 3 active the others never progressed past 'finding' and were shown as paused

log:

[kodi.viewTorrentsListCrash.txt](https://github.com/scakemyer/plugin.video.quasar/files/207318/kodi.viewTorrentsListCrash.txt)

**Comment by scakemyer** [comment]
Still an issue for you?

**Comment by scakemyer** [comment]
No response, closing
