### ISSUE TITLE
after crash torrents list each back to 00 and finding: crash again

### ISSUE THREAD

**Issue by incredulity** [scakemyer/plugin.video.quasar#458]
After quasar crashes previously, after exiting kodi, after restarting kodi and waiting for quasar daemon to start.  Prior torrents list had 3 transfering torrents, and several paused torrents.   Now only 4 torrents are shown zeroed and in Finding state.

Click an item in torrent list
starts 'finding'
.. adds peers
.. data transfers
quasar crashes

wait for quasar daemon to start

repeat process.. crashes again

time between click item and crashing less than 45 seconds

debug log:
http://pastebin.com/M683Mg8C

**Comment by scakemyer** [comment]
Log's gone and can't make any sense of this.
