### ISSUE TITLE
No trakt scrobbling

### ISSUE THREAD

**Issue by eidermar** [scakemyer/plugin.video.quasar#461]
I tried everything I could think of to get this work . I'll provide logs if you want but I checked several times and found nothing related to trakt at all. I wouldn't even know what you would need me to do so you'd see the relevant log entries. I guess starting an item and letting it play all through to the end? 

I made sure that scrobbling works from other sources. I went through the authorization process for the trakt plugin and quasar multiple times, checked the settings, uninstalled reinstalled trakt & quasar - nothing. First I thought it was only failing when I started playback from the library, but it didn't matter actually. I couldn't swear but I thought when you first implemented the feature it was working for me (and made me very happy).

Am I the only one having this problem? Anything obvious I'm not seeing?

**Comment by eidermar** [comment]
OK, this is strange. After days of not getting this to work only a few hours after posting here it magically started working again today. I will monitor this oer the next few days but for now this seems to be resolved. Sorry for cluttering the issues list.

**Comment by scakemyer** [comment]
Exactly, scrobbling cannot work by starting items in the Torrents menu since they're really just torrents with no context about what the media actually is. It's less of an issue now since we can quickly resume a regular item with the "previously chosen" dialog, but you do still have to get back / search for it.
