### ISSUE TITLE
Setting to automatically update Quasar Library every # hours/minutes

### ISSUE THREAD

**Issue by odouma** [scakemyer/plugin.video.quasar#464]
I only reboot my KODI machine if necessary, so the only way to update the Quasar library
is manually.
Is it possible to add a function to auto update the Quasar library every # hours/minutes?

I'm using Watchdog to monitor the Quasar Library, so when the library updates, the KODI library
updates automatically.

**Comment by JoseFSilva** [comment]
+1 for this enhancement.
Thank you in advance, cheers.

**Comment by scakemyer** [comment]
It already updates every 8 hours iirc, but that should probably be configurable.

**Comment by JoseFSilva** [comment]
Good to know, maybe I did something wrong.
A simple setting to choose a number for update interval would be nice indeed.
