### ISSUE TITLE
Bug in pagination settings

### ISSUE THREAD

**Issue by artik** [scakemyer/plugin.video.quasar#468]
When I go to Quasar => settings => items per page 20, I set 100 and save the settings.
When I browse Quasar categories, always 20 items are displayed, instead of 100.

**Comment by scakemyer** [comment]
The MovieDB API only returns 20 items and is not configurable, so the setting is only used for Trakt / search and other results.

**Comment by nix87** [comment]
Welcome back scakemyer, it's nice to see you back after some time :)
