### ISSUE TITLE
Kodi crash when trying to resume to the middle of played video

### ISSUE THREAD

**Issue by konst1988** [scakemyer/plugin.video.quasar#475]
When trying to open a video that was stopped in the middle, Kodi suggests to start from the position left. When selecting this option and selecting the same torrent file, Kodi is crashed. Crash log attached.

[kodi_crashlog-16.0 Git_20160220-a5f3a99-20160416-152728.zip](https://github.com/scakemyer/plugin.video.quasar/files/222201/kodi_crashlog-16.0.Git_20160220-a5f3a99-20160416-152728.zip)

[kodi_stacktrace-16.0 Git_20160220-a5f3a99-20160416-152728.txt](https://github.com/scakemyer/plugin.video.quasar/files/222200/kodi_stacktrace-16.0.Git_20160220-a5f3a99-20160416-152728.txt)

**Comment by ShlomiD83** [comment]
did you set to keep files after playback stop in the settings?

**Comment by konst1988** [comment]
I tried the same scenario in both cases: first time when the video was already in the cache, and second time when i deleted it, it finished buffering it, and than crashed.

**Comment by i96751414** [comment]
It's an issue related with fastresume... Hopefully it will be fixed soon

**Comment by scakemyer** [comment]
See #432
