### ISSUE TITLE
Keep getting "Provider was too slow. Ignored."

### ISSUE THREAD

**Issue by tapir** [scakemyer/plugin.video.quasar#476]
Quasar gives this error for all of my providers. I can manually open a .torrent but if I use quasar's search facility it's always this error.

**Comment by ShlomiD83** [comment]
increase the providers timeout in quasar settings to 30 seconds and try again.

**Comment by tapir** [comment]
unfortunately it didn't work

**Comment by tapir** [comment]
I made a clean install of Kodi and now it works. Thanks
