### ISSUE TITLE
TVShow Time library integration

### ISSUE THREAD

**Issue by KindKitty** [scakemyer/plugin.video.quasar#478]
Are there any plans for integrating Quasar with TVShow Time? That would be great since some people use it instead of Trakt.tv service.

TVShow Time script is already marking watched videos in Quasar correctly (see [here](https://github.com/cxii-dev/script.tvshowtime/issues/44)) so what's missing is to access my shows on that service in Quasar and integrate them to Kodi library, like what already exists for Trakt.tv.

Thank you in advance,
Cheers.

**Comment by palradu** [comment]
+1 for this. I'd love to be able to se Quasar to create .strm files and add them to my library, based on the list in my TVShowTime.com account.

**Comment by heartlogic** [comment]
Also intrested in syncing TVShow Time...

**Comment by scakemyer** [comment]
Sorry guys but this is not going to happen.
