### ISSUE TITLE
Search TV show from main menu

### ISSUE THREAD

**Issue by KindKitty** [scakemyer/plugin.video.quasar#479]
First of all Quasar is now my default content, than you for working on this great addon.

I wanted to add a custom shortcut to Kodi's main menu for searching a TV show on Quasar, what would the command be?
I tried this (see [here](https://www.reddit.com/r/kodi/comments/38jzqd/how_do_i_make_a_shortcut_that_enables_an_addons/)) but it didn't work: 

> plugin://plugin.video.quasar/?action=search

Thank you in advance, cheers!

**Comment by JoseFSilva** [comment]
After further searching other issues on this repo I found a way.
Using the link mentioned above and #264 I was able to accomplish this by using this custom command:

> ActivateWindow(10025,"plugin://plugin.video.quasar/shows/search",return)

I don't know exactly how that works and what the 'return' part does so if someone has a better solution please step in.

**Comment by scakemyer** [comment]
That should be working every time for a while already, probably since search history was added. Will re-open the issue if necessary.
