### ISSUE TITLE
Error adding some TV Shows to library

### ISSUE THREAD

**Issue by txesin** [scakemyer/plugin.video.quasar#48]
Quasar fails when adding some TV Shows to the library, for example: Fargo, Mr. Robot, House of Cards (US). The error in the log is:

19:26 4019.372559 T:1968353280   ERROR: PlayMedia could not play media: plugin://plugin.video.quasar/library/show/addremove/269613

EDIT: It works in pulsar 0.7.1

EDIT2: I found the error, it happens when a Show have a Season without Episodes (Specials for example). I do not have knowledge about Go language, but i think the error is in this file: https://github.com/scakemyer/quasar/blob/master/api/library.go

Line 481: season.Episodes[0].FirstAired. 

have to check if season has episodes.

**Comment by dlucic** [comment]
I have the same issue.

**Comment by i96751414** [comment]
I will fix this as soon as I can
