### ISSUE TITLE
Mark as seen/Unseen

### ISSUE THREAD

**Issue by lordjg** [scakemyer/plugin.video.quasar#480]
Hi guys,
A good enhancement for Quasar is the capacity to mark Movies or episodes shows as seen of unseen. Some times in the credits of a movie i do stop and the movie stays withou any mark of seen or unseen. 
This also improves the management of the trakt lists and collections.

just an ideia.

**Comment by scakemyer** [comment]
That's a Kodi thing, but otherwise see related issue with library integration and .strm files: #16

**Comment by scakemyer** [comment]
Actually #24
