### ISSUE TITLE
Download halts (minix/android)

### ISSUE THREAD

**Issue by dmagen12** [scakemyer/plugin.video.quasar#481]
Thank you for this addon.

Quasar used to work well but recently I have a problem which persists: when I start to watch a video, all is ok for the first 10-20 seconds and than the speed drops to 0 and the download stops. I'm using android/minix.
Thought it was the WIFI but switching to cable connection didn't help. Also tried to replace the external SD card... still the same. The you for any ideas solving it - this is my primary source.
-dan

**Comment by dmagen12** [comment]
I've tried to work it out, didn't succeed yet. Here's what I've found
- after the speed drops to 0 kodi can't be closed and must be forced shut down
- I've tried to reinstall kodi (I'm using v16), it didn't help. I've tried versions 15.2 & 15.0 with similar results
- I've tried changing the settings (buffer size to 100), still the same

I'm running out of ideas...

**Comment by KillerJoeBR** [comment]
You need to use the internal storage in Quasar.  Quasar can't handle very well external storage in Android. (sd card)

**Comment by dmagen12** [comment]
thanks @KillerJoeBR it works !
I can confirm the issue does not occur when using internal storage as suggested above. It does occur when using a SD card. For me its a workaround; if it should be fixed or not - its up to the maintainer.
-dan

**Comment by achaw** [comment]
Yep, i have the same problem on mi nexus player and the usb stick attached, seems to be related to libtorrent or something like that...too bad because NP only have 5,3GB accesible storage to user files...so, quasar is almost obsolet with this bug/issue....

**Comment by elgatito** [comment]
Interesting thing. Man asked to help with configuring Quasar. He runs on android, and had halts while starting movies. Said it does not even start, buffering stopped before getting to 100%, log was nothing interesting, looks like video just stopped playing. Download path was on SD-card.
I asked him to limit downloading to 2MB/sec, and he says now it's fine playing, without lags and so on.

So I think, maybe there is kind of behavior in Android when write buffer is filled up and somehow causing error on OS level. 
Don't know really, but probably good to make benchmark to test SD card and set limits accordingly.

**Comment by scakemyer** [comment]
This sounds a lot like the issue we had in #683. We were supposed to be able to set `connections_limit` to 0 in libtorrent to let it choose the highest possible limit, but integer overflows ended up breaking that. Temporary fix on our side was to *not* set it, since its default wasn't overflowing, but it was properly fixed in libtorrent shortly after. So while this might be a write buffer thing, it might be worth it to file an issue in libtorrent for this one too. I'll also look into where we apply that setting on our end to see if we can find a workaround for now.
