### ISSUE TITLE
Drops down buffering speed

### ISSUE THREAD

**Issue by xalaros** [scakemyer/plugin.video.quasar#482]
After a while, drops down buffering speed in Quasar. It starts to grow up but after 20sec drops down almost to 0kb/s. There are a lot of seeders and it's done to every torrent I try to play in Android TV Box Kodi v16 (download path in external SD card).

**Comment by dmagen12** [comment]
See #481 which seems similar.

**Comment by xalaros** [comment]
But I haven't sufficient space to internal storage thus I use sd card. There is no workaround for this?

**Comment by xalaros** [comment]
Why did you closed this? It didn't solved my problem. I see a lot of people having the same issue. Drops down speed writing to sdcard and no solution for this major problem.
