### ISSUE TITLE
Not loading torrents on Kodi 17 "Krypton" 

### ISSUE THREAD

**Issue by fraannk** [scakemyer/plugin.video.quasar#483]
Hello. I know that Krypton is in its early stages, but Quasar won't load any torrents on Kodi 17. It just says no links were found.

Any workarounds? I though you should know if you didn't already. 
Thanks

**Comment by fraannk** [comment]
This is on Android/NVIDIA shield btw

**Comment by ausafk** [comment]
Mine isn't working either. Using an iMac and Nvidia Shield and neither quasars are working. They just say no links found. Any Help

**Comment by fraannk** [comment]
I actually use exactly the same setup. I got it working with the newest nightly build on my SHIELD, but not on the Mac yet. :)

**Comment by ausafk** [comment]
the nightly build of quasar or kodi?

**Comment by fraannk** [comment]
Kodi 17

**Comment by ausafk** [comment]
Just got it working on the Mac :), running Kodi 17 though going to try and reinstall koi on the shield I'm not a huge fan of running the nightly as i loose skin support.

**Comment by ausafk** [comment]
Just got it all working maybe it was just a kodi error. Now working on both the shield and the mac.

**Comment by scakemyer** [comment]
Considering this as resolved, let's wait until Krypton is further along to open more specific issues as needed.
