### ISSUE TITLE
Library integration issue: Can't select subtitle.

### ISSUE THREAD

**Issue by tapir** [scakemyer/plugin.video.quasar#484]
If you add a TV show to the library and start streaming en episode from the "Recent Episodes" menu on yout tv shows library then the episode info is not shown correctly. No title, nothing. So you can't even select a subtitle for it. Subtitle menu is disabled.

**Comment by scakemyer** [comment]
I believe this is fixed, closing.

**Comment by ShlomiD83** [comment]
I believe he's talking about streaming from the widget, was that fixed? Maybe i missed it?

**Comment by tapir** [comment]
Yeap, this only happens when starting the stream from the widget

**Comment by scakemyer** [comment]
No idea what you mean by widget, but subtitles work from Quasar and from the library. Whatever those widgets are they won't be supported by me, sorry.

**Comment by tapir** [comment]
It's the official kodi video category view where it shows the latest
episodes from your library.

**Comment by scakemyer** [comment]
That's exactly where I tried it from and it worked just as it should...
