### ISSUE TITLE
Not loading Link

### ISSUE THREAD

**Issue by ausafk** [scakemyer/plugin.video.quasar#485]
Ive been using quasar for a while now without issue and suddenly it has stopped working. The providers are fine but it just keeps saying on anything i play no links found. Using nvidia shield tv and iMac both running Kodi 16.1.

**Comment by bluenote73** [comment]
Since this is pretty stale please confirm a fresh install on a fresh build produces this problem, thx

**Comment by scakemyer** [comment]
Laaawgs
