### ISSUE TITLE
Enhancement: Add a filter: compression 264 or 265 or all

### ISSUE THREAD

**Issue by odedeid** [scakemyer/plugin.video.quasar#486]
Some devices can't play the new compression format- 265. 
It'll be better to filter it out (by choise) during the torrent search

**Comment by nix87** [comment]
In torrent list you have h264 and h265 mark so just don't choose h265 and problem solved. I think filter is so unnecessary.

**Comment by ShlomiD83** [comment]
filter them thru the providers settings, that's what i do.
