### ISSUE TITLE
Question (help please): New intallation trakt won't authorize

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#490]
Hi there, need help regarding the option in QUASAR that lets me authorize trakt.
Everytime i press it it gives me error:
navigation error: httperror

**Comment by hfmls** [comment]
pastebin log:

http://pastebin.com/0cdYaL8z

**Comment by hfmls** [comment]
also everytime i try to "update library" gives same error

**Comment by hfmls** [comment]
ok found the error, went back to openelec version OpenELEC-Generic.x86_64-6.0.3 and it is working now.

**Comment by hfmls** [comment]
maybe make it compatible with new openelec/libreelec please?

**Comment by hfmls** [comment]
Hello?

**Comment by bluenote73** [comment]
Closing this for stale date, if this is still happening, please bring it up on the support forum thread, or open a new issue here.  thanks :)
