### ISSUE TITLE
[FR] Pull episode metadata from TVDB instead of TMDB

### ISSUE THREAD

**Issue by tomer953** [scakemyer/plugin.video.quasar#495]
Hi,
great work, and many thanks about your affort.

I noticed that the metadata is being pulled from TMDB which is awesome for movies.
but in tvshows, at least in my language (Hebrew) we are keep updating TVDB site instead, years of work, almost impossible to transfer all the data to TMDB site..

the current status, using TMDB for episodes is causing some problems to us:
1. there is no name for the episode, just number, ie: "20" instead of "The final step"
2. the problem above is causing to some of the subtitle providers to search "20" instead of the actual episode name\filename
3. trakt.tv integration is not working.

Is it possible, to add an alternative option in the add-on setting, to choose where to pull the metadata?
(it will be really great if we can choose the language of the metadata too)

many thanks and keep your awesome work.

**Comment by tomer953** [comment]
I now found this one: https://github.com/scakemyer/plugin.video.quasar/issues/249#issuecomment-186682080

so sorry for bringing it up again.

**Comment by scakemyer** [comment]
No worries, I know it'd be great to be able to use both, and I'd like to eventually bring back TVDB as an option.

**Comment by tomer953** [comment]
OK, great news.

Just found out yesterday something new(to me), did you noticed of a problem with playing library episodes from widgets instead of directly from the library?
it has the same symptoms like I mentioned in the first comments (no episode name etc..)
