### ISSUE TITLE
torrent won't start downloading/streaming from some trackers???

### ISSUE THREAD

**Issue by hdmaniacs** [scakemyer/plugin.video.quasar#496]
Thanks to developers for such amazing addon and torrent stream engine. It's become mine first choice for streaming app's however I have some problems.
When I download torrent file and play from Quasar he won't start downloading torrent everytime. When I try from trackers such as kickass or rarbg torrents start buffering right away but I have some trackers which are not open for everyone like Torrentleech or Awesome-HD and I tried same procedure with torrent files from those two trackers and nothing happens? Quasar won't start buffer when torrents from those places are selected. 

Is there something I should do in settings to enable those kind of torrent files to work? I'm sorry if this is already asked I'm new to all of this so I'm a bit confused here? 

Amazing work with Quasar and thanks for your hard work ;)

**Comment by nix87** [comment]
Not only once but several times this issue was mentioned :D 

Quasar have hard times with torrents from private trackers. If issue can or will be solved still remains to be seen :)

**Comment by vitalyg149** [comment]
Replace windows firewall with something else. I had the same issue and i narrowed it down to firewall. i use private firewall and the issue stopped. You can also try resetting windows firewall and then adding Quasar again and it will start working, but it will fail again a month or a week later.

**Comment by hdmaniacs** [comment]
I tried to turn off firewall but still private torrents won't start buffer on Quasar.

**Comment by scakemyer** [comment]
#38
