### ISSUE TITLE
No JSON at all, resulting on HTTPError()

### ISSUE THREAD

**Issue by mths0x5f** [scakemyer/plugin.video.quasar#498]
http://localhost:65251/show/56296/season/4/episodes returns no JSON and results on a HTTPError() message on Kodi. 

This just happens with fourth season, as http://localhost:65251/show/56296/season/3/episodes works well.

**Comment by nix87** [comment]
I deleted my JSON file i Quasar library folder how I wouldn't have problems with resuming torrents and I don't have problem with that at all, at least I didn't notice some errors? I'm using Quasar on Win platform.

**Comment by hfmls** [comment]
i found some errors to be regarding incompatibility with new versions of kodi/openelec/libreelec, wish they added support for this :)
