### ISSUE TITLE
Some TV shows Season's episodes not loading/displaying correctly

### ISSUE THREAD

**Issue by vitalyg149** [scakemyer/plugin.video.quasar#499]
This is what showing: Episodes are missing from latest season.
![capture](https://cloud.githubusercontent.com/assets/17891915/15093122/a3557db0-144b-11e6-8de9-105d5c0bdca3.JPG)

Here it shows all episodes, using other programs.
![capture2](https://cloud.githubusercontent.com/assets/17891915/15093124/a70ce22c-144b-11e6-81c6-f2426b0034f4.JPG)

**Comment by nix87** [comment]
I'm not sure but this also could be TMDB problem not Quasar's.

**Comment by vitalyg149** [comment]
I checked other programs and they pull info for this show fine and the rest of the seasons look fine in Quasar as well. It only the current season looks messed up.

**Comment by bluenote73** [comment]
Unfortunately it is the nature of online crowdsourced info that sometimes there's problems. Right now I'm unaware of any plans to change this.  You can always become a contributor over at tvdb to fix issues yourself, or at least bring it to the attention of the admins there.
