### ISSUE TITLE
Request: Add trakt support inside QUASAR using latest libreelec and openelec

### ISSUE THREAD

**Issue by hfmls** [scakemyer/plugin.video.quasar#501]
Hi there, so here is the thing, using latest stable openelec build (6.0.3) i can use trakt inside quasar and open collection list and others, but if i update openelec to latest beta build (6.95.3) trakt stops working when trying to open trakt lists.

This is what i do (workaround).
Install 6.0.3 to go to trakt collection list, add episode by episode to library, then i update to 6.95.3, and "it works" but i am not able to open trakt collection lists anymore, if i want to add a show i have to go manually via tvshow inside quasar.

**Comment by xennonx** [comment]
scakemyer, you are a God among men, thanks for all your hard work.

I confirm the same issue here with 6.95.3  I also use VPN for Openelec for my connection, but have tried without. Here is a log dump of just trying to access Tv Show Collection in Trakt. I was previously Authenticated with Trakt in 6.0.3 then updated to 6.95.3. I have however tried a fresh install with same results.
 [http://pastebin.com/kHPybSbM](url)

**Comment by bluenote73** [comment]
I did an upgrade to the latest libreelec, authorized trakt, and was able to access collections and so forth.  Everything performed as expected.  If you're still having trouble, open a new issue or visit the support thread. 
thanks
