### ISSUE TITLE
Why second scanning gives more results?

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#502]
Hi,

First, thank you on your great addon.

Regarding my question, most of the time first scanning gives me less results that usually comes only from one provider. When I do a second scanning I get more results also from the other providers.
Why does it happens? Can you check it?

Another question:
What is the meaning of the "cloud" icon in the result screen?

Thanks.

**Comment by scakemyer** [comment]
Results from providers vary, that's about all there is to it. The cloud icon means multiple providers returned the same result.
