### ISSUE TITLE
Doesn't keep files on the SMB share Download path

### ISSUE THREAD

**Issue by wussap** [scakemyer/plugin.video.quasar#504]
First of all HUGE thank you for that plugin, but I have a little issue here

I've configured SMB share on my NAS drive as Download and Library path, both options enabled - Background handling of torrents & Keep files after playback/download stops. However it didn't save anything at this location, I've checked the write permission and it's OK
e.g. of Download path smb://user:pass@diskstation/video/

**Comment by scakemyer** [comment]
Check the FAQ on the readme, you need to mount it via the OS, but even then if it's too slow libtorrent won't work properly.
