### ISSUE TITLE
Buffering stops at 30 MB

### ISSUE THREAD

**Issue by gilfillan94** [scakemyer/plugin.video.quasar#507]
This only happens for some torrent files but the download will proceed as normal until 30MB has been downloaded and then it will abruptly stop. The issue only happens with some torrents but it is repeatable (trying to download the same file again results in the same issue). The torrent itself is not the issue since I can successfully download it with a different client. Strangely all of the files with problem are from the same source and are roughly the same size (176 MB AVI file, XVID codec)

**Comment by scakemyer** [comment]
Outdated and no logs, closing
