### ISSUE TITLE
Indefenitely Buffering

### ISSUE THREAD

**Issue by jodlajodla** [scakemyer/plugin.video.quasar#51]
Hello,

Thanks for working on such a nice plugin. I'm using it on my Raspberry Pi 2 with OpenELEC and everything except playing the stream works. I was also using Pulsar before this fork came and it worked as expected, but I installed Quasar because it will bring new features.

The problem with Quasar is that once buffer is loaded and file starts playing the black box appears over the video. The video is paused and buffering continues. If I press play button then the file is played for some time, but it soon again starts buffering. This kind of working I firstly saw after Qusar install, with Pulsar I didn't experience that. I'm storing the file to the network share (SMB) which is mounted on system start to downloads folder. The same config existed in Pulsar. The speed of download/upload is 1.5 MB/s so this shouldn't be the issue. The problem is same for 12 GB large files as well for 300 MB files. The same problem exists in all versions of Quasar I tried for now. Do you have any suggestion what to do to reslove that issue?

Here is image of what appears (DL speed was raising in the moment of capture, that's why its only 232 kb/s):
![Quasar Buffering](http://i.imgur.com/inixggu.jpg)

Thanks for help in advance!

**Comment by scakemyer** [comment]
The overlay status has been fixed for a while already, and the "buffering... 0%" at the top is from Kodi, not Quasar, and probably has to do with your SMB mount more than anything else. Please be more specific about "all versions of Quasar" and provide logs if you need more help, and try v0.9.1 to see if it works better.

**Comment by jodlajodla** [comment]
There really was an issue with SMB mount and the problem dissapeared after I changed download path to directory on microSD card. If I compare logs when using SMB mount and local directory there's no difference. Maybe there's a problem with r/w speed from/to SMB mount, but that's almost impossible since all other video files (1080p, 720p) are played without problems. What do you think?

**Comment by scakemyer** [comment]
As I just mentioned on the forum:
> This is a limitation of libtorrent, please keep in mind that most of the legwork is done by it, so if libtorrent can't do something, then Quasar probably can't either. And there are certainly good reasons for libtorrent not to support external storage, since it needs fast read/write access to function properly, so I seriously doubt it's even on their roadmap to support that.
