### ISSUE TITLE
Error "Not enough space" when playing packages.

### ISSUE THREAD

**Issue by timmetj** [scakemyer/plugin.video.quasar#510]
Hi,

When i want to watch an episode from a packaged video, i get the message "Not enough space". This is due to Quasar thinks i need space for the full package (40Gb) while i only need 1 episode (2gb) from it.
You guys thinks you can sort this problem out?

Greetings

**Comment by bluenote73** [comment]
I wouldn't hold my breath for this, but that's just my guess.

**Comment by scakemyer** [comment]
Fixed alongside #647
