### ISSUE TITLE
Crash on start on fresh kodibuntu install

### ISSUE THREAD

**Issue by luukholleman** [scakemyer/plugin.video.quasar#512]
Hey,

Creating this issue to notice you of this problem and help others with the same error. Quasar is crashing on startup on a freshly installed kodibuntu (14.04). The log says quasar can't find libgcc++6. Kodi.log: http://xbmclogs.com/pgdacng8y#line-501

I had to follow these steps before it worked: http://askubuntu.com/a/582910

**Comment by bluenote73** [comment]
Thanks for documenting this

**Comment by bluenote73** [comment]
@scakemyer I can't tell if this is something you can affect, the builders, or if it's a kodi issue?

**Comment by scakemyer** [comment]
#45, #127, #168, #269, #286
