### ISSUE TITLE
Unable to buffer on external path stuck on 9% HELP ANDROID

### ISSUE THREAD

**Issue by eemr92** [scakemyer/plugin.video.quasar#515]
When set the download path to an external SD on android TV Box the download start fine but stop after 30 seconds any idea.?? Thanks

**Comment by tomtomclub** [comment]
ya look ad the free space  from the sd card

**Comment by eemr92** [comment]
It have 26gb free any idea why is doing that thanks for your answer

**Comment by hdmaniacs** [comment]
because Android make problems for Quasar

**Comment by bluenote73** [comment]
Please try this over in the quasar support thread, or if you insist, reopen with at least some specific info including a log.
