### ISSUE TITLE
Add option to rename/move torrent after download is complete (if keeping files)

### ISSUE THREAD

**Issue by imsodin** [scakemyer/plugin.video.quasar#516]
Currently quasar creates the media file with final extension and keeps writing to it until it is finished. It would be great if it either used an extension like .part until it is finished downloading (probably not possible as it should be playable before) or move/rename it after it is finished. E.g. there could be an optional path in settings for storing finished torrents.

**Comment by scakemyer** [comment]
That's not how torrents work...
