### ISSUE TITLE
[Socks5] Access is denied

### ISSUE THREAD

**Issue by xennonx** [scakemyer/plugin.video.quasar#517]
Not sure if this actually means my Sock5 proxy is not working or not... I've set my Socks5 port to the required port 1080
`20:45:11 T:8  NOTICE: [plugin.video.quasar] ERRO  libtorrent   ▶ logAlerts        listen_failed_alert: listening on 0.0.0.0:50600 failed: [accept] [Socks5] Access is denied`

**Comment by bluenote73** [comment]
Use maxthon browser to test your socks access

**Comment by scakemyer** [comment]
Lets shove this under #635 for now, we'll see if this needs to be reopened once that is fixed.
