### ISSUE TITLE
where is scakemyer??

### ISSUE THREAD

**Issue by hdmaniacs** [scakemyer/plugin.video.quasar#520]
I'm sorry but did someone know where is Scakemyer? He's not been online since almost two months and I wonder if this Quasar project is still alive? 

I mean Quasar works today fine but some updates are needed.

I hope he is alright and he will be back soon.

**Comment by hrpc10** [comment]
An excellent question. I am awaiting too.

**Comment by bluenote73** [comment]
Hey scakemeyer, hope all is well where you are.

**Comment by nix87** [comment]
I also hope he is alright.

Recently i was at Kodi's forum and saw that he wasn't there from march.

**Comment by tomtomclub** [comment]
mi to

**Comment by burekas7** [comment]
Good question

**Comment by compyy** [comment]
Busy in his professional life :)

**Comment by nix87** [comment]
It's great if it's just that. Most important that's he is ok :)

**Comment by scakemyer** [comment]
@bluenote73 hope you're well also, mind getting contributor access so I'm not the only motherfucker able to keep this going?

**Comment by bluenote73** [comment]
Glad to see you're alive @scakemyer :)   I'm not a programmer per se though.  I have maintained and done slight edits under C, VBA, c# .. but only by copious and extreme measures.   I didn't know how to access a database one time so I hacked in 50 lines of variable definitions one time ...   I don't think you would thank me for touching code :)   If there's some other way to help out, I'm willing to do so though.

**Comment by scakemyer** [comment]
Well, 50 lines of variable definitions to get DB access is... impressive? Did it work? Either way, this is not so much about code as it is about having trustworthy folks simply having access (wink), helping with issues (lots of "tag as duplicate, close..."), maybe click on "merge" at a pull request for translations once in a while if you feel like it. I'd rather have someone not wanting to touch code as much have access, rather than one that thinks he can but breaks something half the time ;)

**Comment by bluenote73** [comment]
@scakemeyer you misunderstood - instead of accessing a database, I hardcoded a database of variables inside the code. :/  At least I know that was a shit workaround, but it was only for stuff that I personally use for my work.

I'm happy to try and contribute, err, PM me what I need to know?

**Comment by scakemyer** [comment]
Hahaha and in doing so, you made your app twice as fast by not having to do DB lookups ;) Who needs those anyway?

I wish GitHub had support for PM... I guess I'll add a Gitter chatroom :tada:

**Comment by bluenote73** [comment]
@scakemyer hey, I pm'd you contact info
