### ISSUE TITLE
Subtitle-search issue when loading Torrent through JSON-RPC

### ISSUE THREAD

**Issue by hejman** [scakemyer/plugin.video.quasar#521]
Hi,

Movie-title recognition seems to be put totally off when I load a torrent (magnet) through JSON-RPC from my PC.

It works fine when loading a movie via the build-in interface/providers - please advise.

See below photos - thanks.
![img_2971](https://cloud.githubusercontent.com/assets/11835166/16443821/1ebc53e4-3ddb-11e6-9186-e4b40b8caf92.JPG)
![img_2972](https://cloud.githubusercontent.com/assets/11835166/16443822/1ec17900-3ddb-11e6-9b79-961721d21ecb.JPG)

**Comment by scakemyer** [comment]
Did the last few versions with fixed subtitles also fix this? I'm guessing it should be doing a lot better now.

**Comment by scakemyer** [comment]
No answer, closing
