### ISSUE TITLE
Quasar on Android TV (nVidia Shield TV) won't start

### ISSUE THREAD

**Issue by fabioneves** [scakemyer/plugin.video.quasar#524]
Hello,

Here's the log:

```
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] Detected binary folder: /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.quasar/resources/bin/android_arm
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] Using binary folder: /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.quasar/resources/bin/android_arm
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] Updating quasar daemon...
14:54:59 T:1438628144   ERROR: [plugin.video.quasar] Unable to remove destination path for update: [Errno 2] No such file or directory: '/data/data/com.semperpax.spmc16/files/plugin.video.quasar/bin/android_arm'
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] System information: android_arm 3.10.67+
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] Kodi build version: 16.3-0 Git:2016-04-30-22df3d0-dirty
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] OS type: Linux
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] uname: ('Linux', 'localhost', '3.10.67+', '#1 SMP PREEMPT Wed Jun 22 01:28:34 PDT 2016', 'armv8l', '')
14:54:59 T:1438628144   ERROR: [plugin.video.quasar] Unable to copy to destination path for update: [Errno 13] Permission denied: '/data/data/com.semperpax.spmc16'
14:54:59 T:1438628144   DEBUG: POParser: loaded 137 strings from file /storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.quasar/resources/language/English/strings.po
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] System information: android_arm 3.10.67+
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] Kodi build version: 16.3-0 Git:2016-04-30-22df3d0-dirty
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] OS type: Linux
14:54:59 T:1438628144  NOTICE: [plugin.video.quasar] uname: ('Linux', 'localhost', '3.10.67+', '#1 SMP PREEMPT Wed Jun 22 01:28:34 PDT 2016', 'armv8l', '')
14:54:59 T:1438628144   ERROR: [plugin.video.quasar] Traceback (most recent call last):
14:54:59 T:1438628144   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 157, in quasard_thread
14:54:59 T:1438628144   ERROR: [plugin.video.quasar]     proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
14:54:59 T:1438628144   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 112, in start_quasard
14:54:59 T:1438628144   ERROR: [plugin.video.quasar]     quasar_dir, quasar_binary = get_quasar_binary()
14:54:59 T:1438628144   ERROR: [plugin.video.quasar]   File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 82, in get_quasar_binary
14:54:59 T:1438628144   ERROR: [plugin.video.quasar]     dest_files = set(os.listdir(dest_binary_dir))
14:54:59 T:1438628144   ERROR: [plugin.video.quasar] OSError: [Errno 2] No such file or directory: '/data/data/com.semperpax.spmc16/files/plugin.video.quasar/bin/android_arm'
14:54:59 T:1438628144   ERROR: [plugin.video.quasar]
14:54:59 T:1438628144   ERROR: Exception in thread Thread-2:
                                            Traceback (most recent call last):
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/threading.py", line 532, in __bootstrap_inner
                                              File "/var/lib/jenkins/jobs/SPMC-Custom-ARM/workspace/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/threading.py", line 484, in run
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 157, in quasard_thread
                                                proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 112, in start_quasard
                                                quasar_dir, quasar_binary = get_quasar_binary()
                                              File "/storage/emulated/0/Android/data/com.semperpax.spmc16/files/.spmc/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 82, in get_quasar_binary
                                                dest_files = set(os.listdir(dest_binary_dir))
                                            OSError: [Errno 2] No such file or directory: '/data/data/com.semperpax.spmc16/files/plugin.video.quasar/bin/android_arm'
```

**Comment by fabioneves** [comment]
I forgot to say that this was using the latest version.

**Comment by ihavetenfingers** [comment]
Same issue on my Nexus Player running Nougat.

**Comment by ofir38** [comment]
I also have this problem on nvidia shield with spmc. Latest quasar version (installed via github). 
On every start up a message appear - unable to find binary file

**Comment by ofir38** [comment]
I also have this problem on nvidia shield with spmc. Latest quasar version (installed via github). 
On every start up a message appear - unable to find binary file

**Comment by sharadaj** [comment]
Same issue with Nexus Player on Android 7.0. Anyone found a fix yet?

**Comment by fabioneves** [comment]
I found that this only happens if the app is moved to other storage, if I use Kodi/SPMC on the main storage, it works fine!

**Comment by sharadaj** [comment]
Hmm okay I think it must be a different issue then, because my app is already on the main storage. Thanks anyways!

**Comment by lanzorg** [comment]
I have the same issue using LibreElec on my Minix U1 (S905).
However it works with the Android pre-installed system and latest Kodi/SPMC.

**Comment by lcohen999** [comment]
I believe it is an Android 7 issue 

Hopefully it is an easy fix and fixed soon (please)

**Comment by scakemyer** [comment]
I'll be looking into this for the next release (no promises!), but I suspect we'll run into #544 right after.

**Comment by scakemyer** [comment]
Looks like it's all about permission errors on android 7.0, and platform detection is working properly, which means there isn't much we can do other than having someone with a working setup to share any special steps needed. Considering how popular this device is it'd be great to automate it if possible, and at worse have clear instructions to follow.

**Comment by lcohen999** [comment]
I have an Asus Player with 7.0 and am happy to test

Not sure where to begin, though

**Comment by scakemyer** [comment]
Logs of the add-on installation using an android_arm release, and as @fabioneves mentioned Kodi must probably be installed on the main storage.

**Comment by fabioneves** [comment]
@scakemyer yeah, I guess the problem is related to storage permissions. I had a problem in another android TV app, that wouldn't let me see my external storage, after changing the permissions in the settings I was able to do that.

I think this might be the same problem with Kodi, if I allow Kodi to access other storage in the app settings (from Android TV) it might work.

**Comment by sharadaj** [comment]
In case anyone is interested, I ended up just downgrading my Nexus Player back to the last release of Android 6.0.1, rooting it, and using a sideloaded app called MyAndroidTools to disable updates. Quasar is working perfectly again with this setup. If anyone is looking for detailed instructions just post here and I'll put together a quick tutorial. Thanks for all your hard work, @scakemyer!

**Comment by scakemyer** [comment]
Solved and all is well? If so, thanks for closing :)

**Comment by fabioneves** [comment]
Yup, you'll only get problems if moved to another storage. If you keep it on default storage, it'll work just fine.

**Comment by Triton20** [comment]
Hi, I am having the same issue on Nvidia Shield TV, I migrated my 16gb Shield storage over onto a 2 tb external hard drive so kodi and all my addons are on that. I used Quasar all the time before.....is there any way to fix this using external storage with an update? I have managed to revert back to Quasar Version 0.9.42 which works ok with external storage on Kodi 17 Krypton on android 7.0 but I also have SPMC16 on my shield running Kodi 16.2 and I can't get the latest Quasar 9.73 running on that (which I assume from this post is the storage issue). Any help would be much appreciated.

Thanks
Andy

**Comment by inkubux** [comment]
I also have the same issue with external storage on my shield tv. I moved kodi/spmc to a 64GB usb key. Anyone found a solution to make it work with external storage ?

**Comment by fish3191** [comment]
Go into Android TV app settings and make sure Kodi is installed on internal storage and not external storage.  That will fix it.  You can still set your download path for Quasar on the external and it will still work.

**Comment by fearlessleader62** [comment]
Hi what arm version of the current quasar there is 1 for arm 7 and 8 right one for the 64 bit and one for 32 bit?

**Comment by Triton20** [comment]
Just to confirm I now have My Nvidia Shield transferred onto my external storage and no issues with Quasar at all! Runs fine 😊

**Comment by fearlessleader62** [comment]
What version  of quasar are running I know it's arm but on my 2017 16 gb model running 6.3 android  and using a 256gb ssd as internal  storage I what to make sure to install the. Right version
