### ISSUE TITLE
Quasar daemon is crashing

### ISSUE THREAD

**Issue by Znuff** [scakemyer/plugin.video.quasar#525]
I'm not sure what changed on my OS, but recently Quasar.exe started crashing.

	C:\Program Files (x86)\Kodi\portable_data\addons\plugin.video.quasar\resources\bin\windows_x64
	λ quasar.exe
	INFO  main         ▶ main
	INFO  main         ▶ main             ________
	INFO  main         ▶ main             \_____  \  __ _______    ___________ _______
	INFO  main         ▶ main              /  / \  \|  |  \__  \  /  ___/\__  \\_  __ \
	INFO  main         ▶ main             /   \_/.  \  |  // __ \_\___ \  / __ \|  | \/
	INFO  main         ▶ main             \_____\ \_/____/(____  /____  >(____  /__|
	INFO  main         ▶ main                    \__>          \/     \/      \/
	INFO  main         ▶ main
	INFO  main         ▶ main             Version: "v0.9.34" Go: go1.6.2
	INFO  config       ▶ Reload           Reloading configuration...
	panic: runtime error: invalid memory address or nil pointer dereference
	[signal 0xc0000005 code=0x1 addr=0x0 pc=0x590ef2]

	goroutine 1 [running]:
	panic(0xba2c20, 0xc0820040e0)
			/usr/local/go/src/runtime/panic.go:481 +0x3f4
	github.com/scakemyer/quasar/xbmc.executeJSONRPCEx(0xcabac0, 0xc, 0xa2dae0, 0xc0820b27e0, 0x176ce60, 0x0, 0x0, 0x0, 0x0)
			/go/src/github.com/scakemyer/quasar/xbmc/jsonrpc.go:62 +0x392
	github.com/scakemyer/quasar/xbmc.GetAddonInfo(0xc08211d9b0)
			/go/src/github.com/scakemyer/quasar/xbmc/xbmcaddon.go:24 +0x8c
	github.com/scakemyer/quasar/config.Reload(0xc0821aad50)
			/go/src/github.com/scakemyer/quasar/config/config.go:82 +0x12e
	main.main()
			/go/src/github.com/scakemyer/quasar/main.go:84 +0x67c

I've tried both the 32bit and 64bit daemon, they both experience the same issue.

The only recent change to my Windows install is that I recently installed Visual Studio 2015.

**Comment by scakemyer** [comment]
Firewall...

**Comment by Znuff** [comment]
I never have or had a firewall.

**Comment by scakemyer** [comment]
Sorry but with just that part of the logs that's about all I can say, or something's using Kodi's default port.
