### ISSUE TITLE
trakt "watched" are not synced

### ISSUE THREAD

**Issue by vjain419** [scakemyer/plugin.video.quasar#526]
1. I have connected trakt, and when I open collection I can see all tv show which are in trakt collection but odd things, episodes/season which i already watched, doesn't marked as watched in Quasar

2. Also there is no options pop up to say marked it "watched in trakt", i know there is option in Exodus thought. 

Can you please check if 1st is issue in plugin and add 2nd point as feature where use can force "watched/unwatched" in trakt

Version of Qusar : 0.9.34

**Comment by burekas7** [comment]
It's pretty the same as my request #518 
[Request] Sync Watched/Unwatched with Trakt
