### ISSUE TITLE
Missing the ability to forward (Yatse's open/share with ...) torrent's magnet link from Android device's browser

### ISSUE THREAD

**Issue by Zvezke** [scakemyer/plugin.video.quasar#53]
For a long time, I've been streaming torrents with Pulsar without providers.
I've been doing this by using either an Android device (with [Yatse](https://play.google.com/store/apps/details?id=org.leetzone.android.yatsewidgetfree&hl=en)) or Chrome's extension [Play to Kodi](https://chrome.google.com/webstore/detail/play-to-kodi/fncjhcjfnnooidlkijollckpakkebden).
By pressing a TV show's og movie's magnet-icon on a given torrent site (Kickass, or so) the 'Open/Share with ...' menu would open – and choosing 'Play with Kodi' has always opened the stream in Pulsar.

This was possible with the Quasar's initial releases, but unfortunately it stopped with v.0.9.1.
Please bring this feature back. I really miss it.

This will also make Quasar still usable if providers fail or are not installed to begin with.

**Comment by i96751414** [comment]
I will see this tomorrow if I have the time to do it.

**Comment by i96751414** [comment]
Btw, I tried Play to Kodi but it keeps telling me to instal XBMCTorrent.. Could you tell me how to change that? I never used this extension

**Comment by scakemyer** [comment]
I'm pretty sure they both have presets or hardcoded support for Pulsar and others, which is why the first Quasar release, which was still using `plugin.video.pulsar` was working. I'd recommend contacting those developers to let them know about Quasar, or configure their app/extension using `plugin.video.quasar`

**Comment by i96751414** [comment]
You're absolutely right!
I was seeing the request from that chrome extension and look what I've found:
```
[{
	"jsonrpc": "2.0",
	"method": "Playlist.Add",
	"params": {
		"playlistid": 1,
		"item": {
			"file": "plugin://plugin.video.pulsar/play?uri=magnet%3A%3Fxt%3Durn%3Abtih%3AC98F8C951DD0A98DAD8E6BC1A83A07DF4993F067%26dn%3Ddirty%2Bgrandpa%2B2016%2Bhdts%2Bline%2Bx264%2Bexclusive%26tr%3Dudp%253A%252F%252Fglotorrents.pw%253A6969%252Fannounce"
		}
	},
	"id": 1
}]
```

**Comment by scakemyer** [comment]
I knew it ;) there's no real other way to magically have Kodi open magnet links like that. I hope they can be configured, otherwise the devs will have to deal with their hardcoded links.

**Comment by Zvezke** [comment]
When you open the extension's interface in Chrome, you'll see gears in the lower left corner -that's the preferences. In preferences, choose 'others' - there you'll be able to pick which Kodi add-on to use.
At the moment, you can choose between four (I think - I'm not at my computer at the moment) different add-ons: Pulsar, XBMCtorrent, KMediaTorrent and Torrenter.
XBMCtorrent is set by default; so if XBMCtorrent isn't installed, and no other add-on is picked in the preferences you'll be told to install XBMCtorrent.

Let me know if I'm incorrect; then I'll take a closer look tomorrow (I'm in Denmark - it's 03:35 here). 

BTW, thanks a billion for taking on this project. And thanks two billions for taking care of this issue.

Write you later. 

Z

**Comment by dlucic** [comment]
I'm also using "Yatse" and "Play to Kodi". Don't know about "Yatse" but "Play to Kodi" developer is aware of Quasar and will be making an update soon.
