### ISSUE TITLE
no search results from provider but have access 

### ISSUE THREAD

**Issue by kingdingaling83** [scakemyer/plugin.video.quasar#530]
I can access the providers site no problem in a web browser but quasar wont produce results.
can you help?

the url generated works but no results passed back to quasar from provider. 

http://pastebin.com/BNrVy6y6

**Comment by gammbs1** [comment]
Same here

**Comment by joaopauloss** [comment]
Same here ! The problem is with quasar or with unofficial Repo ?

**Comment by bluenote73** [comment]
Please compare against other providers.  If some or all of those work, then you need to ask the person offering the providers for support, not here.

thanks.

**Comment by joaopauloss** [comment]
> Please compare against other providers. If some or all of those work, then you need to ask the person offering the providers for support, not here.

> thanks.

My problem was just with the providers I used for movies, like PirateBay, KickAss. I changed for others, and it worked. 

Thanks.
