### ISSUE TITLE
Come back scakemyer

### ISSUE THREAD

**Issue by Pinhastest** [scakemyer/plugin.video.quasar#531]

**Comment by nix87** [comment]
He is gone for good.  No more Quasar support, I deleted addon month ago.

**Comment by ihavetenfingers** [comment]
do we have an alternative?

**Comment by scakemyer** [comment]
@nix87 You're an idiot.

**Comment by nix87** [comment]
F you man you know!!!!! xD

What I supposed to think after that long long absence of you ha? :D But I'm so glad you are ok, f**k Quasar honestly I thougt you are in some trouble or something after fading just like that. No posts about Quasar stopping or something just disappearance from places where you have acc. You scared me a bit. 

So glad you are alive :D

**Comment by bluenote73** [comment]
Let's try to be supportive and grateful and not give scakemyer the impression that people are entitled to his free time.
(Closed)

**Comment by scakemyer** [comment]
@nix87 hahah love you too man
