### ISSUE TITLE
Stuck on Finding info, 0/-1 seeders and peers when using wifi on Raspberry Pi 3 OSMC

### ISSUE THREAD

**Issue by Azulan** [scakemyer/plugin.video.quasar#532]
Thank you for quasar, it's a great plugin and I appreciate it a lot. I switched from using a wired connection to using the onboard wireless connection. Quasar worked fine while using the Ethernet port but now will always be stuck on the finding info or connecting to peers/seeds while using the wireless. Is there a way to fix this problem? I'm using the August update of OSMC on a Raspberry Pi 3. Logs are [here](http://paste.osmc.io/ohirevozel). Thanks for any help you can provide!

**Comment by bluenote73** [comment]
This is unlikely to be something addressed through software, please try using the OSMC forum or quasar support thread at the Kodi forum. thx
