### ISSUE TITLE
[Request] Trakt Integration - Import entire Collection To Library

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#533]
Hi,

Can you add an option for add entire collection (Movies, TV shows) from Trakt to the quasar's library, instead of add each item at a time.

Thank you.

**Comment by hfmls** [comment]
i would love this too please, because everytime i do a new setup it takes a lot of time to add 1 by 1.

**Comment by burekas7** [comment]
Hi,
Is there any progress regarding this?
Thanks.

**Comment by scakemyer** [comment]
Yep, adding custom lists in a few seconds, import of collections/watchlist/custom lists are next.

**Comment by scakemyer** [comment]
#398 will be where it's at
