### ISSUE TITLE
[Request] Quasar Temporary download folder

### ISSUE THREAD

**Issue by compyy** [scakemyer/plugin.video.quasar#536]
Hello,

As you know Quasar has issues on Android if download folder is External storage, you would have noticed alot of people complaining of buffering issue, it happens with me alot.

On Nvidia Shield TV 16GB model, i have External USB as download folder of Quasar, as soon i play any movie/play the download starts but buffering hangs for a while (I suspect it is a time when full dump file is written on External storage) No matter how fast is the external storage this issue give unpleasent experience.

I have a solution for this problem.
1. Quasar uses internal storage for temporary short files.
2. Once each short file is completely downloaded, it moves the file to External storage and merge it with big file.
3. Player plays the file from external drive.

I think in this way download will be fast as well plus buffering issue will be completely resolve.

Thanks.

I think in this way

**Comment by Rocologo** [comment]
If would be really nice with a feature where the movie is moved to a library after it has been downloaded.

**Comment by scakemyer** [comment]
Ok so what @compyy is asking wouldn't work as it's libtorrent that's managing the storage while buffering, but @Rocologo's idea is what's going to get implemented instead in #440, since it better describes what the feature will do and was filed before this one. See you there.
