### ISSUE TITLE
Performance Degradation v.0.9.35

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#538]
Hi,

I don't know for sure, but it seems that after updating to the new version 0.9.35 the Download/Upload rates are very low (under 400kb/s), even with popular movies.
With 0.9.34 I got above 2000kb/s, even with less popular items and low seeds.

I'm also getting low seeds results.

UPDATE: I removed all quasar files from kodi, and install it again. Now it seems back to normal.

**Comment by burekas7** [comment]
By the way what is the meaning of the numbers here (x/y):
http://s18.postimg.org/tjkhc41ux/Quasar1.png

And what is the meaning here S (n/m) and P (a/b):
http://s18.postimg.org/ls3rdjxpl/Quasar2.png
what is the difference between S and P?

Thanks.

**Comment by bluenote73** [comment]
The S/P is seeders / peers.  You can go ahead and google that there's lots of good expanations.
thanks
