### ISSUE TITLE
Library not able to pull data from tvdb

### ISSUE THREAD

**Issue by dtsexpert** [scakemyer/plugin.video.quasar#54]
Version 0.9.1 beta 2, for some tv shows the library is not able to pull data from tvdb. library folder is there but empty. 
Few example Tv shows that library folder is empty: blinspot, nightwatch, shades of blue,

**Comment by i96751414** [comment]
This is already fixed in last version. See this please: https://github.com/scakemyer/plugin.video.quasar/issues/48
