### ISSUE TITLE
Very long timeout setting needed for magnetic providers to work

### ISSUE THREAD

**Issue by eidermar** [scakemyer/plugin.video.quasar#540]
When magnetic providers are used even with only a single provider in use, provider timeout has to be set very high - up to 60+ sec.  for quasar to return results. Otherwise logs show an error message "script. quasar.magnetic was too slow. Ignored." and Kodi throws an error message. Reading the logs though you can see that the provider returns the results almost instantly. This is confirmed by multiple people on different systems as discussed in forums. Also we cross checked the magnetic providers with Torrenter add-on  where results were returned quickly as expected.

Here are 2 debug logs from Kodi 17 Beta 2 on Ubuntu 16.0.4:

With provider timeout set to 60sec - after 60sec the links are displayed successfully:

http://paste.ubuntu.com/23214726

With provider timeout set to 30sec - after 30sec an error message is displayed (either "no links found" or " one or more items failed to play" - sometimes both):

http://paste.ubuntu.com/23214732

**Comment by delta-heavy** [comment]
Quasar can't control how long it takes for a provider to process a request and return results. I guess most people don't get it. There are so much factors in play here like your internet connection(how fast it is), can your net speed handle the amount of your enabled providers, how busy is each provider's site, etc. Simply not Quasar's problem.

Please close this.

**Comment by compyy** [comment]
I think its a provider issue, check here:


**18:24:09** T:1519380784  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/show/62687/season/1/episode/1/links from ['plugin://plugin.video.quasar/show/62687/season/1/episode/1/links', '71', '']

**18:24:29** T:1489987888  NOTICE: [plugin.video.quasar] [33mWARN  AddonSearcher script.quasar.magnetic ▶ call             [0mProvider script.quasar.magnetic was too slow. Ignored.
18:24:29 T:1489987888  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     [0mReceived 0 links.

Here you can see that provider is still doing its work and Quasar has already decleared it as too slow, so yes the only solution is:

1. Speed-up the provider.
2. Parellel process the provider (use multithreading)
3. or Make quasar to wait for special signal from magnet connector untill then dont timeout.

So who will fix what, we dont know.

**Comment by eidermar** [comment]
@delta-heavy wow, you didn't even read the whole post, did you? Did you read the part about the cross-check with torrenter? Did you even take a look at the logs? So thanks for nothing! Why is it that people have to always be so damn smart and accusing? I really think I did my homework here.

@compyy well, I'm not sure it's actually still doing something at this stage or if it it's just not able to hand over it's results to quasar somehow.  As I wrote, the provider seems to work flawlessly with torrenter. If it really was too slow shouldn't we see the same results there?

**Comment by scakemyer** [comment]
Sorry @eidermar but @delta-heavy is right; you simply can't make two network requests that take the same amount of time to compare. Timeouts are working fine in Quasar, provider searches are already multithreaded, Magnetic also does its own multithreading and has itself a default timeout of 10 seconds which is way too low.
