### ISSUE TITLE
Quasar subtitle

### ISSUE THREAD

**Issue by corrpel** [scakemyer/plugin.video.quasar#541]
Hi, I noticed that for about 3 months the subtitles cannot be found using the Quasar subtitle addon.
It is very useful when you send a torrent from chrome "Play to kodi" (JSON rpc if i am correct).
Can you please bring back to life the subtitle Quasar addon?

**Comment by corrpel** [comment]
Also, as an ideea if it is possible, can you make this addon codependant of the other subtitles addons.
I mean, config Quasar subtitile addon to use the addons installed for fetching, this way we will solve the label issues were we have a lot of issues opened for.

**Comment by scakemyer** [comment]
Was fixed in scakemyer/quasar@9d4f5e0
