### ISSUE TITLE
TV Shows Library No Longer Updating : 404 GetEpisode Error

### ISSUE THREAD

**Issue by ParDev** [scakemyer/plugin.video.quasar#542]
It seems about a month ago the TV shows library stopped automatically updating. If I delete Shows and re-add to the Library, I can see the new episodes - however episodes are not being automatically updated.

If I Manually click on the "Update Library" option in the Quasar settings - this error pops up:

**ERRO  tmdb         ▶ func1            GetEpisode bad status: 404**

Full trace below:
```
00:19:27 T:3228  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/ from ['plugin://plugin.video.quasar/', '34', '']
00:19:27 T:4460  NOTICE: [plugin.video.quasar] [GIN] 2016/09/17 - 00:19:27 |[97;42m 200 [0m|             0 | ::1 |[97;44m  [0m GET     /
00:19:28 T:8156  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/shows/ from ['plugin://plugin.video.quasar/shows/', '35', '']
00:19:28 T:4460  NOTICE: [plugin.video.quasar] [GIN] 2016/09/17 - 00:19:28 |[97;42m 200 [0m|      1.0007ms | ::1 |[97;44m  [0m GET     /shows/
00:19:30 T:1780  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/ from ['plugin://plugin.video.quasar/', '36', '']
00:19:30 T:4460  NOTICE: [plugin.video.quasar] [GIN] 2016/09/17 - 00:19:30 |[97;42m 200 [0m|             0 | ::1 |[97;44m  [0m GET     /
00:21:12 T:4460  NOTICE: [plugin.video.quasar] INFO  config       ▶ Reload           Reloading configuration...
00:21:26 T:6572  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/library/update from ['plugin://plugin.video.quasar/library/update', '-1', '']
00:21:28 T:4460  NOTICE: [plugin.video.quasar] **ERRO  tmdb         ▶ func1            GetEpisode bad status: 404**
00:21:29 T:4460  NOTICE: [plugin.video.quasar]
00:21:29 T:4460  NOTICE: Previous line repeats 1 times.
00:21:29 T:4460  NOTICE: [plugin.video.quasar] [31m2016/09/17 00:21:29 [Recovery] panic recovered:
00:21:29 T:4460  NOTICE: [plugin.video.quasar] GET /library/update HTTP/1.1
00:21:29 T:4460  NOTICE: [plugin.video.quasar] Host: localhost:65251
00:21:29 T:4460  NOTICE: [plugin.video.quasar] Connection: close
00:21:29 T:4460  NOTICE: [plugin.video.quasar] Accept-Encoding: identity
00:21:29 T:4460  NOTICE: [plugin.video.quasar] Connection: close
00:21:29 T:4460  NOTICE: [plugin.video.quasar] User-Agent: Python-urllib/2.7
00:21:29 T:4460  NOTICE: [plugin.video.quasar]
00:21:29 T:4460  NOTICE: Previous line repeats 1 times.
00:21:29 T:4460  NOTICE: [plugin.video.quasar] runtime error: invalid memory address or nil pointer dereference
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:443 (0x430ad7)
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:62 (0x42f12c)
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/signal_windows.go:161 (0x443a5d)
00:21:29 T:6572   ERROR: [plugin.video.quasar] Traceback (most recent call last):
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/library.go:478 (0x53cb3c)
00:21:29 T:6572   ERROR: [plugin.video.quasar]   File "C:\Users\Pardina\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 112, in run
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/library.go:265 (0x538902)
00:21:29 T:6572   ERROR: [plugin.video.quasar]     data = _json(url)
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6a3bc1)
00:21:29 T:6572   ERROR: [plugin.video.quasar]   File "C:\Users\Pardina\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 48, in _json
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/recovery.go:45 (0x6b67b8)
00:21:29 T:6572   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6a3bc1)
00:21:29 T:6572   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/logger.go:63 (0x6b5a51)
00:21:29 T:6572   ERROR: [plugin.video.quasar]     return _opener.open(url, data, timeout)
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6a3bc1)
00:21:29 T:6572   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:284 (0x6aabe9)
00:21:29 T:6572   ERROR: [plugin.video.quasar]     response = meth(req, response)
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:265 (0x6aa80e)
00:21:29 T:6572   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:1910 (0x4c9324)
00:21:29 T:6572   ERROR: [plugin.video.quasar]     'http', request, response, code, msg, hdrs)
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2081 (0x4c9e85)
00:21:29 T:6572   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
00:21:29 T:6572   ERROR: [plugin.video.quasar]     return self._call_chain(_args)
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:1472 (0x4c6645)
00:21:29 T:6572   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
00:21:29 T:4460  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/asm_amd64.s:1998 (0x45ff81)
00:21:29 T:6572   ERROR: [plugin.video.quasar]     result = func(_args)
00:21:29 T:4460  NOTICE: [plugin.video.quasar] [0m
00:21:29 T:6572   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
00:21:29 T:4460  NOTICE: [plugin.video.quasar] [GIN] 2016/09/17 - 00:21:29 |[97;41m 500 [0m|    3.1434166s | ::1 |[97;44m  [0m GET     /library/update
00:21:29 T:6572   ERROR: [plugin.video.quasar]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
00:21:29 T:6572   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by nibirusbr** [comment]
Rasp same error

**Comment by ParDev** [comment]
Turns out it was a bad "show" (The walking dead) - I removed shows one by one from the Quasar DB until i found it. Not sure why TMDB would return 404 for this - maybe there is an extra episode that shouldn't be there or something?

**Comment by ShlomiD83** [comment]
had the same problem, The Walking Dead caused 404 error until i removed it from the library.

**Comment by send2moran** [comment]
The script shouldn't have crashed because of and 404 error in the provider.

**Comment by ParDev** [comment]
@send2moran Watching the episodes was fine (via providers).

Problem was updating library - Walking Dead was getting a 404 and blocking the rest of the library getting updated. After removing it, all is good.

**Comment by send2moran** [comment]
Mine is erroring while updating, i tried to clean all trakt collections but no luck .. 
https://logs.tvaddons.ag/peixv9vyf#line-5327

**Comment by ParDev** [comment]
@send2moran I think it is the same issue.

Go through the Quasar menus to TV Shows - Find all the shows in your library and remove them. 

Or Manually update the QuasarDB file

**Comment by torbvea** [comment]
The library is updating normally again after removing The Walking Dead. Thanks!

**Comment by bluenote73** [comment]
@scakemyer tagging this as a bug for the handling of 404 causing an abort

**Comment by marcelmah** [comment]
I think I have the same (?). I get this in my logs (on Windows 10 and RPI3) when I use my Trakt watchlist to go to SOME series (all series from Discovery and History channel; example: Yukon Gold https://trakt.tv/shows/yukon-gold)

Other series and movies just work (like the before mentioned The Walking Dead)

11:13:12 T:5276  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/shows/ from ['plugin://plugin.video.quasar/shows/', '16', '']
11:13:12 T:4340  NOTICE: [plugin.video.quasar] [GIN] 2016/10/23 - 11:13:12 |[97;42m 200 [0m|      6.0012ms | ::1 |[97;44m  [0m GET     /shows/
11:13:13 T:1396  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/shows/trakt/ from ['plugin://plugin.video.quasar/shows/trakt/', '17', '']
11:13:13 T:4340  NOTICE: [plugin.video.quasar] [GIN] 2016/10/23 - 11:13:13 |[97;42m 200 [0m|      3.5005ms | ::1 |[97;44m  [0m GET     /shows/trakt/
11:13:15 T:1388  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/shows/trakt/watchlist from ['plugin://plugin.video.quasar/shows/trakt/watchlist', '18', '']
11:13:16 T:4340  NOTICE: [plugin.video.quasar] [GIN] 2016/10/23 - 11:13:16 |[97;42m 200 [0m|    1.2601614s | ::1 |[97;44m  [0m GET     /shows/trakt/watchlist
11:13:16 T:3208   ERROR: container.setviewmode called with invalid number of parameters (should be: 1, is 0)
11:13:18 T:2632  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/show/0/seasons from ['plugin://plugin.video.quasar/show/0/seasons', '19', '']
11:13:19 T:4340  NOTICE: [plugin.video.quasar] ERRO  tmdb         ▶ func1            GetShow bad status: 404
11:13:20 T:4340  NOTICE: [plugin.video.quasar]
11:13:20 T:4340  NOTICE: Previous line repeats 1 times.
11:13:20 T:4340  NOTICE: [plugin.video.quasar] [31m2016/10/23 11:13:20 [Recovery] panic recovered:
11:13:20 T:4340  NOTICE: [plugin.video.quasar] GET /show/0/seasons HTTP/1.1
11:13:20 T:4340  NOTICE: [plugin.video.quasar] Host: localhost:65251
11:13:20 T:4340  NOTICE: [plugin.video.quasar] Connection: close
11:13:20 T:4340  NOTICE: [plugin.video.quasar] Accept-Encoding: identity
11:13:20 T:4340  NOTICE: [plugin.video.quasar] Connection: close
11:13:20 T:4340  NOTICE: [plugin.video.quasar] User-Agent: Python-urllib/2.7
11:13:20 T:4340  NOTICE: [plugin.video.quasar]
11:13:20 T:4340  NOTICE: Previous line repeats 1 times.
11:13:20 T:4340  NOTICE: [plugin.video.quasar] runtime error: invalid memory address or nil pointer dereference
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:458 (0x42db91)
11:13:20 T:2632   ERROR: [plugin.video.quasar] Traceback (most recent call last):
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/panic.go:62 (0x42c654)
11:13:20 T:2632   ERROR: [plugin.video.quasar]   File "C:\Users\MediaCenter\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 112, in run
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/signal_windows.go:161 (0x440e77)
11:13:20 T:2632   ERROR: [plugin.video.quasar]     data = _json(url)
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/api/shows.go:184 (0x534670)
11:13:20 T:2632   ERROR: [plugin.video.quasar]   File "C:\Users\MediaCenter\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 48, in _json
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6526b1)
11:13:20 T:2632   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/cache/cache.go:114 (0x7769e1)
11:13:20 T:2632   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
11:13:20 T:2632   ERROR: [plugin.video.quasar]     return _opener.open(url, data, timeout)
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6526b1)
11:13:20 T:2632   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 410, in open
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/recovery.go:45 (0x662571)
11:13:20 T:2632   ERROR: [plugin.video.quasar]     response = meth(req, response)
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6526b1)
11:13:20 T:2632   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/logger.go:63 (0x6616ce)
11:13:20 T:2632   ERROR: [plugin.video.quasar]     'http', request, response, code, msg, hdrs)
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/context.go:97 (0x6526b1)
11:13:20 T:2632   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 448, in error
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:284 (0x6589e5)
11:13:20 T:2632   ERROR: [plugin.video.quasar]     return self._call_chain(*args)
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /go/src/github.com/gin-gonic/gin/gin.go:265 (0x6582b7)
11:13:20 T:2632   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
11:13:20 T:2632   ERROR: [plugin.video.quasar]     result = func(*args)
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2022 (0x4b6736)
11:13:20 T:2632   ERROR: [plugin.video.quasar]   File "C:\Program Files (x86)\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:2202 (0x4b7204)
11:13:20 T:2632   ERROR: [plugin.video.quasar]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /usr/local/go/src/net/http/server.go:1579 (0x4b3a2e)
11:13:20 T:2632   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 500: Internal Server Error
11:13:20 T:4340  NOTICE: [plugin.video.quasar] /usr/local/go/src/runtime/asm_amd64.s:2086 (0x45c171)
11:13:20 T:2632   ERROR: [plugin.video.quasar]
11:13:20 T:4340  NOTICE: [plugin.video.quasar] [0m
11:13:20 T:4340  NOTICE: [plugin.video.quasar] [GIN] 2016/10/23 - 11:13:20 |[97;41m   0 [0m|    1.3006656s | ::1 |[97;44m  [0m GET     /show/0/seasons
11:13:20 T:3208   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.quasar/show/0/seasons
11:13:20 T:3208   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/show/0/seasons) failed
11:13:33 T:5124  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/show/4614/seasons from ['plugin://plugin.video.quasar/show/4614/seasons', '20', '']
11:13:33 T:4340  NOTICE: [plugin.video.quasar] [GIN] 2016/10/23 - 11:13:33 |[97;42m 200 [0m|      155.52ms | ::1 |[97;44m  [0m GET     /show/4614/seasons
11:13:33 T:3208   ERROR: container.setviewmode called with invalid number of parameters (should be: 1, is 0)

**Comment by ShlomiD83** [comment]
i think the problem was solved, added the walking dead to my library just now, cleared my cache, restarted kodi and it updated without an error.

**Comment by scakemyer** [comment]
@bluenote73 definitely, thanks
