### ISSUE TITLE
Not sure if this is a problem...

### ISSUE THREAD

**Issue by nsil60** [scakemyer/plugin.video.quasar#551]
Hello all need your opinion please… so i run Kodi on a pc and/or an iMac... if i stream a very large file, lets say 5gigb it will buffer alot. Now the origin of the file is a torrent so im not sure if this is because its not being seeded by enough people or my pc is too slow or my internet connection is too slow?

Internet download speed = 50mb (sometimes a bit higher)
imac cpu = 2.8ghz i5 pentium with 8 gig ram
pc cpu = Lenovo ThinkPad T420 Core i5 2.50GHz Notebook 6GB 
kodi = jarvis 16
quasar = 0.9.35

The buffering will happen on either machine above that i've tried.

if i download the file and stream locally on my lan it plays perfectly. 

What do u think? 

Thank you in advance for the help all.

**Comment by acs-ferreira** [comment]
It surely depends on how many seeders the file have.
As you've said, locally, the file plays fine so nothing to see with your machine.

Just try another large file/torrent **BUT** correctly seeded and you'll be fixed.

**Comment by ShlomiD83** [comment]
by default quasar pre-buffers only 20 MB, try setting it to 75 MB and try again.

**Comment by nsil60** [comment]
Hello, i tried 75MB. Seems like the stream got a bit further along than usual but still started freezing a few minutes in.

**Comment by scakemyer** [comment]
What @acs-ferreira said, seeders and actual download speed are a lot more relevant than your exact cpu and pre-buffer here.
