### ISSUE TITLE
Unable to find any provider - No links were found

### ISSUE THREAD

**Issue by pyjouss** [scakemyer/plugin.video.quasar#552]
Hi there,

Recently having some issues with Quasar I deinstalled it as well as all providers and reinstalled it (zip version downloaded from here, not repository).
I'm using 9.3.5 ARM v7 on a Raspberry Pi 2.

Since then Quasar acts as if I didn't installed any provider (which I did) I get 2 message every time I select a show/movie: 
- Unable to find any Provider.
- No links were find.

I tried deinstalling, reinstalling, nothing works.

Any idea?
Thanks

**Comment by Sracinas** [comment]
Try setting timeout to 20 seconds in provider settings. It fixed this issue for me.

**Comment by scakemyer** [comment]
Logs would be useful here.

**Comment by eduvirgens** [comment]
Hi friends.
I've the same issue with quasar. I also have desinstalled and reinstalled the plugin, but I didn't get resolve it. I have installed the providers of repository unofficialquasar latest.zip. I'm using Windows7 64bits. I've captured the log file: https://mega.nz/#!S5M2CDCA!O2hCuXf239rncKAnjLXxyai3IzJ4HneTr_AGA-2tRPw
 What I need to do?

**Comment by HalinReno** [comment]
I, too am having this problem. Since I was using a proxy server, I have disabled it, rebooted, and tried with no luck. I have also changed the timeout to 20 seconds but doesn't make a difference. I get the error right after 2 seconds no matter what I change it to. Here is my log:
https://mega.nz/#!iZAxXSqJ!0DF9D8lp4Lb5AZrddeD8q2ELuEh_TPM36K3gQLxzxhw

**Comment by scakemyer** [comment]
Please don't use Mega, Dropbox and the like to share logs. Either paste it directly between triple-backquotes (or not, I add them most of the time anyway...) or drag-and-drop the file right here instead.

Other than an issue with timeouts, there's nothing to fix here. If you're using Magnetic, make sure you also installed the Quasar "bridge".

**Comment by riiiic** [comment]
Are you saying the old non-magnetic, MC's providers are still running ?
Why all of a sudden from one day to another one did they all stop running ? Before hundred of entries and 24h later none, what happened exactly I'm just curious were they shut down ??
Anyway, none of the providers seem to work but EZTV. Outside of kodi they work just fine.

Well, that's sad.

**Comment by scakemyer** [comment]
What? How the hell are providers supposed to work "outside of Kodi"... Anyway, most non-magnetic providers probably still work, nothing sad even if they don't. Not only that but if you do get results from at least one provider, you're not getting the "Unable to find any provider" notification and you're complaining in the wrong issue.

**Comment by riiiic** [comment]
It seems the same issue to me.
Before: Install OpenElec, install Quasar, Install 3 providers, everything worked perfectly.
Now: install OpenElec, Install Quasar, Install 10 providers (or 10 magnetic providers or one at the time, or all together) and getting several messages never found before: "Httperror()", "No providers found" or "getting no results".

This happened to me in less of 24h, with the same system, the same versions (at least for what I know, the same quasar 0.9.36 for sure).
I tried to reset the system, following the same steps I followed in the last year... nothing worked anymore.

From perfectly oiled naturally working to non-understandable not-working anymore system (non-understandable for me anyway).
Already spent too many hours on this, I just wanted to be sure I wasn't the only one.

All the best. 

Bye!

**Comment by scakemyer** [comment]
If it's the same Quasar, it didn't occur to you that the problem was with Magnetic or the providers? You probably didn't read my previous comment about the "bridge" you surely didn't install, which again is not a Quasar issue.

And don't complain to me about any amount of hours you spent on this.

**Comment by riiiic** [comment]
I did install the "bridge" and only one provider works, "EZTV", all the rests can't find any results and they turned out with a blank page (tried them one by one as suggested in the guide of the "bridge").
I'm not complaining with you about time, I'm describing an objective reality concerning me: from 5 minutes of an installation perfectly working to several ours to have a system not working.
Have a nice day.  This is my last message.

**Comment by pknoyes** [comment]
I am having a problem with Quasar.  It was working fine, but now I get an error message "unable to find links", then Error 10054- connection forcibly closed.  This is a Windows error.  I go to their page on Error 10054 and they say it is a Win 7 problem.  I am running Kodi 17.3 in Win 10.  
https://ares-project.uk/logupload/log.php?id=2239940
