### ISSUE TITLE
Quasar dont download using Pelisalacarta addon

### ISSUE THREAD

**Issue by jsantosanton** [scakemyer/plugin.video.quasar#554]
Hello,

i has installed Quasar on Openelec (with raspberry pi 3), when i try to play a film searching by Pelisalacarta addon quasar show the window with the download information and the progress bar but dont download anything.

What is the problem? Firewall? Configuration?

Thanks you so much.

**Comment by scakemyer** [comment]
Way too little info to be able to help here, and some other add-on mixed-in... Firewall.
