### ISSUE TITLE
Some of the titles is unreadable

### ISSUE THREAD

**Issue by Rocologo** [scakemyer/plugin.video.quasar#555]
When ever I search for movies the returned list contains alot of wrong/unreadable titles. Some of the titles are fine, but about 50% is wrong. The same goes for other fields fetched from the Movie Database. The movie cover is fine, is only text which is wrong. And I can download the movie without prpblems.

**Comment by Rocologo** [comment]
This might be related to ticket #254 I found workaround if I mark "Prefer use of original title" I can see all the titles. I am living in Denmark, but my installation is in English and I prefer English titles and subtitles.

**Comment by scakemyer** [comment]
I think you answered your own question :)
