### ISSUE TITLE
Traktv thumbnails

### ISSUE THREAD

**Issue by troop3r85** [scakemyer/plugin.video.quasar#558]
Hi, I'm wondering if this an issue or not but last couple of days I'm unable to see any thumbnails in the traktv section, all other sections work fine, I've tried uninstalling the add on, kodi and on several devices with no luck

**Comment by TTLucian** [comment]
I have the same issue on 2 different android devices.

**Comment by burekas7** [comment]
Me too. In my Trakt Movie Collection in Quasar doesn't show the posters.

**Comment by rosskopf** [comment]
that's because trakt.tv has turned off images API
[https://apiblog.trakt.tv/trakt-api-images-56b43c356427](url)

**Comment by marcelmah** [comment]
That means Quasar will need to look somewhere else to get the posters from...

**Comment by burekas7** [comment]
** This is the Announcement of the author of SALTS addon **

" Trakt has let me know that they are having MAJOR image hosting issues. They have pushed their CDN to the limit (on the order of 1 Petabyte/Month) and have been left with no choice but to completely disable image hosting from their API. To SALTS that means that all movie, show, season, and episode images are going to be broken in the very near future (i.e. only existing cached images will work).

To resolve this, I'm going to have to add brand new code to SALTS to "mix in" images from other sources for all these media types. Not only is it going to take time to "mix in" those images in general, but to build up the full complement of image data that Trakt was previously providing. I will start working on this code tomorrow/this weekend but it's going to very much be an incremental type thing resolved over several builds. "

So here it probably should be the same, or use the same development.

**Comment by burekas7** [comment]
@scakemyer 

From where are you taking the posters today?
Because sometimes it takes weird posters or doesn't take the popular of them
