### ISSUE TITLE
Daemon Fails to Start Android 4.4

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#56]
In the latest update 0.9.1 i get and error message loading daemon at the start of kodi. Something about a file already exists or something like that... (a write permission error?)

Here is my log: http://pastebin.com/4diBMdrm

**Comment by scakemyer** [comment]
Hey, thanks for the report, I was afraid the fix for Marshmallow would cause this for some users. It was fine on another Android 4.4 I tested so I went ahead with it, but just to confirm, it was working fine on beta2 for you?

**Comment by KillerJoeBR** [comment]
Yes it was working before (0.9.1beta2). 

Thanks for looking at this.

**Comment by scakemyer** [comment]
Released v0.9.2, please try it out and let me know if it fixes it. The logs should provide a little more information also in case it doesn't.

**Comment by KillerJoeBR** [comment]
Thanks. I will try the fix later when i get home. About 6 hours from now.

I tried quasar on my android 4.4.2 phone and the version 0.9.1 is working fine. So i guess, just some devices got an error (in my case the firetv first gen)

**Comment by KillerJoeBR** [comment]
OK i can confirm that version 0.9.3 is working fine on my fireTV. Thanks again

**Comment by scakemyer** [comment]
Awesome, thanks for reporting back!
