### ISSUE TITLE
HTTP error on Raspberry Pi

### ISSUE THREAD

**Issue by hollisterca** [scakemyer/plugin.video.quasar#561]
Raspberry Pi with ARM image V0.9.36
Getting the error
Navigation error: HTTPError()

**Comment by ShlomiD83** [comment]
did you turn on the remote control setting?

**Comment by hollisterca** [comment]
To your question: sure
I disabled automatic updates, then reinstalled 0.9.35 and everything works.
With the updates turned on it goes to 0.9.36 and I get the above error.

**Comment by ShlomiD83** [comment]
it happened yesterday to alot of ppl including me on some devices and turning on both remote control options solved it.
so if its not the remote control then logs are needed.

**Comment by hollisterca** [comment]
both remote control options are turned on, same error, downgraded again to 0.9.35 and things are working.

**Comment by GMTA** [comment]
I have the same issue. See the attached log. The "xxx", "yyy", etc. are edits.

[20161112-kodi-quasar-log.txt](https://github.com/scakemyer/plugin.video.quasar/files/587438/20161112-kodi-quasar-log.txt)

**Comment by mancuniancol** [comment]
I have the same error with my Windows version.

`10:16:52 T:11056  NOTICE: [plugin.video.quasar] /go/src/github.com/scakemyer/quasar/xbmc/addons.go:17 (0x560221)
10:16:52 T:12216   ERROR: [plugin.video.quasar]     return opener.open(url, data, timeout)`

**Comment by mancuniancol** [comment]
well if the previous version works that means that it is a regression in the latest one. :P

**Comment by mancuniancol** [comment]
I can play the videos using the magnetic contextual menu.  Then, the problem is with the Quasar's menu

**Comment by mancuniancol** [comment]
I've had the same error, but the remote control options were off.  I've changed to on and it is working as usual.

**Comment by GMTA** [comment]
Enabling the remote control options did not resolve this issue. Probably a separate issue?

**Comment by giannidallatorre** [comment]
Same problem here, with a Raspberry Pi 2, fixed downgrading to version `0.9.35`

**Comment by philwolstenholme** [comment]
I'm seeing this too on 0.9.36, with all the remote control options in Kodi enabled.

**Comment by scakemyer** [comment]
After making sure the remote control options are enabled, try restarting Kodi. IPv6 to connect to Kodi and the add-on from the daemon was disabled in v0.9.36 to fix #12.

**Comment by philwolstenholme** [comment]
That seems to fix the issue, thanks!

**Comment by bubuleur** [comment]
Hello same problem for me for version 0.9.36 httperror with the providers cpasbien and t411
Best regards

**Comment by scakemyer** [comment]
@bubuleur solution and explanation are in my last comment

**Comment by scakemyer** [comment]
Same as #550
