### ISSUE TITLE
How do I clear watching (%) status?

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#562]
Hi,

If I started a video and stopped, there is indication where I stopped by % value.
Is there any way to reset it or remove it somehow?

Thanks.

**Comment by scakemyer** [comment]
Fairly sure this is a Kodi thing and has nothing to do with Quasar.

**Comment by burekas7** [comment]
Hi,
Is there any progress regarding this?
Thanks.
