### ISSUE TITLE
Bug & Request: Some info labels returns empty values

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#566]
Hi,
Can you fix that so these info label for the items will return their related values, respectively if it's a movie or tvshow/season/episode?

Currently:
xbmc.getInfoLabel("ListItem.DBTYPE") - returns empty
xbmc.getInfoLabel("ListItem.OriginalTitle") - returns empty
xbmc.getInfoLabel("ListItem.IMDBNumber") - returns empty

Whereas these are ok:
xbmc.getInfoLabel("ListItem.Year") - ok
xbmc.getInfoLabel("ListItem.TVShowTitle") - ok
xbmc.getInfoLabel("ListItem.Season") - ok
xbmc.getInfoLabel("ListItem.Episode") - ok

Thanks.

**Comment by burekas7** [comment]
According to 0.9.37
xbmc.getInfoLabel("ListItem.OriginalTitle") - is ok now

- but -
xbmc.getInfoLabel("ListItem.DBTYPE") - still returns empty
xbmc.getInfoLabel("ListItem.IMDBNumber") - still returns empty
(I'm checking it in the trakt lists for example)

**Comment by scakemyer** [comment]
Damnit... I think the python `setInfo` method just doesn't set those.

**Comment by burekas7** [comment]
If you want, you could check how it's done on these addons: Exodus or Salts (At least for the DBTYPE value, because IMDBNumber is not working there also)

**Comment by scakemyer** [comment]
Finally found it, it's `mediatype` we need to set since Jarvis...

**Comment by scakemyer** [comment]
I'm hoping that setting `Code` will do the same for `IMDBNumber`, if not I won't be spending more time on that one.

**Comment by burekas7** [comment]
Check with 0.9.41 but still the same.
Thank you for the attempt anyway.

**Comment by scakemyer** [comment]
For IMDBNumber only or both? DBTYPE is populated reliably now over here.

**Comment by burekas7** [comment]
Both.
xbmc.getInfoLabel("ListItem.DBTYPE")
xbmc.getInfoLabel("ListItem.IMDBNumber")

I checked it for example in Movies -> IMDB Top 250

**Comment by burekas7** [comment]
Thanks, now it works! :)
Version 0.9.42
