### ISSUE TITLE
v0.9.36 breaks TMDB lookup

### ISSUE THREAD

**Issue by yutrea** [scakemyer/plugin.video.quasar#568]
Hi,

My Quasar stopped working (HTTPError when clicking on any entries) when I upgraded to v0.9.36. I can confirm that downgrading to v0.9.35 fixes the issue.

I'm attaching debug logs from both v0.9.35 and v0.9.36, which illustrates the issue.

[Quasar_v0.9.35_working.txt](https://github.com/scakemyer/plugin.video.quasar/files/609587/Quasar_v0.9.35_working.txt)
[Quasar_v0.9.36_crash.txt](https://github.com/scakemyer/plugin.video.quasar/files/609588/Quasar_v0.9.36_crash.txt)

**Comment by scakemyer** [comment]
See #550 and #561. Make sure remote control options are enabled and restart Kodi.
