### ISSUE TITLE
Peers and Seeds wrong counted

### ISSUE THREAD

**Issue by lollo78** [scakemyer/plugin.video.quasar#573]
Hi, 
I noticed a wrong correspondence from peers/seeds shown in the query and the same ones during video playing.

**Comment by scakemyer** [comment]
Quasar quickly scrapes trackers to try to get the most accurate estimate before actually starting to stream a torrent, but there isn't much else we can do. Providers typically return those numbers initially, but those numbers are often even more inflated than what "bad" trackers report.

**Comment by scakemyer** [comment]
I just tried getting the median of what trackers report, and the results were even more inaccurate, most often too low. The current way of getting the highest count is the closest we can get until streaming actually starts.
