### ISSUE TITLE
Cubox, quasar 0.9.36 - Unable to find any providers

### ISSUE THREAD

**Issue by riiiic** [scakemyer/plugin.video.quasar#574]
Hello everybody, 

I'm new here and normally I don't even have to write cause all the instructions work perfectly.
However, since a couple od days, my quasar set up (Cubox-i4 pro, openElec 6.0.3) doesn't want to find any results anymore, whenever I search for something. Blank page.
I tried to flash the SD card and reinstall everything from scratch and I encounter first the "HTTPerror()" solved with ----> settings - services - remote control (both option on).

But then I got the same results, blank page. I understood something is realted with "MC's Provider" no long working, so I follow the instruction and install Magnetic Torrent manager and a bunch of Magnetic MC's provider, but know I got this new error "unable to find any provider"

What is is exactly I'm doing wrong here ? It seems this problem is only affecting me.

Thanks a lot for your help.

ric

**Comment by scakemyer** [comment]
#552
