### ISSUE TITLE
You must restart Kodi before using Quasar

### ISSUE THREAD

**Issue by epullay** [scakemyer/plugin.video.quasar#576]
Hello. I recently installed Quasar and I followed a tutorial doing every step as listed. After installing the add-on, a message popped up saying "You must restart Kodi before using Quasar".
Of course, I closed Kodi, reopened it, and the same popup appears again. I've closed and reopened Kodi at least 5 times now, and the same thing keeps happening.

I'm also sorta a newbie when it comes to logs, so.. I'll just do what I found on the official Kodi wiki says.

Log: http://paste.ubuntu.com/23626934/
If you need any other kind of information, I'll provide it right away.

I'm currently using Kodi Krypton. I downloaded it from the windows store.

**Comment by scakemyer** [comment]
Good logs, this goes with the Windows Store issue: #547
