### ISSUE TITLE
Change download dialog to decide on-the-air

### ISSUE THREAD

**Issue by ghost** [scakemyer/plugin.video.quasar#577]
First, I want to describe my situation.  Sometimes, I am looking to watch a movie.  But, the torrent that I've chosen is slow or I've changed my mind.  If I cancel the torrent will stop, if I don't have the download in background on.

However, sometimes, I want just download the file. Then, I need to activate the download in background.  but, if I've changed my mind. I cannot cancel on-the-air.  I have to go to the menu to cancel it there.

Then, my request, it is possible of course, is:

[image]

The **download in background** button will close the window and the file will continue to download.

The **stop** button will stop, the file will be removed of any download list and the download will stop.

If nothing is selected, the torrent will be played as usual.

Please, let me know if I wasn't clear.

**Comment by scakemyer** [comment]
The new behavior asking to keep downloading solves this, and re-implementing a custom progress dialog would've been too error-prone to be worth it, if even possible.
