### ISSUE TITLE
Bug: Trakr Tv shows collection - Navigation error: HTTPrror()

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#578]
Hi,

Since 0.9.37:
TV Shows -> Trakt -> List -> Collection - is not working and getting "Navigation error: HTTPrror()"
(With Movies Collection there is no problem)

Thanks.

**Comment by scakemyer** [comment]
Nice catch, updated the routes but missed the old paths...

**Comment by scakemyer** [comment]
I'll release 0.9.38 right away, thanks!

**Comment by burekas7** [comment]
This bug of "Navigation error: HTTPError()" returns in 0.9.40.
And now it occurs also with Movies Collection

**Comment by ShlomiD83** [comment]
did you re-authorize you trakt account after updating?

**Comment by burekas7** [comment]
Yes, I have tried this also.
Still the same.

**Comment by johnnyslt** [comment]
Here's a log 

http://sprunge.us/CIXV

**Comment by scakemyer** [comment]
Ok this is a separate issue related to the fix for Trakt images, thanks for the log, will try to push a hotfix today.
