### ISSUE TITLE
inability to play specified type of torrents

### ISSUE THREAD

**Issue by lyanko** [scakemyer/plugin.video.quasar#579]
Hi. I want to thank author for this great addon. I'm using it very often and works pretty good for me, although I wanna ask something. Why Quasar stops when I put torrent from my private trackers like Torrentleech is e.g.? I saw that recently some providers came out for some private trackers but people complain about Quuasar inability play them? The more awkward thing is that other, and not so complex like Quasar is, torrent addons like Torrenter or Yet Another Torrent Player plays my torrents from Torrentleech with easy. If they can I think Quasar can do the same cause after all they are all torrent players right? And the funny part is that Quasar have all settings for seeding, keeping ratio clean or avoiding h'n'r everything what needs to make your life at private tracker possible but if it's disabled to play them then all those options are unnecessary :)

If author wants to give him credentials (user and password) for Torrentleech or some another private tracker which I posses to see where could be the problem I can do that cause I would really like to help. I tried in past Torrenter and I didn't like him I want to stay with Quasar cause it's amazing but just if this thing can be done to improve addon I think it will be great. :)

**Comment by scakemyer** [comment]
#38

**Comment by lyanko** [comment]
I'm sorry didn't see that this was already put as a issue. As I said if some developer need credentials for some private tracker I can provide him as I want to help as much as I can :)

Great work though, Quasar is stunning addon.
