### ISSUE TITLE
v0.9.39 master no binary after install

### ISSUE THREAD

**Issue by arierotman** [scakemyer/plugin.video.quasar#581]
HI,
Libreelec official 7.02 running on Intel NUC (linux_x64)
Using Master v0.9.39 after install no bin folder under /storage/.kodi/plugin.video.quasar/resources
Using plugin.video.quasar-0.9.39.linux_x64.zip works OK.
10x

**Comment by scakemyer** [comment]
Please make full sentences and provide logs.

**Comment by ShlomiD83** [comment]
never install the master, only the zips from the releases page.

**Comment by arierotman** [comment]
OK now it works! 
For some reason when I  downloaded the plugin.video.quasar-0.9.39.zip from here:
https://github.com/scakemyer/plugin.video.quasar/releases/download/v0.9.39/plugin.video.quasar-0.9.39.zip
the zip file did not contain the binary files for each O.S I.E "windows_x86", linux_x64 etc...
Under plugin.video.quasar-0.9.39\plugin.video.quasar\resources\bin
Downloaded the file again and now everything is there.
Thank you!

**Comment by scakemyer** [comment]
The file didn't change, you probably downloaded the zip from the front page with the 'Clone or download' button.

**Comment by arierotman** [comment]
well you may be  correct, however everything started when Quasar stopped working this morning. after investigating It I noticed that Quasar was updated to version 09.39 and the error was "unable to find binary "(mine is in Hebrew) or sometimes "please reboot Kodi"  after trying to click on Quasar.
This is not the first time. this has happened to me It happened before on Openelec..
I tried to do a clean Install but all the repo's I used From Israel to name but one, http://repo.thewiz.info/
I also noticed from this repo it actually refers to https://githhub-cloud.s3.amazonaws.com
The only one that worked before was on the unofficial Quasar Repo version 0.935.
I hope we are not dealing with so called "repo poisoning" this has happed before with with other ad-ons  like KMedia.
thank you again ! and Have a great weekend.
