### ISSUE TITLE
[Bug] Import TV Shows Trakt Collection raises exception

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#585]
Hi,

When trying import Trakt TV shows collection by "Add to library", there is an error:
GetShow bad status: 404
Navigation error: HTTPError()

It does imports some of the collection, but some of them not.
Manually add them specific is working.

Log: http://pastebin.com/ekpf83zC

(Version: 0.9.41)

**Comment by scakemyer** [comment]
Before anything else, thanks for your bug reports, that's how it should be done.

Turns it's a regression introduced in 0.9.36 in commit scakemyer/quasar@4591fef, nice catch :)

**Comment by burekas7** [comment]
Update:

Now I'm still getting the error:
GetShow bad status: 404

But then there is a notification:
Item add successfully added to library

It does imports some of the collection, but some of them not.
When I'm trying manually add them it says "Item already in library", but it's not exist there.

Log: http://pastebin.com/tUT4c7Sq

(Version: 0.9.42)

**Comment by scakemyer** [comment]
The error shouldn't prevent any other show from being added, I just forgot to make sure the Trakt object had a TMDB ID...

**Comment by burekas7** [comment]
(0.9.43)
In the folder these shows doesn't exist while in the log it says:
NOTICE: [plugin.video.quasar] WARN  library      ▶ AddShowCollection  FlashForward (84024) already in library
NOTICE: [plugin.video.quasar] WARN  library      ▶ AddShowCollection  Heroes (79501) already in library
NOTICE: [plugin.video.quasar] WARN  library      ▶ AddShowCollection  Revolution (258823) already in library
NOTICE: [plugin.video.quasar] WARN  library      ▶ AddShowCollection  Jericho (79330) already in library
NOTICE: [plugin.video.quasar] WARN  library      ▶ AddShowCollection  Lost (73739) already in library

So I think the "already in library" status prevents from it to be added again or something.
Can you just override folders when add to library even if already exist?

**Comment by scakemyer** [comment]
The "already in library" warnings that include the ID mean they're in you're regular Kodi library. Disable the "Ignore duplicates" to add them in your Quasar library folder, and yes the folders and strm files just get overridden in that case.

**Comment by burekas7** [comment]
Thanks man, now everything is ok :)
