### ISSUE TITLE
Quasar repository not working

### ISSUE THREAD

**Issue by prilly** [scakemyer/plugin.video.quasar#586]
Hi

Seems the ibuilt quasar repository is not working as intended, i have a cubox armv7 that is not updating quasar addon past version v35, the repository that wuasar is adding to kodi is showing the most recent version of v35 and not v41 for the armv7 build. this is not correct i belive.

so for me to upgrade to v41 i needed to do that manualy with a .zip

**Comment by scakemyer** [comment]
Can't help without logs. Another one solved this by just reinstalling Quasar #582. Will reopen if there really is an issue.
