### ISSUE TITLE
WHY!!! Help please!!! 

### ISSUE THREAD

**Issue by jrod10133** [scakemyer/plugin.video.quasar#587]
im having few issues with quasar it was like 20 updates in a week n now quasar been acting stupid wat the hell is going on every time i try to watch something it cuts off like wat the hell n it doesnt delete the leftover of movie anymore wat am i doing wrong cuz quasar was working for me now is not! i got other torrent addon like popcorntime n torrenter n they work just fine quasar is a really cool addon but now it just crashing all the fucking time please!!! somebody help me with this issues if anybody need my log file or whatever u call it to help me let me know

**Comment by scakemyer** [comment]
You're the one acting stupid. GTFO kiddo.
