### ISSUE TITLE
Trakt: scrobbling by the offical addon

### ISSUE THREAD

**Issue by herrwusel** [scakemyer/plugin.video.quasar#588]
This is just a suggestion but as far as I understand quasar is syncing/scrobbling what I watch. I really like the offical's addon feature that I can vote at the end. Is it possible to let the offical addon do the scrobbling(weird word)?

And a question: When I add trakt's watchlist to my library will quasar also update the library whenever I remove items from that list?

I'm really happy about this plugin and appreciate what you are doing scakemyer! Is there any way to spend you a coffee/beer?

**Comment by scakemyer** [comment]
Scrobbling seems to be working fine now with the official add-on, in which case it's probably better to use that and disable it in Quasar instead.

Library integration currently can't remove items when you remove them from a list. It keeps track of what it added overall but can't actually sync items per list with the current implementation. It can however update/add your lists periodically. There's definitely improvements to be made here.

I've added a donation button on the website at https://quasar.surge.sh if you have some bitcoins to spare :beer:
