### ISSUE TITLE
Internet throttle.

### ISSUE THREAD

**Issue by Sandbird** [scakemyer/plugin.video.quasar#59]
Using this addon, as well as Pulsar, my router gets throttled, blocking the internet.
Can you please add an option to limit max connections allowed ?
Torrenter uses that, and its the only way to stop this. I've had this problem with another Thompson but I had the same problem with an old Linksys router....and i am not the only one.
Thanks

**Comment by Sandbird** [comment]
love ya!

**Comment by rosskopf** [comment]
thank u!! :+1:

**Comment by scakemyer** [comment]
It will be in the next release, already pushed out two of those yesterday so I had to slow it down a little ;)
