### ISSUE TITLE
thx man!

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#590]
This is not an issue xD Thanks man for returning to Quasar actively. It's amazing to see this addon progressing so fast again. The best video addon of all of them no doubt. Cheers and hope it will last for many years, we can just enjoy it :)

**Comment by nix87** [comment]
OMG I just saw this great addition with private trackers and soon I wanted to try and now we have everything. It's all working well now.

You are amazing bro, happy Christmas and let the great things follows you through your life.

**Comment by scakemyer** [comment]
Thanks! Merry Christmas to you also and let's all hope 2017 isn't as shitty ;)

[![F*** 2016](https://img.youtube.com/vi/HogH1uFjoxc/0.jpg)](https://www.youtube.com/watch?v=HogH1uFjoxc)
