### ISSUE TITLE
Update loop when using an unofficial repo and the GitHub API fails to return last tag

### ISSUE THREAD

**Issue by kostaboxon** [scakemyer/plugin.video.quasar#591]
Letting you know i am in a continuous loop of Quasar Add-On Updated then immediately downloading again with the same Quasar Add-On Updated. repeatedly  the same loop.
Still showing 0.9.42

**Comment by scakemyer** [comment]
Logs man, logs.

**Comment by scakemyer** [comment]
Blind guess is that you have some unofficial repo causing a conflict within Kodi.

**Comment by kostaboxon** [comment]
Here is the log.
[01_KODI.txt](https://github.com/scakemyer/plugin.video.quasar/files/665578/01_KODI.txt)

**Comment by scakemyer** [comment]
I was mostly right, unofficial repo combined with the GitHub API not returning the last tagged version... Try removing the Unofficial Quasar Repo for now and adding the other, newer providers-only one. I'll see what I can do on this side to prevent those conditions from causing this update loop. I'm also in the process of adding a backup, regular repo so we depend a little less on GitHub.

**Comment by kostaboxon** [comment]
I Looked at below lines in my log. Thought something was not right.
 16:48:32 T:545699410144  NOTICE: [plugin.video.quasar] Resetting RPC objects...
16:48:38 T:545691021536  NOTICE: [plugin.video.quasar] [33mWARN  repository   ▶ getLastRelease   [0mUnable to find a last tag, using master.
16:48:38 T:545691021536  NOTICE: [plugin.video.quasar] INFO  repository   ▶ GetAddonFiles    [0mLast release:  on master
16:48:38 T:545691021536  NOTICE: [plugin.video.quasar] [33mWARN  repository   ▶ getLastRelease   [0mUnable to find a last tag, using master.
16:48:39 T:545691021536  NOTICE: [plugin.video.quasar] INFO  repository   ▶ fetchChangelog   [0mFetching add-on changelog...
Thanks again.
No ZIPS

**Comment by heartlogic** [comment]
I am too having the same issue... 

I have installed version 0.9.42 manually from the .zip file in the site and i am in a constant updating loop... 

I am also having the Unofficial Quasar Repo but the new version seems to come from Quasar repository with version number 0.9.45...

I have LibreELEC in a media center... 

Tell me if you need any additional information...

**Comment by kostaboxon** [comment]
Updated itself from 0.9.42 which had the loop
to 0.9.44 which worked. No more loop.
Thank you.

**Comment by heartlogic** [comment]
Now version is 0.9.45 and i still have the loop...

**Comment by kostaboxon** [comment]
I have no idea where you got 0.9.45 version.
0.9.44 is the current version. 
Look at releases. There is no 0.9.45 version.
https://github.com/scakemyer/plugin.video.quasar

**Comment by scakemyer** [comment]
There's nothing different regarding any of this between 0.9.42 and 0.9.44. As it stands, as long as the GitHub API returns the last tag, or you don't have an unofficial repo, updates work as expected. I'll make sure this doesn't happen when those conditions are combined in a subsequent release, but for now removing the unofficial repo is the best solution. The update loop would also eventually end as soon as the GitHub API returns the last tag.

**Comment by kostaboxon** [comment]
Auto Update to 0.9.45 Installed successfully.
No loop.

**Comment by heartlogic** [comment]
At the time i tested there was no official 0.9.45 version, i was also expecting 0.9.44...

But i got 0.9.45 version form the Quasar repo (not the unofficial) and i got the loops...

Now since there is an official 0.9.45 i will try later at night and report if it works alright...
