### ISSUE TITLE
Request: Delete All for downloaded torrents

### ISSUE THREAD

**Issue by johnnyslt** [scakemyer/plugin.video.quasar#595]
Hi,

Please add a **Delete All** context menu for downloaded torrents, that are seeding or paused.

This is a time saver :timer_clock: 

Thanks !

**Comment by scakemyer** [comment]
You can use the shiny new web UI for this until I implement it in the add-on, just point your browser to `http://<Kodi IP or hostname>:65251/web/`

**Comment by scakemyer** [comment]
`Delete torrent and files` per torrent or as mentioned the web UI will have to do.
