### ISSUE TITLE
TypeError: When using "cast" or "castandrole" you need to supply a list of tuples for the value in the dictionary

### ISSUE THREAD

**Issue by rosskopf** [scakemyer/plugin.video.quasar#597]
Hi,
In Quasar v0.9.44 when the movie start to play i get an error.
it has something to do with Infolabels.

```
[plugin.video.quasar] Traceback (most recent call last):
[plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 133, in run
[plugin.video.quasar]     data = _json(url)
[plugin.video.quasar]   File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/navigation.py", line 100, in _json
[plugin.video.quasar]     item.setInfo(type='Video', infoLabels=infoLabels)
[plugin.video.quasar] TypeError: When using "cast" or "castandrole" you need to supply a list of tuples for the value in the dictionary
```

I'm running kodi 16 on LibreELEC (official) - Version: 7.0.2, kernel: Linux x86 64-bit
I have uploaded a log on pastebin.
thanks.

[http://pastebin.com/1D9w3h5E](http://pastebin.com/1D9w3h5E)

**Comment by jrod10133** [comment]
im having the same problem i think im never gonna update quasar cuz every time i do its alwayz something............... im staying with 0.9.42 the only ver. tha works

**Comment by scakemyer** [comment]
@jrod10133 Please do, just don't come complaining about it, prick.

**Comment by scakemyer** [comment]
@rosskopf Thanks for the report, will release 0.9.45 with the hotfix shortly.

**Comment by scakemyer** [comment]
Going through Trakt listings don't trigger this error since we don't get Cast and Crew. But then 0.9.45 will be up in a few minutes...
