### ISSUE TITLE
images are not showing in trakt lists

### ISSUE THREAD

**Issue by rosskopf** [scakemyer/plugin.video.quasar#599]
Hi again :)

Images in "trakt" are not loading, i get requests on TMDB and images are in de cache folder but are not showing. 

LibreELEC (official) - Version: 7.0.2, kernel: Linux x86 64-bit
pastebin: [http://pastebin.com/zbQhNXB3](http://pastebin.com/zbQhNXB3)

thanks.

**Comment by scakemyer** [comment]
All I can see is that you're using a custom TMDB API key, which is perfectly fine, and 4 GetImages warnings out of dozens of list items which is normal. It's not *all* images now is it?

**Comment by rosskopf** [comment]
1 image is working in my list this morning in trending and my watchlist, don't know what movie it was, i'm at work now.

This evening i shall try reinstall and report back.

**Comment by rosskopf** [comment]
If i chance the language in kodi from dutch to english then the images are showing :)

**Comment by scakemyer** [comment]
Ha! Right.. I remember leaving the language field empty for the GetImages call, and mostly getting the english covers but a few non-english ones too... so I set the language field to the user's setting. It's already a pretty expensive thing to request images from TMDB for each Trakt listing, and slowed down every Trakt list significantly but we just don't have any alternative now that Trakt no longer serves images directly. Might as well make sure we get the most out of those API calls. Fixing it to better handle other languages.

**Comment by rosskopf** [comment]
that was quick, many thanks!
enjoy your beer ;)

**Comment by scakemyer** [comment]
That's a whole pitcher you sent there, thanks! :beers:
