### ISSUE TITLE
Error on LibreElec 7: binary not found

### ISSUE THREAD

**Issue by paulsmid** [scakemyer/plugin.video.quasar#601]
Hi I have the same issue on my Wetek Hub where I installed on SD Libreelec 7 but also tried the 7.9 build. All same error: unable to find binary after install Quasar. I tried all the different Linux versions of Quasar.

**Comment by scakemyer** [comment]
If you have the same issue, post in the same issue. #570

**Comment by paulsmid** [comment]
Hi, I think it is the same problem. Do you know any solution for this 
issue? I am running LibreELEC on my Wetek Hub from SD. Thanks.
-- 
Hartelijke groeten,

Paul Smid
