### ISSUE TITLE
[Request] Delete torrent and downloaded files

### ISSUE THREAD

**Issue by guindous** [scakemyer/plugin.video.quasar#603]
Hi! A handy feature could be to add an action to "Torrent" window related whit torrent's context menu called "Delete torrent and files" that not only deletes the torrent itself but also all downloaded files/folders associated with it.
Thanks in advance for your great work with this plugin.

**Comment by scakemyer** [comment]
That's what the "Keep downloaded files" and "Ask to keep downloaded files" settings are about. Too many context menu items is like not enough.

**Comment by guindous** [comment]
I will explain myself a little more to see if this feature qualifies to be reopened. I use the "Keep downloaded files" all the time because the limited bandwidth of mi Internet connection. The lack of good connection is due geographical inconveniences, not because I'm a stingy person :D. So, direct streaming is not an option for me and I have to wait the download to be finished. When the files are already downloaded, I watch the content and after that I eliminate the torrent and the downloaded files. To do that, I have use two differents dialogs: in Kodi "file commander" dialog I delete the downloaded files and from "Torrents" Quasar dialog I delete the torrent. That's why, at least in my situation, this could be a handy feature.
Anyway, @scakemyer thanks for your fast response.

**Comment by scakemyer** [comment]
Alright, I see how this makes sense.

**Comment by scakemyer** [comment]
You could also enable "Ask to keep", cancel buffering and answer yes the first time, once your download is done hit play and answer no the second time around.
