### ISSUE TITLE
In the Web UI the counting of downloading and total is not working

### ISSUE THREAD

**Issue by ibox99** [scakemyer/plugin.video.quasar#604]
In the Web UI the counting of downloading and total is not working.
i added a torrent trought magnet link and it started to download but the counting never changed.

**Comment by scakemyer** [comment]
Anything in the developer console? (ctrl-shift-J in Chrome, ctrl-shift-K in Firefox)

**Comment by ibox99** [comment]
Hello, with the last version (48) it appears to be working. The downloading
and completed information.

The "active"(slide) button that stops the downloads, after a second or two
activates itsealf again but the quasar remains off. Then we have to turn
off again and on again so it restarts the download.

My configuration :
-openelec  5.95.5 (kodi 15.1) because the recent versions are a bit
unstable
- using dolphin browser in Android 5.1
Due to be an older configuration some errors can come from that.

By the way, a suggestion: an option in the web UI, if you want to stream
(view) or just download in the background.
Thank you for the great work.

Sorry if I confused you more.

Em 26/12/2016 17:56, "scakemyer" <notifications@github.com> escreveu:

**Comment by ibox99** [comment]
I again. Other thing I noticed now, when we put it to stream trough web UI
it begins the stream "normally", then restarts the stream 2 times before it
becomes stable.

Em 26/12/2016 21:04, "Ibox 99" <ibox99@gmail.com> escreveu:

**Comment by scakemyer** [comment]
Considering this solved.
