### ISSUE TITLE
Hi Sir,navigation error,httperror

### ISSUE THREAD

**Issue by brmnh** [scakemyer/plugin.video.quasar#609]
This is the log

**Comment by brmnh** [comment]
12:31:42 T:592  NOTICE: ActiveAE DSP - starting
12:31:42 T:592  NOTICE: initialize done
12:31:42 T:592  NOTICE: Running the application...
12:31:42 T:592  NOTICE: WebServer: Started the webserver
12:31:42 T:592  NOTICE: starting upnp client
12:31:42 T:5748  NOTICE: ES: Starting UDP Event server on 0.0.0.0:9777
12:31:42 T:5748  NOTICE: UDP: Listening on port 9777
12:31:42 T:3292  NOTICE: [plugin.video.quasar] quasar: starting jsonrpc service
12:31:42 T:4444  NOTICE: [plugin.video.quasar] quasard: starting quasard
12:31:42 T:2756  NOTICE: [script.module.magnetic]
12:31:42 T:2756  NOTICE: [script.module.magnetic]                           _   _
12:31:42 T:2756  NOTICE: [script.module.magnetic]  _ __  __ _ __ _ _ _  ___| |_(_)__
12:31:42 T:2756  NOTICE: [script.module.magnetic] | '  \/ _' / _' | ' \/ -_)  _| / _|
12:31:42 T:2756  NOTICE: [script.module.magnetic] |_|_|_\__,_\__, |_||_\___|\__|_\__|
12:31:42 T:2756  NOTICE: [script.module.magnetic]           |___/
12:31:42 T:2756  NOTICE: [script.module.magnetic]
12:31:42 T:2756  NOTICE: [script.module.magnetic] Author: mancuniancol
12:31:42 T:2756  NOTICE: [script.module.magnetic] Version: 0.9.69a
12:31:42 T:2756  NOTICE: [script.module.magnetic] Magnetic service at 127.0.0.1:5005
12:31:42 T:4444  NOTICE: [plugin.video.quasar] Deleting stale files set([u'Torrents'])
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             ________
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             \_____  \  __ _______    ___________ _______
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main              /  / \  \|  |  \__  \  /  ___/\__  \\_  __ \
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             /   \_/.  \  |  // __ \_\___ \  / __ \|  | \/
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             \_____\ \_/____/(____  /____  >(____  /__|
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main                    \__>          \/     \/      \/
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             Version: "v0.9.48" Go: go1.7.4
12:31:44 T:4444  NOTICE: [plugin.video.quasar] INFO  config       ▶ Reload           Reloading configuration...
12:31:46 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             Addon: plugin.video.quasar v0.9.48
12:31:46 T:4444  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        Setting Session settings...
12:31:46 T:4444  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        Setting Encryption settings...
12:31:46 T:4444  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ configure        Setting Proxy settings...
12:31:46 T:4444  NOTICE: [plugin.video.quasar] INFO  tmdb         ▶ CheckApiKey      Checking TMDB API key...
12:31:46 T:4444  NOTICE: [plugin.video.quasar] INFO  btservice    ▶ alertsConsumer   Consuming alerts...
12:31:47 T:4444  NOTICE: [plugin.video.quasar] NOTI  libtorrent   ▶ logAlerts        external_ip_alert: external IP received: 221.2.15.64
12:31:47 T:4444  NOTICE: [plugin.video.quasar] NOTI  tmdb         ▶ CheckApiKey      TMDB API key check passed, using ae4bd1b...
12:31:47 T:4444  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             Updating Kodi Addon Repositories
12:31:47 T:3292  NOTICE: [plugin.video.quasar] Resetting RPC objects...
12:31:47 T:3828   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
12:31:47 T:3828   ERROR: CCurlFile::Open failed with code 0 for http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml.md5
12:31:47 T:3828   ERROR: XFILE::CFileCache::Open - failed to open source <http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml.md5>
12:31:47 T:3828   ERROR: CRepositoryUpdateJob[repository.quasar] failed read checksum for directory 'http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml'
12:31:52 T:5408   ERROR: [plugin.video.quasar] Traceback (most recent call last):
12:31:52 T:5408   ERROR: [plugin.video.quasar]   File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 131, in run
12:31:52 T:5408   ERROR: [plugin.video.quasar]     data = _json(url)
12:31:52 T:5408   ERROR: [plugin.video.quasar]   File "C:\Users\john\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\navigation.py", line 48, in _json
12:31:52 T:5408   ERROR: [plugin.video.quasar]     with closing(urllib2.urlopen(url)) as response:
12:31:52 T:5408   ERROR: [plugin.video.quasar]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 127, in urlopen
12:31:52 T:5408   ERROR: [plugin.video.quasar]     return _opener.open(url, data, timeout)
12:31:52 T:5408   ERROR: [plugin.video.quasar]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 410, in open
12:31:52 T:5408   ERROR: [plugin.video.quasar]     response = meth(req, response)
12:31:52 T:5408   ERROR: [plugin.video.quasar]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 523, in http_response
12:31:52 T:5408   ERROR: [plugin.video.quasar]     'http', request, response, code, msg, hdrs)
12:31:52 T:5408   ERROR: [plugin.video.quasar]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 448, in error
12:31:52 T:5408   ERROR: [plugin.video.quasar]     return self._call_chain(*args)
12:31:52 T:5408   ERROR: [plugin.video.quasar]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 382, in _call_chain
12:31:52 T:5408   ERROR: [plugin.video.quasar]     result = func(*args)
12:31:52 T:5408   ERROR: [plugin.video.quasar]   File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 531, in http_error_default
12:31:52 T:5408   ERROR: [plugin.video.quasar]     raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
12:31:52 T:5408   ERROR: [plugin.video.quasar] HTTPError: HTTP Error 500: Internal Privoxy Error
12:31:52 T:5408   ERROR: [plugin.video.quasar]
12:31:52 T:592   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.quasar/
12:31:52 T:592   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/) failed
12:31:59 T:592  NOTICE: Storing total System Uptime
12:31:59 T:592  NOTICE: Saving settings
12:31:59 T:592  NOTICE: stop all
12:31:59 T:592  NOTICE: stop player
12:31:59 T:592  NOTICE: ES: Stopping event server
12:31:59 T:592  NOTICE: stopping upnp
12:31:59 T:5748  NOTICE: ES: UDP Event server stopped
12:31:59 T:592  NOTICE: WebServer: Stopped the webserver
12:31:59 T:592  NOTICE: stop sap announcement listener
12:31:59 T:592  NOTICE: clean cached files!
12:31:59 T:592  NOTICE: unload skin
12:32:00 T:2756  NOTICE: [script.module.magnetic] Exiting providers service, Bye!
12:32:00 T:4784  NOTICE: [plugin.video.quasar] quasar: exiting quasard
12:32:00 T:3008  NOTICE: [plugin.video.quasar] quasard: exiting quasard daemon
12:32:00 T:3008  NOTICE: [plugin.video.quasar] quasard: quasard daemon exited
12:32:00 T:4444  NOTICE: [plugin.video.quasar]
12:32:01 T:3292  NOTICE: Previous line repeats 39 times.
12:32:01 T:3292  NOTICE: [plugin.video.quasar] quasar: exiting jsonrpc service
12:32:02 T:592  NOTICE: stopped
12:32:02 T:592  NOTICE: destroy
12:32:02 T:592  NOTICE: closing down remote control service
12:32:03 T:592  NOTICE: unload sections
12:32:03 T:592  NOTICE: special://profile/ is mapped to: special://masterprofile/
12:32:04 T:592  NOTICE: destroy
12:32:04 T:592 WARNING: Attempted to remove window 10013 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10014 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10015 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10016 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10017 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10018 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10019 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10021 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10107 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10115 from the window manager when it didn't exist
12:32:04 T:592 WARNING: Attempted to remove window 10104 from the window manager when it didn't exist
12:32:04 T:592  NOTICE: closing down remote control service
12:32:04 T:592  NOTICE: unload sections
12:32:04 T:592  NOTICE: application stopped...
12:32:04 T:592   ERROR: dllFreeLibrary - Invalid hModule specified

**Comment by scakemyer** [comment]
Remote control options / Windows firewall / other Quasar process running.

**Comment by brmnh** [comment]
Hi Sir,I already turn on the remote control option and turn off my computer’s windows firewall.

**Comment by scakemyer** [comment]
`HTTP Error 500: Internal Privoxy Error` has nothing to do with Quasar, this is on your end. Please stop opening issues and good luck.

**Comment by brmnh** [comment]
Hi Sir,but it says navigation error too.I turn off my proxy.It still reminds navigation error and http error.

**Comment by brmnh** [comment]
Sir are you online?

**Comment by scakemyer** [comment]
I don't know, this is 100% on your end and specific to your setup. Goodbye now.
