### ISSUE TITLE
Fails to start Deamon Android X86

### ISSUE THREAD

**Issue by Rikitik** [scakemyer/plugin.video.quasar#61]
Deamon fails to start on Android 4.2.2 X86(Tab 3)
Unable to find Binary(however i verified the it exists in the zip)
plugin.video.quasar-0.9.3.zip\plugin.video.quasar\resources\bin (but no Android X86)
Does Android X64 support X86?
Note Pulsar never worked on this device Either

Kodi Log
`http://p.ahkscript.org/?p=9e3ed786`

**Comment by scakemyer** [comment]
I'll be adding android_x86 very soon, thanks for the logs!

**Comment by Rikitik** [comment]
Thank you but unfortunatly the deamon crashes and after 3 attempts gives Erno 11

`http://p.ahkscript.org/?p=b0e8fbc9`

**Comment by OteCortes** [comment]
Hi,
First of all, thx for all your work.
I downloaded the x86 version to test in one tablet i own and the version 0.9.6 starts, but crash.
Here is my logs in case it can help you.

[http://p.ahkscript.org/?p=cf38ad2a](http://p.ahkscript.org/?p=cf38ad2a)

**Comment by scakemyer** [comment]
android_x86 requires Android 5.x, I just couldn't get libtorrent to compile using a lower API level

**Comment by Rikitik** [comment]
Oh man, this is bad Newer roms(android 5/6) for the Tab 3 are unstable at best

**Comment by scakemyer** [comment]
Yeah sorry, but I've already spent way too many hours trying to get this to compile using API level 19, while it just worked with 21. Feel free to give it a shot: https://github.com/scakemyer/libtorrent-go

**Comment by scakemyer** [comment]
Closing for now, let's open a new issue if this doesn't work on 5 or 6
