### ISSUE TITLE
library integration duplicates

### ISSUE THREAD

**Issue by kingdingaling83** [scakemyer/plugin.video.quasar#611]
hey there,

here's an example of a local NFO file for an episode i have locally
http://pastebin.com/m6f34fPS

I try to add the show to my librabry but it duplicates it. 

which scraper should i set it to?

**Comment by scakemyer** [comment]
None will work in this case, there's just no ID in your nfo file.

**Comment by kingdingaling83** [comment]
ok do you know of what software i can use to add ID into my NFO file?
tinymedia manager?
