### ISSUE TITLE
Unable to resolve .torrent file at:  | Get : unsupported protocol scheme ""

### ISSUE THREAD

**Issue by Paco112** [scakemyer/plugin.video.quasar#612]
I have this error since version > 0.9.45 with my provider ( https://github.com/Paco112/script.quasar.t411 ) :

Unable to resolve .torrent file at:  | Get : unsupported protocol scheme ""

**Comment by Paco112** [comment]
Ok i have fix my provider by create a magnet uri !

**Comment by scakemyer** [comment]
Great :) Please don't post links to providers here, we've already got a few issues taken down because of things like that. Thanks!
