### ISSUE TITLE
Kodi crashes sometimes when trying to open stream from multi-part archives

### ISSUE THREAD

**Issue by herrwusel** [scakemyer/plugin.video.quasar#613]
Hi there,

I have one provider scakemyer[gosh, your name is weird :D] where from time to time Kodi crashes when starting to stream.
I'm using an Intel NUC with the latest LibreELEC alpha.

Here are the last lines of the log:
http://pastebin.com/ZJe2HprC
If you need more I can provide the entire log.

Another thing I noticed with this provider is that Quasar can't handle packaged files. Quasar then want me to chose between 'nameoffile.r01' etc. Maybe unpacking is feature for future Quasar. I didn't want to open another issue because it's not that important to me.

**Comment by scakemyer** [comment]
Please, no provider-related issues, sorry herrwusel :( (talk about weird names uh!) We've already lost access to some.

The unpacking of rar files isn't something that can or will be supported either and doesn't have anything to do with providers either, if that can shed some light on your issue.

**Comment by herrwusel** [comment]
What I really meant was that this behavior never happened before - only with this provider. I still think it's an Quasar issue. It seems that Quasar has problems playing the video file because it is zipped inside. So maybe Quasar could just decline these kind of torrents.

I try to reproduce it with Big Buck Bunny or something similar. Maybe next year ;)

**Comment by scakemyer** [comment]
I get what you're saying, also saw it happen. You're right that it shouldn't crash and at least just notify it can't play those files. I apologize to my most valued user for closing his issue too early ;)

**Comment by scakemyer** [comment]
There's nothing in those logs though, which I appreciate somehow since it means less provider-specific stuff, but if you happen to see a golang stacktrace, that'd be the most helpful part.

**Comment by scakemyer** [comment]
Next release will support downloading and extracting those multi-part rar archives :)

**Comment by dal00** [comment]
Why are you extracting those files? Kodi is able to play directly from rar if no compression is used and that is normally the case. Which technical limitation do you have for not streaming from the rars or at least playing directly from them after a download?
