### ISSUE TITLE
Request: no need to clear caches on settings changes

### ISSUE THREAD

**Issue by rosskopf** [scakemyer/plugin.video.quasar#616]
Hi,
Is it possible to not clear the cache folder everytime u go in the settings in Quasar and press ok.
Thanks.

**Comment by scakemyer** [comment]
Clearing cache is highly overrated... it's really just the lists/pages and individual items, so yeah, you got it. There's no real need to clear it, and Quasar is already reloading its settings for those that don't require a restart.

**Comment by rosskopf** [comment]
Thanks scakemyer! :D
