### ISSUE TITLE
Quasar using the original title despite settings 

### ISSUE THREAD

**Issue by herrwusel** [scakemyer/plugin.video.quasar#617]
I encountered that Quasar is using the original title instead of using the language of Kodi. As a result the search results are not really what you want to see.

**Comment by scakemyer** [comment]
The payload to providers is supposed to include both; the original title by default, fallback to title if empty, as well as the list of all available translated titles. I suppose we could have yet another setting for that, but I'd be inclined to let providers deal with which title it wants to search for / actually fallback to.

**Comment by herrwusel** [comment]
Thanks for the information.

It is solved now by the provider.

**Comment by scakemyer** [comment]
Awesome, let's thank the man who can't be named ;)
