### ISSUE TITLE
Open issues regarding the Results dialog

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#618]
Hi,

According to this screenshot: ...
Few things regarding the Results dialog:
1) The scrollbar there, can you fix it to be stretched and fits to the dialog? (Or is it skin issue?)
2) Can you make the focus result item's text be scrolling when the text is long?
3) Less critical but there is a little problem with the search method, for example "The Show S01E05", it gave results from other tv shows because they also included the words "The", "Show", "S01E05".
Or like here: ...

Thanks.

**Comment by scakemyer** [comment]
Both 1. and 2. are skin issues. Your skin isn't scaling the scrollbar properly, and text is scrolled automatically in other skins also.
Last point is all on the provider(s), what they do with the search payload and the results they return, maybe too many fallbacks/extras are enabled, or not enough filtering. Either way it's not on Quasar to filter those, and even for providers, I don't see how they could reliably filter results that **do** include your search terms without returning a few false positives, short of using neural nets or cross-referencing other valid names.
