### ISSUE TITLE
Addon does not have the correct structure

### ISSUE THREAD

**Issue by hrqmonteiro** [scakemyer/plugin.video.quasar#62]
I'm trying to install both the plugin.video.quasar and the Repository (http://sourceforge.net/projects/icanuckxbmcrepo/files/repository.unofficialquasar-latest.zip/download) but this message "Addon does not have the correct structure" is showing up when i try to install

**Comment by scakemyer** [comment]
Don't put no stinkin' sourceforge links here. Get the add-on from the [releases page](https://github.com/scakemyer/plugin.video.quasar/releases), I can't help you with copies on third-party repositories.
