### ISSUE TITLE
[Request] Input library path manually with keyboard

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#622]
Currently you can set the path only with the Browse Folder dialog.
My request is add an option to edit the path manually with the keyboard screen.

My main target is when I set the library path location in my userdata, I don't want the path will include my username, so I can use the "special://" instead

Instead of this:
"C:\Users\<username>\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.quasar"
Change it to this:
"special://userdata/addon_data/plugin.video.quasar"

* Also the same for "Download path"

Thanks.

**Comment by m4xc4v413r4** [comment]
Isn't that handled by Kodi?

**Comment by scakemyer** [comment]
Nice to see you're still around @m4xc4v413r4 :) I think it *should* be handled by Kodi, the dialog might be missing some flags/options to enable those, will look into that as it'd be a better solution.

**Comment by MrLegendary** [comment]
Or you could just edit the settings.xml file in userdata/plugin.video.quasar... That worked for me.

**Comment by m4xc4v413r4** [comment]
But if we change it from **type="folder"** it won't let you choose by browsing. Not sure there's a way to have both :/

**Comment by scakemyer** [comment]
Yeah I double-checked also, doesn't seem like there is any other option to make it show special paths... I'd leave it as it is honestly, no need to do crazy workarounds for something that works well, and if Kodi ends up allowing to choose special paths as folders then we'd just inherit the change.

**Comment by m4xc4v413r4** [comment]
I can't test right now as I'm on my phone but the only way I see on top of
my head would be to default the source folder as **special://home** maybe,
I don't know if after you browse to another folder from that point, the
path keeps the special, or if it just becomes a complete path.

If it works, it wouldn't hurt anyone since you can still browse to any
folder.

In any case, what's the deal with not wanting the user on the path? :/

Em 08/01/2017 01:45, "scakemyer" <notifications@github.com> escreveu:

**Comment by burekas7** [comment]
@MrLegendary 
Where do I need to write the path? source?
From the setting.xml file
        <setting id="download_path" type="folder" label="30001" source="auto" option="writeable" />
        <setting id="library_path" type="folder" label="30026" source="auto" option="writeable" />

@scakemyer 
Where do you save and read the folders that I set in the addon settings in kodi?
I don't see the path I set in the setting.xml file

**Comment by scakemyer** [comment]
I don't, and neither does Quasar; Kodi does. And your answer is right in your own original post...

**Comment by burekas7** [comment]
It's ok.
I looked for the settings.xml file in the addons quasar folder instead in the userdata\addon_data quasar folder.
So I change it manually as MrLegendary's advised (But it still could be nice to add an option for set it with a keyboard when pressing on the text field, and add a 'browse' button in the right for select a folder as it today.

**Comment by scakemyer** [comment]
Requiring two clicks to get to the browsing part for all other users but you? No, sorry. This is a standard "choose path" dialog. Power-users can change their settings.xml file manually.

**Comment by burekas7** [comment]
I have a problem with the manual changing.

In the settings.xml I wrote:
`    <setting id="library_path" value="special:\\userdata\addon_data\plugin.video.quasar\" />`

But Quasar give me exception for this path: "Library path not set"
`11:28:29 T:12504   ERROR: [plugin.video.quasar] Exception: GetFileAttributesEx special:\userdata\addon_data\plugin.video.quasar: The filename, directory name, or volume label syntax is incorrect.`

While in Quasar settings in kodi, when pressing on the path it does take me to the correct location.

**Comment by burekas7** [comment]
Now it's ok (0.9.68), thanks!  👍

**Comment by scakemyer** [comment]
Yeah, added a TranslatePath for your sorry a**... sigh...
