### ISSUE TITLE
No Buffering - stuck with "Finding" message since v0.9.46 -

### ISSUE THREAD

**Issue by nabsboss** [scakemyer/plugin.video.quasar#624]
Hi,

Thanks a lot for your amazing work, for supporting and improving Quasar !!!

I use Quasar with magnetic t411 provider on Win8.1 x64 and until v0.9.45 it was working like a charm.
Since v0.9.46, when i choose a file, the windows open with Finding message included the link that it suppose to download but it stuck here and there is no buffering.
I try it on an android system and i have same issue.

If i use link the link directly on a brower, i get the file with success.
If use another torrent client like torrenter with magnetic it success.
I download the torrent from t411 manually and use the "add torrent", it success

I disabled proxy and i have same issue
I disabled firewall and i have same issue
I did my test on differents sources (movie, tvshow) and i have same issue

When i modify the settings for testing i always reboot kodi.

This is log file if it can help: http://pastebin.com/bt72ViJd
The issue is only with t411, the others providers are working well.

Thank you for your help !

**Comment by scakemyer** [comment]
As you said, the issue is with a single specific provider. There isn't anything to fix on Quasar's side in this case, it's just not getting a valid torrent file in the first place.
