### ISSUE TITLE
404 and 429 error codes

### ISSUE THREAD

**Issue by Jezze83** [scakemyer/plugin.video.quasar#625]
I try to add my movies from trakt collection folder. I get everytime 429 and 404 error codes. I have 300 movies my trakt account but it adds only few movies. Is there any settings on quasar what i should try? That is great feature if it work. Here is my debug log: http://pastebin.com/89MkdsM5

**Comment by Jezze83** [comment]
What this mean? :D Is fix coming to next version?

**Comment by scakemyer** [comment]
Exactly, though you might have to wait a few days.

**Comment by Jezze83** [comment]
Thats ok, hope that will be fixed. You doing great work!

**Comment by Jezze83** [comment]
Btw, does quasar add movies to my library automatically when i add movie or tv show to my trakt collection? If so, do i have to change some settings from quasar?

**Comment by scakemyer** [comment]
Yes it can, you need to set Advanced / Trakt / Sync frequency.

**Comment by Jezze83** [comment]
I have now 0, does that check constantly trakt collection?

**Comment by scakemyer** [comment]
No that means it's disabled.

**Comment by Jezze83** [comment]
1 hour is minimum?
