### ISSUE TITLE
Large port range causes 0.9.49+ to crash on Android ARM 32-bit

### ISSUE THREAD

**Issue by Znuff** [scakemyer/plugin.video.quasar#626]
Having a large range between `listen_port_min` and `listen_port_max` causes quasar/libtorrent to open up all those ports at start-up, resulting in a `Too many open files` error from the OS.

This started happening with 0.9.49, once with the upgrade to libtorrent 1.1, as per changelog.

## Expected Behavior
While the changelog warns you about reducing the port-range, it is not exactly clear that having a large port-range defined will result in the binary crashing due to the OS restrictions. Further more, people that have it set to automatically update the addon via Kodi never actually see the changelog and are clueless as to why the binary crashes on start-up.

A lot of people's ISPs throttle traffic on known bittorrent ports (6881 to 6889) or downright block it, so people will assign a different range for torrent clients. 

I personally have the port range 56000 to 57000 defined for bittorrent ports, forwarded to the box that does torrenting (in this case a dedicated box for Kodi with Quasar).

I believe that the users expects for the torrent client (quasar) to pick a random port in the range defined by `listen_port_min` and `listen_port_max` rather than it listening on all those ports (or, rather, trying to listen on all those ports).

## Current Behavior
Quasar crashes with `listen_failed_alert: listening on 0.0.0.0 : 0.0.0.0:56499 failed: [open] [TCP] Too many open files`

## Possible Solution
This could be handled more elegantly by either hard-limiting the number of ports that the client listens on, or provide a warning about the setting (if it's insanely high, like mine was) upon start-up.

## Steps to Reproduce (for bugs)

1. Configure a high range between `listen_port_min` and `listen_port_max`
2. Upgrade from 0.9.48 to 0.9.49
3. Have the Quasar binary unexpectedly crash with previously working settings

## Context
Due to lack of time to research during the holidays, and actually read the changelog (I know, my bad), I had to stick to 0.9.42, as that was the previous working build for me (holidays were a busy time, didn't really get to use Kodi, so I missed a few updates).

This causes frustration with the users which aren't able to read the changelog (because the Kodi addon updater doesn't list anything under "changelog" under updates).

## Your Environment

* Version used: 0.9.49+
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC): Kodi (16.1 Git:2016-04-24-f6ceced). Platform: Android ARM 32-bit
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10): Android 6
* Link to Kodi debug log: http://paste.ubuntu.com/23770938/

**Comment by scakemyer** [comment]
And that, ladies and gents, is how issues should be filed. Thanks @Znuff, you can expect a proper fix shortly.

**Comment by scakemyer** [comment]
So libtorrent keeps opening 6881 no matter what I set `listen_interfaces` to, but we'll be opening only two random ports in the specified range from now on.

**Comment by scakemyer** [comment]
Thanks again for the awesome bug report, I'm sure the template helped but taking the time to properly explain saves a lot of time and questions on my end, wish they were all like this :+1:

**Comment by Znuff** [comment]
You're welcomed. Thanks for the fix.
