### ISSUE TITLE
No Seeders\Leechers Shown From Some Providers

### ISSUE THREAD

**Issue by ShlomiD83** [scakemyer/plugin.video.quasar#628]
After updating to 0.9.52 i get no seeders\leechers information in the choose stream dialog.
0.9.51 works fine.

using windows 7 64 bit.
debug log : http://pasted.co/e4d22c3b

**Comment by scakemyer** [comment]
Nothing to do with the update, this is all on the providers.

**Comment by ShlomiD83** [comment]
so how do you explain reverting to 0.9.51 works?

**Comment by scakemyer** [comment]
It doesn't, look closer.

**Comment by ShlomiD83** [comment]
if you say so..

**Comment by scakemyer** [comment]
Seriously, I don't want to be mean but it really gets old every time there's an update. The infamous providers have been half-broken for about week, so unless you come up with actual details, I can't do anything but be annoyed at your report. So please put some effort in your issues next time, I've put up a nice template to fill up, and if you want me to take you seriously and spend time on your issue, do spend time on filing it properly.
Look, Quasar received 4 links:
```
18:39:50 T:6940  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     Received 4 links.
18:39:50 T:6940  NOTICE: [plugin.video.quasar] INFO  linkssearch  ▶ processLinks     Scraping torrent metrics from 8 trackers...
```
Your provider spews this for every result:
```
                                             size: None
                                             seeds: 0
                                             peers: 0
```
And from the 8 trackers Quasar received, two timeout immediately and the others just don't respond:
```
18:39:53 T:6940  NOTICE: [plugin.video.quasar] WARN  linkssearch  ▶ 1                Tracker udp://.../announce failed: Request timed out.
18:39:54 T:6940  NOTICE: [plugin.video.quasar] WARN  linkssearch  ▶ 1                Tracker udp://.../announce failed: Request timed out.
18:39:55 T:6940  NOTICE: [plugin.video.quasar] ERRO  linkssearch  ▶ func2            Timed out waiting for trackers.
```
What more do you want?

**Comment by ShlomiD83** [comment]
You're the expert, just wanted to know if something changed or got broken.

**Comment by scakemyer** [comment]
Nope. Look at the release notes, hell, look at the [changes](https://github.com/scakemyer/quasar/compare/v0.9.51...scakemyer:v0.9.52), it's just 4 good fixes.

**Comment by ShlomiD83** [comment]
i dont know man.. tried 0.9.52 with previous versions of magnetic and still nothing.
RARBG API dont send seeders leechers, not in its current version. so quasar is responsible for scrapping the trackers, if in 0.9.51 it's working and in 0.9.52 it's not, i dont see how it's the provider's fault.

**Comment by scakemyer** [comment]
F****** hell...

**Comment by Jezze83** [comment]
Works fine here with latest update.

**Comment by scakemyer** [comment]
Nah, it seems fine, but providers that do return no seeds/peers in the first place just stay that way, I *did* screw up the channel/waitgroup/timeout that lets the tracker scrapers fill up those values.
