### ISSUE TITLE
Library Integration - Items get re-added although removed from library

### ISSUE THREAD

**Issue by eidermar** [scakemyer/plugin.video.quasar#632]
This is most likely more a question than a bug report regarding the logic behind library integration from trakt lists. Altogether it's just a minor issue and doesn't take away from the brilliance of the add-on.

## Expected Behavior
When I add a custom list (or collection) from my trakt lists to the library via context menu, all the shows get added to the library path and after scanning to the kodi library. When I select individual shows within the trakt lists from quasar and select remove from library, they should not be re-added to library at the next scan/update. Shows that are already in the library should not be added even if they are in one of the added trakt lists in Quasar.

## Current Behavior
I tried with both "ignore duplicates" (I think maybe the naming is misleading here. Does ignore mean to not add them or ignore that they are existing?) checked and unchecked but existing shows always get re-added to the library which leads to duplicates. The work around this I made a custom list that does not include the potential duplicate shows. I could not figure out the correct procedure to get rid of the already added list altogether and choose a different list? Also I'm not sure if the "ignore duplicates" is supposed to only check for the full show folder or even existing and missing seasons (e.g. locally available is S01&S02 is it possible to add only S03 to the library via quasar?

## Possible Solution
I don't know, maybe add an option to reset existing library integration (ideally separate for shows and movies)? Maybe this is just a user error or I try to use the feature in a way it's not designed to work?

## Steps to Reproduce (for bugs)
see above

## Context
I'd like to get a clean kodi library, that has mixed content from quasar .strm files and local content. If possible I'd like to pick full lists instead of manually adding each show. Already existing Shows should not be added as duplicates.

## Your Environment
Kodi 17 RC, Ubuntu 16.04, Intel NUC

I'm not sure anything useful can be read from the logs here, but I'll happily provide them if you want me to.

## Additional Comment
What you did with Quasar is breathtaking. Thank you not only for your hard work but also for sharing it with us and patiently supporting us in your spare time.

**Comment by KillerJoeBR** [comment]
I second this. It's really difficult to delete/remove a series or movie from kodi library when adding from Quasar. They need to be manually selected from within Quasar and use context menu to remove it. One by one. If you don't do this, it will be back again on next scan/update. I really don't know if this is something doable but it would be great.

**Comment by scakemyer** [comment]
I'll be giving the library integration a lot more attention for the next release. I was going to look into Trakt watched status syncing first, and both are high on the priorities list, but library integration should behave as expected before anything else. That includes proper duplicate and merge handling, Trakt list syncing and everything in between.

**Comment by burekas7** [comment]
@KillerJoeBR 
If I understand what you mean,
So I remember there is a setting in kodi settings that should be turned on for enable kodi to delete files in your system, so when you doing the "remove from library" operation, it also should asks you if you want to delete the .strm file also (Not the folder, just the file inside. So the folder remains empty after that). So in this case you won't need to remove it from library in the addon itself with the context menu.
I think it's "Remote Control" in "Services" settings.

Regarding to the main issue,
I checked the"remove from library" inside quasar, and it actuall delete all the folder.
I think you should you "Clean Library" option from Library settings in kodi settings after this, or make kodi rescan you library source folder ("Scan for new content" in Videos -> Files -> the relevant source), so kodi should find that there are missing content and ask you if remove them from library.

**Comment by scakemyer** [comment]
Sorry about this one guys, I'll get around to it soon enough, just not the next release (again) as I said. Plenty of more immediate fixes were needed, and to be honest this one is just grunt work with little pay-off when you don't use library integration. It doesn't take anything away from its importance, especially the bug(s) described here, and I will work on this as soon as possible.

**Comment by herrwusel** [comment]
Now that it's fixed: will quasar actively remove items from library? Just wanted to know ;) Trakt's watchlist removes items if the item is set as watched.

**Comment by scakemyer** [comment]
One thing (or three dozen...) at a time ;) This is all just to prevent duplicates, and keep track of removed movies/shows/episodes properly. The amount of edge cases and back-and-forth between the different types of IDs made this one of the most complicated things I've ever implemented, but I think we've got a solid basis now. So what you're asking should at least be *more* possible, and will look into it after we put this through its paces in 0.9.61 :)

**Comment by scakemyer** [comment]
@herrwusel I know I can be annoying with this, but do you mind creating a new issue for that? I've already linked this one here to many commits, and it gets referenced three times in the next changelog ;)
