### ISSUE TITLE
Online-Aired TV Shows do not show full episodes list due to TMDB air date

### ISSUE THREAD

**Issue by Znuff** [scakemyer/plugin.video.quasar#633]
We're gonna talk about the newly released TV Show called [Beyond](https://www.themoviedb.org/tv/67726-beyond).

"Beyond" airs on the Freeform TV channel every Monday, but with a twist: the show has been fully available online on Hulu, Freeform.go.com (and a few others which I can't remember) since 2nd of January.

## Expected Behavior
Quasar should show the full episode list of the TV Show.

## Current Behavior
Quasar only lists the first 3 (currently aired on TV) episodes. This is not exactly an issue with Quasar directly, but rather with it's data source (tmdb). 

## Possible Solution
It's not ideal, ofcourse, and I can't figure out a way to handle this more elegantly" there could be a whitelist of TV Shows are available in fully regardless of the air date. 

## Context
Well, basically I can't watch this TV Show with Quasar because I can't progress past the 3rd episode until it's actually aired, even if my providers have sources for the other episodes.

## Your Environment

Environment is not relevant for this issue.

**Comment by Znuff** [comment]
Also, a relevant tweet from TMDB:

https://twitter.com/themoviedb/status/818949164683796480

**Comment by scakemyer** [comment]
They do have the whole episode listing, so we can do something about it in Quasar. Adding a setting to show all available episodes should be an acceptable solution here. Also noticed there's a caching issue now that we're not clearing it on every setting change and upgrade, but that's another issue.
