### ISSUE TITLE
(Library Integration) Movies and TV shows don't work anymore

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#638]
Seems like the new version of Quasar (0.9.53) stopped working the library integration function. Movies and TV shows work fine inside Quasar. But the ones that are/were added to Kodi Library doesn't work anymore.

I can provide a log later, but i'm pretty sure it's not working for anyone (at least the android version).

EDIT: The "Add to library" is working okay. It's when we try to play them from inside kodi's library that it's not working (just to be clear).

**Comment by scakemyer** [comment]
I have the feeling you are right. Looking into it and will release a hotfix...
