### ISSUE TITLE
quasar is spamming DNS requests for google.com

### ISSUE THREAD

**Issue by trisk** [scakemyer/plugin.video.quasar#64]
This issue is identical to https://github.com/steeve/plugin.video.pulsar/issues/208

I noticed pulsar was sending DNS requests for the `google.com.` A and AAAA records once every second. I removed it and installed plugin.video.quasar 0.9.3 just now, but the problem is still occurring.

The threads in the quasar daemon process are doing the `google.com.` lookup followed by connecting a socket to UDP port 9 on one of the addresses returned by the lookup, registering the socket with epoll, then almost immediately closing the socket without sending any traffic.

OpenELEC does not cache the DNS results so the lookups might be side effects of regular calls to `net.Dial`. The lookup/connect/close every second seems like strange behaviour, though.

**Comment by scakemyer** [comment]
Got me worried for a second, then remembered I had completely removed the GA tracking, so at least that's not it. But you're right, it's doing a lookup every second [here](https://github.com/scakemyer/quasar/blob/master/bittorrent/service.go#L93). I don't like that either.

**Comment by trisk** [comment]
Sorry for opening the bug in the wrong place, for some reason I was under the impression the daemon wasn't open source (though it appears to be missing a licence still?). Would make more sense to have the connectivity check triggered by a connection timeout, I think.

**Comment by scakemyer** [comment]
It's ok to file most issues here, and yes I'll be looking into changing the connectivity check, or feel free to make a PR on the daemon's repo.
