### ISSUE TITLE
After installation and reboot it always says restart kodi

### ISSUE THREAD

**Issue by ugur1yildiz** [scakemyer/plugin.video.quasar#642]
After update to 0.9.55 it crashes. After fully uninstalling and installing by using linux_arm7 zip  file it says constantly to reboot Kodi before using Quasar. I checked the binary in ~/.kodi/addons/plugin.video.quasar/resources/bin/linux_armv7 
and it is there.

How do we solve the problem?
  
LibreElec 7.90.008 
Raspberry Pi 3

* Link to Kodi debug log:
http://paste.ubuntu.com/23811549/plain/
[01_KODI.log.txt](https://github.com/scakemyer/plugin.video.quasar/files/709111/01_KODI.log.txt)

**Comment by scakemyer** [comment]
See #549, last comment should help you solve this, the update is working just fine.
