### ISSUE TITLE
In select stream mode, when restarting the stream and confirming to use the same source - no need to show select stream dialog

### ISSUE THREAD

**Issue by meijin007** [scakemyer/plugin.video.quasar#643]
Steps:
1) set the addon settings: Disable the "select source automatically" option.
2) start stream.
3) stop the stream.
4) continue the stream from the same source.
Expected: Won't show "select source" dialog.
Actual: Showing the select source dialog with one option, with it meaningless.
attached logs (should be at the end of it)
[kodi.txt](https://github.com/scakemyer/plugin.video.quasar/files/709219/kodi.txt)

**Comment by scakemyer** [comment]
Yeah I'm aware of this, it is meaningless indeed, I admit I was a little lazy in that implementation, will fix.
