### ISSUE TITLE
[Bug/Request] Auto & Force refresh for Trakt lists

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#645]
[Request] Auto & Force refresh for Trakt lists

Sometimes the Trakt lists are not updated (For example with new episodes).

So my suggestion is to add 2 options in settings:
- Force refresh for Trakt Lists
- Auto Refresh setting with value in hours / in every kodi startup

(Just like there are "Update Library", "Library update frequency" and "Library Delay on startup")

Thanks.

**Comment by burekas7** [comment]
Hi,
Is there any new about this?
Currently, I need to use the manual search every time because the TV Shows from Trakt lists have stopped showing new content of new episodes.

**Comment by scakemyer** [comment]
Mentioned the caching issue in #633, you could also just clear your cache manually for now.

**Comment by burekas7** [comment]
Thanks it helped.
Do I need to do it each time or is it kind of a known bug which will be fixed later?

**Comment by scakemyer** [comment]
It'll get fixed sooner than later, probably for next release since it really shouldn't be doing that.

**Comment by burekas7** [comment]
Hi,

There is still glitches when episodes are not updated in Trakt lists (My Collection)
Also after clear cache.

Version 0.9.69

**Comment by burekas7** [comment]
@scakemyer 
It seems that the update problem is with one tv show (The 100)
How can I force it to update? (I already tried Clear cache and Update Library)
* I check it my trakt collection in the addon (Not in kodi library)

Log:
http://pastebin.com/i04dJAcE

Focused on:
```
23:33:46 T:13224  NOTICE: [plugin.video.quasar] [GIN] 2017/02/13 - 23:33:46 | 200 [0m|    972.3947ms | ::1 |  [0m GET     /shows/trakt/collection
23:33:49 T:13224  NOTICE: [plugin.video.quasar] [GIN] 2017/02/13 - 23:33:49 | 200 [0m|      1.0074ms | ::1 |  [0m GET     /show/48866/seasons
23:33:51 T:13224  NOTICE: [plugin.video.quasar] [GIN] 2017/02/13 - 23:33:51 | 200 [0m|      18.086ms | ::1 |  [0m GET     /show/48866/season/4/episodes
```

**Comment by scakemyer** [comment]
Probably stale cache from *before* the caching refactor. Just remove `com.tmdb.show.48866.*`, or the whole folder if you really feel like waiting a few minutes after restarting Kodi.

**Comment by burekas7** [comment]
Thanks, now it's ok.
