### ISSUE TITLE
Some movies quasar is finding

### ISSUE THREAD

**Issue by xabier100** [scakemyer/plugin.video.quasar#648]
I some movies and tv series quasar it stays finding all the time.
I fix this problem selecting other movies. Then qusar start buffering correctly. And then I selected again the movie that I want to see.
I would like to rewiev this problem and repair 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version Kodi 16.1 Jarvis):
* Operating System and version (Android 4.4.4):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by scakemyer** [comment]
No logs and most probably a provider issue, sorry.
