### ISSUE TITLE
Import to library - Specials get mixed in the season

### ISSUE THREAD

**Issue by peer23peer** [scakemyer/plugin.video.quasar#65]
When importing shows into the library specials S00-### episodes gets mixed up with S01 episodes. All the S## are special episodes

![image](https://cloud.githubusercontent.com/assets/8535734/12809656/0c797c16-cb21-11e5-92e9-b98f7556192d.png)

**Comment by i96751414** [comment]
That's a Kodi bug, unfortunately...

**Comment by nix87** [comment]
At my Kodi specials are seperate from seasons? I have e.g. folders for s1,s2, s (specials).

**Comment by i96751414** [comment]
When there's only S1 and Specials Kodi won't seperate them. Whend there are more than 1 seasons (S1, S2, ...) Kodi will separate them.
