### ISSUE TITLE
Adding invalid magnet links and torrent files cause crash

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#654]
This bug occurs all the time (at least with me). Select a movie, search providers, find results, select a fault one and then Quasar crashes right away.

**Comment by scakemyer** [comment]
Please, same rules apply, no issues about providers here.

**Comment by scakemyer** [comment]
Take them to https://bitbucket.org/scakemyer/script.quasar.burst

**Comment by scakemyer** [comment]
This is actually a known Quasar bug, I've already got two `// FIXME` lines about this in the daemon... We need to validate magnet links and torrent files before feeding them to libtorrent to prevent this.
