### ISSUE TITLE
Crash on Krypton RC3 when trying to play anything

### ISSUE THREAD

**Issue by luispabon** [scakemyer/plugin.video.quasar#655]
http://pastebin.com/1EwwPiaz

Using v0.9.57 with Magnetic providers.

Clicking on any film results on that - in this case, Moana from the Most Popular category, although it happens on any film.

This is on a fresh Krypton installation.
 
Windows 10 Pro, Kodi 17.0 RC3.

**Comment by luispabon** [comment]
Went away after I opened up Kodi to remote control (for yatse) - I imagine that's needed to make it work!

**Comment by scakemyer** [comment]
Yes, says so right on the first page ;) Thanks for closing the issue yourself, much appreciated.
