### ISSUE TITLE
Adding torrent files from URL via web interface does not work

### ISSUE THREAD

**Issue by pitsi** [scakemyer/plugin.video.quasar#659]
After today's update to version 0.9.58, torrents can not be added through quasar's web interface, either in the form of a magnet link or a torrent url. It fails with this message

![screenshot_5](https://cloud.githubusercontent.com/assets/5880037/22183325/127f6e72-e0c4-11e6-874e-9e5c7d7a9402.jpg)

Loading a torrent stored locally, through quasar > add torrent > file, works like it should. 
The above was only tested on my pi zero, thus no log. I will test it on my main pc (64bit linux with kodi 16.1) later on and report if it happens there too.

**Comment by scakemyer** [comment]
Tried reloading the page? Web UI works perfectly...

**Comment by pitsi** [comment]
The web ui does work, adding a torrent through it does not work. Also tried reloading kodi and restarting the pi zero altogether.

**Comment by pitsi** [comment]
Forgot to mention that the pi zero runs libreelec 7.0.3 (kodi 16.1).

**Comment by pitsi** [comment]
Same thing on my pc (kodi 16.1 on debian testing x64) and on my openelec (kodi 14.2, the last 32bit version of openelec). All the above were installed from the zip file that is related to their architecture.

As promised. this is the log from the pc installation. Run kodi, opened quasar's web interface in the browser, loaded a magnet link and nothing happened.

http://paste.debian.net/910006/

**Comment by scakemyer** [comment]
Something's wrong with your networking setup, and it has nothing to do with the latest update to the UI where I merely added a "Made with :heart:" mention at the bottom... All I can see in there is that libtorrent is also not happy with it:
```
listen_failed_alert: listening on 0.0.0.0 : 0.0.0.0:6881 failed: [open] [TCP] Address family not supported by protocol
```

**Comment by Argotera** [comment]
I have the same problem using 0.9.58 in an MM android platform.
If I roll back to 0.9.57 it works fine. I can try to upload a log if needed.
and by the way:

Scakemyer, thanks for all of your contributions!

**Comment by pitsi** [comment]
All my devices are properly connected to the network and the same applies when the above were run. All plugins, including quasar as I describe above, had access to the network and on the internet properly. And their connectivity can be - and was - checked on settings > system information inside kodi, They all have or get ips as 192.168.1.x and the rest. Double checked via ssh on the *elecs running ifconfig.

The pc (wired, static ip) and the openelec (wireless, static ip) were tested on the same network, while the pi zero (wireless, dhcp) was at a friend's. The only thing they had in common was that I reached their quasars' web incerfaces via chrome (on windows) and chromium (on linux). 

It is really hard to get the log from the *elecs, because I can access only certain folders via samba and the one that the log is is not shared via it, so using my pc was the easiest solution. So, the quasar's web interface was accessed from a browser on the same pc that was running kodi. So, I used "localhost:65251/web" to get there instead of "192.168.1.2:65251/web". So I guess that is what makes the "0.0.0.0 " thing appear on the log.

I will try some other browser later on and try to get the log of the openelec somehow.

**Comment by pitsi** [comment]
New log from my openelec (192.168.1.3) while connected to the quasar's web interface from a laptop (192.168.1.101) through firefox on windows 7

http://paste.debian.net/910074/

**Comment by scakemyer** [comment]
So basically both logs show the UI is served as it should, first log only showed a hit on `/web/`, the second got requests for all assets too, but that's about it... So logs of actually adding a torrent would've been more appropriate. Either way, magnet links are working just fine but can confirm torrent files from URLs are failing, but never with that error screen from the UI. If that's really what you get each time it's the console logs from your browser that I'll need.

**Comment by pitsi** [comment]
I have no idea what the logs really show. All logs were retrieved and posted after a torrent or a magnet url was added. If they show nothing, then they are not verbose enough I guess...
 
And the problem appears with magnet urls too, not just torrent files. The "good" thing with torrent files is that you get to see the message on the screenshot I posted above, mentioning that something is wrong. With magnet urls this message does not appear at all.

How can I see the browser logs that you mention?

**Comment by scakemyer** [comment]
<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>J</kbd>

**Comment by Argotera** [comment]
Still having the same problem in 0.9.59.

This is a console log. I had to google to find out what that was, so I hope it includes the needed info

This is from firefox 0.9.57

http://paste.debian.net/910196

this is from ff 0.959

http://paste.debian.net/910195

**Comment by scakemyer** [comment]
Should all be fixed in v0.9.60, thanks to those logs.

**Comment by pitsi** [comment]
It seems a lot happened while I was sleeping :|
Wow guys! Thanks a lot. It's a pleasure working with devs/maintainers/reporters like you :)

**Comment by scakemyer** [comment]
I'll take it, thanks ;)

**Comment by Argotera** [comment]
And it works! Thank you scakemyer!
