### ISSUE TITLE
"One or more items failed to play" after initial buffering

### ISSUE THREAD

**Issue by atomtm** [scakemyer/plugin.video.quasar#66]
I get this error message for every video I am trying to play using Quasar. This happens immediately after the initial buffering has finished. Are there any settings I have to make on my Kodi? I am trying this on Amlogic Ambox (Android 4.4) . I works fine on rpi - openelec though.

**Comment by corrpel** [comment]
I have this issue when something else is playing (ex. music) and start a video using pulsar.

**Comment by nix87** [comment]
Try to pause a bit video and then press play and see what will happen?

**Comment by atomtm** [comment]
This happens before anything starts playing. After the buffering I get immediately this message.

**Comment by nix87** [comment]
Then there is something wrong with your installation or Kodi folder I don't know.

I can confirm that everything work like a charm after 0.9.3 update.

**Comment by atomtm** [comment]
Are there any configuration I have to make on the plugin.appreciate your feedback

**Comment by atomtm** [comment]
Here is my log file if this might help : http://xbmclogs.com/p0h3zbm0k

**Comment by scakemyer** [comment]
There's no crash or anything here, just a timeout on Kodi's side. Try removing a few add-ons to speed things up. This error shows up from other add-ons and can really slow things down:
```
CPythonInvoker(34): Script invoked without an addon. Adding all addon modules installed to python path as fallback. This behaviour will be removed in future version.
```

**Comment by atomtm** [comment]
Ok I will try and disable most of them and try this again !

**Comment by scakemyer** [comment]
Let me know how that goes, if there's still a problem we can reopen this :)

**Comment by atomtm** [comment]
Sorry didn't see your comment. I have disabled most of the addons , but the problem persists. 
Is there anything else I can try ? I have thought to do a fresh install on kodi and see how that goes . I am really interested in using your addon , so any suggestions are appreciated.
Thank you !

**Comment by atomtm** [comment]
I have used "Fresh start addon" to get a fresh kodi system , installed quasar (0.9.11) using tvaddons added "quasar kickass provider" but the problem persists. Please let me know if you need more info.
Thank you !

**Comment by atomtm** [comment]
Is there any update to my issue?

**Comment by makruiten** [comment]
I have exactly the same error on two different Raspberry Pi devices with OpenELEC installed. It buffers until complete, but then throws an error before playing.

**Comment by aspyropoulos** [comment]
I have the same issue as @makruiten. Windows 7 machine.

**Comment by aspyropoulos** [comment]
Finally all good from my side had to restart kodi. Everything works fine now.
