### ISSUE TITLE
Manual Search is slower then a regular search

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#661]
1) When I'm doing a manual search from the main menu it seems to takes longer then searching directly from the list's items.

2) In addition to (1), Why when I got a timeout due to one of the providers, it still doesn't show the results from all the rest?

In order to reproduce it I did manual search for: Colony S02E02

* From the log the problematic provider was RARBG (Which didn't do any problem when searching directly)
* Using the new addon "Burst" (0.3.0)
* Timeout is set for 20 sec
* Set 9 providers: YTS, RARBG, 1337x, TorLock, MagnetDL, BTjunkie, idope, EZTV, Zooqle
* Quasar Version: 0.9.58
* Kodi 16.1
* Win 10, 64bit

Kodi Logs:
(Both searches for the same content: Colony S02E02)
* The Manual Search (with the timeout issue) >>> http://pastebin.com/fQDpCEd2
* Standard search (Directly from Trakt list, without timeout) >>> http://pastebin.com/GF0FwZ0j

Thanks.

**Comment by scakemyer** [comment]
No issues about providers here.

**Comment by burekas7** [comment]
Where can I discuss about this?

**Comment by scakemyer** [comment]
Look in the addon.xml ...
