### ISSUE TITLE
Quasar causes Kodi to restart all the time

### ISSUE THREAD

**Issue by bpasero** [scakemyer/plugin.video.quasar#664]
I just did a fresh Kodi 16.2 install with a fresh Quasar install and the new repository manager (Burst? forgot the name). Anyway, when I access Quasars settings (Advanced), Kodi decides to restart.

**Comment by scakemyer** [comment]
Try that again by filing the issue template and providing logs.

**Comment by bpasero** [comment]
@scakemyer good point, where does Quasar log to?

**Comment by scakemyer** [comment]
Same place as everything else, see http://kodi.wiki/view/Log_file/Easy or http://kodi.wiki/view/Log_file/Advanced#Location for a specific answer to your question

**Comment by raulcano** [comment]
Hi guys, I had the same problem and reported here:
https://github.com/scakemyer/plugin.video.quasar/issues/698
