### ISSUE TITLE
[Request] priority min seeds min filesize

### ISSUE THREAD

**Issue by corrpel** [scakemyer/plugin.video.quasar#666]
Hi,
It would be awesome to sort by min seed and file size.
How i have Quasar configured:
Two providers.
Provider 2: minimum file size 4GB - maximum 1 download
Provider 1: minimum file size 0.5GB - maximum file size 4GB maximum - 5 downloads
When searching, it uses the files from Provider 1 first since there are more seeders.
But provider 2 have enough seeders and the quality is much better.
So, it would be great to pick 4GB+ file if seeds >=50 for example, else fail back to default.
Maybe should be included and editable min seeds and file size as priority.
What do you think?

**Comment by scakemyer** [comment]
File size is not a reliable metric to sort with, providers may or may not return it, and it's an arbitrary string with any kind of suffix. Use the Balanced mode of sorting with your preference of Resolution and tune the % of seeders required to choose the fallback resolution.
