### ISSUE TITLE
0.9.60 update failed on rpi3

### ISSUE THREAD

**Issue by lollo78** [scakemyer/plugin.video.quasar#667]
Hi, the update to 0.9.60 broken my Quasar installation on LibreElec and Raspberry Pi 3.
The update failed from the official repo.

**Comment by lollo78** [comment]
Sorry, maybe an issue of my sd overclock configuration. With the default config the add-on is updated.

**Comment by scakemyer** [comment]
Good to hear, thanks for closing the issue yourself :)
