### ISSUE TITLE
Library Integration: Issue when adding TVshows to kodi library

### ISSUE THREAD

**Issue by Airbox79** [scakemyer/plugin.video.quasar#67]
Bug report:
Within Quasar and when adding a TVShow, strm files are generated within the directory set via the library path in the configuration, but sometimes not, expecially when you add several shows in a row. This leads to that the show is added to kodi library but doesn't have any seasons or episodes in them.

Noted in Quasar versions:
0.9.1-beta2
0.9.4

**Comment by nix87** [comment]
This is old problem which is fixed after 0.9.3 release.

And how you succedd to add sveral shows in a row. You can add just one by one with Quasar?

**Comment by Airbox79** [comment]
Yes, in a sequential matter, not parallel.

**Comment by eskape** [comment]
Thanks! 

Does pulsar automatically update the library with new shows?
I've tried the Favourites Subscription addon. But it does not play. 
It uses plugin://plugin.video.pulsar/show/80379/season/9/episode/14/links

**Comment by i96751414** [comment]
Yes
