### ISSUE TITLE
[Bug] Kodi crashes on startup

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#670]
In the last period, my kodi has began to crash after ~20-30 seconds after it starts.
I didn't found something special in the logs, but I assume that it could be related to Quasar.

## Expected Behavior
Kodi not supposed to crash on startup.
And it actually never crashed like that before.
Sometimes it does work without crashing, but it's very not stable on each time I'm starting Kodi.

## Current Behavior
In the last period, my Kodi has began to crash after ~20-30 seconds after it start.

## Possible Solution
I didn't found something special in the logs, but I assume that it could be related to Quasar.

## Steps to Reproduce (for bugs)
1. Just turn on kodi.
2. Waiting ~30-60 seconds (Basically ~10 seconds after quasar.exe is starting)
3. Error message - kodi crashed, close it etc...

## Your Environment
* Version used: 0.9.60 (But it happened also before, I don't remember on which version it started)
* Burst 0.3.1
* Environment name and version: Kodi 16.1
* Operating System and version: Win 10, 64 bit
* Link to Kodi debug log:
Crash log (Lite): http://pastebin.com/0x2kVXrJ
Crash log (Debug): http://pastebin.com/Q0DFvZgn
Crash log 2 (Lite): http://pastebin.com/3dqrRQ8B
Crash log 2 (Debug): http://pastebin.com/4GRnXr1K

NOTE: If you think it's not a Quasar problem, please tell me.
Thanks.

**Comment by scakemyer** [comment]
You'll have to try a fresh install of Kodi or even Windows itself, because so far this doesn't look related to Quasar at all. Will re-open if there really is something here, but please stop blaming Quasar for every ill your Windows boxes experience; it's just a fully open-source golang program wrapped in a Kodi add-on and not some magical overlord of your system...

**Comment by burekas7** [comment]
The last thing I want is to automatic blame Quasar which is the best addon ever that has been made for kodi.
I have made a lot of tests in trying to eliminate things such as skin issues, other repos, addons etc.
After all it seems that it does relate to quasar, because when I removed Quasar & Burst & Repo, there is no crash.

More info about this strange crash:
I don't know why, but this happens at very specific case -
Once a day, at the first time after the PC is turned on, and during kodi startup.
* Just to mention, on the second time and so on, there wasn't any crash during the kodi startup (Even after killing the quasar.exe if needed)

Logs:
* **Without Quasar** installed - **Kodi doesn't crash**:
https://pastebin.com/03L0Tb28
* **With Quasar** installed - **Kodi crashes** when running on the **first** time in the day after PC turn on:
https://pastebin.com/zfVRdxjN
* Additional log when kodi crashed, same scenario:
https://pastebin.com/1MhCBTSF
* **With Quasar** installed - **Kodi doesn't crash** when running on the **second** time in the day after PC turn on.
https://pastebin.com/Pi10ieRF

What I have noticed from the logs is when it crashes only these lines exist:
```
11:10:25 T:9896  NOTICE: [plugin.video.quasar] INFO  repository   ? fetchChangelog   Fetching add-on changelog for plugin.video.quasar...
11:10:25 T:9896  NOTICE: [plugin.video.quasar] INFO  repository   ? fetchChangelog   Fetching add-on changelog for script.quasar.burst...
```

But on the second running and on (when it doesn't crash), there are also answers:
```
20:38:05 T:10556  NOTICE: [plugin.video.quasar] INFO  repository   ? fetchChangelog   Fetching add-on changelog for plugin.video.quasar...
20:38:05 T:10556  NOTICE: [plugin.video.quasar] INFO  repository   ? fetchChangelog   Fetching add-on changelog for script.quasar.burst...
```
```
20:38:08 T:10556  NOTICE: [plugin.video.quasar] INFO  repository   ? GetAddonsXMLChecksum  Last available release of plugin.video.quasar: v0.9.78
20:38:08 T:10556  NOTICE: [plugin.video.quasar] INFO  repository   ? GetAddonsXMLChecksum  Last available release of script.quasar.burst: v0.5.10
20:38:08 T:10556  NOTICE: [plugin.video.quasar] [GIN] 2017/04/19 - 20:38:08 | 200 [0m|    4.3567141s | ::1 |  [0m GET     /repository/scakemyer/plugin.video.quasar/addons.xml.md5
```
I don't know if this is connected to the problem but just something I noticed.


Quasar 0.9.78 (But it started long time ago)
Burst 0.5.10
Quasar Repo 0.9.78
Skin Confluence
Kodi 16.1
Windows 10, 64 bit

**Comment by scakemyer** [comment]
The issue here is most probably related to the shaky SSL support in Kodi 16, where simply requesting https URLs that use newer certificates crashes the Python interpreter in Kodi. I'd have to find other references to that issue to back this up, but the simple solution is to upgrade to Kodi 17; having bad SSL support is pretty dangerous by itself and should be enough to convince anyone to upgrade for that reason alone.

**Comment by burekas7** [comment]
OK, thanks. But if so, why Kodi doesn't crash on each startup?
It crashes only once a day after my PC is on, and from the next opening and on, it doesn't crash anymore. Why?
Is there any special process that Quasar does only once a day or something?
