### ISSUE TITLE
[request] improvement for --- 0.3.2

### ISSUE THREAD

**Issue by lollo78** [scakemyer/plugin.video.quasar#674]
---

**Comment by scakemyer** [comment]
Last warning for posting here about providers.

**Comment by lollo78** [comment]
I'm really sorry, now I got it why you close it.
Really, really sorry. :*

**Comment by scakemyer** [comment]
Thanks, you're lucky you have enough activity on your GitHub profile to not look like a sockpuppet account.

**Comment by lollo78** [comment]
XD
