### ISSUE TITLE
Kubuntu 14.04 - Kodi 16 - Latest Quasar Crashing After Installation

### ISSUE THREAD

**Issue by lukescotney** [scakemyer/plugin.video.quasar#677]
Hi there, I've used Quasar plenty and it's worked on my Mac, Windows, Android and Ubuntu set ups however trying to set it up on Kubuntu has proven difficult for me. I've installed use the large ZIP file and the stand-alone Linux_x64 too and both builds give the same result.

It use to crash straight after installation but following #45 I was able to get further. But now after installation the daemon starts, I get the notification about library paths and a few seconds after that it all crashes and reboots again. 

I've tried to set the library path after the crashing has aborted itself and I can just go into the settings manually. But the crashing persists just without the library notification.

Kodi 16
Kubuntu 14.04

Log:
http://paste.ubuntu.com/23890797/

**Comment by scakemyer** [comment]
There'll be a fix in 0.9.62 for those crashes in jsonrpc.go, but before then, do you have both remote control options enabled in Kodi? As a sidenote, you really should upgrade that kubuntu box to 16.04; LTS from Canonical != LTS from bleeding edge programs like Quasar.

**Comment by lukescotney** [comment]
Shit. That's an oversight. Enabled them now and it's going good now!

I did start with 16.04 but I was getting problem after problem from fresh installs. Networking, Graphics, Sounds it all fucked up one way or another and then intermittent boot up problems every time I fixed something. But yeah it's all fixed now man - thanks for the support!
