### ISSUE TITLE
Provider issue: MC Kickass v1.0 for Quasar

### ISSUE THREAD

**Issue by Airbox79** [scakemyer/plugin.video.quasar#68]
Bug Report:
Example, you choose a TV episode within Kodi (library integrated = not tested from within Quasar) and get a choose stream dialog up (so far so good), but when you choose one of the files to stream, Quasar starts to buffer / download (stream) another file than the choosen one (the file size is incorrect), so you actually have stop the stream, and choose again in blindness to get the stream you actually want to look at. I have no idea if this is a Quasar or a provider problem when it comes to sorting and getting the right input from the dialog. Maybe both the Quasar team and MC need to check on this? 

Versions that this issue has been seen:
MC Kickass for Pulsar v3.0.11 & Pulsar v0.7.1 (i9)
MC Kickass for Quasar v1.0.0 & Quasar v0.9.1
MC Kickass for Quasar v1.0.0 & Quasar v0.9.4

Thanks!

Best regards
AirBox

**Comment by scakemyer** [comment]
Sorry but can't help you regarding providers.

**Comment by Airbox79** [comment]
Ok, I have moved the issue to mancuniancols github, and we will see.

Thanks that you looked at the problem, scakemyer!

Best regards
AirBox
