### ISSUE TITLE
Quasar Crashing Nvidia Shield TV with Panic Error.

### ISSUE THREAD

**Issue by compyy** [scakemyer/plugin.video.quasar#680]
## Expected Behavior
Should run fine.

## Current Behavior
Crashes as soon as it starts.

## Possible Solution
couldnt find any, there is another issue opened as 544  but these errors are different than those errors reported in that issue.

## Steps to Reproduce (for bugs)
1. Install Quasar on Latest Kodi 17 RC4 on Android Shield TV Running Android 7.0

Logs:
http://paste.ubuntu.com/23895188/

**Comment by scakemyer** [comment]
See #673 and #679, I'll be releasing v0.9.62 in a few hours at most and it should hopefully take care of those.
