### ISSUE TITLE
tracker_error_alert in 0.9.62 on RPi3

### ISSUE THREAD

**Issue by sharron2** [scakemyer/plugin.video.quasar#681]
Hello! Awesome plugin here. Thanks for all of your hard work.

I am seeing an issue that is preventing all torrent playback on RPi3 on version 0.9.62.  I have tried this with many torrents and all fail with the same error. Note this used to work on the same setup.  On the Kodi UI the torrent just says Finding (0.00%) until it finally times out.

I am testing this with a known working torrent for magnet link for the publicly available ...: 

~~Log Below.~~

**Comment by sharron2** [comment]
Note, I did try an uninstall and reinstall of the quasar client and rebooted etc. Thanks again!

**Comment by scakemyer** [comment]
There's just not enough peers and/or working trackers for what you're looking for, try private trackers. And don't post magnet links and torrent links here, ever. This is your one and only warning.

**Comment by eidermar** [comment]
hmm, not sure. With the last update quasar caused an infinite update loop. after de-installing and re-installing quasar and burst manually, I'm having the same problems with any torrent. burst finds the torrents and no matter which ones I choose quasar will be stuck on "finding" until it eventually times out. I quickly tested the torrents outside of quasar and they were working. I'm not at home at the moment so I cannot offer logs right now. I will provide them as soon as I'm with my machine again.  Ubuntu 16 / Intel NUC. Until today everything was working fine - no changes to the setup whatsoever.

**Comment by herrwusel** [comment]
I can confirm that quasar is stuck on finding (the same torrent is working on my other pc which is in the same network with the same vpn - tried it with vpn off as well). I have the problem since today. My kodi machine is an intel nuc with the latest libreelec beta. 

https://paste.ubuntu.com/23900205/

**Comment by scakemyer** [comment]
I'll go back a few commits of libtorrent on its RC_1_1 branch for 0.9.63, at least until 1.1.2 gets released with the proxy fix. I have yet to find a torrent that gets stuck in Finding state on the rpi3 I can test with, so this is obviously a mixed bag, and there are other connectivity errors in that log @herrwusel which make me doubt it's solely libtorrent that's acting up.

**Comment by scakemyer** [comment]
See solution in #683 until v0.9.63 gets released.
