### ISSUE TITLE
Finding (0.00%)

### ISSUE THREAD

**Issue by ieswideopen** [scakemyer/plugin.video.quasar#683]
Since the last updated my Minix Neo U1 just times out after a few minutes finding no sources.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by ieswideopen** [comment]
Android 5.1, Kodi 16.1

**Comment by ieswideopen** [comment]
I fixed it. I had to play around in the bittorent settings.

**Comment by scakemyer** [comment]
Mind telling us what it was that fixed for you? Folks in #681 might like to hear it, and so do I.

**Comment by ieswideopen** [comment]
I just had to set a connection number, which I set at 50. It's been so long that I've had quasar working, it's worked fine for years,  that I don't recall having to do this before the last update. But I really can't remember.

**Comment by scakemyer** [comment]
Ha, that really sheds some light on the issue. There was 1 commit in the RC_1_1 branch we're using about that, removing a hard-set limit, which must have caused this bug in libtorrent.

Just double-checked and with no connections limit set, torrents do get stuck on Finding... As mentioned in the other issue I'll revert libtorrent to a fixed commit until 1.1.2 gets released.

**Comment by ieswideopen** [comment]
Glad that it helped, and I'm especially glad you know what you're talking about.

**Comment by thatguy93** [comment]
I just made an account to THANK ieswideopen!! this fixed my issue with torrents stuck on finding in last month , i didnt want to post here because i thought its providers fault but guess not. THANK YOU AGAIN!

**Comment by scakemyer** [comment]
Wait... you've had that issue for a month? Reverting just before that commit fixed it over here...

**Comment by thatguy93** [comment]
I spoke too soon, it fixed btjunkie provider but TorrentDownloads,GloTorrents are still not working and Zooqle provider shows theres not enough space on the download path even though the file is 2 gb and i have 9 gb free space

**Comment by thatguy93** [comment]
And YTS also not working, sorry if im not allowed to post this here

**Comment by scakemyer** [comment]
Thank you for ruining this issue with providers...
