### ISSUE TITLE
Quasar daemon keeps Crashing - issue with gzip

### ISSUE THREAD

**Issue by lafayetteduarte** [scakemyer/plugin.video.quasar#685]
Hi. 
After upgrading the add-on the service keeps crashing.
sometimes causing the openelec to restart.
Can you help?

Thank you
Here are the log info:

23:07:06  21.027714 T:1540703136  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0mVersion: v0.9.62 Go: go1.8rc3
23:07:06  21.028753 T:1540703136  NOTICE: [plugin.video.quasar] INFO  config       ▶ Reload           [0mReloading configuration...
23:07:06  21.178101 T:1540703136  NOTICE: [plugin.video.quasar] INFO  main         ▶ main             [0mAddon: plugin.video.quasar v0.9.62

Found 2 stack traces reporting null references:
1) This one , aparently trying to update the library:

23:15:03 338.978699 T:1427903392  NOTICE: deleting video codec
23:15:03 338.989746 T:1591358368  NOTICE: [plugin.video.quasar] [31mERRO  xbmc         ▶ VideoLibraryGetShows  [0minvalid error <nil>
23:15:03 338.992950 T:1591358368  NOTICE: [plugin.video.quasar] panic: runtime error: invalid memory address or nil pointer dereference
23:15:03 338.993927 T:1591358368  NOTICE: [plugin.video.quasar] [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5783d0]
23:15:03 338.994537 T:1591358368  NOTICE: [plugin.video.quasar]
23:15:03 338.995148 T:1591358368  NOTICE: [plugin.video.quasar] goroutine 70 [running]:
23:15:03 338.995819 T:1591358368  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.updateLibraryShows()
23:15:03 338.996490 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:143 +0x38
23:15:03 339.016327 T:1591358368  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.LibraryUpdate.func2()
23:15:03 339.017334 T:1441788832   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
23:15:03 339.017517 T:1441788832   ERROR: CCurlFile::Open failed with code 0 for http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml.md5
23:15:03 339.017731 T:1441788832   ERROR: Open - failed to open source <http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml.md5>
23:15:03 339.017853 T:1441788832   ERROR: CRepositoryUpdateJob[repository.quasar] failed read checksum for directory 'http://localhost:65251/repository/scakemyer/plugin.video.quasar/addons.xml'
23:15:03 339.022247 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:987 +0x2c
23:15:03 339.025360 T:1591358368  NOTICE: [plugin.video.quasar] System information: linux_armv7 4.4.41
23:15:03 339.026062 T:1591358368  NOTICE: [plugin.video.quasar] Kodi build version: 16.1 Git:ce88c8c
23:15:03 339.026550 T:1591358368  NOTICE: [plugin.video.quasar] OS type: Linux
23:15:03 339.027313 T:1591358368  NOTICE: [plugin.video.quasar] uname: ('Linux', 'OpenELEC', '4.4.41', '#1 SMP Wed Jan 11 15:08:33 CET 2017', 'armv7l', '')
23:15:03 339.795807 T:1963778048  NOTICE: CDVDPlayer::CloseFile()
23:15:03 339.795990 T:1963778048  NOTICE: DVDPlayer: waiting for threads to exit
23:15:03 339.796051 T:1963778048  NOTICE: DVDPlayer: finished waiting
23:15:03 339.808105 T:1963778048  NOTICE: CDVDPlayer::CloseFile()
23:15:03 339.808289 T:1963778048  NOTICE: DVDPlayer: waiting for threads to exit
23:15:03 339.808350 T:1963778048  NOTICE: DVDPlayer: finished waiting

2) Something wrong with cache data? tried cleaning the cache using the UI. no luck.

23:20:12 648.072998 T:1591358368  NOTICE: [plugin.video.quasar] [33mWARN  library      ▶ isDuplicateEpisode  [0mNo external IDs found for S00E38 (1402)
23:20:12 648.075500 T:1591358368  NOTICE: [plugin.video.quasar] [33mWARN  library      ▶ writeShowStrm    [0m/storage/.kodi/userdata/addon_data/plugin.video.quasar/Shows/The Walking Dead (2010)/The Walking Dead (2010) S00E38.strm already exists, skipping
23:20:13 649.029846 T:1591358368  NOTICE: [plugin.video.quasar] panic: runtime error: invalid memory address or nil pointer dereference
23:20:13 649.031067 T:1591358368  NOTICE: [plugin.video.quasar] [signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x29b25c]
23:20:13 649.031799 T:1591358368  NOTICE: [plugin.video.quasar]
23:20:13 649.032471 T:1591358368  NOTICE: [plugin.video.quasar] goroutine 73 [running]:
23:20:13 649.033142 T:1591358368  NOTICE: [plugin.video.quasar] compress/gzip.(*Reader).Close(0x0, 0xcfd750, 0x56c40028)
23:20:13 649.034119 T:1591358368  NOTICE: [plugin.video.quasar] 	/usr/local/go/src/compress/gzip/gunzip.go:292 +0x14
23:20:13 649.035156 T:1591358368  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/cache.(*FileStore).Get(0x56c405c0, 0x57df3100, 0x19, 0x876708, 0x56c405b0, 0xcfd750, 0x56c40028)
23:20:13 649.036072 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/cache/filestore.go:71 +0x364
23:20:13 649.037109 T:1591358368  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/tmdb.GetSeason(0x57a, 0x6, 0x937780, 0x2, 0xc45ea880)
23:20:13 649.038086 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/tmdb/season.go:19 +0x184
23:20:13 649.039001 T:1591358368  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.writeShowStrm(0x56e1a4d8, 0x4, 0x0, 0x876398, 0x56e4e4c0, 0x0)
23:20:13 649.039978 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:668 +0x2fc
23:20:13 649.040955 T:1591358368  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.doUpdateLibrary.func1(0x56c96200, 0x9603c4, 0x56c96200)
23:20:13 649.041870 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:381 +0x244
23:20:13 649.042664 T:1591358368  NOTICE: [plugin.video.quasar] github.com/boltdb/bolt.(*DB).View(0x56e96fc0, 0x9606dc, 0x0, 0x0)
23:20:13 649.043518 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/boltdb/bolt/db.go:629 +0x84
23:20:13 649.044434 T:1591358368  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.doUpdateLibrary(0x892aa0, 0x0)
23:20:13 649.045288 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:386 +0x3c
23:20:13 649.046082 T:1591358368  NOTICE: [plugin.video.quasar] github.com/scakemyer/quasar/api.LibraryUpdate.func5(0x12c)
23:20:13 649.047058 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:1092 +0x60
23:20:13 649.047852 T:1591358368  NOTICE: [plugin.video.quasar] created by github.com/scakemyer/quasar/api.LibraryUpdate
23:20:13 649.048645 T:1591358368  NOTICE: [plugin.video.quasar] 	/go/src/github.com/scakemyer/quasar/api/library.go:1100 +0x20c
23:20:13 649.061401 T:1591358368  NOTICE: [plugin.video.quasar] System information: linux_armv7 4.4.41
23:20:13 649.062012 T:1591358368  NOTICE: [plugin.video.quasar] Kodi build version: 16.1 Git:ce88c8c
23:20:13 649.062561 T:1591358368  NOTICE: [plugin.video.quasar] OS type: Linux
23:20:13 649.063110 T:1591358368  NOTICE: [plugin.video.quasar] uname: ('Linux', 'OpenELEC', '4.4.41', '#1 SMP Wed Jan 11 15:08:33 CET 2017', 'armv7l', '')

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by scakemyer** [comment]
Fixed in #684, please search closed issues next time...
