### ISSUE TITLE
[Request] Do Not Delete

### ISSUE THREAD

**Issue by compyy** [scakemyer/plugin.video.quasar#688]
Hello,

I have tried to find this feature in Quasar, couldnt find, may be you can help.

So here is what i want.

In my settings, i have disabled background download plus keep files after download, due to space limitation.

But sometimes i get into nasty situations.

1. I am watching a movie, i pause it for a break, dont touch the remote in a break, kodi screens times out, quasar is stopped by kodi and it deletes the file, then i have to download the file again :(.

2. I am watching a movie, in the middle i decide to stop and watch it later, i had to stop and it deletes the file again, i have to download it again.

Solution:

- There should be an option in Quasar like >>  "Ask to keep file when stopped" if someone enables that feature so whenever he stops or pause the movie, there should be an Radio button enable/disable which should confirm if to keep file or delete file.

I hope i could clear enough my request.

**Comment by scakemyer** [comment]
That was implemented 21 versions ago, as an "Ask to keep" setting, changed to "Ask to delete" in 0.9.50... Just look closer.

**Comment by compyy** [comment]
Hello,

Yes but its in reverse, you have to disable the setting to keep the files and then you can on the go can delete files once you watch it, but i was asking is the reverse.

**Comment by scakemyer** [comment]
You're the one thinking in reverse; you can't have both. If you don't want to lose the files, enable all options, background handling, keep the files and 'Ask to delete', and answer Yes to delete the files once you know you won't be streaming them again. That's it.
