### ISSUE TITLE
Feature request: Resume stream

### ISSUE THREAD

**Issue by Airbox79** [scakemyer/plugin.video.quasar#69]
I have mentioned this to i9 in the past, but it would be good to have a feature (if possible) in Quasar where it actually saves the stream in some way (either the torrent file or something else) and when you resumes a TV Show episode or a movie, it will start to stream from the last stream you used. If this feature is added, it will go faster to resume a movie / episode you have seen earlier and skip the choosing stream part since you almost always try to find the same stream as you had before.

Example from user point of view on how this would work in theory:
1. Click on the TV Episode
2. Choose Resume
3. A dialog shows up where you can choose to resume the same previous stream (showing its name) or to continue to the dialog with choosing streams from the configured providers.

It would be good if the last downloaded subtitle will be saved as well and used with the same stream, but if another stream is used, to remove the subtitle (so you don't pollute Kodi with a lot of crap files).

Thanks!

Best regards
Airbox

**Comment by nix87** [comment]
I think it's impossible to that with streams? 

The best you can is save file after watching at your system, then choose same stream like first one. In that way Quasar will recognize your already downloaded torrent and play like you play physical copy on your system and not like a stream where Quasar needs to download torrent.

**Comment by Airbox79** [comment]
Well, you can resume a stream by choice which mean that it forwards to the last position you looked at. Why can't this stream file info be saved? Doesn't sound impossible to me. However, I think we will let the developers of Quasar to judge this to see what's possible or not.

**Comment by dtsexpert** [comment]
@Airbox79 nix87 is trying to help here, instead of showing appreciation, I have show the attitute here.
This is the common sense question: without saving the file in advance, how could kodi play resume at 16th minutes of the show when then the file is still being download at the 1st 2 minutes (example of you stop the show at the 16th minute last play)

**Comment by Airbox79** [comment]
My best thanks, scakemyer! It will be cool to test this new feature when it comes in a future release!

All credz to you and i9 for all your efforts you put into this project in your free time! I know myself that this isn't easy when you have to combine this with the real life as well.

Best regards
AirBox
