### ISSUE TITLE
any support for ios

### ISSUE THREAD

**Issue by si458** [scakemyer/plugin.video.quasar#694]
looking back on old issues you said a year ago the wasnt any support for ios

will the ever be any support for ios?

im happy to help compile, as i can install the add-on without any issues on my iphone 7 ios 10

but it keeps saying 'unable to find binary'

**Comment by scakemyer** [comment]
That's because there's no binary for iOS yet. I'll look into it at some point, but it can easily take me over a week to get a new platform working. #452
