### ISSUE TITLE
[Request] Toggle for Quasar Notifications

### ISSUE THREAD

**Issue by lollo78** [scakemyer/plugin.video.quasar#695]
Hi scakemyer, just a little request.
Could you add a toogle switch in General settings to disable all Quasar notification (daemon on, bad request and so on that appear or could appear at kodi startup)?
Something like a "do not disturb" function...
Thank you very much for all the hard work.

**Comment by lollo78** [comment]
Thx a lot

**Comment by lollo78** [comment]
Just tried. Also with "Do not disturb mode" on, I still see Quasar message on startup.

**Comment by scakemyer** [comment]
It cuts the sound, that's it. I'm not doing anything more complicated than that, take it or leave it.

**Comment by lollo78** [comment]
I hope that in the next future, when Quasar will be more mature, and you will have more free time, you'll consider to add a system to hide also the text message. For now, thx as usual

**Comment by scakemyer** [comment]
Already considered it while implementing your request, and no, it's not a good idea to remove notifications completely. If there are some that you feel shouldn't show up we can discuss that, but hiding all of them won't happen, at v1.0 or v5.0.

**Comment by lollo78** [comment]
I can understand why for your dev point of view is not a bad idea to disable all the messages: some of them could help the user or you to identify issues and debug. But for an user point of view, all the addons that shown messages on startup (and there are a lot of add-ons that do that) is very frustrating. At any boot is a total "dong" sound of jingle concert and minutes of text message slideshows. My request was simply to give at each user the possibility to chose if leave the notifications or not. I'm really sorry if I bored you.

About the discuss: maybe you could group the notification "for purposes" and leave to the users the choice of which messages show or not by toogles like:

- Show information messages (like Quasar daemon is on...)
- Show error message (bad request...)
- Show prov. message (link not found...)
...

This is only my two cents. Of course you are the boss and all the decisions is yours.
Thx again for all 👍

**Comment by scakemyer** [comment]
This is all very reasonable. And I do agree the "bad request/status" notifications could be hidden, and if so, probably not from yet another setting; they could probably just be ignored already and show a warning in the logs instead.

I don't think hiding the daemon has started notification would do anyone a favor, we'd just end up with more users trying to open Quasar too soon after launching Kodi, and getting the new "Looks like Quasar is still starting up, give it a few seconds..." instead. And if we'd hide that one too, the user would just be clueless as to why he can't get into Quasar. So no, I'm not only seeing this from a dev point of you. And as much as grouping notifications into different types sounds like a good idea, the same principle applies to "No links founds" messages; not showing those would just leave the user clueless as to what is happening.

**Comment by lollo78** [comment]
I realized that there are a lot of dynamics that I simply ignored. What you wrote confirm that you are the only one who knows what kind of messages might be hidden or not. So if you think that other tweaks could be added to the "non disturbe" mode, you are welcome.
Really thanks, for all

**Comment by scakemyer** [comment]
Don't worry about it, and no, I'm not the only one that knows what should or shouldn't be shown as notifications; the discussion is a valid one either way, and as I said, I agree some notifications should probably be gone. Meanwhile the no-sound Do Not Disturb is the best compromise.
