### ISSUE TITLE
Add ordering to files list

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#697]
When I choose stream for a Season of a Show, I get list of files, and they are sometimes ordered, sometimes not. There is no reason NOT to sort file names in one torrent file. 
One more thing - if number of files in the torrent is equal to number of episodes, then switching to next episode can jump to the next file in the list. 
In perfect just select stream for a whole season and automatically preset stream+file for each episode.

## Expected Behavior

Files list in a stream should be ordered by name.

## Current Behavior

Files are randomly printed.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by scakemyer** [comment]
Let's leave the auto-next-episode for another issue, if you don't mind filing one with a description of how you think it should behave. Since I haven't really thought about that much, your idea of it would be helpful in fleshing out how to implement it.

**Comment by 5ay3h** [comment]
@scakemyer great work!
But, can you make the sort smarter (numbers aware)? 
For instance:
* `['e 01', 'e 10', 'e 2']` => `['e 01', 'e 2', 'e 10']`
* **NOT**: `['e 01', 'e 10', 'e 2']` => `['e 01', 'e 10', 'e 2']`

**Comment by scakemyer** [comment]
Thought about that, but it requires a lot more work and parsing, and the question is why are filenames in the same torrent named differently? So the immediate answer is no, it's not worth it. Cancel that torrent with inconsistent names in the first place and choose another one ;)

**Comment by elgatito** [comment]
Not seeing better way than add leading zeros to every number found in a file name, for example, making 5 digit number of any matched. Format of a file name should be the same within single torrent, so should not be any problem.

**Comment by 5ay3h** [comment]
> inconsistent names

Most files list torrents like tv shows, have numbers index prefix (season/episode) ; so by not taking numbers in account we can ruin the original desired order.

FYI, I can help code 🙂

**Comment by scakemyer** [comment]
You're missing the point. We don't need to extract and parse numbers to take them into account. It simply doesn't matter with proper prefixes for seasons and episodes. S01E10 will come after S01E02. The problem is, as I've stated with inconsistent names, where you'd have S01E2 and S01E10, which honestly doesn't happen very often, and if so, that torrent shouldn't be chosen anyway. So my point stands, you'd just be wasting time parsing numbers out of filenames.

**Comment by elgatito** [comment]
I'm jealous you have trackers that follow naming rules and so on. non-english world is not so good:)
My idea was to avoid any parsing and comparison with filenames, but rather do
filename -> filename_sort [where 'TTD_by_x17arch.s1e01.avi' would be transformed into 'TTD_by_x00017arch.s00001e00001.avi']

That would be enough to sort any kind of filenames.
