### ISSUE TITLE
Quasar Burst causes restart loop on Kodi

### ISSUE THREAD

**Issue by raulcano** [scakemyer/plugin.video.quasar#698]
## Expected Behavior
Kodi should not be restarting indefinitely in a loop (duh).

## Current Behavior
When the plugin Quasar Burst is installed, Kodi keeps restarting every 25 seconds or so.
Even if I disable Quasar Burst, this restart loops keep happening.
Only by de-installing Quasar Burst, this undesired behavior stops.

## Possible Solution
Since I don´t know where the problem lays, I can´t propose any meaningful solution.

## Steps to Reproduce (for bugs)
1. Install Quasar from zip file (plugin.video.quasar-0.9.65.linux_armv7.zip)
2. Once Quasar is installed, install Burst from the Quasar repository.
3. After a few seconds, the restart loop commences. The thing being restarted is Kodi and not the whole system, since I can access Openelec via SSH during these restarts.

## Context
Just trying to use Quasar as usual, with the new Quasar Burst addon.

## Your Environment
* Version used: Quasar 0.9.65, Quasar Burst 0.4.1
* Environment name and version: OpenELEC: 6.0.3
* Operating System and version: kernel: Linux 4.1.8
* Link to Kodi debug log: (see attachment)

[kodi.log.txt](https://github.com/scakemyer/plugin.video.quasar/files/752521/kodi.log.txt)

**Comment by raulcano** [comment]
The issue mentioned here seems to be the same:
https://github.com/scakemyer/plugin.video.quasar/issues/664

**Comment by scakemyer** [comment]
No issues about providers here, sorry. Thanks for taking the time to properly fill the issue template though. Please refer to Burst's readme for support.

**Comment by raulcano** [comment]
Ok, thanks for the quick answer. Can you please point me to the readme ?

**Comment by raulcano** [comment]
Ok, I imagine it is here: 
https://bitbucket.org/scakemyer/script.quasar.burst/src

**Comment by scakemyer** [comment]
In your case it's in `/storage/.kodi/addons/script.quasar.burst/README.md`
