### ISSUE TITLE
Error with quasar burst (TypeError: argument of type 'NoneType' is not iterable)

### ISSUE THREAD

**Issue by Kelso76** [scakemyer/plugin.video.quasar#700]
Hi! 
I'm new to Github and Quasar so i will try to do my best to do things according to what is asked.

I have this error in Quasar when selecting an episode or a movie. I know it's Quasar burst that give me this error as i see the icon. And Quasar give me the "no links found" notification.
I'm using the latest version of both. Made a clean install of Kodi and both Quasar addons. 
The platform i use is Xiaomi mi Box(Mdz 16 Ab), last firmware.
I guess you need a log file but i don't know how to find nor share it with you.
So if someone can help me with this i'll upload the log file.
Thanks for you help.

**Comment by meijin007** [comment]
logs?

**Comment by Kelso76** [comment]
As i said, i dont know how to do that.
Si if you or someone else van guide me through the process , i'd be more than happy to provide a log

**Comment by scakemyer** [comment]
No issues about providers here.
