### ISSUE TITLE
Not able to run binary if path has non-ascii chars

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#702]
When %APPDATA% path on Windows has non-ascii chars addon cannot start binary. It is surely there, I see it, but path is "broken" when trying to get it.

You can see from the log that other plugins resolve path correctly. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Last from release (both x64 and x86)
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC): Kodi 17
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10): Windows 7 x64
* Link to Kodi debug log: http://paste.ubuntu.com/23939745/
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by elgatito** [comment]
I have tried running Kodi with portable (-p) to use userdata in program files.
Now getting another error with "unable to remove/copy destination path".
Log: http://paste.ubuntu.com/23940060/

Maybe somehow related to current issue because of "(x86)" in the path.

**Comment by scakemyer** [comment]
That (x86) is fine, it's your user name. Working on a fix. Note that you have two quasar processes running in that second log file, so exit Kodi, fire up Task Manager and kill the remaining processes.

**Comment by elgatito** [comment]
I confirm that is another issue.
I have uninstalled Kodi, reinstalled to C:\Incoming (well, got rid of any spaces in the path and so on), on clean install I change regional -> language, 
Then: Install latest Quasar from Zip, Installed latest Burst from zip.
What I've got: errors about remove/copy binary, but Quasar seems to work. Providers is empty.

**Comment by scakemyer** [comment]
I'll need you to test those fixes first; I don't want to commit this before knowing it actually works.
[plugin.video.quasar-0.9.66.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/754234/plugin.video.quasar-0.9.66.windows_x64.zip)

**Comment by elgatito** [comment]
Tried that zip. 
Getting another error from python now: http://paste.ubuntu.com/23940217/
This is running without "-p", with default %APPDATA%

**Comment by scakemyer** [comment]
Here's another try.. [plugin.video.quasar-0.9.66.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/754276/plugin.video.quasar-0.9.66.windows_x64.zip)

**Comment by elgatito** [comment]
Got another error with the latest: http://paste.ubuntu.com/23940298/

**Comment by scakemyer** [comment]
[plugin.video.quasar-0.9.66.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/754360/plugin.video.quasar-0.9.66.windows_x64.zip)

**Comment by elgatito** [comment]
New error: http://paste.ubuntu.com/23940357/

**Comment by scakemyer** [comment]
You still have two processes running, please fix that and keep an eye on it. Won't solve the last error but still..

**Comment by scakemyer** [comment]
[plugin.video.quasar-0.9.66.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/754440/plugin.video.quasar-0.9.66.windows_x64.zip)

**Comment by elgatito** [comment]
Tried twice with a reboot.
Before running installation there is no quasar executable.
Maybe it;s running twice, or there s some kind of compasion of path that thinks it needs binary move. Not sure.

After last error I see no quasar.exe running

http://paste.ubuntu.com/23940558/

**Comment by elgatito** [comment]
The very last version gives "binary not found" - http://paste.ubuntu.com/23940583/

**Comment by scakemyer** [comment]
Last try for today
[plugin.video.quasar-0.9.66.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/754515/plugin.video.quasar-0.9.66.windows_x64.zip)

**Comment by elgatito** [comment]
No luck. "Binary not found"
http://paste.ubuntu.com/23940732/

**Comment by honest1987** [comment]
Same here 

System: Android 7 (nvidia shield tv 2015)
Kodi: 17
Language: English

On startup a message saying "unable to find Quasar binary" shows up.
Restarting Kodi does not solve the problem.

**Comment by scakemyer** [comment]
@honest1987 I doubt this is the same issue, see other issues about Android 7.

**Comment by scakemyer** [comment]
@elgatito Here's another try
[plugin.video.quasar-0.9.66.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/755814/plugin.video.quasar-0.9.66.windows_x64.zip)

**Comment by elgatito** [comment]
No luck. Getting non-ascii errors: http://paste.ubuntu.com/23945956/
Tried last build and 0.9.67

**Comment by scakemyer** [comment]
You still have two processes running, in every log... We're getting there but you'll really have to fix that. So uninstall Quasar, restart Kodi, re-install it *once* and get some new, cleaned up logs ;)

**Comment by elgatito** [comment]
Interesting part that after installing quasar I don't see any of them in the log...

**Comment by scakemyer** [comment]
Any of them what?

**Comment by elgatito** [comment]
quasar.exe

**Comment by scakemyer** [comment]
You're not supposed to actually...

**Comment by elgatito** [comment]
I always did uninstall+restart, then install and copy-paste log.

Tried with uninstalling kodi, removing kodi home directory and install quasar. Same error.
http://paste.ubuntu.com/23945998/

**Comment by scakemyer** [comment]
Not the same error at all...
[plugin.video.quasar-0.9.67.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/756693/plugin.video.quasar-0.9.67.windows_x64.zip)

**Comment by elgatito** [comment]
Error: http://paste.ubuntu.com/23946013/

**Comment by scakemyer** [comment]
[plugin.video.quasar-0.9.67.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/756698/plugin.video.quasar-0.9.67.windows_x64.zip)

**Comment by elgatito** [comment]
Error: http://paste.ubuntu.com/23946027/

**Comment by scakemyer** [comment]
[plugin.video.quasar-0.9.67.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/756742/plugin.video.quasar-0.9.67.windows_x64.zip)

**Comment by elgatito** [comment]
Error: http://paste.ubuntu.com/23946143/

**Comment by scakemyer** [comment]
Last one, then this gets labelled as 'wontfix' and you fix it yourself. Otherwise Quasar will officially not support non-ascii characters in the binary path, at least on Windows and probably all platforms, because it's just f***ing insane to use non-ascii chars in paths in the place and expect everything to actually work.
[plugin.video.quasar-0.9.67.windows_x64.zip](https://github.com/scakemyer/plugin.video.quasar/files/756773/plugin.video.quasar-0.9.67.windows_x64.zip)

**Comment by scakemyer** [comment]
Relevant Python issue, also marked as "won't fix": https://bugs.python.org/issue19264

Looks like you'll have to wait for a Kodi version with Python 3.

**Comment by elgatito** [comment]
Okay. Last try did not succeed neither - http://paste.ubuntu.com/23946178/

I have tried running Kodi with portable mode ("-p"). It uses portable_data folder in the installation path.
Installed, started, then showed it could not update Quasar addon (there is an error in the log).

http://paste.ubuntu.com/23946196/

Burst could not be installed automatically, when installed manually from zip it does not appear in providers section.

http://paste.ubuntu.com/23946254/

If problem with Burst and "automatically updated" are not connected to this issue, then using portable mode would be a workaround.

The problem is not in profile name, but in Kodi, that forces using profile path in Windows.

**Comment by scakemyer** [comment]
So portable mode seems like a viable workaround. For the rest, you forgot to enable both remote control options: `No available JSON-RPC connection to Kodi`.

**Comment by elgatito** [comment]
Oh, sh*t. Sorry. Did so many reinstalls that forgot about remote options.

Tried once again with clean profile: http://paste.ubuntu.com/23946310/ 
Same notification from Quasar about automatic update. 
Installed Burst from Quasar repo, appeared in providers list, tested, works fine.
