### ISSUE TITLE
Enhancement: Preselect Episode in files list

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#705]
When user wants to watch an episode, and providers to season search, user gets list of files, when list is ordered by name preselected is the first one.
Here we can regexp for episode in the file name and preselect it.
Episodes usually come in this formats:
S01 E01
S01E01
1x01

So it can be something like:
/(^|\W)S{%.2d, season}\sE{%.2d, episode}\W/g
/(^|\W)S{%.2d, season}E{%.2d, episode}\W/g
/(^|\W){season}x{%.2d, episode}\W/g

Small enhancement will make it much easier when jumping through episodes.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by scakemyer** [comment]
> Some people, when confronted with a problem, think
“I know, I'll use regular expressions.”   Now they have two problems.

**Comment by elgatito** [comment]
Mostly - yes :)
That is to avoid trash in file names or when it's part of a title.

**Comment by scakemyer** [comment]
First file is already preselected, in both Jarvis and Krypton. If not you have a skin issue.

**Comment by elgatito** [comment]
I'm not talking about first episode. I've just taken examples with "01". 
I mean when I want to use any episode it fires up search for season+episode. Thus for some providers it is not possible to find episode itself, so it starts searching for an episode and that gives us a list of files for a whole season. So if I switch over episodes I will still get same list of files with episode being preselected.

**Comment by scakemyer** [comment]
That would be way to expensive, doing season+episode searches. Use what's implemented, ie. season searches for past seasons, and episode searches for current ones.

**Comment by elgatito** [comment]
That is why, now, if you add series to a library, play season or episode - it fires search for an episode, but if you use only burst as provider, with enabled trackers which do not have separate episodes, then you get no results at all. 
Legacy providers for that trackers did have 2nd, 3rd queries for episode search, that was a copy of season_search. That was the only way to find episode in a few countries...

**Comment by scakemyer** [comment]
Please, stop it about providers here.
