### ISSUE TITLE
When installing Quasar for the first time - the Quasar repo is disabled

### ISSUE THREAD

**Issue by meijin007** [scakemyer/plugin.video.quasar#706]
## Expected Behavior
1) install Quasar on the clean machine.
2) the Quasar repo is disabled. 

## Current Behavior
Quasar repo will be enabled by default

## Your Environment

* Version used: 0.9.66
* Kodi 17 RC3
* Windows/Raspberry Pi 3 with ArchLinux

**Comment by scakemyer** [comment]
Unless this changed in Krypton, are you sure you're not just skipping step 3 of the installation steps, ie. Restart Kodi?

**Comment by scakemyer** [comment]
Yep, that's a new Krypton thing... Will see if/how we can get around it.
