### ISSUE TITLE
[Bug] Add/Remove for Library/Collection/Watchlist doesn't change

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#709]
The menu items in the context menu doesn't change to "Remove..." after doing the "Add" operation (And the opposite)
Relates to: Library, Collection and Watchlist

## Current Behavior
1) After doing "Add to library", it doesn't change to "Remove from library"
2) Sometimes after doing "Remove from collection" or "Remove from watchlist" it doesn't update quickly to the options to "Add to..." (Probably due to Timeout exception)
3) After doing "Add to collection" or "Add to watchlist" it doesn't update to "Remove from..." unless I go up and back again even if there is no error in the log.

## Expected Behavior
1) After doing "Add to library", it should change to "Remove from library" (And the opposite)
2) After doing "Add/Remove Collection/Watchlist", it should change to "Remove/Add" respectively.

## Possible Solution
Regarding to number 2 it look like there is an Timeout exception, but I don't sure if it is the reason.

## Steps to Reproduce (for bugs)
For example: Movies -> Recently Released -> iBoy
(But maybe it happens it other locations/Movies)
- Add/Remove to/from library
- Add/Remove to/from collection
- Add/Remove to/from watchlist

## Your Environment
* Version used: 0.9.68
* Environment name and version: Kodi 16.1
* Operating System and version: Windows 10, 64bit

* Link to Kodi debug log:
http://pastebin.com/AEuaPUaL

**Comment by scakemyer** [comment]
Add/Remove to/from Collection and Watchlist will be fixed in the next release, a simple selective cache clearing issue. Add/Remove to/from library should be fine though, since we now rely on duplicate checking which doesn't use or require caching; but you do have to scan/clean the Kodi library for the change to take effect, and although we already clear the right caches after this, and pages get refreshed once scanning/cleaning is done, we sometimes don't get the notification fast enough from Kodi, so by the time the page gets refreshed, Quasar hasn't been able to update its view of the Kodi library. Going back and returning to the same page usually shows an updated context menu as you expect. I think we could however double-check our own DB for this, which would be really cheap to do, so I'll look into that to make sure it doesn't have any unintended side-effects.

**Comment by burekas7** [comment]
First, the Add/Remove To/From Collection&Watchlist are working good now (0.9.69), Thanks.

Regarding the Add/Remove to/from Library, basically I don't use it as library in my kodi,
I just checked if it adds/removes items to the Quasar libraries folders (Previously it worked)
So the 'Clean Library', or Going back and returning doesn't affect.
Currently as I said, it always shows "Add to library", and shows "already in library" if pressed.

What do you think about the solution of when opening the context menu, scanning the Quasar libraries folders and compare the item to them, so if the folder already exist change it to "Remove", and if not change it to "Add"?

**Comment by scakemyer** [comment]
No that's not how it should be done. Currently it uses the same duplicate checking methods the library uses, which are fast and cheap to use, but Quasar's view of the Kodi library has to be up to date. We already have the info in our own BoltDB so it'll just be a matter of checking that instead, or both; no need to do expensive folders comparisons.

**Comment by scakemyer** [comment]
Made a few tests with checking both our DB and regular duplicate checking, and it isn't much better, if anything it's even worse and inconsistent. So I'd leave the add/remove from library as it is and recommend to rescan/clean after adding or removing to get an updated context menu. At least what you see then reflects the actual state of what Quasar's view of the Kodi library is.

**Comment by burekas7** [comment]
As I said previously, I don't integrate Quasar with kodi library, so the rescan\clean doesn't change it and the context menu is always stuck on "Add".
The problem is that I can't do the "Remove" operation because it always on "Add Library", and it always tell me "already in library".
In some versions before it worked, after add an item to the library it changed to "Remove" and the item was add to the library folder, and the same with "Remove", the item removed from the library and the context menu changed back to "Add". So what has been changed since then?

**Comment by scakemyer** [comment]
The point of using add to library is to use the Kodi library... And what changed? This is [what changed](https://github.com/scakemyer/quasar/compare/v0.9.54...v0.9.70)... I'll look into checking both our DB and the Kodi library again but don't hold your breath for this.

**Comment by burekas7** [comment]
I know and if I understand it right, these operation of add/remove to/from library basically just add/remove a folder with the strm file inside from the library path, then kodi just scan new or missing content in the video source path.
How did it was recognized in the past whether it's already add to the folder or not, you know better then me. But it worked (Even when Quasar still not defined as the main source in my Kodi library)
But anyway, thanks for your efforts.

**Comment by scakemyer** [comment]
Fixed in v0.9.71

**Comment by burekas7** [comment]
Thanks man, working like a charm 👍
