### ISSUE TITLE
Quasar library integration - crash

### ISSUE THREAD

**Issue by Airbox79** [scakemyer/plugin.video.quasar#71]
Bug Report:
A Movie or a TV Show episode are added to the Quasar Library (within Quasar). The Kodi content settings on Movies and the Show directory (set under the library configuration in Quasar) then scans and imports it to the Kodi Library = so far so good. When you remove the TV Show or the Movie from the Kodi Library (via manage under TV Shows or Movies in Kodi) it goes well. But after readding it via Quasar to the Quasar Library again, a pop up dialog shows up saying cleaning the database and the dialog just hangs forever = you can't turn the htpc box of via the remote, or exit, and you have to push the button for 5 seconds so it turns it self off. It works to reboot or shutdown Openelec via ssh as well.

Speculation:
When adding a TV Show or a Movie from Quasar, it adds this to the json db file under the library path in the configuration. When re adding the movie/show, it sees that the strm files are gone (that has been wiped by the Kodi Manage tool) and freezes up since it doesn't have any exception on that. 

Seen on:
Openelec v6.0.0 with Pulsar v0.7.1 (i9)
Openelec v6.0.1 with Quasar v0.9.1
Openelec v6.0.1 with Quasar v0.9.4
Openelec v6.0.1 with Quasar v0.9.5

**Comment by scakemyer** [comment]
Paging @i96751414

**Comment by i96751414** [comment]
Looking at this later

**Comment by hfmls** [comment]
yes, the only problem is that it takes foverer to make a simple change everytime.

Remove one tvshow and the library gets remade and it takes like 5-10 minutes.

Besides, after reboot, tvshow is still there :D

**Comment by scakemyer** [comment]
Closing, will be fixed with #32, #107 and #259
