### ISSUE TITLE
Quasar downloads not starting on FireTv2 (kodi)

### ISSUE THREAD

**Issue by n0490b** [scakemyer/plugin.video.quasar#711]
I have set up Quasar along with the Burst add on. The problem occurs when I select something to download. No matter what I select to download it always stays at 0.00% on the pop up after I select a file to download. I have tried many different files. I have also tried restating, uninstalling & reinstalling, changing the download folder location of my mounted drive to `Android\data\org.xbmc.kodi\files\Quasar` after doing some searching but still no luck.  

## Your Environment
Amazon FireTV 2 running Kodi 16.1
1TB Seagate drive mounted using StickMount 

I have attached my debug log since its too big to post. TIA
[QuasarDebugLog.txt](https://github.com/scakemyer/plugin.video.quasar/files/762274/QuasarDebugLog.txt)

**Comment by n0490b** [comment]
anybody?

**Comment by walid73** [comment]
Try  disable  some provider I think you have a lot provide  enable

**Comment by scakemyer** [comment]
That's a storage issue on your end, I'm guessing that StickMount thing doesn't allow libtorrent to use regular OS-level storage APIs, or something of the sorts, but this is not an issue with Quasar.
