### ISSUE TITLE
JSON rpc error

### ISSUE THREAD

**Issue by jonudewux** [scakemyer/plugin.video.quasar#712]
On latest 68 version, Quasar didn't start even if json rpc is enabled. 
[kodi startup log](http://sprunge.us/TVhM)

**Comment by scakemyer** [comment]
You need to restart Kodi after enabling them. The check doesn't lie, it can or cannot connect; starting the daemon with the check failing wouldn't do you any favor.

**Comment by jonudewux** [comment]
I'm not saying that check lie, ok lets see in log:
line 160 - 20:11:53 T:2726556560   ERROR: [plugin.video.quasar] error(111, 'Connection refused')
line 162 - 20:11:57 T:3038155328  NOTICE: WebServer: Started the webserver
After 4 seconds all kodi server are started.
It's a good idea if connection to kodi server fails, quasat to re-try it with some delay.
It is a dirty hack but if I put some delay in service.py, everything is working fine.



In general quasar was check

**Comment by scakemyer** [comment]
Good point, will fix for next release.
