### ISSUE TITLE
Quasar doesn't start on latest OSMC release (based on Kodi 17)

### ISSUE THREAD

**Issue by joelvdvoort** [scakemyer/plugin.video.quasar#714]
Hello,

Two days ago I upgraded to the latest OSMC release which is based on Kodi 17. When I reinstalled Quasar it fails to start with error message "ioerror(21 'is a directory')".

I've enabled debug logs and pasted only the relevant section when quasar logs something. The logs can be found here: http://paste.ubuntu.com/23962502/

How to reproduce:
1. Run previous OSMC release on Raspberry pi 3
2. Upgrade OSMC using apt or from the GUI
3. Remove old Quasar version 0.9.66 and install 0.9.68
4. Start quasar from gui (which fails on my setup)

My environment details:
* Version used: 0.9.68
* Environment name and version: OSMC (latest), Kodi 17

Any help would be greatly appreciated, thanks.

**Comment by scakemyer** [comment]
Ok that log isn't helping at all, sorry. I've had 0 issues with a test box I have with OSMC; it actually took more time to backup the .kodi folder than to upgrade OSMC... and everything worked perfectly afterwards. Please share the whole log of when you're trying to install Quasar and I'll look into it.

**Comment by joelvdvoort** [comment]
Here's a complete log: http://paste.ubuntu.com/23962961/

Steps taken:

1. Removed Quasar
2. Enabled debug logging
3. Installed Quasar
4. Stopped and pasted debug logging

Just to be clear on this. If you think this has nothing to do with the Quasar code, I'll just nuke the install and see what happens next, no need to waste time on what could be a broken OSMC install from upgrading.

**Comment by scakemyer** [comment]
Start by nuking `/home/osmc/.kodi/userdata/addon_data/plugin.video.quasar`, it makes no sense that it thinks `bin/linux_armv7/quasar` is a directory...

**Comment by scakemyer** [comment]
Restart your box after doing that, seems you had a process already running too

**Comment by joelvdvoort** [comment]
Removing the directory worked. Thank you very much!

**Comment by scakemyer** [comment]
I'm not sure what happened there, but basically you don't have to remove Quasar before updating Kodi or Quasar itself, so it looks like just removing it didn't stop the daemon, which caused the issue when trying to reinstall it after your OSMC upgrade.

**Comment by vvinni** [comment]
I have the same problem and removing /home/osmc/.kodi/userdata/addon_data/plugin.video.quasar
Do not worked...

I don't know how to get my log... Anyone could help?

**Comment by vvinni** [comment]
Founded the way...

https://paste.osmc.tv/debumogavu

My log
