### ISSUE TITLE
Quasar stops working/reacting after failing to load categories

### ISSUE THREAD

**Issue by demircis** [scakemyer/plugin.video.quasar#715]
## Expected Behavior

Loading movie categories, allowing to browse categories like "Trending" or "Most Popular", playing movies/TV shows
## Current Behavior

Instead of loading the movies/TV shows, it is loading infinitely without progress, after the failure quasar stops loading content altogether, is unable to play streams (also loading).
## Possible Solution

\-
## Steps to Reproduce (for bugs)

1. Start browsing movies/TV shows with Quasar
2. Starts infinitely loading

## Context

Happens randomly after using Quasar for some time; trying to access folders like "Most Popular" or "Trending" in the Movie or TV shows directory
## Your Environment

* Version used: 0.9.68
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC): LibreELEC 7.95.2 Beta running Kodi 17.0
* Link to Kodi debug log: http://paste.ubuntu.com/23962605/
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by scakemyer** [comment]
There's a bad loop in the rate limiter's cool-down method, testing a fix already and it'll be in 0.9.69 within a day or two. Until then, when that happens, restarting Kodi and therefore Quasar should do. Sorry about this one.

**Comment by demircis** [comment]
Great, thank you for the quick reply.

**Comment by rosskopf** [comment]
thanks scakemyer :)
