### ISSUE TITLE
Download keeps dropping when using external storage on openelec

### ISSUE THREAD

**Issue by a1danslat3** [scakemyer/plugin.video.quasar#72]
Hello,

First off amazing work. 

However I'm currently having issues using external storage path on openelec. I'm using Wetek play with openelec 5.9 kodi 14.2. When I set the download path to external storage e.g 8gb usb ntfs/exfat the starts to download and gather seeds but then the download speed completely drops down to 1kb ? It works perfect using onboard storage.

Is this a known bug ? otherwise please close this issue

**Comment by iainconnor** [comment]
Same behaviour here. Android S95 Kodi 15.2

**Comment by scakemyer** [comment]
> This is a limitation of libtorrent, please keep in mind that most of the legwork is done by it, so if libtorrent can't do something, then Quasar probably can't either. And there are certainly good reasons for libtorrent not to support external storage, since it needs fast read/write access to function properly, so I seriously doubt it's even on their roadmap to support that.
