### ISSUE TITLE
Quasar stuttering and buffering speed drops down

### ISSUE THREAD

**Issue by PixieScr** [scakemyer/plugin.video.quasar#721]
Hi!, i have problem with Quasar, when i play video...buffering speed in Quasar starts grow up and after some time drops down to 0 and then again grow up..., in meantime when download speed drops down my video starts stuttering and freezing. In internal storage, usb stick and sd card is this problem...but when i mount hdd to my tv box then everything with Quasar is ok. Im using Libreelec kodi 17.

Edit: I see that people suggest to use internal storage or hard disk, because problem is sd card and usb stick. But for me interal storage have buffering speed drops down, only hard disk working fine. Has anyone have solution ?

**Comment by scakemyer** [comment]
This means your internal storage has issues too, in which case you should run a disk check before anything else. Then you can try enabling the "tuned storage settings" in the BitTorrent section, which will use more RAM but might help to get more constant speeds, but other than that there's nothing we can do; storage is all managed by libtorrent and it already does the best it can with the requirements of torrents.

**Comment by PixieScr** [comment]
Update: Quasar work with internal storage but only when i have LibreElec on SD card, when i have LibreElec on NAND then Quasar dont work normaly.

**Comment by elgatito** [comment]
That can happen if you try to play high-bitrate movies from a slow storage, plus it gets write operations, so read operations lack speed in that case.
You can benchmark sd-card and nand to understand how they work : http://unix.stackexchange.com/questions/108838/how-can-i-benchmark-my-hdd

**Comment by PixieScr** [comment]
Thx for the link
