### ISSUE TITLE
Quasar and burst refuse to auto-update Android Kodi 17.

### ISSUE THREAD

**Issue by sask3m** [scakemyer/plugin.video.quasar#723]
Using Spmc both auto-update and when I check repositories Quasar shows up but with Kodi 17 neither my Nvidia shield or nexus player will auto update nor do I see the quasar repo.  Would a log help with this?

   Just to mention other programs do update.

**Comment by scakemyer** [comment]
I'll update the readme regarding the Unknown sources setting in Kodi 17, since if you don't enable that setting before installing Quasar, the repository is there but needs to be enabled manually. Otherwise it gets installed and enabled just fine after fixing #706
