### ISSUE TITLE
Not able to select manual stream

### ISSUE THREAD

**Issue by Clavisnl** [scakemyer/plugin.video.quasar#729]
## Expected Behavior
Able to choose stream manual, not automatic. Happens since 0.9.68.

## Current Behavior
Only able to select automatic streams from version 0.9.68 to 0.9.70
## Your Environment
Windows 10 x64 Kodi 17 RC
Works in old versions before 0.9.68.

Currently using 0.9.41

**Comment by scakemyer** [comment]
When you open an issue, what does it say about bug reports without logs? Both automatic and manual choose stream are working just fine. You might have to clear caches or restart Kodi when you change the setting, and I'll look into fixing that, but that's about it.

**Comment by scakemyer** [comment]
scakemyer/quasar@1db493a fixes the stale cache that caused this confusion for you

**Comment by Clavisnl** [comment]
Thanks :) Ill try this when i get home.
Keep up the good work!
