### ISSUE TITLE
0.9.71

### ISSUE THREAD

**Issue by ieswideopen** [scakemyer/plugin.video.quasar#730]
The latest update causes quasar on my android box to crash until it aborts.  On both Kodi 16 & 17.

!--- Provide a general summary of the issue in the Title above -->

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by scakemyer** [comment]
And where's your log

**Comment by scakemyer** [comment]
**Bug reports without logs will likely be dismissed and closed**
