### ISSUE TITLE
0.9.71 crashing

### ISSUE THREAD

**Issue by ieswideopen** [scakemyer/plugin.video.quasar#731]
https://www.dropbox.com/s/rj58mo3p7wdn6u4/kodi.log?dl=0

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by sask3m** [comment]
Crashing for me as well.

**Comment by scakemyer** [comment]
And you had to open another issue... with yet another non-descriptive title, and absolutely nothing about Quasar crashing in those logs... c'mon guys

**Comment by ieswideopen** [comment]
Heading to bed. It'll have to wait til tomorrow afternoon. Thanks

**Comment by sask3m** [comment]
This is on latest  Spmc 16.5.5 Nvidia shield tv, Kodi 17 didn't want to update.

    http://pastebin.com/haeP56vr

**Comment by sask3m** [comment]
Kodi 17 crashing as well on my Shield, guess it's an android thing.

    http://pastebin.com/sv0EXexA

**Comment by scakemyer** [comment]
Seems like it, looking into it now, has to do with the new lockfile mechanism which will solve about half the issues on Windows, but obviously Android doesn't like it. I'll have a fix for you to test within a few minutes, can't release a hotfix without confirming it works.

**Comment by scakemyer** [comment]
[plugin.video.quasar-0.9.71.android_arm.zip](https://github.com/scakemyer/plugin.video.quasar/files/776028/plugin.video.quasar-0.9.71.android_arm.zip)

**Comment by sask3m** [comment]
Still crashing. Here is Kodi log.

   http://pastebin.com/df10kxL2

**Comment by scakemyer** [comment]
You're not running what I just uploaded, daemon would show as v0.9.71-1-g12cb2d3

**Comment by sask3m** [comment]
I d/l what is in the link above. Says 9.71 android arm.

**Comment by scakemyer** [comment]
That's the zip's filename yes, but your logs would show the daemon as v0.9.71-1-g12cb2d3 is what I'm saying, which means you downloaded that file, but that's not the one you installed / tested with / sent logs about.

**Comment by sask3m** [comment]
Ok ill try again.

**Comment by scakemyer** [comment]
Actually I'll have you try another one, missed a return call once retrying succeeds...

**Comment by scakemyer** [comment]
[plugin.video.quasar-0.9.71.android_arm.zip](https://github.com/scakemyer/plugin.video.quasar/files/776067/plugin.video.quasar-0.9.71.android_arm.zip)

**Comment by scakemyer** [comment]
That one has to show v0.9.71-1-g1435d2c

**Comment by sask3m** [comment]
Still crashing. I loaded 9.7 and dameon started then I loaded this last link and crashed.

    http://pastebin.com/H0fPPj03

**Comment by scakemyer** [comment]
You're obviously not installing the right zip file, daemon still says: `Version: v0.9.71` instead of `Version: v0.9.71-1-g1435d2c`

**Comment by sask3m** [comment]
Well I don't know what to say i d/l the link and install from hd and its the only 9.71 I have I deleted all the other ones.

**Comment by scakemyer** [comment]
Send the logs of when you **install** that last version, because in those, it's already installed and you keep running the same stock v0.9.71...

**Comment by sask3m** [comment]
http://pastebin.com/0DiPtW5E

  Maybe the old log isn't getting deleted and replaced or something. I dunno. Does it show a time somewhere in there to compare. oTher than that I'm at a aloss if its the wrong one again.

**Comment by scakemyer** [comment]
Yes it's always the same log from 20:55:46

**Comment by sask3m** [comment]
Ok ill try and see if i can figure this out.

**Comment by sask3m** [comment]
Ok what a workout that was, lol.  Here are the log and old log just in case hopefully you can find something in there.  The damn files were hidden on my shield for some reason. 

  http://pastebin.com/FChQJZKe  : log
  
   http://pastebin.com/crT2f9jv : old log

**Comment by scakemyer** [comment]
Finally! So the "TemporaryError" from lockfile isn't that temporary... Can you check if there's a file at `/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.quasar/.lockfile` ?

**Comment by sask3m** [comment]
ok under plugin.video.quasar there are three other folders and a bunch of what I presume are text files but NO lockfile.

**Comment by scakemyer** [comment]
It starts with a dot, for hidden files, so you have to do `ls -la`

**Comment by sask3m** [comment]
Yeah i see a bunch of files in there that start with . such as .travis.yml and gitignore so lockfile just doesn't seem to show up.

**Comment by scakemyer** [comment]
That's where it should be, you see `.firstrun` ?

**Comment by sask3m** [comment]
No the first . I see is .gitignore, .gitlab, .gitmodules, .travis and thats all the ones that start with a .

**Comment by scakemyer** [comment]
Go back to 0.9.70, start it up, then check for that `.firstrun` file again. If it's not there it's a file permission issue and we have other problems.

**Comment by sask3m** [comment]
Yes the .firstrun file shows up.

**Comment by scakemyer** [comment]
Alright we're good. So it's the lockfile package, which I'm rewriting right now...

**Comment by sask3m** [comment]
I then try 9.71 again and first is gone and still no .lockfile

**Comment by scakemyer** [comment]
yeah it doesn't get to that part before crashing... I really hate how relying on a simple package that is supposed to do one simple job ends up in a rewrite...

**Comment by sask3m** [comment]
i need my son here he's a programmer as well but not me, lol.

**Comment by scakemyer** [comment]
[plugin.video.quasar-0.9.71.android_arm.zip](https://github.com/scakemyer/plugin.video.quasar/files/776367/plugin.video.quasar-0.9.71.android_arm.zip)

**Comment by scakemyer** [comment]
v0.9.71-1-ga7c4ec3 
[plugin.video.quasar-0.9.71.android_arm.zip](https://github.com/scakemyer/plugin.video.quasar/files/776527/plugin.video.quasar-0.9.71.android_arm.zip)

**Comment by scakemyer** [comment]
Previous one should work, but I'd push this one as soon as it's confirmed to work.. v0.9.71-1-g893cdf9
[plugin.video.quasar-0.9.71.android_arm.zip](https://github.com/scakemyer/plugin.video.quasar/files/776690/plugin.video.quasar-0.9.71.android_arm.zip)

**Comment by Kelso76** [comment]
Tested  v0.9.71-1-g893cdf9 and no crashes. Seems to work file.

**Comment by scakemyer** [comment]
:tada: many thanks, pushing 0.9.72

**Comment by Kelso76** [comment]
You're welcome :)

**Comment by ieswideopen** [comment]
Tried it this morning; it works, thanks.

**Comment by sask3m** [comment]
Sorry for powering out on you last night Scakemyer had to hit the fart sack
wasn't sure how long it take.  Nice to see you got it working, many thanks.
:)

**Comment by elgatito** [comment]
I've got a request to find a reson for crush loop.
Here is a log - http://paste.ubuntu.com/24029338/
Possibly related to this issue?

**Comment by scakemyer** [comment]
Nope, that one looks a lot more like #746, this one here is fully resolved
