### ISSUE TITLE
torrents not streaming

### ISSUE THREAD

**Issue by fdsgdsfgsdfg** [scakemyer/plugin.video.quasar#737]
quite simply, they just don't. sending a magnet link from my browser results in an error. 
LibreELEC Kodi 16 on rPi3
http://paste.ubuntu.com/24002404/

**Comment by scakemyer** [comment]
I don't know how the hell you're "sending" it but that'll never work, and clearly you're not using the webUI either. The endpoint is `/play?uri=...`, but even then, external sources should use `/playuri?uri=...`

**Comment by fdsgdsfgsdfg** [comment]
I'm using PlayToKodi Chrome browser addon.

**Comment by scakemyer** [comment]
Ha, that's not even your issue, you're sending it to `plugin://plugin.video.xbmctorrent` ... wrong plugin mate.

**Comment by fdsgdsfgsdfg** [comment]
damn I feel stupid right now : )
thanks mate : )
