### ISSUE TITLE
Option "Choose stream automatically" does not work for the latest TV Show episode

### ISSUE THREAD

**Issue by heartlogic** [scakemyer/plugin.video.quasar#745]
I try to choose stream manually and i can't. 

## Expected Behavior
When we disable option "Choose stream automatically" at the torrent search we should have a list of active torrents to nanually choose. Please note that this is happening only on the latest episode of a TV Show. In the old ones this option is working alright. 

## Current Behavior
Now either way,  enabled or disabled, a stream is being automatically chosen. 

## Steps to Reproduce (for bugs)
Just try to watch the latest episode of a TV Show with this option disabled. 

## Your Environment
* Version used: 0.9.73
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC): LibreELEC 7.95beta6 (Kodi 17.1 RC) on S905X TV box
* Link to Kodi debug log:
http://paste.ubuntu.com/24017371/

**Comment by scakemyer** [comment]
It's working perfectly fine here. My guess is that you're playing from library integration, which gets its .strm files written according to your setting at that time, which was to automatically choose stream, in which case we should get rid of writing `/play` or `/links` in strm files, and use a different URI in those to allow us to respect the current setting no matter what it was set at when the library got updated.

**Comment by elgatito** [comment]
I was just investigating links/play definotion in strm files. Why it's there if we always get to navigation.py which can get current setting and act accordingly.

**Comment by scakemyer** [comment]
Because that's how it was implemented initially by i9, and I didn't think about that possible side-effect when I refactored the library integration last month. It's also not something that should be handled in navigation.py either but in the daemon.

**Comment by heartlogic** [comment]
Yes, you are right. I always use Kodi library to start watching videos.

**Comment by scakemyer** [comment]
For now, delete the strm file in question, update the library and that you should fix it. Will have a proper fix for this in the next release.

**Comment by scakemyer** [comment]
I really have to apologize to i9; he had implemented that correctly and I'm the one that over-simplified and messed it up during the refactor.
