### ISSUE TITLE
OS Error 3 -  continuous crashing on Android (AFTV)

### ISSUE THREAD

**Issue by navehgrofi** [scakemyer/plugin.video.quasar#746]
as from version 67 Quasar keeps crashing until stopped (version 66 still working well)

1. Deleted all Quasar / Burst folders from both add ons / user data
2. tried reinstalling both dedicated system depended zip, and the large, general one

setup:

Kodi Jarvis 16.1
Amazon Fire TV 2nd Gen

Log File - http://paste.ubuntu.com/24018527/

**Comment by scakemyer** [comment]
There's not enough lines to the stacktrace to know what's causing this for you... I'll need a few more lines between the `panic: runtime error` one and `System information` from the add-on, so if you don't mind, let it crash until it stops, check the logs between those lines, and once there's enough of them (showing which file and line number caused it), share that log file. There isn't much I can do without that.

**Comment by navehgrofi** [comment]
Here is  afresh new one:
http://paste.ubuntu.com/24018799/

**Comment by scakemyer** [comment]
Almost but not quite, it cut about three lines short of getting something useful.

**Comment by elgatito** [comment]
armv8? working with with 8th?

**Comment by scakemyer** [comment]
Just to be clear, the "OSError 3" isn't the issue here, that just means the add-on finds a stale lockfile from the previously crashed process, but can't kill the process it thinks still exists, then just keeps going. It should take about a minute to fix the cause of the crash once we get a good stacktrace.

**Comment by navehgrofi** [comment]
hmmm very strange, even though i get the crash message this seems to be the end of the Log.
ill open en extended debug log

**Comment by scakemyer** [comment]
We won't get anything more from a debug log, that doesn't change what the daemon outputs and just adds noise in our case.

**Comment by navehgrofi** [comment]
oh ok then ill give it another go

**Comment by scakemyer** [comment]
Noticed something too, your library path is set to the same path as the daemon's binary, which can't be good. The bittorrent service also can't write to your download path: `Unable to create Torrents folder`, which I've seen often and never caused a crash here, but you might want to look into that also.

**Comment by navehgrofi** [comment]
ok....checking

**Comment by navehgrofi** [comment]
although i didn't set library path at all though

**Comment by scakemyer** [comment]
Either way, a good stacktrace will go a long way in finding the root cause of this.

**Comment by navehgrofi** [comment]
uploading another one i got...

hope this one do the trick - http://paste.ubuntu.com/24018846/

**Comment by navehgrofi** [comment]
A success!

it seems setting the Library path and changing my Download path worked!

**Comment by scakemyer** [comment]
Previous log got closer... I had the feeling it'd be solved by setting the download path, but would've liked to know where the crash was anyway ;)

**Comment by navehgrofi** [comment]
i don't mind trying adding more logs, but it doesn't seems to produce much more than i've uploaded

**Comment by scakemyer** [comment]
That's fine, I have a good idea of where it might be, and considering it solved anyway.
