### ISSUE TITLE
Rutor (Burst provider) with TV Show "3%"

### ISSUE THREAD

**Issue by ORGaniZMo** [scakemyer/plugin.video.quasar#747]
## Expected Behavior
When I try to play a TV show "3%" - error "Internal server error"

## Steps to Reproduce (for bugs)
1. Go to Quasar -> TV Shows -> Search -> type 3% -> Done
2. In the search results, select 3% -> Season 1 -> Choose any of the series - Choose any of the torrents with 3% - Choose any of the files.
3. Just wait for a full buffer.
4. Internal Server Error.

## Your Environment
Version used: Kodi 17
Operating System and version: Windows 7/8
Link to Kodi debug log:
http://paste.ubuntu.com/24032013/
![screenshot007](https://cloud.githubusercontent.com/assets/25881599/23112251/c3e22ad6-f750-11e6-8439-7b4731ef83bb.png)
![screenshot009](https://cloud.githubusercontent.com/assets/25881599/23112252/c3e267da-f750-11e6-90b4-43e13227faef.png)

**Comment by ORGaniZMo** [comment]
At the same time the other TV Show, such as "The Big Bang Theory" is played without any problems.

**Comment by scakemyer** [comment]
No issues about providers, I don't care if this is really about Quasar
