### ISSUE TITLE
Available streams dialog appears under Opening stream on Kodi 14.2

### ISSUE THREAD

**Issue by dtsexpert** [scakemyer/plugin.video.quasar#75]
0.9.6 works fine, few minor things I would like to report
1. Exiting the Kodi makes it freeze. Need to hard reboot by unpluging the power cord
2. Love the new list font size and layout, but on top of the feed list there is smaller popup showing 'opening stream'. If I hit cancel it closes the feed list as well. I still can scroll up and down the feed list. Clicking at one of the feed, kodi downloads and plays fine.
Android box 5.1.1, Kodi 14.2
Pastebin http://pastebin.com/ihpp5Nsx
![img_0753](https://cloud.githubusercontent.com/assets/17037033/12837238/65bff832-cb75-11e5-9162-4e2d1c454921.JPG)

**Comment by scakemyer** [comment]
Thanks, it's working properly here on 15.2, and since those are using regular xbmcgui controls it looks like it's a Kodi bug. I'll check to see if there's something I can do about it for older versions.

**Comment by dtsexpert** [comment]
When you coders have time, kindly please take a look at this issue again. I need to use kodi 14.2 since this is the only version that works with Amlogic S905 hardware decoder.
For now I am using the 0.9.5 but really would like to be up to date since the available streams layout looks great.

**Comment by scakemyer** [comment]
Chances are this will be fixed alongside #105

**Comment by scakemyer** [comment]
Can you try 0.9.12 to see if the xml-based dialog solves this?

**Comment by dtsexpert** [comment]
@scakemyer  still same issue. Available stream still appears under opening dialog
Thanks for your help.

**Comment by scakemyer** [comment]
Alright thanks for reporting on this. I had a workaround I was working on which wasn't ideal but should be a better compromise.

**Comment by i96751414** [comment]
I really hate those language issues.. I thought on choosing the encodings based on the language

**Comment by scakemyer** [comment]
Alright so even with the more standard XML-based dialog, and a few other things I've tried locally, Kodi 14 just doesn't display custom dialogs over native ones. So this is an ugly fix, reverting to the standard xbmc.Dialog() for Kodi < 15, and you won't be getting the nice two-line Available streams, but at least it won't show up under Opening stream.

I'd still like to revisit the whole process of what gets triggered when, so we wouldn't have the Opening stream dialog in the first place but only after having chosen a stream, but this will have to do for the time being.

**Comment by i96751414** [comment]
You don't need to do that... Just change the title string of that window

**Comment by scakemyer** [comment]
This has nothing to do with #142, you're confusing the two issues.

**Comment by i96751414** [comment]
I think Im not understanding the real issue here. ..

**Comment by scakemyer** [comment]
Title (and screenshot) says it all ;)

**Comment by i96751414** [comment]
It doesn't happens to me... Its quite strange

**Comment by scakemyer** [comment]
With Kodi 14.2? Same happened every time here, no matter what I tried. No problem with Kodi 15, hence the dirty workaround for the time being.
