### ISSUE TITLE
Show download and upload rates in Torrents list

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#754]
1) The bug: The percentage value inside the Torrents screen is not the same as it is in the notification. The value in the Torrents screen doesn't refresh it's value like it does in the notification when you inside (In order to do that you need to go out and back in). Is it possible to fix this?

2) The request: Add also the Down&Up rates in the title. I think only in the Torrents screen it's enough, but you could also add it also in the notification.

Screenshot:
https://s28.postimg.org/sk0wfk3jx/screenshot016.png
https://s28.postimg.org/pegapckxp/screenshot019.png

Thanks.

**Comment by scakemyer** [comment]
1. Nope, not without refreshing the directory listing, which would be insanely annoying, especially if you're in the process of deleting a torrent or doing any other operation.
2. We're keeping the main menu clean, so definitely not there, but I can look into what could be done when under the Torrents section. I'll be adding an aggregated down&up speeds in the WebUI also.

**Comment by burekas7** [comment]
@scakemyer 
Thanks.
1) In addition to the text in the notification, can you add this also in the torrents item list in Torrents category?
(I think it could be instead of the time's value there)
Or this screen could not refreshed like the notification?

2) Does the max down/up rates in the settings relate to the total rates or per torrent?
(Also regarding the percentage value, how do you calculate the total value?)
