### ISSUE TITLE
since 0.9.6 is out - the addon always asking for upgrade

### ISSUE THREAD

**Issue by meijin007** [scakemyer/plugin.video.quasar#76]
even thou the latest (0.9.6) is installed, Quasar keep asking for updating it.
Also: Nothing in change log.

**Comment by meijin007** [comment]
BTW, this is creating a lot of problem, since the add on always trying to update itself while working, making the addon to restart

**Comment by scakemyer** [comment]
Can you share some logs? I've let it update like a normal user here after pushing the new version and it worked as it should.

**Comment by hfmls** [comment]
Same problem here

**Comment by meijin007** [comment]
Fixed in 0.9.8

**Comment by hfmls** [comment]
yes, all good

**Comment by scakemyer** [comment]
Awesome, thanks for closing this :)
