### ISSUE TITLE
tv shows not updating in library anymore

### ISSUE THREAD

**Issue by tomoniu** [scakemyer/plugin.video.quasar#764]
Some Tv shows are not updating: Timless(last .strm plugin://plugin.video.quasar/library/show/play/66786/1/10), Grey's anatomy(plugin://plugin.video.quasar/library/play/show/1416/season/13/episode/10), Bull (plugin://plugin.video.quasar/show/66840/season/1/episode/10/links) .
there are others that don't update(Elementary, Criminal Minds, etc), but i also have TV shows that update normaly.
I tried removing the shows from library(both kodi and quasar) and then re-adding them, but quasar creates exactly the same .strm files as before. No errors are generated. 

## Expected Behavior
When Quasar library updates, .strm files should be created

## Current Behavior
.strm files for new episodes of some shows are not created anymore....
They don't show up when i search the show using Quasar plugin either. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: I have Kodi 17, OSMC, on Raspberrry Pi2.
* Environment name and version (e.g. Kodi 15/16/17, SPMC, OSMC, OpenELEC):
* Operating System and version (Android 4/5/6, Windows 7/8/10, macOS 10.11, Ubuntu 16.10):
* Link to Kodi debug log:
<!--- See http://kodi.wiki/view/Log_file/Easy or paste to http://paste.ubuntu.com directly

**Comment by elgatito** [comment]
Give the kodi.log file.

**Comment by tomoniu** [comment]
I also tried to manualy create a .strm file containing (plugin://plugin.video.quasar/library/show/play/66786/1/11) you cand find the error when i tried to play it, in the log.

[kodi.log.txt](https://github.com/scakemyer/plugin.video.quasar/files/800504/kodi.log.txt)

**Comment by scakemyer** [comment]
That's just stale caches from *before* the caching refactor, see #645. They'd eventually start updating again once the way-too-long expiration passed, and I don't recommend doing this often (or at all for that matter), but in your case it's probably better to delete the whole `cache` folder at `/home/osmc/.kodi/userdata/addon_data/plugin.video.quasar/cache`

**Comment by scakemyer** [comment]
Restart Kodi after you do so, and wait a few minutes for Quasar to warm up the caches again. Might want to restart Kodi again once you see the "Caches warmed up" notification, that way if the warming up missed a few shows because of rate limiting, they'll get picked up on the second pass. Everything should work as expected afterwards.

**Comment by tomoniu** [comment]
It worked. It took longer to update the library, and a few timeouts, but now everything looks in order. Thanks a lot.

**Comment by scakemyer** [comment]
Good to hear. I'll eventually improve the handling of those timeouts with delayed retries, and those stale cache issues will stop popping up by themselves within a few weeks at most, so closing this one. Enjoy :)
