### ISSUE TITLE
Crashes on the 2nd use on libreelec.

### ISSUE THREAD

**Issue by yazun** [scakemyer/plugin.video.quasar#768]
## Steps to Reproduce (for bugs)
After 2nd restart after installation plugin refuses to start/crashes.
Reinstalling and removing cache/ page. files helps only after re-installation, but goes back to the same crash cycle on the next boot (esp after freeze of kodi, which probably is not related)

```
20:50:10.136 T:140646365763328  NOTICE: [plugin.video.quasar] INFO  main         ▶ func6            [0mUpdating Kodi add-on repositories...
20:50:10.137 T:140646365763328  NOTICE: [plugin.video.quasar] panic: runtime error: invalid memory address or nil pointer dereference
20:50:10.137 T:140646365763328  NOTICE: [plugin.video.quasar] [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xa8e184]
```

## Your Environment
Librelec 8.0.0 (same with 7.9*).
Linux x64.
Kodi 17
Quasar 0.9.74 

Full log:
http://paste.ubuntu.com/24067332/

Cheers

**Comment by scakemyer** [comment]
Your library path is empty. I'll add yet another fix for this but for now just set it at least to the same folder as your download path.

**Comment by yazun** [comment]
I had both set before to NFS mount before at no avail.
I changed to local disk and it seems ok now.
thanks for the fast response!

**Comment by scakemyer** [comment]
You can't use `nfs://` mounts, but you might be able to use the locally mounted path. It's not a recommended setup though, and #440 will solve this to a certain extent by allowing to move completed downloads to a different path (but still locally mounted).
