### ISSUE TITLE
Seeding information are showing during playback

### ISSUE THREAD

**Issue by heartlogic** [scakemyer/plugin.video.quasar#770]
## Expected Behavior
When an episode or a movie pauses we see seeding progress information. When movie playback starts this information is not visible so we can watch the episode or the movie. 

## Current Behavior
Sometimes, not always, this information stays visible during playback and we cannot make it go away. 

## Steps to Reproduce (for bugs)
1. Pause playback
2. Start playback 

## Your Environment
* Version used: 0.9.74
* Environment name and version: LibreELEC 8.0.0c, Kodi 17.1 RC
* Operating System and version: Amlogic TV Box with S905X
* Link to Kodi debug log:
http://paste.ubuntu.com/24067844/
Please check the second episode because the issue was there

**Comment by scakemyer** [comment]
Yeah there's just absolutely nothing in those logs that could help debug this. Which skin are you using? If anything, this'll be solved alongside #728 since it's related to the same RPC objects for which I'll be adding more checks and clean-ups.

**Comment by scakemyer** [comment]
Actually, it looks like there are two players running/closing at the same time:
```
23:41:34.760 T:4118487824  NOTICE: CVideoPlayer::CloseFile()
23:41:34.760 T:4118487824  NOTICE: VideoPlayer: waiting for threads to exit
23:41:34.760 T:4118487824  NOTICE: VideoPlayer: finished waiting
23:41:34.760 T:4118487824  NOTICE: CVideoPlayer::CloseFile()
23:41:34.760 T:4118487824  NOTICE: VideoPlayer: waiting for threads to exit
23:41:34.760 T:4118487824  NOTICE: VideoPlayer: finished waiting
```
Along with other not-very-good-looking VideoPlayer notices and warnings, so this looks more like bugs in that version of Kodi or LibreELEC being the cause of this. Either way, the fixes I mentioned should help deal with issues like that on our side, unless it really is as it looks and a first player has a "stuck" image, in which case you'd still see the overlay status anyway...

**Comment by heartlogic** [comment]
I am using default Krypton Kodi skin with no additions or changes. I also saw many errors in logs and when i tried to replay the episode i could't even if it was 100% downloaded.

**Comment by scakemyer** [comment]
You're running a beta version of LibreELEC from three days ago, and there's not a single error from Quasar in there beside the very normal `tracker_error_alert` from libtorrent. You're being very light on details and so far this doesn't look like an issue with Quasar, at all.

**Comment by heartlogic** [comment]
I don't know if this is from Quasar or LibreELEC Kodi, but i cannot post it in LibreELEC forums since seeding information overlay appears only when using Quasar. 

Please tell me what else details you need to help clarify this issue.

If you cannot find anything in Quasar then i will close it until it becomes more pernanent or i can find a more reliable guide to reproduce it.
