### ISSUE TITLE
Tell user which platform/arch package should be used when getting the "Unable to find Quasar binary" error

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#772]
Currently user needs to select proper architecture/version to run Quasar. 
While python code does not differ, but only Binary is different for all the platforms/arch's?

We can detect better choice automatically in daemon.py, and download the binary. Should be applied only for non-existing ones.

This would be a great gain for non-geek users, that often meet problems with getting right version.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by elgatito** [comment]
I can try to impement it on my own, if you are ok with this task.

**Comment by scakemyer** [comment]
There's already full platform/arch detection in `osarch.py`, and an all-binaries release for non-technical users and/or universal installs... I don't think downloading the daemon binary on-the-fly would be a good idea and would only add unneeded complexity to an already complex setup.

**Comment by scakemyer** [comment]
Not only that, but following the first install from the all-platforms zip, the add-on updates itself with the right platform/arch zip. So yeah, not changing the way this currently works. If anything I'll just add the link to the "all platforms" zip on the website...

**Comment by elgatito** [comment]
I have a great and "easy" idea.
Currently we show "Binary not found" error and that is all.
Why not detect osarch and show error like: "Could not find Quasar Binary, make sure you use {Windows x64} plugin bundle".
That will drop off many questions.

**Comment by scakemyer** [comment]
That sounds a lot better.

**Comment by scakemyer** [comment]
Fixed in #777
