### ISSUE TITLE
Resume not working in Windows

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#774]
Not sure about Linux, on Libreelec it seem to work with the latest version.
Now testing on windows and for me resume does not work. Can't say it's always like that or not. For what I'm testing - it never does the last place.

Steps:
- In Quasar -> Movies -> In Trend -> Select any --> Add to the library (let it be Movie AAA)
- Open Movies -> Start AAA
- Quasar asks to select stream. selecting, buffer started, play started from the beginning
- Rewind somewhere in the middle
- Wait a minute, and stop playback

- Open Movies -> Start AAA
- Kodi show Movie is in watching state and propose to resume play, click yes
- Quasar asks to use previous stream, click yes.
- Play started from beginning of the file.

Log file: http://paste.ubuntu.com/24082770/ (last attempt is when trying to resume but could not and started from the beginning)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: Latest 

* Environment name and version: Kodi 17

* Operating System and version: Windows 7

* Link to Kodi debug log: http://paste.ubuntu.com/24082770/

**Comment by ShlomiD83** [comment]
tried with an episode and resume worked fine. forwarded to the middle, paused, played a little, stopped, selected the same torrent and it resumed from the point i stopped.
