### ISSUE TITLE
Impossible to reach internet when quasar starts to stream (port 80 blocked ?)

### ISSUE THREAD

**Issue by thomas-seres** [scakemyer/plugin.video.quasar#775]
## Expected Behavior
Streaming starts, possible to reach the web (for example to download subtitles)

## Current Behavior
Once the streaming starts, I really don't know why, but it's impossible for me to reach the web (I tried with a web browser, or inside Kodi to download subtitles, it's not possible either)

The stream does not have any problem and works perfectly, but no more internet for all other process.
I have to kill the quasar process to get back to the web.

Maybe the port 80 is blocked by quasar once the stream begins ?

## Environment
Windows 10
Quasar : v0.9.74 - Fresh Install
Quasar Burst  - Fresh Install
Kodi Krypton V17.0 - Fresh Install

**Comment by scakemyer** [comment]
No, Quasar doesn't block port 80... You shouldn't use torrents if you don't understand how it works at a minimum. Just limit the down/up rates and the connections limit in Quasar settings...

**Comment by thomas-seres** [comment]
Not related to the down/up rates limits. And yes I know how torrents works.

This happened to me since the new update, so for sure, the description of the issue is not perfect (I apologize for that), but I never experienced that, even when I was using xbmcTorrent, Pulsar and Quasar in previous versions.

So thanks anyway, 
I will try to figure out why this is happening with this version, but not sure that being condescending will help in any way.

**Comment by elgatito** [comment]
@thomas-seres can you post a kodi.log with debug enabled?

**Comment by scakemyer** [comment]
Boo-f**king-hoo, I'm always condescending, get used to it mate. Getting dumb as f**k issues like this one and being accused of blocking ports doesn't help either, mind you. And it's always the last update, then somehow it's all fine again, until the next update. It gets pretty old... If streaming works, then your internet works, so look elsewhere or stop using Quasar, I couldn't care less.
