### ISSUE TITLE
Search results

### ISSUE THREAD

**Issue by gkarav** [scakemyer/plugin.video.quasar#779]
Kodi + Quasar + Burst (Latest version)

Many times when selecting  a Tv Series then Season and finally episode
You get irrelevant results.

For example when in Black Sails S02 in almost every episode the top results are from a Russian tracker (i have enabled most of them) but its not S02 its S04.

In some cases i found totally irrelevant results that they don't event belong to the particular tv show.

**Comment by scakemyer** [comment]
Read the warning regarding issues about providers when posting a new issue? This is your one and only warning.
