### ISSUE TITLE
subtitles issue on 0.9.11

### ISSUE THREAD

**Issue by kodi1** [scakemyer/plugin.video.quasar#78]
Kodi says that there is a external subtitle, but they doesn't appear:
22:30:28 T:2750411840   ERROR: Open - Unhandled exception
22:30:28 T:2750411840   ERROR: Open - Error opening special://temp/whvpoint..srt
22:30:28 T:2750411840   ERROR: OpenStream - Unable to create subtitle parser

On 0.9.0 version everything works fine, I think.

**Comment by scakemyer** [comment]
Closing in favour of scakemyer/quasar#13
