### ISSUE TITLE
Set*Watched fires randomly

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#780]
I'm opening new episode, when buffering completes and player starts I seek somewhere else, after a few seconds Kodi exists to the episodes list and show episode as completed.

To be sure, I have updated plugin.video.quasar from the repo, added new tv show from Quasar.

Somehow it gets here:
```
if stopped.Ended || progress > 90 {
				if stopped.Item.Type == "movie" {
					xbmc.SetMovieWatched(stopped.Item.ID, 1, 0, 0)
				} else {
					xbmc.SetEpisodeWatched(stopped.Item.ID, 1, 0, 0)
				}
```

Log cut:
```
10:15:11.267 T:2872  NOTICE: [plugin.video.quasar] INFO  library      ▶ func1            Stopped at 8.876559%
10:15:11.268 T:1108   DEBUG: JSONRPC: Incoming request: {"jsonrpc":"2.0","method":"VideoLibrary.SetEpisodeDetails","params":{"episodeid":53,"lastplayed":"2017-03-02 10:15:11","playcount":1,"resume":{"position":0,"total":0}},"id":0}
```

Full Log: http://paste.ubuntu.com/24094907/

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by scakemyer** [comment]
What? There's nothing wrong in those logs, `VideoLibrary.SetEpisodeDetails` was only sent each time you stopped the player, which is exactly what it should be doing...

**Comment by elgatito** [comment]
The problem is I did not stop the video. The player started to play I seeked somewhere in the middle. Buffering starts, and in a few second I'm out of player and video is marked as watched.

**Comment by scakemyer** [comment]
Then it's a side-effect / duplicate of #756 if anything.
