### ISSUE TITLE
Daemon crash when path has unicode

### ISSUE THREAD

**Issue by elgatito** [scakemyer/plugin.video.quasar#781]
With the latest version (0.9.75) Quasar daemon crashes when player is stopped.
Probably this one causes it:
```
11:13:39.856 T:4936   ERROR: [plugin.video.quasar] (quasar.rpc) In Handler method QuasarRPCServer.OverlayStatus_Create()
11:13:39.857 T:4936   DEBUG: [plugin.video.quasar] C:\Users\����\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\rpc.py::OverlayStatus_Create:291 overlay = OverlayText()
                                            C:\Users\����\AppData\Roaming\Kodi\addons\plugin.video.quasar\resources\site-packages\quasar\overlay.py::__init__:30 self._background = xbmcgui.ControlImage(x, y, w, h, os.path.join(ADDON_PATH, "resources", "img", "black.png"))
11:13:39.858 T:4936   ERROR: [plugin.video.quasar] Unhandled error: UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-12: ordinal not in range(128)

```

Log: http://paste.ubuntu.com/24095076/

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by scakemyer** [comment]
Well, it's now using your own fix, so fix it again. And dude, you're opening way too many issues, for everything and nothing. Get on Gitter so we can chat instead...

**Comment by elgatito** [comment]
Sorry. Somehow python was using old code, this is updated Kodi log. Python not throwing error, but Go is
http://paste.ubuntu.com/24095182/
