### ISSUE TITLE
Request Realdebrid sync up

### ISSUE THREAD

**Issue by JackieBrown911** [scakemyer/plugin.video.quasar#783]
It's an new feature request, just like red beard and premiumize sync up. Is it possible to develop a feature to use Real Debrid authorization?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by scakemyer** [comment]
No.

**Comment by bloombergg** [comment]
nope.  you should instead invest that money in usenet
