### ISSUE TITLE
System is getting very slow

### ISSUE THREAD

**Issue by rridder** [scakemyer/plugin.video.quasar#785]
Hello,

Over the past couple of month there have been a lot of updates with nice new features. But can it be that because this quaser is gotten a lot more heavy to use? I'm having a Wetek Play and never had any problems with playing 1080p files of  +/- 8gb. Everything got even more slow after krypton release (on libreelec). Lately i have to choose 420p torrents because almost everything hangs and at some point crashes. When i play a file without quaser just from the hard disk everything is fine. 

I've tried reinstalling kodi and starting from scratch as i tought this was maybe the case for an old install but nothing changed.

Setup:
Kodi Krypton (libreelec 8) on Wetek play 
Skin: Ftv 
Using magnetic for providers. 
AMLogic AML-872 MX (1.5 GHz Dual Core)
GPU: Mali MP400 (Dual Core)
RAM Memory: 1GB DDR III

Could it be possible quaser requires higher technicacle specs then before?

**Comment by KillerJoeBR** [comment]
What about other Add-ons? I think your issue is probably not related to Quasar. But you should provide a log and do a test with other Add-ons to see if they are fine.

**Comment by KillerJoeBR** [comment]
You could also download an old Quasar version from the release page and test if it's better

**Comment by rridder** [comment]
Thank you for your fast reply. But i'm not really running any other plugin's. Besides the ones needed by my skin. Here is a log:

https://jpst.it/UFQj
When download is starting the cpu is just going to 100% all the time.

**Comment by scakemyer** [comment]
We might be using 2-3% more juice with all the new features, at most, which got totally dwarfed by the performance gains of Go 1.8 of around 30%, especially on ARM. If anything Quasar has gotten a lot faster. Make sure you have only one stream running at a time if you have performance issues, but even with 10 active torrents CPU usage should stick around 5%, and try with the stock Estuary skin; a bunch of skin add-ons is the best way to kill CPU cycles...

**Comment by rridder** [comment]
Thanks for the reply scake, yes i already tought so. Also tried emptying the download queue and so on. The estuary skin is not running very smootly either so don't know what is going on. Ordered the wetek play 2 probably will be a lot faster.

**Comment by scakemyer** [comment]
Are you sure you're not trying to play 8gb HEVC files either? Anyway, send screenshots of the `top` command alongside logs and what you're exactly doing in Kodi, if you think there really is an issue with Quasar. Might be easier to try an old version first with the same setup and stream...

**Comment by rridder** [comment]
Well it's the only plugin installed beside youtube plugin. Yes my system can't play h265 so only h264. Will try an older version of quasar see if that helps. For now i'm back to downloading the file first. You can close this tread. Will reopen it if it's not better with the new system.

**Comment by scakemyer** [comment]
Yeah don't know what else to tell you, I have a load average of 0.08 over here with 9 active streams, so my guess is that it really is your skin or skin add-ons on Krypton that's causing the issue.

**Comment by bloombergg** [comment]
what eMMC version?

where are you writing incomplete torrents? not path, the type of media.  local or lan?

try limiting connections to 12

how much freespace on internal storage?

@ridderr

**Comment by bloombergg** [comment]
@rridder
