### ISSUE TITLE
Providers stopped working with 0.9.6

### ISSUE THREAD

**Issue by deusbraga** [scakemyer/plugin.video.quasar#79]
All the providers that were working in my computer, android stick openelec, and rpi2 stopped working with 0.9.6. Is this a recurring error?

**Comment by scakemyer** [comment]
Providers can return their name separately in 0.9.6 but that isn't a breaking change for the API, see #73

**Comment by deusbraga** [comment]
Once again, sorry for my ignorance but in practice what does that mean? what i know is that every time i try starting something it returns no links were found. this is the log
[kodia.txt](https://github.com/scakemyer/plugin.video.quasar/files/119346/kodia.txt)

Does it mean the coder of the providers is going to make changes to his files?

**Comment by scakemyer** [comment]
Sorry but I can't help you further regarding specific providers.
