### ISSUE TITLE
[Decoder TimVision Android Tv (ARM)] Search Problem

### ISSUE THREAD

**Issue by leandresca** [scakemyer/plugin.video.quasar#791]
**## Current Behavior**
I installed Quasars and Quasars Burst CORRECTLY on Android (ARM). 
Quasars start properly, and Burst is enabled properly. 
When I try to search for anything, it starts to turn the blue circle of Kodi, and never stops.
Actually it does NOT do any research, since it does not appear at the top right circle of providers (search).

THIS IS NOT A PROVIDER PROBLEM. 

Quasar is the problem, because I also tried to use Megnetic Torrent, and the result is the same.

**## Possible Solution**
It could be that the decoder does not have the root?

**## Steps to Reproduce (for bugs)**
1. Install Quasar 
2. Install Quasar Burst
3. Config Providers in Quasar Burst
4. Try to find a torrent with Search in Quasar

**## Your Environment**
I have used Quasar 0.9.73/0.9.74 and 0.9.75

*** Environment name and version:**
I have Kodi 17.0 Krypton

*** Operating System and version:**
Android TV 5.1.1
http://i2.hd-cdn.it/img/max_width660/max_height436/id554825.jpg
http://i2.hd-cdn.it/img/max_width660/max_height436/id554832.jpg

**Comment by scakemyer** [comment]
Debug logs, screenshots of your system specs aren't useful here.

**Comment by leandresca** [comment]
This is Log File (used Kodi Logfile Uploader): http://paste.ubuntu.com/24124636/

This is a video of the bug: https://www.youtube.com/watch?v=p1bKRP06A2c

**Comment by leandresca** [comment]
What could be the problem?

**Comment by leandresca** [comment]
Problem solved with the decoder update to Android 6.
