### ISSUE TITLE
IMAGES for Wiki

### ISSUE THREAD

**Issue by bluenote73** [scakemyer/plugin.video.quasar#794]
![snipaste_20170307_115911](https://cloud.githubusercontent.com/assets/6239498/23679349/89a57696-033c-11e7-881d-b91fb3b92eb9.png)
![snipaste_20170307_120050](https://cloud.githubusercontent.com/assets/6239498/23679350/89b7f370-033c-11e7-85be-632468a016c4.png)
![snipaste_20170307_120149](https://cloud.githubusercontent.com/assets/6239498/23679352/89ca9318-033c-11e7-85b5-c41b7560e22b.png)
![snipaste_20170307_120431](https://cloud.githubusercontent.com/assets/6239498/23679356/89cba9ec-033c-11e7-8b9a-fadf4a362038.png)
![snipaste_20170307_120935](https://cloud.githubusercontent.com/assets/6239498/23679354/89cabd7a-033c-11e7-9fb5-531e4955f239.png)
![snipaste_20170307_125732](https://cloud.githubusercontent.com/assets/6239498/23679357/89cb285a-033c-11e7-872d-26e154111db9.png)
![snipaste_20170307_125842](https://cloud.githubusercontent.com/assets/6239498/23679358/89ccf842-033c-11e7-82f0-a4bebf1d3528.png)
![snipaste_20170307_130011](https://cloud.githubusercontent.com/assets/6239498/23679353/89cab280-033c-11e7-9e29-181fafafdb7d.png)
![snipaste_20170307_114227](https://cloud.githubusercontent.com/assets/6239498/23679359/89dc2f38-033c-11e7-89b2-3e72e416758e.png)
![snipaste_20170307_114324](https://cloud.githubusercontent.com/assets/6239498/23679360/89dcba7a-033c-11e7-9599-2d7d9339f61c.png)
![snipaste_20170307_114346](https://cloud.githubusercontent.com/assets/6239498/23679361/89dd00d4-033c-11e7-9213-8a2afd2f20f3.png)
![snipaste_20170307_115147](https://cloud.githubusercontent.com/assets/6239498/23679364/89e0b238-033c-11e7-90a3-9a52121758cf.png)
![snipaste_20170307_115257](https://cloud.githubusercontent.com/assets/6239498/23679362/89df64d2-033c-11e7-80b5-cdd770550ba9.png)
![snipaste_20170307_115508](https://cloud.githubusercontent.com/assets/6239498/23679363/89df8264-033c-11e7-906e-a1148349a1f9.png)
![snipaste_20170307_115829](https://cloud.githubusercontent.com/assets/6239498/23679365/89ef494c-033c-11e7-9b81-b807903f493e.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:

* Environment name and version:

* Operating System and version:

* Link to Kodi debug log:

**Comment by stephen8263** [comment]
would not the interface be

tun0
