### ISSUE TITLE
New Providers for quasar

### ISSUE THREAD

**Issue by mancuniancol** [scakemyer/plugin.video.quasar#8]
First, good work with Quasar.  I want to support your work, but I cannot do it if you keep the pulsar name in the directory.  Then, I want to propose you to do the change to plugin.video.quasar ASAP and I will release a quasar version of my whole providers catalogue.  I will use script.quasar.name_provider.

I've uploaded one test for you, https://github.com/mancuniancol/script.quasar.yify-mc/archive/0.0.1.zip

Please, let me know if you want to work in this idea. Or, your point of view.  If you don't want it, don't worry, I won't take personal.  But, I won't promise support in the repos that I have connections because of conflict with the first pulsar version :(

**Comment by scakemyer** [comment]
Hey, that'd be awesome. Really appreciate your willingness to support the fork. I meant to reply on the forum but still can't PM...

**Comment by mancuniancol** [comment]
Good, just let me know if the test works and I will change an publish everything asap.

**Comment by meijin007** [comment]
@mancuniancol please, at least for the near future, maintain both pulsar and quasar providers...

**Comment by scakemyer** [comment]
```
from pulsar import provider
```
Should be `from quasar import provider`, only thing that prevents it from working really.

In addon.xml, set the quasar version to 0.9.1 as it will be the first release with the rename. Pulsar is still mentioned in the description (and changelog) ;)

You can also get rid of `import re` in main.py as it's not being used there.

**Comment by mancuniancol** [comment]
You changed inside the main too. 
OK. 
About the import, it seems I forgot to run the optimization after I've migrated from re to beautifulsoup.  But, I am still not sure if I should do it for the dependency problem. 
Anyway, I hope to release them couple hours. If you don't mind I will copy the fanart from Quasar. 
I will leave this thread open until I release everything. 
For the sake the Quasar, the providers should be apart from the main project.

**Comment by meijin007** [comment]
@mancuniancol Will you add them to your repo (pulsar-unofficial?)

**Comment by mancuniancol** [comment]
Yes, I will do in a couple hours. I am still working it

**Comment by mancuniancol** [comment]
Ok. I've released some. I will continue working this morning :).  I will push them to the repos that I know

**Comment by mancuniancol** [comment]
Btw, is it possible to have a copy of Quasar before I push everything to the repo?

I don't want to have any bug in my providers that it could affect the experience with the new addon.

**Comment by mancuniancol** [comment]
I will test each provider to be sure that everything is ok. It will take me longer that I've thought, but I think it is better

**Comment by mancuniancol** [comment]
I have to wait until I have the binaries for windows to test the providers

**Comment by scakemyer** [comment]
Looked over the code, they'll work just fine. Are they available in your repositories already?

**Comment by mancuniancol** [comment]
No. I don't push them until I can test them.  But, they are available in my github

https://github.com/mancuniancol

**Comment by scakemyer** [comment]
New release is out for you to test :)

**Comment by mancuniancol** [comment]
Thank you, I am already working it. :)

Btw,

[quasar.txt](https://github.com/scakemyer/plugin.video.quasar/files/108479/quasar.txt)

**Comment by mancuniancol** [comment]
I will try to send mostly all the providers before my noon. It will be available in couple hours :D

**Comment by scakemyer** [comment]
Neat ascii :)

**Comment by mancuniancol** [comment]
;) I've sent 12 providers.  I will work in the rest this weekend.

**Comment by mancuniancol** [comment]
For the sake of the kodi thread.  Try not to speak about the providers, it is forbidden subject.

**Comment by i96751414** [comment]
@mancuniancol I don't know if you want to develope one, but I suggested on forum to people start developing legal providers too. I will probably do one myself. If you want to develop one (a simple thing) go ahead :)
http://forum.kodi.tv/showthread.php?tid=257967&pid=2228560#pid2228560

**Comment by mancuniancol** [comment]
Yes, but from which sources? The only ones that I know Netflix and Amazon has already addons. Or what kind of content you want?

**Comment by mancuniancol** [comment]
For me it is more about practicing Python, then I would be delighted to create legal content providers.  The only problem, I do know from where

**Comment by hfmls** [comment]
Are the providers available yet?  Can't find them.  Thank you

**Comment by mancuniancol** [comment]
Github.com/mancuniancol

**Comment by mancuniancol** [comment]
OK, I think that we don't need more this opened

**Comment by i96751414** [comment]
@mancuniancol Your providers are not working here, just to let you know. Btw torrentz was a nice one to have :) never failed me

**Comment by mancuniancol** [comment]
That is weird, Ive tested before release them. Could you share your debug log?,  please?

**Comment by hfmls** [comment]
i downloaded from here:
https://github.com/mancuniancol?tab=repositories

don't download the pulsar ones, download the quasar, here it worked ok. using eztv yizi and kickass

**Comment by mancuniancol** [comment]
Thank you hfmls.  And I have another report that they are working well https://forums.tvaddons.ag/addon-releases/31572-pulsar-providers-unofficial-pulsar-repo-post324511.html#post324511

Then, @i96751414  is something in your side.

**Comment by hfmls** [comment]
at first i was downloading pulsar ones too, because u were giving the link:
https://github.com/mancuniancol
instead of:
https://github.com/mancuniancol?tab=repositories

:P np

**Comment by i96751414** [comment]
Yeah it might be. Or i was using the wrong ones...  I will try again later
