### ISSUE TITLE
Cannot stream local torrent from network (smb) 

### ISSUE THREAD

**Issue by liutkiz** [scakemyer/plugin.video.quasar#801]
## Expected Behavior
I can stream my local torrents from network attached storage over smb

## Current Behavior
Add Torrent
File
Choose local torrent in network attached storage (Samba server)
Quasar shows "working" and nothing happens

(streaming from local storage - Android TV storage - works fine, can see that in logs)

## Possible Solution
Support network attached storage.

## Context
I have a samba server at home, where I put my local torrent files. I would like to choose them from Quasar in Android TV, to be able to watch it.

## Your Environment
Everything is in logs (Android TV 6.0, Quasar v0.9.75, Kodi v17), cannot do that on mac as well
* Link to Kodi debug log:
http://paste.ubuntu.com/24157879/

**Comment by savageflavors** [comment]
have you tried with NFS?

**Comment by liutkiz** [comment]
Haven't tried it, need to flash my Asus router to have NFS support. Actually in Quasar 0.9.75 the pop up shows that Quasar does not support network attached storage, so I guess NFS will not help here.

**Comment by scakemyer** [comment]
https://github.com/scakemyer/plugin.video.quasar#can-i-set-it-to-download-directly-to-my-nas
