### ISSUE TITLE
Episodes are missing in library integration, but not in quasar

### ISSUE THREAD

**Issue by ElMouse** [scakemyer/plugin.video.quasar#806]
Good day. Please kindly advise regarding the following issue:

The Quasar is aware of the recent episodes of the show "Last week tonight with John Oliver"
see [screenshot](http://imgur.com/CA2W1mv)

The show is added to my library.
However only episodes up until the end of 2016 are added.
see [screenshot](http://imgur.com/0J3CL5O)

It is not a problem of kodi seeing the files, because actually only these srt files exist and being added to the library.
see [screenshot](http://imgur.com/eFIEm2K)

Removing the show from my library, deleting the files, adding it again does not resolve the issue. Again only these episodes are added.

Other shows i have added do not exhibit this behavior. They work perfectly fine. All episodes are visible and new episodes are being added when they are released.
So this behavior is kind of weird and is existent only for this show. Please kindly advise.
Can maybe someone advise if they see the same behavior for this show? Is it quasar bug, or my local weird problem?

i am on Windows 10, Kodi 16.1

thanks for the quasar it is awesome

**Comment by ElMouse** [comment]
Maybe someone else kindly can check if they have the same problem? Just find the show Last Week Tonight with John Oliver in Quasar and  add it to your library. Then check if any episodes for season 4 have been added.
Thanks.

**Comment by scakemyer** [comment]
This is either a caching issue (search closed issues where I describe how to remove single-show caches) or related to #750
