### ISSUE TITLE
[Bug] Trakt Collection returns error notification

### ISSUE THREAD

**Issue by burekas7** [scakemyer/plugin.video.quasar#809]
When trying going to "Movies -> Trakt -> Collection" it returns an error.

## Current Behavior
Movies -> Trakt -> Collection didn't update the items there, so I deleted the cache folder content.
And now when I'm going back to the Movies Collection in the addon, it returns error message
"Bad status getting Trakt collection for movies: 401"

* This error shows up also with TV Shows Collection

## Your Environment
* Version used: 0.9.75
* Environment name and version: Kodi 16.1
* Operating System and version: Win 10, 64bit
* Link to Kodi debug log: http://pastebin.com/CtL0DFnY

**Comment by burekas7** [comment]
It seems to be solved after reactivate the Trakt account.

**Comment by scakemyer** [comment]
Should be the last time you have to re-authorize, since tokens now get refreshed automatically, unless the authorization gets revoked from the website or elsewhere.
