### ISSUE TITLE
OSMC Vero 4k platform not detected correctly in osarch.py

### ISSUE THREAD

**Issue by leevh** [scakemyer/plugin.video.quasar#810]
Brand new Vero 4k unit (by OSMC), Quasar wouldn't start from fresh install, very similar to issue #570 .  Narrowed it down to it being a 32bit OSMC installed on 64bit hardware (see excerpt below from logs)

```
21:51:57.366 T:4114318256  NOTICE: Starting Kodi (17.1-RC1). Platform: Linux ARM (Thumb) 32-bit
21:51:57.366 T:4114318256  NOTICE: Using Release Kodi x32 build (version for Vero)
21:51:57.366 T:4114318256  NOTICE: Kodi compiled Feb 24 2017 by GCC 4.9.2 for Linux ARM (Thumb) 32-bit version 3.16.39 (200743)
21:51:57.366 T:4114318256  NOTICE: Running on Open Source Media Center 2017.02-2, kernel: Linux ARM 64-bit version 3.14.29-8-osmc
21:51:57.366 T:4114318256  NOTICE: FFmpeg version/source: ffmpeg-3.1-kodi
21:51:57.366 T:4114318256  NOTICE: Host CPU: AArch64 Processor rev 4 (aarch64), 4 cores available
```

For a quick test I changed [line 25 of osarch.py](https://github.com/scakemyer/plugin.video.quasar/blob/master/resources/site-packages/quasar/osarch.py#L25) to just "arm" and its working again.  I've pasted the log below as well, and with some more time I could probably come up with a patch, but I just wanted to get this out there as these units are shipping out now. If there's any info I could supply about the hardware, please let me know. Thank you for the awesome addon!

LOG http://pastebin.com/wKNKdHt6

**Comment by elgatito** [comment]
```
21:51:57.366 T:4114318256  NOTICE: Starting Kodi (17.1-RC1). Platform: Linux ARM (Thumb) 32-bit
21:51:57.366 T:4114318256  NOTICE: Using Release Kodi x32 build (version for Vero)
21:51:57.366 T:4114318256  NOTICE: Kodi compiled Feb 24 2017 by GCC 4.9.2 for Linux ARM (Thumb) 32-bit version 3.16.39 (200743)
21:51:57.366 T:4114318256  NOTICE: Running on Open Source Media Center 2017.02-2, kernel: Linux ARM 64-bit version 3.14.29-8-osmc
```

Needs a rewrite for OS/Platform detection to corrently handle 32/64 bit for ARM arch.

**Comment by elgatito** [comment]
@leevh , can you try to replace the code block from line 21 to this one and say if it works fine for your environment:
```
        if "aarch" in platform.machine() or "arm64" in platform.machine():
            if xbmc.getCondVisibility("system.platform.linux.raspberrypi"):
                ret["arch"] = "armv7"
            elif platform.architecture()[0].startswith("32"):
                ret["arch"] = "arm"
            else:
                ret["arch"] = "arm64"
```

**Comment by leevh** [comment]
@elgatito , confirmed this works for my environment, thank you!

**Comment by scakemyer** [comment]
Fix will be in the next release :+1:
