### ISSUE TITLE
Empty TV Shows section 

### ISSUE THREAD

**Issue by inkubux** [scakemyer/plugin.video.quasar#812]
I have installed Quasar on my Nvidia Shield on Kodi 17.1.

Movie section works fine, but when I want to access the TV Shows section all I get is an empty folder

With nothing. I tried closing and restarting Kodi but still the same

Here is the log I get The /shows is the last entry in the log: 

> 15:23:28.061 T:138538845264  NOTICE: [plugin.video.quasar] [GIN] 2017/03/22 - 19:23:28 | 200 [0m|    1.218385ms | 127.0.0.1 |  [0m GET     /shows/
15:23:30.808 T:138538845264  NOTICE: [plugin.video.quasar] [GIN] 2017/03/22 - 19:23:30 | 200 [0m|     935.782µs | 127.0.0.1 |  [0m GET     /shows/
15:23:33.583 T:138538845264  NOTICE: [plugin.video.quasar] [GIN] 2017/03/22 - 19:23:33 | 200 [0m|   20.475417ms | 127.0.0.1 |  [0m GET     /provider/
15:23:35.744 T:138538845264  NOTICE: [plugin.video.quasar] [GIN] 2017/03/22 - 19:23:35 | 200 [0m|     4.24901ms | 127.0.0.1 |  [0m GET     /provider/script.quasar.burst/settings
15:24:08.672 T:137951741008   ERROR: GetDirectory - Error getting plugin://plugin.video.quasar/provider/script.quasar.burst/settings
15:24:08.674 T:137951741008   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.quasar/provider/script.quasar.burst/settings) failed
15:24:09.367 T:138538845264  NOTICE: [plugin.video.quasar] [GIN] 2017/03/22 - 19:24:09 | 200 [0m|    20.57026ms | 127.0.0.1 |  [0m GET     /provider/
15:24:09.912 T:138538845264  NOTICE: [plugin.video.quasar] [32mNOTI  library      ▶ doUpdateLibrary  [0mLibrary updated
15:24:09.971 T:138334585936  NOTICE: VideoInfoScanner: Starting scan ..
15:24:09.987 T:138334585936  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00
15:24:10.009 T:138407265360  NOTICE: EMBY.kodimonitor -> Method: VideoLibrary.OnScanStarted Data: null
15:24:10.010 T:138407265360  NOTICE: EMBY.kodimonitor -> Method: VideoLibrary.OnScanFinished Data: null
15:24:10.708 T:138538845264  NOTICE: [plugin.video.quasar] [GIN] 2017/03/22 - 19:24:10 | 200 [0m|  107.819895ms | 127.0.0.1 |  [0m GET     /provider/
15:24:12.342 T:138538845264  NOTICE: [plugin.video.quasar] [GIN] 2017/03/22 - 19:24:12 | 200 [0m|   19.862448ms | 127.0.0.1 |  [0m GET     /provider/
15:24:21.437 T:138538845264  NOTICE: [plugin.video.quasar] INFO  torrents     ▶ func1            [0mCurrently downloading:
15:24:21.528 T:138538845264  NOTICE: [plugin.video.quasar] [GIN] 2017/03/22 - 19:24:21 | 200 [0m|    6.487135ms | 127.0.0.1 |  [0m GET     /torrents/
15:24:32.269 T:138538845264  NOTICE: [plugin.video.quasar] [GIN] 2017/03/22 - 19:24:32 | 200 [0m|    7.141875ms | 127.0.0.1 |  [0m GET     /shows/

I know there is not a lot of details in there but I don't know where to look

Thanks a lot

**Comment by elgatito** [comment]
You should enable debug logging and paste your log somewhere on the internet (like pastebin.com).
First link on google about getting this: http://www.htpcbeginner.com/kodi-log-file/

**Comment by inkubux** [comment]
here is a full debug log

http://pastebin.com/4Q5GX9Nu

**Comment by inkubux** [comment]
Here is a dump of http://localhost:65251/shows/

In case it helps further

**Comment by inkubux** [comment]
Another thing is in the new kodi webgui  :8080, the tv shows menu works. I don't know why it won't work in the real kodi interface.

**Comment by inkubux** [comment]
After further tests here are the findings I did:

Main tv shows menu or shortcut to to Menu tv shows don't work (empty folder)
From A remote App (Kore, Yatse, Webgui) TVShows menu works.
When creating a widget for a skin, TV show menu will list all the categories and let me create a widget which will then display normally as a widget.

I'm kind a of lost there. It looks like the main menu does not wait for the call to **localhost:65251/shows/** to be completed before displaying. Where in all other place (Webgui, Widget creation, Yatse) they all wait for the async call to be completed.

I hope this helps you identify the issue. If you want me to do other tests or anything even if it requires changing a python file or anything let me know. I really want to resolve this issue :)

**Comment by inkubux** [comment]
Ok finally after a full kodi re-install on my shield everything works normally. I'm closing this issue
