### ISSUE TITLE
Streaming stops/stutters after about 3 minutes on RPI3 with 32 GB SD card.

### ISSUE THREAD

**Issue by JorisE73** [scakemyer/plugin.video.quasar#816]
Hello, I've installed Quasar 0.9.75 on a RPI3 with LibreElec 8.0.1 with Kodi Krypton 7.0.1, I use a Samsung micro SDHC Evo+ 32 GB Class 10 card.
I've tried to stream a 11 GB file to test it and after about 1:30 - 2 minutes in it stops and stutters or has artifacts even though the file has downloaded about 30% of the 11GB with a download speed of about 9 - 10 MB/s. 
I made an Advanced Settings XML file with the following settings:      <memorysize>157286400</memorysize>
    <buffermode>1</buffermode>
    <readfactor>30</readfactor>
After a reboot I tested it again and it now it buffers faster but it still stops and has occasional artifacts and stuttering but now after about 4 -5 minutes.
I also tested it on a 2 GB file with the same results.
Is this a limitation of a RPI3? Or am I missing something in the config of it, should I add something to the advanced settings file?

**Comment by scakemyer** [comment]
Those advanced settings seem fine. With the speed you're getting and size of the file, I'm guessing you're stressing that poor rpi3's cpu a little too hard. Try actually limiting your d/l rate, and setting your connections limit, something like 5MB/s and 100 to 150 connections tops.

**Comment by JorisE73** [comment]
I had set the buffer to 100 and already had set the connection limit to 100, I'll try it with a 5MB/s limit and post the results. Thanks for the quick reply man!

**Comment by JorisE73** [comment]
Setting the d/l rate to 5MB/s actually did the trick I think, the 11GB file played well past 10 minutes and then I stopped it. Another question though, would it make some difference to use a 32GB USB3 stick as the download and library location instead of the SD card?

**Comment by scakemyer** [comment]
Good to hear, you can also check how much CPU is being used while playing with a certain button, which depends on your input method (no need to enable debug mode for that either). That way you could see what's the max speed it can handle while playing high bitrate files like those.
I'm pretty sure the SD card will be faster, as I don't think the rpi3 actually supports USB3 anyway. You should probably stick to what you have now; I'm sure that storage option is fast enough. You could however add an external hard drive, and use the "Move completed downloads to separate folders" feature to free up your SD card automatically.

**Comment by foklorr** [comment]
UFD often have multiple write streams whereas sdcard not.
