### ISSUE TITLE
Kodi reboots at startup after March 25th; possibly Quasar related

### ISSUE THREAD

**Issue by endlessterror** [scakemyer/plugin.video.quasar#817]
LibreELEC 7.0.2 (Kodi 16.1) on a AMD A4-5000 (x64 build, 4Gb of RAM, HDD based), as well as RPi2 (runs from 8Gb Sandisk SD card). Both builds were working rather rock-steady, with regard to crashes. 

Recently though and on both platforms  I have been receiving Kodi crashes upon startup. These *seem* to happen around (or immediately after) Quasar startup, and before the caches are warmed up.

If it starts and manages to display that caches are now warmed up, things seem to be working alright.

It is simply a hunch that this is Quasar-related, even though Quasar revision history does not show anything to be related. I definitely have not (and will not) updated LibreELEC itself. I have attached Kodi logs (including crash logs) at XXXXXXX.

<REDACTED>

## Steps to Reproduce (for bugs)
1. Simply boot
2. Most of the time this causes an intermittent Kodi (not system)

**Comment by scakemyer** [comment]
Only the log files please, either copy/pasted on paste.ubuntu.com, or drag-n-dropped right here directly. I don't have time, and quite simply don't want to mess with compressed archives of your logs.

**Comment by endlessterror** [comment]
Kodi logs are around 20Mb in size, that is why I uploaded them compressed; the other files (system setup etc) were simply bundled as extra information. 

Tried to upload only the combined 01_kodi.log to paste.ubuntu.com, but due to the size I received a 502 error from the web server during upload.

I had to butcher the file a little: http://paste.ubuntu.com/24301174/

**Comment by scakemyer** [comment]
Not related to Quasar and nothing changed around that date, sorry.
