### ISSUE TITLE
Encoding issue of movie names on Ubuntu/Linux

### ISSUE THREAD

**Issue by scakemyer** [scakemyer/plugin.video.quasar#82]
As reported by nkgx on the forum, and I'm also seeing this in a VM:

<img src="http://i.imgur.com/LHqRJlh.jpg" />

@i96751414 anything in the translation system regarding encoding you think might be causing this?

**Comment by i96751414** [comment]
Unfortunately Python is the worst thing regarding this... Can you give me more details? Like language, which section is that, so I can reproduce the same here

**Comment by scakemyer** [comment]
English, movies only, shows seem fine. No idea if it's from the daemon, in or because of translations on the Python side, or in the json between both. My first guess is with `GetLocalizedString()` doing `.encode('utf-8')` on all labels.

**Comment by meijin007** [comment]
duplicate of ‫https://github.com/scakemyer/plugin.video.quasar/issues/23 ?

**Comment by scakemyer** [comment]
Yes it is, but I'll mark #23 as the duplicate since the problem isn't just with Hebrew

**Comment by meijin007** [comment]
Not already fixed?

**Comment by scakemyer** [comment]
Is it? Haven't tested yet with the new encoding fixes.

**Comment by meijin007** [comment]
I don't see this problem any more. (Although now I use the translated titles, so lets wait for others input).

**Comment by meijin007** [comment]
Ok, this problem is still presents. also for director name, elso not only on Ubuntu (I am using Arch linux ARM)

**Comment by scakemyer** [comment]
I tried debugging that for a while yesterday, the daemon is sending the right names and everything. Right up to feeding the list item's label and all, no matter what I tried, encoded as strings or unicode or ascii, Kodi chews them up in `xbmcplugin.addDirectoryItems`. I can't find a shred of logic to explain why it's doing that...

**Comment by tobiasvandriessel** [comment]
Very strange, on my Debian/Linux it's also present.

**Comment by infinicode** [comment]
Same problem here with Ubuntu 15.10 Wily. Lang is set in both Ubuntu and Kodi to en_US. I've setup the option "use_original_title" to "true", and still the same problem for movie names.

The daemon seems to working correctly, as the information exposed by the API seem to be correct too.

If I can help to debug just let me know.

![img_20160217_201928](https://cloud.githubusercontent.com/assets/1757109/13122296/93a79868-d5b6-11e5-9b5e-b02d24866b9f.jpg)

![json](https://cloud.githubusercontent.com/assets/1757109/13122418/1498ca5a-d5b7-11e5-8f86-55177de188e9.png)

**Comment by infinicode** [comment]
The problem seems to be related with Kodi itself. I've upgraded the the unstable branch and everything works perfectly, both movies and tv shows.

Version of Kodi with the error: 2:15.2~git20151101.0902-final-0wily
Version of Kodi without the error: 2:16.0~git20160205.0918-rc3-0wily

**Comment by scakemyer** [comment]
There's just no way this wasn't caused by Kodi, and I finally found the bug report: http://trac.kodi.tv/ticket/16414

**Comment by scakemyer** [comment]
I'm afraid the only fix is to upgrade to Jarvis, as it was included in beta-5. Finally closing this one, there's nothing more we can do since it's a memory corruption issue in XBMCAddon::Dictionary when using the new C++11 ABI in gcc 5.1 and up
