### ISSUE TITLE
Stream Season doesn't work since v0.9.76

### ISSUE THREAD

**Issue by Airbox79** [scakemyer/plugin.video.quasar#826]
## Expected Behavior
Show all episodes within the season torrent, choose episode to stream

## Current Behavior
It gives a message saying "index out of range" and it seems that its connected with the following error:
navigation.py", line 83, in getInfoLabels elif 'episode' in sys.argv[0] or ('show' in sys.argv[0] and id_list[1] and id_list[2]):
IndexError: list index out of range

## Steps to Reproduce (for bugs)

1. Choose TV Series
2. Search Homeland or House of Cards
3. Mark a Season
4. Choose Stream
5. Choose the tv serie season torrent
6. Error, "index out of range", shows up with after searching

## Your Environment

* Version used:

Quasar v0.9.76 & Quasar Burst v0.5.9
* Environment name and version:

Kodi 17.1
* Operating System and version:

LibreElec v8.0.1

* Link to Kodi debug log:

**Comment by elgatito** [comment]
Should be fixed in the next release.
