### ISSUE TITLE
multi-file issue? 

### ISSUE THREAD

**Issue by nix87** [scakemyer/plugin.video.quasar#83]
Hi. I know that this was already been on issue list but there something to be done for actually this can work right? Can developers say what needed to be done for this? Probably something in providers, but if you can tell what it would be nice?

Yes, sorry.. I press enter on mistake xD

**Comment by scakemyer** [comment]
You'll have to be more descriptive than that.

**Comment by scakemyer** [comment]
Yes see #17 and scakemyer/quasar#8

**Comment by nix87** [comment]
Can't belive I didn't find time to check those threads again I thought they were forgotten :facepalm:

Great, thanks for the answer btw +1
