### ISSUE TITLE
Make use of your strm watched state fix in gdrive addon?

### ISSUE THREAD

**Issue by horstepipe** [scakemyer/plugin.video.quasar#831]
Hey
Sorry, this is no issue with your project, but I didn't find another way to contact you.
There is a nice Gdrive addon for Kodi which has the same problem about strm files in library and the watched state by ddurdle:

https://github.com/ddurdle/GDrive-for-KODI

Do you think it is possible to adopt your fix in this addon?

Best regards

**Comment by scakemyer** [comment]
Already solved since 0.9.70 :)

**Comment by horstepipe** [comment]
Thank you very much.
I hope ddurdle will figure it out
