### ISSUE TITLE
No results for a day or two

### ISSUE THREAD

**Issue by jhill54** [scakemyer/plugin.video.quasar#838]
Hi guys, I had a question regarding the updating of trackers within the app.  If I'm 100% sure a release is available (x tracker, public or private) and I do a search within Quasar, no results show up for sometimes, for a day or two for that particular release.  Has anyone else experienced this?  Thanks for your help!

**Comment by scakemyer** [comment]
Please use a brief title and a description next time.

**Comment by lanzorg** [comment]
I had an android box (MINIX neo u1) + 3G modem with very slow speed (~100ko/s) and I experienced this kind of problems, it failed all the times and sometimes quasar restarted itself.  
I don't know if it was because of the minix performance or internet speed.
