### ISSUE TITLE
Quasar keeps crashing

### ISSUE THREAD

**Issue by konvar** [scakemyer/plugin.video.quasar#841]
Kodi (17.2-RC1 Git:20170419-661dd08). Platform: Windows NT x86 32-bit

http://paste.ubuntu.com/24484788/

The problem started after I used trakt watchlist.
If you need more details tell me.
Thank you.

**Comment by scakemyer** [comment]
Always need more details, and non-descriptive titles like "Quasar keeps crashing" are insanely annoying to developers... Try rebooting that Windows machine first: `No connection could be made because the target machine actively refused it`...
