### ISSUE TITLE
Video stops after 20~ minutes

### ISSUE THREAD

**Issue by ilanerukh** [scakemyer/plugin.video.quasar#85]
After playing a video for about 20 minutes, the video stops and Kodi goes to its main screen. Tried to wait to download reach 100% before start playing the video, but the issue remains. Tried with different providers and different files, and the video still crashes.

Using WIndows 10 x64 Kodi 15.2. Tried the big zip file and the windows x64 zip file 0.9.6.

**Comment by i96751414** [comment]
You should provide a log.

**Comment by ilanerukh** [comment]
Okay. The log says that there's no internet connection. However, internet connection in the same point is fine, and it happens in every video.

01:58:49 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:49  INFO  btplayer         Adding torrent
01:58:49 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:49  INFO  btplayer         Setting save path to D:\pulsar
01:58:49 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:49  INFO  btplayer         Enabling sequential download
01:58:49 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:49  INFO  btplayer         Downloading mr robot s01e08 real 720p hdtv x264 killers ethd
01:58:49 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:49  NOTI  libtorrent       state_changed_alert: mr robot s01e08 real 720p hdtv x264 killers ethd: state changed to: dl metadata
01:58:49 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:49  NOTI  libtorrent       torrent_added_alert: mr robot s01e08 real 720p hdtv x264 killers ethd added
01:58:49 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:49  NOTI  libtorrent       add_torrent_alert: added torrent: magnet:?xt=urn:btih:E047B8E6D827FFC5677EA5F77E6557BE033F6969&dn=mr+robot+s01e08+real+720p+hdtv+x264+killers+ethd&tr=udp%3A%2F%2Ftracker.publicbt.com%2Fannounce&tr=udp%3A%2F%2Fglotorrents.pw%3A6969%2Fannounce&as=http%3A%2F%2Ftorcache.net%2Ftorrent%2FE047B8E6D827FFC5677EA5F77E6557BE033F6969.torrent&as=http%3A%2F%2Ftorcache.net%2Ftorrent%2Fe047b8e6d827ffc5677ea5f77e6557be033f6969.torrent&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F
01:58:49 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:49  NOTI  libtorrent       torrent_resumed_alert: mr robot s01e08 real 720p hdtv x264 killers ethd resumed
01:58:51 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:51  INFO  btplayer         Buffer loop
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  INFO  btplayer         Metadata received.
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  NOTI  libtorrent       metadata_received_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD] metadata successfully received
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  NOTI  libtorrent       state_changed_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]: state changed to: checking (r)
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  INFO  btplayer         Chosen file: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]\Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS.mkv
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  NOTI  libtorrent       state_changed_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]: state changed to: downloading
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  INFO  btplayer         Setting piece priorities
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  NOTI  libtorrent       torrent_checked_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD] checked
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  NOTI  libtorrent       torrent_paused_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD] paused
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  NOTI  libtorrent       torrent_resumed_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD] resumed
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  NOTI  libtorrent       torrent_paused_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD] paused
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  INFO  btplayer         Checking for sufficient space on D:\pulsar...
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  INFO  btplayer         Total size of download: 812733653
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  INFO  btplayer         All time download: 0
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  INFO  btplayer         Size total done: 0
01:58:59 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 01:58:59  INFO  btplayer         Size left: 812733653
01:59:51 T:9280  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
02:00:31 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:00:31  INFO  btplayer         Waiting for playback...
02:00:32 T:5632  NOTICE: [plugin.video.quasar] [GIN] 2016/02/06 - 02:00:32 |[90;47m 302 [0m| 1m43.0898537s | ::1 |[97;44m  [0m GET     /play
02:00:32 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:00:32  INFO  torrentfs        Opening /Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]/Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS.mkv
02:00:32 T:4324  NOTICE: DVDPlayer: Opening: http://10.0.0.1:65251/files/Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]/Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS.mkv
02:00:32 T:4324 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
02:00:32 T:4324  NOTICE: DXVA::CProcessorHD::PreInit - The Direct3d device doesn't support DXVA-HD.
02:00:32 T:4324  NOTICE: CWinRenderer::Preinit - could not init DXVA-HD processor - skipping
02:00:32 T:9500  NOTICE: Thread DVDPlayer start, auto delete: false
02:00:32 T:9500  NOTICE: Creating InputStream
02:00:32 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:00:32  INFO  torrentfs        Opening /Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]/Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS.mkv
02:00:32 T:9500  NOTICE: Previous line repeats 1 times.
02:00:32 T:9500  NOTICE: Creating Demuxer
02:00:32 T:9212  NOTICE: Thread FileCache start, auto delete: false
02:00:32 T:9500  NOTICE: Opening stream: 0 source: 256
02:00:32 T:9500  NOTICE: Creating video codec with codec id: 28
02:00:32 T:9500  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
02:00:32 T:9500  NOTICE: Creating video thread
02:00:32 T:9500  NOTICE: Opening stream: 1 source: 256
02:00:32 T:9500  NOTICE: Finding audio codec for: 86019
02:00:32 T:9500  NOTICE: Creating audio thread
02:00:32 T:9976  NOTICE: Thread DVDPlayerVideo start, auto delete: false
02:00:32 T:9976  NOTICE: running thread: video_thread
02:00:32 T:3168  NOTICE: Thread DVDPlayerAudio start, auto delete: false
02:00:32 T:9976  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1280x720)
02:00:32 T:3168  NOTICE: running thread: CDVDPlayerAudio::Process()
02:00:32 T:3168  NOTICE: Creating audio stream (codec id: 86019, channels: 6, sample rate: 48000, no pass-through)
02:00:32 T:9976  NOTICE:  fps: 23.976024, pwidth: 1280, pheight: 720, dwidth: 1280, dheight: 720
02:00:32 T:3168  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
02:00:32 T:9976  NOTICE: Previous line repeats 1 times.
02:00:32 T:9976  NOTICE: Display resolution DESKTOP : 1920x1080@ 60.00 - Full Screen (16)
02:00:32 T:9976  NOTICE: D3D: rendering method forced to DXVA processor
02:00:32 T:4324 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
02:00:32 T:8612  NOTICE: Stream All The Sources: Service: Playback started
02:00:32 T:3168  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
02:00:33 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:00:33  INFO  btplayer         Playback loop
02:00:34 T:7876   ERROR: C:\Users\Ilan\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
02:00:55 T:9544  NOTICE: Thread JobWorker start, auto delete: true
02:03:40 T:7876   ERROR: C:\Users\Ilan\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
02:03:52 T:3168  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 32
02:03:52 T:3168  NOTICE: CDVDPlayerAudio::OutputPacket duplicate 3 packets of duration 32
02:04:51 T:9280  NOTICE: Previous line repeats 3 times.
02:04:51 T:9280  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
02:05:10 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:05:10  NOTI  libtorrent       state_changed_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]: state changed to: finished
02:05:10 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:05:10  NOTI  libtorrent       torrent_finished_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD] torrent finished downloading
02:05:10 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:05:10  INFO  btplayer         Buffer is finished, resetting piece priorities...
02:05:10 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:05:10  NOTI  libtorrent       state_changed_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]: state changed to: downloading
02:05:10 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:05:10  INFO  btplayer         Checking for sufficient space on D:\pulsar...
02:05:10 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:05:10  INFO  btplayer         Total size of download: 812733653
02:05:10 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:05:10  INFO  btplayer         All time download: 795822583
02:05:10 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:05:10  INFO  btplayer         Size total done: 791150592
02:05:10 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:05:10  INFO  btplayer         Size left: 21583061
02:07:15 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:07:15  INFO  btplayer         Buffer is finished, resetting piece priorities...
02:07:15 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:07:15  NOTI  libtorrent       state_changed_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]: state changed to: finished
02:07:15 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:07:15  NOTI  libtorrent       torrent_finished_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD] torrent finished downloading
02:07:15 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:07:15  NOTI  libtorrent       state_changed_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD]: state changed to: seeding
02:09:53 T:9280  NOTICE: AddOnLog: PVR IPTV Simple Client: EPG Loaded.
02:16:24 T:5632  NOTICE: Previous line repeats 1 times.
02:16:24 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:24  INFO  btservice        No internet connection available
02:16:24 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:24  INFO  btservice        Stopping DHT...
02:16:24 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:24  INFO  btservice        Stopping LSD...
02:16:24 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:24  INFO  btservice        Stopping UPNP...
02:16:24 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:24  INFO  btservice        Stopping NATPMP...
02:16:25 T:9212   ERROR: CCurlFile::FillBuffer - Failed: Failure when receiving data from the peer(56)
02:16:25 T:9212  NOTICE: CCurlFile::FillBuffer - Reconnect, (re)try 1
02:16:25 T:9212   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
02:16:25 T:9212  NOTICE: CCurlFile::FillBuffer - Reconnect, (re)try 2
02:16:25 T:9212   ERROR: CCurlFile::FillBuffer - Failed: Couldn't connect to server(7)
02:16:25 T:9212   ERROR: CCurlFile::FillBuffer - Reconnect failed!
02:16:25 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:25  INFO  btservice        Internet connection status changed, listening...
02:16:25 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:25  INFO  btservice        Starting DHT...
02:16:25 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:25  INFO  btservice        Starting LSD...
02:16:25 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:25  INFO  btservice        Starting UPNP...
02:16:25 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:16:25  INFO  btservice        Starting NATPMP...
02:17:15 T:3168 WARNING: CDVDMessageQueue(audio)::Get - asked for new data packet, with nothing available
02:17:16 T:9500  NOTICE: CDVDPlayer::OnExit()
02:17:16 T:9500  NOTICE: DVDPlayer: eof, waiting for queues to empty
02:17:16 T:9500  NOTICE: Closing stream player 1
02:17:16 T:9500  NOTICE: CDVDMessageQueue(audio)::WaitUntilEmpty
02:17:16 T:9500  NOTICE: Waiting for audio thread to exit
02:17:16 T:3168  NOTICE: thread end: CDVDPlayerAudio::OnExit()
02:17:16 T:9500  NOTICE: Closing audio device
02:17:16 T:9500  NOTICE: Deleting audio codec
02:17:16 T:9500  NOTICE: Closing stream player 2
02:17:16 T:9500  NOTICE: CDVDMessageQueue(video)::WaitUntilEmpty
02:17:16 T:9976 WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available
02:17:16 T:9976   ERROR: Got MSGQ_ABORT or MSGO_IS_ERROR return true
02:17:16 T:9500  NOTICE: waiting for video thread to exit
02:17:16 T:9976  NOTICE: thread end: video_thread
02:17:16 T:9500  NOTICE: deleting video codec
02:17:16 T:9500  NOTICE: DXVA::CDecoder::Close - closing decoder
02:17:16 T:9500  NOTICE: DXVA::Close - closing decoder context
02:17:16 T:8612  NOTICE: Stream All The Sources: Service: Playback completed
02:17:16 T:8612  NOTICE: Stream All The Sources: Service: Playback Stopped
02:17:16 T:8712  NOTICE: Thread LanguageInvoker start, auto delete: false
02:17:16 T:4324  NOTICE: CDVDPlayer::CloseFile()
02:17:16 T:4324  NOTICE: DVDPlayer: waiting for threads to exit
02:17:16 T:4324  NOTICE: DVDPlayer: finished waiting
02:17:16 T:4324  NOTICE: CDVDPlayer::CloseFile()
02:17:16 T:4324  NOTICE: DVDPlayer: waiting for threads to exit
02:17:16 T:4324  NOTICE: DVDPlayer: finished waiting
02:17:16 T:6624  NOTICE: Thread JobWorker start, auto delete: true
02:17:16 T:4324   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
02:17:17 T:3104  NOTICE: Skin Helper Service --> Video database changed - type: episode - resetAll: False, refreshing widgets....
02:17:17 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:17:17  INFO  btplayer         Removing the torrent and deleting files...
02:17:17 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:17:17  NOTI  libtorrent       torrent_removed_alert: Mr.Robot.S01E08.REAL.720p.HDTV.x264-KILLERS[EtHD] removed
02:17:17 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:17:17  NOTI  libtorrent       torrent_deleted_alert:  -  deleted
02:17:17 T:5632  NOTICE: [plugin.video.quasar] 2016-02-06 02:17:17  NOTI  libtorrent       cache_flushed_alert:  -

**Comment by scakemyer** [comment]
The internet lookup was removed, it should be fine now, see #64

**Comment by ziiky** [comment]
`ello
sry for posting in closed topic but ...
for a while I have very similar problem on kodi 16.0 with quasar. After playing a video for about 20 minutes, the video suddenly stops and Kodi goes to its main screen. That happened even if I hit  pause for buffing or wait to download reach 100%.
This happening on 2 identical amlogic m8s amlogic (2gb/8gb) quadcore boxes only on kodi16 on every last quasar version. I did not have this issue on kodi 15.2 nor windows version .
Can u help to solve this issue? Regards
