### ISSUE TITLE
Question???

### ISSUE THREAD

**Issue by ghost** [scakemyer/plugin.video.quasar#859]
how can i keep seeding on quasar im using a private trackers so i need to seed back! but quasar doesnt keep seeding in the background it does it for like 30min or so n then it gone can anyone give me some info on this what can i do in the quasar setting to keep seeding

**Comment by elgatito** [comment]
There is a seed time limit setting in Quasar settings (Bittorrent tab), by default it's 1 hour to seed. If you set if to 0 - you will have to manually stop seeding.

**Comment by ghost** [comment]
"elgatito"  
Thanks for ur help i really appreciate it
