### ISSUE TITLE
Quasar doesn't work over wifi - RPI3(OSMC)

### ISSUE THREAD

**Issue by istocc** [scakemyer/plugin.video.quasar#876]
## Context
Hi friends,

Recently i acquired a Raspberry PI 3 and installed LibreElec/OSMC.

my quasar got stucked at "Finding 0%" and when i manually add the torrent it got stucked ate "Buffering 0%".

## Your Environment

* Version used: v0.6.1

* Environment name and version: Kodi 17.3

* Operating System and version: OSCM/LibreELEC both were used in it last update

**Comment by foklorr** [comment]
works for me
