### ISSUE TITLE
When upload speed limit is set to 1-2 kB/s, Quasar doesnt download a file

### ISSUE THREAD

**Issue by drake0101** [scakemyer/plugin.video.quasar#89]
When I set upload speed limit to 1-2kB/s, Quasar will ask every torrent provider, then provide me with list of torrents. When I choose the file I want to download/stream, its stuck on "Finding (0.00%)".
At 10kB/s limit its the same. At 20kB/s its starts to download, but very slowly.
With no upload speed limit set, its works very fast.

**Comment by scakemyer** [comment]
That's just obvious.

**Comment by drake0101** [comment]
How is it obvious? If in uTorrent client I will limit upload speed, then the download speed isnt affected.

**Comment by scakemyer** [comment]
1-2kB/s isn't enough to even make the connections, and this is all managed by libtorrent which determines it can't do anything with that limit. Not an issue with Quasar, and yes, it is really obvious, regardless of how uTorrent does things.

**Comment by hfmls** [comment]
it takes around 60k to get magnet link meta data (depends on torrent size/files) plus, more kb to connect and such, i guess 1-2 kb isn't enough to keep torrent "alive" i think that's what you want?
"keep alive" give it around 5-10kb, should be ok.
