### ISSUE TITLE
Feature suggestion: Using Google "API" for suggestions while searching

### ISSUE THREAD

**Issue by Lillecarl** [scakemyer/plugin.video.quasar#899]
Hi!

You can make GET requests like this one http://google.com/complete/search?output=toolbar&q=imdb+godf and it'll spit some XML about suggestions back, this would help people searching with remotes rather then keyboard.

If implemented i'd suggest a configuration entry for a search prefix (See i prefixed IMDB, to make Google understand i'm looking for media content/actors. Which ofc should be removed from the suggestion before hitting search.

I understand it might not be easily achievable to implement the gui part, but it'd be a killer feature 👍 

Limiting the requests to one per second while typing is probably a good idea, to not piss big brother off.

Maybe https://www.themoviedb.org/documentation/api is a better option to investigate, anyhow some kind of autocomplete would be really cool :)

**Comment by elgatito** [comment]
There are suggestion plugins for Kodi, if you start typing - it will show suggestions.

**Comment by Lillecarl** [comment]
Thanks for the tip! :)
