### ISSUE TITLE
kodi crashes when using external sd/usb as storage

### ISSUE THREAD

**Issue by dtsexpert** [scakemyer/plugin.video.quasar#90]
Finding streams is fine. First it downloads fine, after like 30 seconds Kodi freezes/crashes.
Not sure if this is Quasar, or Android issue. Box is root with full read/write permission to external SD. Setting to use the internal memory works fine.
Kodi 14.2, Android 5.1.1
Attached is the crash logs.
[SendLog.txt](https://github.com/scakemyer/plugin.video.quasar/files/120399/SendLog.txt)

**Comment by scakemyer** [comment]
> This is a limitation of libtorrent, please keep in mind that most of the legwork is done by it, so if libtorrent can't do something, then Quasar probably can't either. And there are certainly good reasons for libtorrent not to support external storage, since it needs fast read/write access to function properly, so I seriously doubt it's even on their roadmap to support that.

**Comment by johnnyslt** [comment]
Have tried to format external storage as ext4? I think quasar doesn't work with fat32.

**Comment by dtsexpert** [comment]
I tried exfat & ntsf, still no luck.

**Comment by scakemyer** [comment]
The filesystem won't change anything, external storage will not work unless it's eSATA mounted at the OS level. Forget USB or NAS storage.

**Comment by bilbonvidia** [comment]
what about with marshmallows adopted storage option?
