### ISSUE TITLE
which version of Quasar is for Raspberry Pi 3?

### ISSUE THREAD

**Issue by hadifarnoud** [scakemyer/plugin.video.quasar#916]
I keep trying ARM versions. which one should work on Pi 3? then I look for solving those errors

**Comment by marcoruval** [comment]
plugin.video.quasar-0.9.78.linux_armv7.zip

**Comment by hadifarnoud** [comment]
it keeps crashing on Raspberry Pi OpenELEC

**Comment by placidities** [comment]
quasar uses more io than rpi can provide

download torrents another way.  use openelec on pi to watch
