### ISSUE TITLE
Quasar 0.9.7 doesn't delete file

### ISSUE THREAD

**Issue by Filosofos** [scakemyer/plugin.video.quasar#92]
It seems that if you play a movie for about a few minutes and stop it, quasar doesn't delete the file and keeps downloading it. Then, if you try to play a new movie in the same session, a new parallel download starts until it crashes. 

I can provide logs if needed.

**Comment by scakemyer** [comment]
Read the release notes. v0.9.8 adds a background progress dialog so you see what it's doing.

**Comment by Filosofos** [comment]
I updated to v0.9.8 and saw the background progress dialog, which confirms what i commented earlier. Although i stopped the movie, it kept on downloading.
When i opened Kodi again i found that in the log file:
NOTICE: [plugin.video.quasar] Deleting stale files set ([u'movie name', u'985ebf95ed6aacc7e4c7e76252b0b32d9f8e00b4.fastresume', u'movie name', u'171ec810c40de198ffe36a7c1fe7d513211523d5.fastresume'])

**Comment by scakemyer** [comment]
That's how it works with background handling of downloads, which you can turn off in the settings if you prefer the way it was.

**Comment by i96751414** [comment]
Shouldn't this be disabled by default?

**Comment by Filosofos** [comment]
Sorry, didn't realize the purpose of it.
Thank you.

**Comment by scakemyer** [comment]
@i96751414 I guess I was too enthusiastic about the feature, I suppose you're right.

**Comment by i96751414** [comment]
The feature is awesome :) Is just that for slower devices it can be problematic

**Comment by scakemyer** [comment]
Well, it doesn't change anything if you stick to one download at a time ;) And you can actually resume almost instantly where you left off. Disabling it prevents all that awesomeness really...

**Comment by i96751414** [comment]
Yeah.. you're right

**Comment by scakemyer** [comment]
I'm torn... I don't want to force this, but there's hardly a better way, and it still honours the "Keep file after download" setting too...

**Comment by scakemyer** [comment]
Let's just let it simmer like this, and see how we should adjust things to make it even smoother. If the response is mostly on the awesome side we'll know it's just small fixes, otherwise we can default it back and re-evaluate how it should work.

**Comment by nix87** [comment]
I find this feature very useful in some occasions.

**Comment by meijin007** [comment]
where can I find more info about this feature? I don't fully understand what is that useful for?

**Comment by hfmls** [comment]
I can't cancel or delete files that are in background downloading,  fix please?

**Comment by scakemyer** [comment]
Fixed in scakemyer/quasar@c775439
