### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by marathone** [scakemyer/plugin.video.quasar#936]
1st, apologies for using the github page for this, but couldn't find any other way of contacting the project. So please excuse the noise.
On the projects website, there is an option to donate viva bitcoin. For those of us not familiar with that currency, and/or uncomfortable with using an unknown - Could you perhaps open up a Patreon account (micro-payments processor) https://www.patreon.com ?

**Comment by placidities** [comment]
find a bitcoin exchange platform.  There are many many choices.   Some you can trade amazon gift cards for coin anonymously.

**Comment by marathone** [comment]
@placidities  No shit Sherlock - Please, Stop spamming the project. One should never make it difficult to donate, if one wants donations.

**Comment by marathone** [comment]
I don't wish to use bitcoin, I wish to use dollars. I guess if you don't want donations, you can always make it difficult to donate. Your choice!
