### ISSUE TITLE
has this fork been stabbed to death?

### ISSUE THREAD

**Issue by placidities** [scakemyer/plugin.video.quasar#938]
no updates? 

Are there forks of this fork?

**Comment by ShlomiD83** [comment]
the addon still works like a charm (knock on wood).
but there's a ongoing fork called Elementum:
https://github.com/elgatito/plugin.video.elementum

**Comment by marathone** [comment]
I've found 'Elementum' not to be very stable. Quasar rules for moi. Is Quasar expected to work on the new Kodi release coming soon - does it work on the betas?

**Comment by cali4nick8** [comment]
I agree with @marathone Elementum is very unstable. And now quasar stopped working with the new version of Kodi 18.0. Please bring it back!!

**Comment by scakemyer** [comment]
F*** it. We're back.

**Comment by elgatito** [comment]
Return of the year :)

**Comment by ShlomiD83** [comment]
Finally, welcome back mate!

**Comment by burekas7** [comment]
@scakemyer IS COMING !!! ;)

**Comment by veniciusgp** [comment]
> F*** it. We're back.

Welcome back Jedi Master

**Comment by ShlomiD83** [comment]
so i guess no new release is on the horizon after all?
