### ISSUE TITLE
all completed files did not modev to completed floder

### ISSUE THREAD

**Issue by MaksVal** [scakemyer/plugin.video.quasar#940]
## Expected Behavior
move a downloaded file to another folder

## Current Behavior
All completed files did not moved
`09:58:13.229 T:1423184640  NOTICE: [plugin.video.quasar] ERRO  btservice    ▶ func1            Missing item type to move files to completed folder for Cinderella.2015.1080p.BluRay.x264.WiKi .mkv
`

## Your Environment

* Version used: 0.9.78

* Environment name and version: OSMC (kernel 4.14.78-4-osmc) last updated

* Operating System and version: 

* Link to Kodi debug log: https://paste.ubuntu.com/p/hWtjw3qGD8/

#888 ???

**Comment by scakemyer** [comment]
Yes, will track in #888
