### ISSUE TITLE
Wrong subtitles when third party subtitle addon is used

### ISSUE THREAD

**Issue by Filosofos** [scakemyer/plugin.video.quasar#95]
I have no problem with quasar's subtitle addon but when using third party subtitle addons, then for some movies and not for every movie, i get completely wrong subs that have nothing in common with the movie name. 
For those, when using the manual search, i get the correct ones.

**Comment by deusbraga** [comment]
THanks for all the amazing work but I'm still having this  same issue with the subtitles, it gets the subtitles completely wrong everytime I try to use a 3rd party subtitle addon. It's almost as if the force original title option only worked for quasar's subtitle addon. Is there a workaround solution?

**Comment by Filosofos** [comment]
@scakemyer mentioned [here](https://github.com/scakemyer/plugin.video.quasar/issues/234#issuecomment-186446387) that he hasn't looked into subs yet, so it is still an open issue i suppose.

**Comment by scakemyer** [comment]
Closing, this will be looked into and is better explained in #256
