### ISSUE TITLE
Can not Path to Nas

### ISSUE THREAD

**Issue by trongthuan0311** [scakemyer/plugin.video.quasar#98]
I can't locate the dowload path and library path to Nas ( linksys ea4500 with usb input ). Althouht i set the dowload path in setting buf Quasar alway dowload the movie  to internal storage ( my Fire tv ). 
The firetv have had a narrow space . Thanks you awsome work

**Comment by scakemyer** [comment]
As I mentioned on the forum:
> This is a limitation of libtorrent, please keep in mind that most of the legwork is done by it, so if libtorrent can't do something, then Quasar probably can't either. And there are certainly good reasons for libtorrent not to support external storage, since it needs fast read/write access to function properly, so I seriously doubt it's even on their roadmap to support that.
