### ISSUE TITLE
0.9.8 blocks compluty the system

### ISSUE THREAD

**Issue by lordjg** [scakemyer/plugin.video.quasar#99]
0.9.8 blocks compluty the system on startup. I'm running a wetek play with openelec and afterboot the screen freez and I can't do nothing.
the solucion was to connect by ssh and remove the quasar folders. after that all worked just fine. i installed the 0.9.5 and It's all running fine.
UPDATE:nevermind my sistem got a stupid error...

**Comment by i96751414** [comment]
Was this a Quasar problem? If not, you may close this issue.

**Comment by lordjg** [comment]
no. thanks for the replay. at first o thought it was but i've figured out now. please close it.

**Comment by i96751414** [comment]
I can't close it, but I think you can. Otherwise we must wait for scakemyer to close it.
